### PR TITLE
Initial commit for wago binding [new attempt]

### PR DESCRIPTION
**Pull request by BinaryCraX**

### CODE REVIEW

**Comment by teichsta** [comment]
merged manually into master. Thanks @BinaryCraX, Best, Thomas E.-E.

**Comment by nickma82** [comment]
@BinaryCraX "eclipse always crashes"
I had a simmilar issue and downloaded the plugin developer version of eclipse lunar directly from the [eclipse site](http://www.eclipse.org/downloads/packages/eclipse-rcp-and-rap-developers/lunasr1a). After choosing the same working-directory as with the old-crashing eclipse it worked perfeclty!

**Comment by BinaryCraX** [comment]
@nickma82 "eclipse always crashes"
Thank you very much for this tip :)

**Comment by teichsta** [comment]
the corresponding Wiki page for the Wago is still missing @BinaryCraX. Could you please add it?

**Comment by BinaryCraX** [comment]
@teichsta i've just added a basic documentation of the wago-binding to the Wiki. I'll complete it as soon as possible.

**Pull request closed without merging**
