### PR TITLE
Fix absolute path problem in systeminfo Binding and add unit tests

### PR DESCRIPTION
**Pull request by 9037568**
This fixes the absolute path problem from #2430 and adds a package of unit tests for the systeminfo binding.

### CODE REVIEW

**Comment by paulianttila** [comment]
First of all, thanks for the contribution. It's really nice to have unit tests for system binding as well.

What I'm not fully like is to have special case for DirFiles and DirUsage commands in config parser. I think we should have universal approach here. My proposal for config syntax is following:

DirFiles:60000:'c:\Users\foo'

Where target (path) should also be accepted without ' characters for backward compatibility. 

DirFiles:60000:/Users/foo

Then it should be possible to handle this universally without any special cases. Regex most probably is to easiest way to check the syntax. 

What do you think @9037568?

**Comment by 9037568** [comment]
Yes, that could work.  But you're only moving the special case around, not eliminating it.

Another problem is that the apostrophe is rather common in file paths, so you'd have to create special handling for that, too.

**Comment by paulianttila** [comment]
You are right, apostrophe is valid character for file paths, so it can't be used.

Why I still want to have generic solution is that I have introduced FileSystem commands (already merged), which doesn't work windows with absolute paths either. So my opinion is still, that binding provider shouldn't have command specific dependencies.

One possibility is to escape colon character from file path. 

E.g.

DirFiles:60000:c\:\Users\foo

Parser then replace escaped sequence \: by "magic string" before split the config variable and then replace it back to colon after split.

**Comment by teichsta** [comment]
What if you use (escaped) double quotes ' \" '? That should help identifying the different configuration elements better! Any chance to get this fixed until next week? Thanks, Thomas E.-E.

**Comment by 9037568** [comment]
Submitted a simplification of the parameter parsing...

**Comment by teichsta** [comment]
Great, if you could now finally sqash your commits into one i am happy to merge this PR. Thanks, Thomas E.-E.

**Comment by 9037568** [comment]
Ok. I _think_ that's done. Still don't entirely grok git.

**Pull request merged**
