### PR TITLE
Adding in Energy Monitor and also attempting to make polling response…

### PR DESCRIPTION
**Pull request by foxy82**

### CODE REVIEW

**Comment by teichsta** [comment]
Hi @foxy82 thanks for this contribution! Could you please explain in more detail what this PR is about? Thanks, Thomas E.-E.

**Comment by foxy82** [comment]
Hi,

This pull request does two things:

1) Adds the ability for the LightwaveRF binding to handle messages from a LightwaveRF energy monitor
2) Fix an issue when we send a message we don't process the "ok" (acknowledgement from the LightwaveRF hub that message is received). As such we end up attempting to send the message again.

Regards,
Neil

**Comment by foxy82** [comment]
Hi,

Is that enough feedback?

Regards,
Neil

**Comment by foxy82** [comment]
I've created a new pull request (https://github.com/openhab/openhab/pull/3457) with extra changes so closing this.

**Pull request closed without merging**
