### PR TITLE
SimpleBinary binding

### PR DESCRIPTION
**Pull request by docbender**
Hi, this binding enables connect devices through UART using simple binary protocol. Protocol is easy to implement into home made devices.

My binding repository can be found here: https://github.com/docbender/openHAB-SimpleBinary

### CODE REVIEW

**Comment by teichsta** [comment]
Thanks for this contribution @docbender. Since we are in the preparations of the 1.8 release we won't be able to review this PR before mid of January. I hope for your understanding. Best, Thomas E.-E.

**Comment by docbender** [comment]
Of course I have no problem with that. If you're interested in the binding and you wanna edit something just let me know.

**Comment by ModuloFS** [comment]
Hello docbender, i like your SimpleBinary Binding! I just implement the Protocol on an Atmel ATmega32/16 in the Programming Language C. In principle it based on your arduino example code.  If  someone else is interesstet in the code, i will share it! I hope you will continue on working on the Binding. It is essential if you want to build your own devices!

**Comment by docbender** [comment]
Hi @ModuloFS, glad to hear that you're enjoying this binding. If you wanna create pull request with your code for ATmega into my repo you're welcome. Best

**Comment by ModuloFS** [comment]
Hello again @docbender, now i tested my code for the Atmel with more than one slave at the RS485 line, but no i get timeout errors for both connected slaves. If you put each slave alone on the bus, they work without problems. Is there any known issiue for this Problem, or is it not possible to put more than one slave on the RS485 line? Best, Flo

**Comment by ModuloFS** [comment]
Ok, now ive got the problem @docbender . It was in the processSerial() - function. If you have two times the slave address together in the "serbuf" it causes a problem, because the messagetype cannot be filtered. To solve this problem ive added the following lines in the "default" case of "switch(serbuf[1])" : `	         
default:
for(int i=0;i<serbuflen;i++)
{
         serbuf[i] = serbuf[i+1];
}
serbuflen--;
break;`
But i have discovert an additional issiue. If a slave on the RS485 line is not answering, the binding poll only this slave until it answeres. This is a problem, because from this point on the other slaves are not polled. That means, as soon a slave is faulty, the entire bus is not working anymore. Undoubtedly, it would be better that the other working slaves would be pollt continue.

**Comment by docbender** [comment]
Hello @ModuloFS. The problem with requests block by dead device was in some old version device library.  I'll look on it.... Have you tried the latest version?

**Comment by ModuloFS** [comment]
Yes, iam running the latest release which you released on May 20th with the heading: "Multidevice communication improved".

**Comment by docbender** [comment]
Hi, at first side I did not find any weird behavior in my system with unconnected device. I made some changes in thread concurrency at command buffer handling. I also found that one command was lost if some device was dead (probably in your case this was live device command). Try to test this binding: 
https://github.com/docbender/openHAB-SimpleBinary/releases/download/0.5.0.test/org.openhab.binding.simplebinary-1.9.0-SNAPSHOT.jar
If the problem still occurs, run it in debug and post your logs.

**Comment by 9037568** [comment]
Hi, @docbender . Thanks for this PR. I'm getting ready to start a review of the changes. Do you have any additions that need to be made first?

**Comment by docbender** [comment]
Hi, @9037568 I made lot of changes since this request. So should I merge this changes and create a new request?

**Comment by 9037568** [comment]
I'd say which ever is easier for you.

**Comment by docbender** [comment]
So new pull request #4809 been made.

**Pull request closed without merging**
