### PR TITLE
new binding for picnet home automation devices

### PR DESCRIPTION
**Pull request by paolodenti**
Hi,
i am just submitting a new binding for picnet home automation devices

I just left the binding project, the modified pom.xml and the default configuration

Thanks
Paolo

### CODE REVIEW

**Comment by paolodenti** [comment]
we have some further developments on another branch (rollershutter and dimmer added).
As the pule request has not yet been executed can i merge those changes in the meanwhile?

**Comment by teichsta** [comment]
> can i merge those changes in the meanwhile?
yes, please :-) (i saw you did it meanwhile)

**Comment by paolodenti** [comment]
Thanks teichsta. we will do it for sure. As you point out, we are just in the first development version. For future fixes and add ons commit messages will be meaningful.

**Comment by paolodenti** [comment]
how should we proceed about the binding documentation in the wiki?
Should i wait for pull request completion before adding the documentation?
And how do i modify the wiki adding our binding markdown?

**Comment by watou** [comment]
You can create a new page in the wiki by going [here](https://github.com/openhab/openhab/wiki/_new).  Look at other pages for bindings as examples, and press the Edit button on one in order to see the markdown formatting its author(s) used (but don't save).  When you are ready to share the documentation (i.e., you know the release it will appear in), simply [edit the sidebar](https://github.com/openhab/openhab/wiki/_Sidebar/_edit) and carefully add your binding to the list at the correct point.  Make note in your wiki page of what release it will first appear in.

**Comment by paolodenti** [comment]
@teichsta do you have any forecast about pull request execution? Thanks

**Comment by wtrucci** [comment]
Tested on production and all works fine. I hope this binding will be included as soon is possible :-)

**Comment by paolodenti** [comment]
Substituted by #3229 (using a dedicated branch instead of master)

**Pull request closed without merging**
