### PR TITLE
Rewritten rule engine, allows using regexp matching and also 'item in'…

### PR DESCRIPTION
**Pull request by derolf**
https://community.openhab.org/t/allowing-regular-expression-matching-in-rules/2072/7

These changes do:

- extended rule syntax to catch a change/update/command of an item in a group: 
the <code>item in \<groupItem\>...</code>' (etc) monitors events to any item in the group, executes the script and provides the changed item is local variable <code>item</code>

- extended rule syntax to have regular expression strings for item names: the <code>item "\<regexp\>"...</code> and <code>item in "\<regexp\>"...</code> matches item names by regexp resp. their groups by regexp, hence the item name in item triggers is generally handled as regexp if quoted.

- expose item variable in rule script to access the item that triggered the rule: an item-based rule script has a local variable <code>item</code> pointing to the triggering item

- (minor bug fixes)

Syntax changes for rules:

```
EventTrigger:
	ItemEventTrigger |
	TimerTrigger |
	SystemTrigger
;

ItemEventTrigger:
	'Item' (in?='in')? item=ItemName trigger=(UpdateEventTrigger|CommandEventTrigger|ChangedEventTrigger)
;


CommandEventTrigger:
	{CommandEventTrigger}
	'received command' (command=ValidCommand)?
;

UpdateEventTrigger:
	{UpdateEventTrigger}
	'received update' (state=ValidState)?
;

ChangedEventTrigger:
	{ChangedEventTrigger}
	'changed' ('from' oldState=ValidState)? ('to' newState=ValidState)?
;		
```

### CODE REVIEW

**Comment by paixaop** [comment]
+1

**Comment by martinjo** [comment]
:+1:

**Comment by teichsta** [comment]
@derolf thanks for this contribution and sorry for not coming to you earlier. As you probably know 1.8 has been the last release coming with it's own core components. From 1.9 onwards all 1.x bindings will be operated on the 2.x/ESH core. Therefore we agreed on a core-code-freeze a long ago. Hence it makes no sense to work on this PR anymore.

I hope for your understanding!

Best, Thomas E.-E.

**Comment by derolf** [comment]
FHEM is anyway much better and less convoluted…

**Comment by kaikreuzer** [comment]
It seems that @derolf spent quite some efforts on this, it feels a bit unfair to reject this half a year later... Isn't the contribution still valuable and it should be checked, how it can be contributed to ESH as it has been [suggested here](https://community.openhab.org/t/allowing-regular-expression-matching-in-rules/2072/6?u=kai)? 
If we have meanwhile lost @derolf to FHEM, it might be too late to help on this, though...

**Pull request closed without merging**
