### PR TITLE
Insteonplm Thermostat 2441TH

### PR DESCRIPTION
**Pull request by djcampbell**
Adding support for Insteon Thermostat 2441TH to insteonplm binding

### CODE REVIEW

**Comment by teichsta** [comment]
@berndpfrommer could you have a look at this, please? Thanks, Thomas E.-E.

**Comment by berndpfrommer** [comment]
Daniel, did you fix the logging? You can simply do so by fixing, committing, and then pushing into the branch on which this pull request is based on. That should automatically update the pull request.

Sorry for being pushy: I want to merge your changes in once they are complete so I can add the extended message querying as well.

**Comment by djcampbell** [comment]
Sorry, yeah I did fix my copy.  I didnt realize you were waiting on me.
Then I started adding additional functions to set cool and heat setpoints
to a specific value... rather than just the increase / decrease functions -
which is halfway done.  I'll try to finish it up tonight and commit the
changes.  On weekends my day job gets in the way of the fun work.

Daniel

**Comment by djcampbell** [comment]
Hello Bernd,
    Apologies for the delay.  I just committed my latest changes.  I
successfully figured out the Data2 query so now I am pulling heat and cool
setpoints.and now I am setting the setpoints directly rather than
incrementing them.  This will allow dynamic changing of setpoints from
openhab rules.  (custom schedules)

Please let me know if you see anything that needs to be addressed.  I will
be testing it further here on my setup.

Thank you,
Daniel

**Comment by berndpfrommer** [comment]
I got a whole bunch of changes sitting in my local branch that I want to merge with this PR. I know there will be conflicts, so I'd prefer this PR to go forward before I submit my changes.
Thomas, any chance you can merge this PR before the Easter weekend?

**Comment by teichsta** [comment]
sorry @berndpfrommer didn't see this mails during vacation!

**Comment by berndpfrommer** [comment]
@djcampbell would you be kind enough to update the insteonplm wiki page? Just add another section maybe below the one for the power meter, with an example configuration for the thermostat, then enter the thermostat (with device number) into the table of supported devices.
BTW I started to use your thermostat extensions yesterday night and they seem to work fine.

**Comment by djcampbell** [comment]
Sure thing! I'll let you know once the wiki has been updated!

Daniel

**Comment by djcampbell** [comment]
I just finished updating the wiki doc.  I added F00.00.18 to the list of
supported devices and inserted a section describing the thermostat items
and sitemap config below the X10 section.

Thank you,
Daniel

**Pull request merged**
