### PR TITLE
[Nest] Enh: Add hvac_state property to thermostat object

### LINKED ISSUE #2658: [Nest] Enh: Add hvac_state thermostat property
Add the new ([May 2015 API update](https://developer.nest.com/documentation/cloud/release-notes)) property `hvac_state` to Thermostat objects, which reports `heating`, `cooling` or `off`, depending on what HVAC equipment is currently running.

### PR DESCRIPTION
**Pull request by watou**
Users check [the wiki page](https://github.com/openhab/openhab/wiki/Nest-Binding) (updated shortly) for a note about changing permissions to Thermostat read/write v3, reauthorizing your client and updating `nest:pin_code` in `openhab.cfg`.  

Closes #2658.

### CODE REVIEW

**Comment by watou** [comment]
Hi @teichsta, how do you feel about adding this to 1.7.1?  Nest sent the notice out about the new feature on Wednesday and it's such a small code change (I've tested it).  I will update the wiki accordingly.

**Comment by watou** [comment]
Hi @teichsta , in case you missed my question about tagging this for inclusion in 1.7.1?  Unless you prefer to wait for 1.8.0.  Just making sure you considered the question.

**Comment by teichsta** [comment]
Thanks for this ping! rescheduled for 1.7.1 …

**Comment by watou** [comment]
Thanks a lot, Thomas.

**Pull request merged**
