### PR TITLE
Fix: OneWireBinding possible ClassCastException during startup

### PR DESCRIPTION
**Pull request by Dennis650**
Fixes issue #3194

### CODE REVIEW

**Comment by teichsta** [comment]
Hi @Dennis650 thanks for this fix (and the investigations done in #3194). The PR lgtm. Could you please finally squash your commits into one? Thanks, Thomas E.-E.

**Comment by Dennis650** [comment]
doesn't work. please delete.

**Comment by Dennis650** [comment]
Hi, i created a new PullRequest #3303

**Comment by teichsta** [comment]
>Where is a working tutorial for squashing commits?

e.g. this one http://davidwalsh.name/squash-commits-git lgtm. For me also works this workflow (assuming you are on a dedicated branch for the PR):

* reset (mixed mode) your branch to the first commit
* commit+amend your changes to this first commit
* (force) push to your feature branch (the PR branch)

Thanks, Thomas E.-E.

**Pull request closed without merging**
