### PR TITLE
[RRD4J] Fix rrd interval #4559

### PR DESCRIPTION
**Pull request by J-N-K**
Again, there is a lot of reformatting. The only change besides that is in l. 238.

This fixes the data points with too early (#4559) or too late timestamps. However, it can still happen that the last datapoint/timestamp is duplicated. This outside the scope of the RRD4J binding but must be fixed in the REST implementation.

There are a lot of warning (e.g. l. 169) about wrong type casts in the logger. Can someone with deeper JAVA knowledge advice on that?

### CODE REVIEW

**Comment by J-N-K** [comment]
I opened an [issue](https://github.com/eclipse/smarthome/issues/2538) for the double end-time.

**Comment by J-N-K** [comment]
is there any reason that blocks merging?

**Comment by 9037568** [comment]
LGTM.  Has there been any verification from @CarstenMadsen or the community?

**Comment by watou** [comment]
@J-N-K, I see the only non-formatting change in this branch currently is:

```diff
-		    if (!Double.isNaN(value)) {
+                    if (!Double.isNaN(value) && (((ts >= start) && (ts <= end)) || (start == end))) {
```

Please confirm that this change is still wanted and will not cause a regression.

> There are a lot of warning (e.g. l. 169) about wrong type casts in the logger. Can someone with deeper JAVA knowledge advice on that?

Line 169 is now:

```java
logger.warn("Could not persist '{}' to rrd4j database: {}", new String[] { name, e.getMessage() });
```

I recommend removing all the `new String[] { arg0, arg1 }` and replacing them with `arg0, arg1` since the logger can handle variable arguments, and we don't need to keep creating and garbage collecting the String or Object arrays.

**Comment by J-N-K** [comment]
@watou, The change is what is intended. RRD4J returns one datapoint before and (id exists) after the requested time interval. This is obviously confusing and leads to wrong ordering of the datapoints in the REST API (when called with boundaries).

The loggers have been adjusted. I was just wondering if there is a reason the `new String[]` is used.

**Comment by watou** [comment]
> I was just wondering if there is a reason the new String[] is used.

It might be that the logger API accepted an array after the format string, and then later added variable argument support.  The ideal usage now is to avoid temporary object construction for logging statements, so pass variable arguments instead of creating a new array.  Also, pass `someObject` instead of `someObject.toString()` as an argument, as `.toString()` would only be needed if the logger needed to actually format a log entry and `.toString()` might require work and/or temporary object creation.

**Comment by J-N-K** [comment]
I changed that.

**Comment by watou** [comment]
OK to be merged then, @J-N-K ?

**Comment by J-N-K** [comment]
Yes. Works for me.

**Pull request merged**
