### PR TITLE
DSC Alarm Binding: IT-100 TCP Connection Support

### PR DESCRIPTION
**Pull request by marclennox**
As per the following discussion with @RSStephens 

https://community.openhab.org/t/dsc-alarm-binding-with-tcp-serial-server/5701

I have added support for the DSC Alarm binding to communicate with an IT-100 through a TCP/IP serial server.

Note that for some reason I'm getting a bad checksum when trying to send "partition disarm" from the web console, but everything else seems to work.

Also note that I have only tested this with my setup (IT-100 behind a Moxa N-Port tcp/serial server).

Let me know if there's anything you'd like changed.  Thanks!

### CODE REVIEW

**Comment by teichsta** [comment]
Thanks @marclennox for this contribution. @RSStephens would you be so kind and have a look into this?

**Comment by marclennox** [comment]
No problem.

@RSStephens let me know if you'd like any changes, and also note that I figured out why the checksum error on disarm.  It's because the binding is not padding the code to 6 digits if it's less than 6.  As per the IT100 developer guide, you have to pad the user code with trailing zeros to get to 6 characters.

**Comment by RSStephens** [comment]
Hey Thomas, I will be glad to look into it.  Thanks.   

Hello Marc,  I may ask you to add some code to your PR if that is okay with you.  I think you have already found the issue it's just a matter of implementing the solution.  Thanks.

**Comment by marclennox** [comment]
I can take a look at fixing the code padding issue.  Note however that I don't think this bug is a result of my PR.  I'm guessing this is a bug in the released version also.

**Comment by RSStephens** [comment]
Hello Marc,

You are absolutely right the programming does not format the output for the IT100 as a 6 digit user code.  It is an over site on my part.  The program was originally designed for the Envisalink which does not require the user code to be 6 digits.  I just didn't read the IT100 documentation closely enough.  Sorry about that.  This can be fixed with the following lines of code if you would be willing to add this to your pull request:

				if(!connectorType.equals(DSCAlarmConnectorType.IT100))
					data = apiData[0] + String.format("%-6s",dscAlarmUserCode).replace(' ','0');
				else
					data = apiData[0] + dscAlarmUserCode;

The change is in the **API.java** file, and needs to go with in the **sendCommand()** method for *case PartitionDisarmControl*.  The the change would go from this:

 			case PartitionDisarmControl: /*040*/
 				if (apiData[0] == null || !apiData[0].matches("[1-8]")) {
 			    	logger.error("sendCommand(): Partition number must be a single character string from 1 to 8, it was: {}", apiData[0]);
 					break;
 				}
 				
 				if (dscAlarmUserCode == null || dscAlarmUserCode.length() < 4 || dscAlarmUserCode.length() > 6) {
 					logger.error("sendCommand(): User Code is invalid, must be between 4 and 6 chars: {}", dscAlarmUserCode);
 					break;
 				}
				
				data = apiData[0] + dscAlarmUserCode;
				
				validCommand = true;
  				break;

To this:

 			case PartitionDisarmControl: /*040*/
 				if (apiData[0] == null || !apiData[0].matches("[1-8]")) {
 			    	logger.error("sendCommand(): Partition number must be a single character string from 1 to 8, it was: {}", apiData[0]);
 					break;
 				}
 				
 				if (dscAlarmUserCode == null || dscAlarmUserCode.length() < 4 || dscAlarmUserCode.length() > 6) {
 					logger.error("sendCommand(): User Code is invalid, must be between 4 and 6 chars: {}", dscAlarmUserCode);
 					break;
 				}
				
				//Start Added Code
				if(!connectorType.equals(DSCAlarmConnectorType.SERIAL))
					data = apiData[0] + String.format("%-6s",dscAlarmUserCode).replace(' ','0');
				else
					data = apiData[0] + dscAlarmUserCode;
				//End Added Code
				
				validCommand = true;
  				break;

This should append the necessary zeros to the end of the user code to make it 6 digits, as required by the IT100.  When you have an opportunity could you please make that change in your PR?  I greatly appreciated it, and thank you for finding this bug.

Thanks,
Russell

**Comment by marclennox** [comment]
Absolutely. I will try to get this updated over the weekend.

**Comment by RSStephens** [comment]
Thank you Marc.

The code if showing *if(!connectorType.equals(DSCAlarmConnectorType.SERIAL))* where as it should be *if(!connectorType.equals(DSCAlarmConnectorType.IT100))*.

**Comment by teichsta** [comment]
thanks guys … let me know when this PR is ready to merge.

**Comment by marclennox** [comment]
I've fixed and tested the code padding issue, rebased and squashed the PR commit.

**Comment by RSStephens** [comment]
Thank you Marc!

Thomas, this PR is ready to merge.

**Comment by teichsta** [comment]
also cherry-picked into master

**Pull request merged**
