### PR TITLE
Indicator

### PR DESCRIPTION
**Pull request by paixaop**
Improve Indicator class to support Items bound to indicator bits. This allows the user to set and reset indicator button lights individually and to use them in rules. For example we can sync indicators between  different scene  controllers.

For example here is a setup with two Cooper Scene controllers with 5 buttons each. First bind `Switch` items to each of the controller's buttons. The `bit` parameter specifies the bit of the Z-Wave Indicator that is bound to a certain button on the scene controller. Usually button 1 is the least significant bit, hence bit 0.

In this example buttons 1 in node 2 and node 3 will turn ON and OFF the Item `GF_Kitchen_Lights`.

	Switch SC_Kitchen_2_Button_1 "Kitchen Controller 2 Button 1" {zwave="2:command=INDICATOR,bit=0"}
	Switch SC_Kitchen_2_Button_2 "Kitchen Controller 2 Button 2" {zwave="2:command=INDICATOR,bit=1"}
	Switch SC_Kitchen_2_Button_3 "Kitchen Controller 2 Button 3" {zwave="2:command=INDICATOR,bit=2"}
	Switch SC_Kitchen_2_Button_4 "Kitchen Controller 2 Button 4" {zwave="2:command=INDICATOR,bit=3"}
	Switch SC_Kitchen_2_Button_5 "Kitchen Controller 2 Button 5" {zwave="2:command=INDICATOR,bit=4"}
	
	Switch SC_Kitchen_3_Button_1 "Kitchen Controller 3 Button 1" {zwave="3:command=INDICATOR,bit=0"}
	Switch SC_Kitchen_3_Button_2 "Kitchen Controller 3 Button 2" {zwave="3:command=INDICATOR,bit=1"}
	Switch SC_Kitchen_3_Button_3 "Kitchen Controller 3 Button 3" {zwave="3:command=INDICATOR,bit=2"}
	Switch SC_Kitchen_3_Button_4 "Kitchen Controller 3 Button 4" {zwave="3:command=INDICATOR,bit=3"}
	Switch SC_Kitchen_3_Button_5 "Kitchen Controller 3 Button 5" {zwave="3:command=INDICATOR,bit=4"}
	
	Dimmer GF_Kitchen_Lights "Ceiling Lights" {zwave="4:command=SWITCH_MULTILEVEL"}
	
Now we can create a rule that syncs the indicators in the two controllers. Regardless from where the Item `GF_Kitchen_Lights` is changed the LEDs on button 1 of node 2 and node 3 will change accordingly. Light is ON button LEDs are on, Light is OFF button LEDs are off.

	rule "Sync Kitchen Ceiling light Indicators"
	when
		Item GF_Kitchen_Lights changed
	then
		var Number percent = 0
		if(GF_Kitchen_Lights.state instanceof DecimalType) percent = GF_Kitchen_Lights.state as DecimalType 
		if( percent == 0 ) {
			sendCommand(SC_Kitchen_2_Button_1, OFF)
			sendCommand(SC_Kitchen_3_Button_1, OFF)	
		}
		else {
			sendCommand(SC_Kitchen_2_Button_1, ON)
			sendCommand(SC_Kitchen_3_Button_1, ON)
		}
	end

You can use this functionality  to setup two or more scene controllers in common 3-way or n-way configurations. Meaning you can turn the light ON using one controller and turn it OFF using another, as the light "state" syncs between all of them.

### CODE REVIEW

**Comment by cdjackson** [comment]
Looks fine. Can you please squash the commits?

**Comment by paixaop** [comment]
@cdjackson done.

**Comment by paixaop** [comment]
Chris

I cannot find the code for this in the master, did you remove it?
The master has an old version of the indicator class, which was the first one that I wrote and does not work very well...

**Comment by cdjackson** [comment]
I can see it in GitHub so it is fine

**Comment by cdjackson** [comment]
Sorry - email sent before finished....  It's in github, so it's fine as far as I can tell...  If it's not the correct version, then I'm not sure what went wrong as looking at the commit history we've merged the versions that you have committed - I've not deleted any as far as I know...

**Comment by cdjackson** [comment]
If I look at the file with [blame](https://github.com/openhab/openhab/blame/master/bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/commandclass/ZWaveIndicatorCommandClass.java), it shows that this commit (ae6aee5) was merged into master, so I don't think there's anything wrong with the merging.

**Comment by paixaop** [comment]
Thanks Chris I was looking to the wrong branch. That's what I get for trying to code with no sleep.

**Pull request merged**
