### PR TITLE
initial commit of issue template

### PR DESCRIPTION
**Pull request by steve-bate**
Proposed initial version of issue template for openhab. We can tweak it over time but I'd like to get an initial version into the repository.

### CODE REVIEW

**Comment by kaikreuzer** [comment]
lgtm

**Comment by steve-bate** [comment]
Thanks, I'll go ahead and merge it.

**Comment by cdjackson** [comment]
How about a prompt for debug logs - it’s normally the first thing I have to ask for in most ZWave issues...

**Comment by watou** [comment]
Looks good, would also recommend a prompt to gather precise version(s) of openHAB and relevant addons that are being reported.

**Comment by steve-bate** [comment]
I've created another branch for updating the issue template based on your feedback. Thanks. #4270 I'll wait a day or two to see if there is other feedback before merging the PR for the updates.

**Pull request merged**
