### PR TITLE
Extended MAX!Cube binding types to read config values

### PR DESCRIPTION
**Pull request by habnefrage**
I have added some additional binding types for configurations values.
It is now possible to bind these values to items and show them in openhab.

Examples:
Number 	GF_WZ_HT_Fenster_tempComfort 		"tempcomfort [%s]" 					<temperature> 	(gGF_WZ_HT_Fenster) 							{ maxcube="KEQ0380055:type=tempcomfort" }
Number 	GF_WZ_HT_Fenster_tempEco 			"tempeco [%s]" 						<temperature> 	(gGF_WZ_HT_Fenster) 							{ maxcube="KEQ0380055:type=tempeco" }
Number 	GF_WZ_HT_Fenster_tempSetpointMax 	"tempsetpointmax [%s]" 				<temperature> 	(gGF_WZ_HT_Fenster) 							{ maxcube="KEQ0380055:type=tempsetpointmax" }
Number 	GF_WZ_HT_Fenster_tempSetpointMin 	"tempsetpointmin [%s]" 				<temperature> 	(gGF_WZ_HT_Fenster) 							{ maxcube="KEQ0380055:type=tempsetpointmin" }
Number 	GF_WZ_HT_Fenster_tempOffset 		"tempoffset [%s]" 					<temperature> 	(gGF_WZ_HT_Fenster) 							{ maxcube="KEQ0380055:type=tempoffset" }
Number 	GF_WZ_HT_Fenster_tempOpenWindow 	"tempopenwindow [%s]" 				<temperature> 	(gGF_WZ_HT_Fenster) 							{ maxcube="KEQ0380055:type=tempopenwindow" }
Number 	GF_WZ_HT_Fenster_durationOpenWindow	"durationopenwindow [%s]" 			<temperature> 	(gGF_WZ_HT_Fenster) 							{ maxcube="KEQ0380055:type=durationopenwindow" }
Number 	GF_WZ_HT_Fenster_boostDuration		"boostduration [%s]" 				<temperature> 	(gGF_WZ_HT_Fenster) 							{ maxcube="KEQ0380055:type=boostduration" }
Number 	GF_WZ_HT_Fenster_boostValve 		"boostvalve [%s]" 					<temperature> 	(gGF_WZ_HT_Fenster) 							{ maxcube="KEQ0380055:type=boostvalve" }
Number 	GF_WZ_HT_Fenster_decalcification 	"decalcification [%s]" 				<temperature> 	(gGF_WZ_HT_Fenster) 							{ maxcube="KEQ0380055:type=decalcification" }
Number 	GF_WZ_HT_Fenster_valveMaximum 		"valvemaximum [%s]" 				<temperature> 	(gGF_WZ_HT_Fenster) 							{ maxcube="KEQ0380055:type=valvemaximum" }
Number 	GF_WZ_HT_Fenster_valveOffset 		"valveoffset [%s]" 					<temperature> 	(gGF_WZ_HT_Fenster) 							{ maxcube="KEQ0380055:type=valveoffset" }
String 	GF_WZ_HT_Fenster_programData 		"programdata [%s]" 					<temperature> 	(gGF_WZ_HT_Fenster) 							{ maxcube="KEQ0380055:type=programdata" }

### CODE REVIEW

**Comment by marcelrv** [comment]
@habnefrage note: this one should not be copied to OH2, as for OH2 we will implement this in a different way most probably (as thing configuration, which is currently under development).

**Comment by teichsta** [comment]
since you've reformatted the classes reviewing is quite hard. Can you give an indication what have changed? Can you also please fix the Merge conflict? Please don't forget to squash your commits into one once this PR ready. Thanks, Thomas E.-E.

**Comment by teichsta** [comment]
any news @habnefrage?

**Comment by teichsta** [comment]
any chance to get this done until the coming weekend @habnefrage?

**Comment by teichsta** [comment]
any chance to get this done today?

**Comment by marcelrv** [comment]
We haven't heard from @habnefrage for a month.
For OH2 I've fixed the merge problems.

For this one it's bit more complicated due to the reformat, hence would like him to pick it up.

**Comment by teichsta** [comment]
thanks for the update Marcel! Let's touch wood that he manage to work on this today …

**Comment by teichsta** [comment]
i've manually merged this into master. Would be great if you could have a look. Thanks, Thomas E.-E.

**Pull request closed without merging**
