### PR TITLE
Only listen to changed events, not updates.

### PR DESCRIPTION
**Pull request by digitaldan**
The rest code was broadcasting both update and changed events, we only want to push changed message. Note, i did no cleanup or formatting changes as the already commented out code may prove useful as a guide for later debugging.  This was in reference to PR #2233 and a conversation around caching.

### CODE REVIEW

**Comment by digitaldan** [comment]
@teichsta, i was looking back through the commit history to see when this code was added, I found https://github.com/openhab/openhab/commit/f025f609a7494f3d19fb8cf3de5373dd5a2462c4  which was titled "merged khome's atmosphere fix"  , do you know what this was fixing?  Looking at the commit, I can't tell if  subscribing to updates was intentional or not.  For reference, the commit subscribed to both update and changed messages which ends up delivering a lot of noise to rest clients that only care about changed data.  My PR is commenting out the subscribing to updates, so that only changed data is delivered.  Thanks!

**Comment by teichsta** [comment]
> do you know what this was fixing

no, admittedly i can't remember anymore! If i got the discussion in #2233 and at  https://groups.google.com/d/msg/openhab/UeexB3MRLBU/T-_NXi5MVrAJ correctly the noise should be handled even by small devices. Do you have any figures?

**Comment by digitaldan** [comment]
In a basic case if I have 5 bindings that poll every 5 seconds, and each binding has 5 items, that means we are sending down 25 items over 5 seconds to REST clients, which is basically all the time, even though nothing has changed.  I agree even small clients can handle this, but those on cellular connections are strained, and devices left on all the time such as touch panels end up wasting a lot of cpu.  The issues we recently addressed in the REST binding had far more volume then this, items were being updated several times per second even thought the values had not changed.  

This PR keeps everything intact with the original  commit, but without subscribing to updates which I now understand was the original intent of the system. From the discussion you mentioned I now realized that the system understands changed vs updated events, which you would think I would know by now ;-)   So I think this is the correct behavior ( and how it use to be)

 Also if I read the comment above the line I disabled it reads "don't react on update events" , so maybe this was just a mistake left in during some testing or debugging? I feel good about this so far in my testing.

**Comment by teichsta** [comment]
ok, let's try this "fix" ;-)

**Comment by digitaldan** [comment]
Fingers crossed!

**Pull request merged**
