### PR TITLE
Homematic: Configurable connection timeout for CcuClient

### PR DESCRIPTION
**Pull request by gerrieg**
see https://github.com/openhab/openhab/issues/2686

### CODE REVIEW

**Comment by gerrieg** [comment]
I have made it yet configurable, see: https://groups.google.com/d/topic/openhab/gcc-YYjxhcg/discussion

**Comment by teichsta** [comment]
Hi @gerrieg thanks for taking over! This PR looks good to me. Could you please squash your commits into one finally? Thanks, Thomas E.-E.

**Comment by gerrieg** [comment]
@teichsta 
I got some errors while squashing, i don't know if this is OK now. If not, just delete this PR, i will make a new one.
BR, Gerhard

**Comment by teichsta** [comment]
hmm … i still see 5 commits … would be great if you could try again or create a new PR (referencing this) Thanks, Thomas E.-E.

**Comment by teichsta** [comment]
superseded by #2728

**Pull request closed without merging**
