### PR TITLE
[plugwise] Fix #1003: high CPU load

### LINKED ISSUE #1003: high CPU load with plugwise
With plugwise Binding The CPU load is ~80%, without plugwise binding is ~ 30%.

In the openHAB community is also Another guy hase detail information.
http://goo.gl/2I020E

### PR DESCRIPTION
**Pull request by jowiho**
Fixes #1003

Fixed high CPU load of plugswise binding, by removing a busy
loop in the sendMessage code.
Simplified sending and proecssing of messages by replacing misused
Quartz jobs with straightforward background threads. Clean up
locking of the various queues in the Stick.

### CODE REVIEW

**Comment by teichsta** [comment]
Thanks @jowiho for this contribution. Can somebody else (except you) confirm this fix works? Others created discussion threads at community.openhab.org in order to find Testers …

**Comment by jowiho** [comment]
Hi @teichsta, I've posted a request for testing in the original issue thread. Let's see if anyone responds.

**Comment by teichsta** [comment]
great, thanks!

**Comment by watou** [comment]
@jowiho Has anyone responded on the forum, or could you ask for testers again?  Thanks for this.

**Comment by jowiho** [comment]
@watou There's one reply on the forum (https://github.com/openhab/openhab/issues/1003) that confirms that my patch does what it is supposed to do.

**Comment by watou** [comment]
@jowiho Thanks, did you make a discussion topic on the forum at https://community.openhab.org/ ?  Many more potential plugwise users are likely to read https://community.openhab.org/ than the issues list.  It's encouraging that one user did report success.  Do you think this needs further testing?  In any case, could you resolve the conflicts to prepare it for merge?  Many thanks!

**Comment by teichsta** [comment]
>  In any case, could you resolve the conflicts to prepare it for merge?

@jowiho could you please?

**Comment by jowiho** [comment]
I'll fix the conflict as soon as I have time (within a few days).

**Comment by jowiho** [comment]
@teichsta I've resolved the merge conflicts. The PR is ready for merge again.

**Comment by jhoekstra** [comment]
Is there a way to test this binding with a repo based install? Got very high CPU-usage as well using plugwise.

**Comment by watou** [comment]
@Jhoekstra I just made a [JAR](https://dl.dropboxusercontent.com/u/4286376/pr-4162/org.openhab.binding.plugwise-1.9.0-SNAPSHOT.jar) from the current state of this PR, where you could replace the current JAR with it.  Please report back here if it appears to work as advertised, or if it doesn't.

**Before merging this PR**, please verify that it's properly rebased to master, because I pulled the PR locally to build the JAR, and the list of changed files I see in SourceTree seems incorrect.

**Comment by jhoekstra** [comment]
With the binding from Watou I see a considerable drop in load.
CPU usage went down from 75-80% to 10-15% on a dualcore VM.
So works as advertised :)

**Comment by watou** [comment]
Great news!  Now to verify that the PR files changed are correct before merge, as mentioned above. Thanks for testing @jhoekstra!

**Comment by teichsta** [comment]
since the PR shows one changed files nothing else seem to be changed … i certainly didn't get your point @watou

**Comment by watou** [comment]
The PR branch looked like it had other commits in it, but it seems OK on reinspection, so please proceed without any delay on my account.

**Comment by watou** [comment]
Thanks @jowiho!  Could you and @jhoekstra test the [Cloudbees build](https://openhab.ci.cloudbees.com/job/openHAB1-Addons/lastSuccessfulBuild/artifact/bundles/binding/org.openhab.binding.plugwise/target/) build # 1259 or later (after this merge; build not ready as of this writing)?  Just to double check all is well?

**Comment by jhoekstra** [comment]
Seems ok to me, low load and switching like before.

**Comment by watou** [comment]
Great to hear that, thanks @jhoekstra!

**Pull request merged**
