### PR TITLE
add support for 220V 30-amp Load Controller N/O

### PR DESCRIPTION
**Pull request by larizzo**

### CODE REVIEW

**Comment by teichsta** [comment]
@berndpfrommer would be great if could have a look into this one, please …

**Comment by robnielsen** [comment]
@teichsta  see https://community.openhab.org/t/insteonplm-support-for-2477sa1-insteon-load-controller-relay/10288/8

**Comment by berndpfrommer** [comment]
Looks good to me, can go in. I have already updated the Wiki accordingly.

**Comment by teichsta** [comment]
great, thanks guys!

**Pull request merged**
