### PR TITLE
reapply code cleanup done in 3df021d2bd82797ff09b3c367a70ac583577cd06

### PR DESCRIPTION
**Pull request by teichsta**
some of the files cleaned up by @kaikreuzer in 3df021d2bd82797ff09b3c367a70ac583577cd06 has been readded by accident later. This PR removes these files again. @watou @kaikreuzer could you please have a quick look at this one, please?

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Thanks @teichsta, lgtm. Let's wait if Jenkins is happy as well and we should be good to merge.

**Comment by teichsta** [comment]
Thanks @kaikreuzer for the quick response!

**Comment by peuter** [comment]
Is there a reason why the CometVisu backend has been deleted from the repo?

**Comment by watou** [comment]
@peuter Only addons remain on the master branch in this repo.  The 1.8 branch has the full 1.x distro. Not sure this answers your question?

**Comment by peuter** [comment]
@watou Thanks for clearing that up. If I get that right, the current master branch (and later 1.9.x release) will only provide the 1.x addons for openHAB2, and there will be no full blown 1.9.x release. Right?

**Comment by teichsta** [comment]
> and there will be no full blown 1.9.x release. Right?
correct!

The full-blown release is ESH/OH2 based and contains 1.9-er bindings incorporating the combat-layer …

**Pull request merged**
