### PR TITLE
a few bug fixes to make the addons work on openHAB 2 (Karaf)

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by maggu2810** [comment]
Seems your formatter does not work.

**Comment by kaikreuzer** [comment]
It worked and I had to disable it, because it changed the complete files. Remember that we are here at openHAB 1, where hardly any code complies to the openHAB 2 formatter!

**Comment by maggu2810** [comment]
> we are here at openHAB 1

Didn't realize that.

**Comment by teichsta** [comment]
since we didn't require any special formatter other than the Eclipse build-in one. Shall we apply the formatter to all files once? And require the ESH formatter after that?

**Comment by kaikreuzer** [comment]
> Shall we apply the formatter to all files once? And require the ESH formatter after that?

Probably after the 1.8 release, when we remove the runtime & designer code and switch to the openHAB 2 IDE.

**Comment by teichsta** [comment]
Thanks, Kai!

**Pull request merged**
