### PR TITLE
MyQ Device fixes

### PR DESCRIPTION
**Pull request by computergeek1507**
Changed trace to debug level for device data. Added new device name to regex. Fixed door state logging.

### CODE REVIEW

**Comment by watou** [comment]
Discussion [here](https://community.openhab.org/t/chamberlain-myq-binding/4192/34)

**Comment by teichsta** [comment]
could you please squash your commits @computergeek1507?

Thanks, Thomas E.-E.

**Comment by computergeek1507** [comment]
@teichsta I think it's good to go.

**Comment by teichsta** [comment]
Thanks @computergeek1507!

**Pull request merged**
