### PR TITLE
GPIO binding enhancements and fix for Debian package issue

### PR DESCRIPTION
**Pull request by dpslavov**
New functionality for GPIO binding: pinmaps, console commands and possibility to forcibly take control of already exported pins.
Fix for Debian package for runtime, extract "webapps/static/index.html" into "/var/lib/openhab".

### CODE REVIEW

**Comment by teichsta** [comment]
Hi @dpslavov, any chance to carve out the Debian package fix into a separate PR? We are going to release a 1.6.2 Bugfix Release soon which contains a series of fixes. Best, Thomas E.-E.

**Comment by teichsta** [comment]
HI @dpslavov any news? Would you be able to split the PRs? Best, Thomas E.-E.

**Comment by teichsta** [comment]
@theoweiss could you please have a look at this PR?

**Comment by theoweiss** [comment]
Yep.

**Comment by teichsta** [comment]
@theoweiss any chance to get the deb packages stuff into 1.7?

**Comment by theoweiss** [comment]
The changes to distribution/pom.xml are not needed anymore, with PR #2141 the approach of handling the permissions has changed. The changes to distribution/pom.xml should be removed from this PR.

The other deb packaging related changes are needed for beaglebone.pinmap. I suggest: if beaglebone.pinmap is static it should be moved to org.openhab.io.gpio as a resource of the bundle, if not the configuration should go to openhab.cfg.
Furthermore as far as I can see the current approach would only work if openHAB was installed using the deb files.
@dpslavov could you revert the changes to distribution/pom.xml and explain the beaglebone.pinmap.

**Comment by teichsta** [comment]
@dpslavov any chance to incorporate the suggested feedback? Otherwise we are going to close this PR. Best, Thomas E.-E.

**Comment by JSurf** [comment]
I am very interested in the 'force option' commit making it into OH.

https://github.com/dpslavov/openhab/commit/3f3bacf844cce8de1dd67ef12eb8b4d844cbc2ff

if this pull request is closed without merge i could create a new pull request with this option only
I have no interest in the other changes and have also no knowledge about pinmaps

**Comment by teichsta** [comment]
@JSurf yes, please go ahead!

**Comment by dpslavov** [comment]
Well, after 6 months I'm no longer interested this PR to be merged. Do whatever you like with this PR.

**Comment by teichsta** [comment]
ok, then i'll close this PR and appreciate a new PR by you, @JSurf

**Pull request closed without merging**
