### PR TITLE
Netatmo binding for Netatmo Weather and Netatmo Welcome

### PR DESCRIPTION
**Pull request by wep4you**
I have successfull implemented the Netatmo welcome binding #3815 into the Netatmo binding, and did some refactoring, and also add new keyword weather for the configuration. For backward compatibility i left the config without the keywords welcome or wether default as weather config.

With this implementation there is also issue #3225 closed, this is now the implementation. For correct use the wiki has to be updated after the code was merged.

@watou @robnielsen @clinique Response about the changes would be nice

@napoleonmm83 @steve-bate Info because of the issue #3225

### CODE REVIEW

**Comment by robnielsen** [comment]
@wep4you is it possible to get the code up to date with openhab master, then add in your changes. It's going to be hard to review when it contains both code reformatting and new functionality.

**Comment by wep4you** [comment]
@robnielsen i already merged the Code with OpenHab Master before i sent the push request, so all is included. The binding runs for netatmo weather station and netatmo welcome in my production environment since yesterday without a problem.

**Comment by napoleonmm83** [comment]
where i can get the file

**Comment by robnielsen** [comment]
@wep4you. It appears that you've synced up with an earlier version of master that doesn't have the code reformatting, nor the other updates that were done in the past week by Thomas. If you look at the history for openhab/master (https://github.com/openhab/openhab/commits/master/bundles/binding/org.openhab.binding.netatmo) and your PR (https://github.com/wep4you/openhab/commits/master/bundles/binding/org.openhab.binding.netatmo) you'll see that there are 5 commits missing, including one for new functionality for multiple station support.

**Comment by wep4you** [comment]
@robnielsen Hmm I tried a code merge with synchronize, didn't work with gut before. I'll try to get the commits to my master, but don't know how exactly to do this so I'll read the guy docu ;)
Hopefully I find the right way. Is it possible to get this in the push request or do I have to cancel and commit again?

**Comment by wep4you** [comment]
@napoleonmm83 The code is in my fork it's not merged back at the moment, but I work on it. The binary is not published jet

**Comment by robnielsen** [comment]
@wep4you, You should be able to use the same PR. You can force push to replace what's on github. You might also want to squash your commits into a single commit, you'll need to do this before the PR gets merged.

**Comment by wep4you** [comment]
@robnielsen Thanks for the links i see what im missing from the log. Can you tell me wich is the best way to get this changes in my master branch. I think i should tag my changes in my fork. Go back to the head without my changes. Put all commits form openhab master to my fork (but don't know how), and then merge the changes from my tagged files, after this do a squash (have already done so i know how) and do a force commit on my PR?

**Comment by robnielsen** [comment]
Hi @wep4you, your approach sounds reasonable, but I'd take a more cautious approach by manually re-doing your changes to make sure you don't accidentally undo some other changes. BTW, are you aware that there is a netatmo test project that has some simple unit tests for the netatmo binding?

BTW, you'll want to make sure you grab from openhab/master today, it contains a PR that I submitted for OH2 support.

**Comment by wep4you** [comment]
@robnielsen I have problems to get a clean build of the openhab master so i don't know how long it takes to get the build working, after that i can merge the code, and ill grab the latest changes

**Pull request closed without merging**
