### PR TITLE
Update to new ESH feature

### PR DESCRIPTION
**Pull request by dvanherbergen**
In preparation of https://github.com/openhab/openhab-distro/issues/11

Signed-off-by: Davy Vanherbergen <davy.vanherbergen@gmail.com>

### CODE REVIEW

**Comment by teichsta** [comment]
also cherry picked onto 1.8

**Comment by watou** [comment]
Did [build #175](https://openhab-ci.innoq.io/jenkins/view/openHAB/job/openhab-1/175/) fail due to this merge?
```
...
[ERROR] Failed to execute goal org.apache.karaf.tooling:karaf-maven-plugin:4.0.3:verify (verify) on project openhab-addons-verify: Verification failures -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :openhab-addons-verify
```

**Comment by teichsta** [comment]
already working on it …

**Comment by kaikreuzer** [comment]
Should be fixed by https://github.com/openhab/openhab/pull/3713

**Pull request merged**
