### PR TITLE
Fibaro RGBW

### PR DESCRIPTION
**Pull request by drewwaite**
Issue #3662

### CODE REVIEW

**Comment by drewwaite** [comment]
Attempt #2. That looks better.

**Comment by cdjackson** [comment]
The PR looks better (thanks),  but I don't think you've put the reference in the right place? If this is meant to be for the RGB, then it's not correct as you've put it in with the roller shutter...

**Comment by cdjackson** [comment]
Oh - to fix this, don't change the PR - just move the lines to the right place (assuming it's wrong), recommit and push - it will update the PR automatically.

**Comment by drewwaite** [comment]
Opps. My error. I didn't realise the "item label" was at the bottom. Fixed.

**Comment by cdjackson** [comment]
It is in this case, and probably most cases, but you need to look at the structure of the XML - the reference needs to go inside the Product tag for the right product - it’s not about the order or the elements…

**Comment by cdjackson** [comment]
Thanks.

**Pull request merged**
