### PR TITLE
[MyStrom] Reduces http call due to complaint of mystrom.

### PR DESCRIPTION
**Pull request by coolweb**
Improve performance of Mystrom binding by reducing http calls to mystrom server.
It's an important fix because mystrom had performance issue on their servers without this improvement.

@teichsta Could you review it?
Thx.

### CODE REVIEW

**Comment by watou** [comment]
@coolweb, what led to all the reformatting?  Ideally, the reformatting had already been done by @teichsta after the 1.8 release, and your PR would only have the code changes without reformatting, so it will be clearer what has changed for the purpose of review.  Was this PR based on the latest master branch?  If somehow the IDE formatting wasn't already on master, could you make a separate PR that only reformats?

Also, for all `@since` JavaDoc tags, could you fix them to be `1.8.0` for those files you edited and didn't create (and also remove the `-SNAPSHOT` parts).  Only new files you're introducing here should be marked `1.9.0`.

**Comment by coolweb** [comment]
@watou yes it is based on latest version of master. So the only solution is to delete my fork and this PR and do a new one for the formatting and after it is accepted do a new one for the code fix? That's right?

**Comment by watou** [comment]
@coolweb maybe not the only solution, but a good one that will deal with the two issues separately (1. Formatting only changes, since not correct w.r.t. current IDE setup, 2. Your binding fixes.).  Would that be OK?

**Comment by coolweb** [comment]
@watou my ide setup is the setup from openhab eclipse installer...

**Comment by watou** [comment]
> my ide setup is the setup from openhab eclipse installer...

Perfect.

**Comment by coolweb** [comment]
@watou  I do a new pull request, I don't know why but from a fresh install, the code formatting seems to be good in eclipse. The new pull request contains removing the keyword `snapshot` and the fix to reduce http call, the new pull request is: #4295 

Thx.

**Comment by watou** [comment]
Closing in preference to #4295.

**Pull request closed without merging**
