### PR TITLE
added washingmachine and dryer image

### PR DESCRIPTION
**Pull request by SimonButtazzi**
As there was no icon for dryer, I added a set of icons in different states for both devices.

### CODE REVIEW

**Comment by teichsta** [comment]
Great, thanks a lot! What is the license of these icons? Did you create them yourself?

**Comment by SimonButtazzi** [comment]
Hi Thomas,
yes, I created them by myself and I would be happy for every usage. Doesn't matter where or by whom :-)

Are there other icons missing I can create if I have time and matching ideas?

Simon

**Comment by teichsta** [comment]
Thanks @SimonButtazzi

**Comment by teichsta** [comment]
ftr: PR at openHAB2: https://github.com/openhab/openhab2/pull/359

**Pull request merged**
