### PR TITLE
Freebox binding: fix phone calls handling (fix #4363)

### LINKED ISSUE #4363: Freebox binding: phone calls not correctly handled
When a new phone call is established, the Freebox creates a new call entry with a duration set to 0. The call entry is updated with a right duration when the phone call is closed.
If the refresh occurs while a phone call is opened, the item linked to the duration is set to 0 and never updated when the call is closed.
The fix is that a phone call with a duration set to 0 should not be considered by the binding.

I will provide the fix.

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: Laurent Garnier lg.hc@free.fr

### CODE REVIEW

**Comment by lolodomo** [comment]
Please include if possible this fix in coming 1.8.3.

**Comment by kaikreuzer** [comment]
@lolodomo This class is completely out of sync with the 1.8 branch - if something needs to be fixed on 1.8.x, please create a separate PR directly for the 1.8 branch. Thanks!

**Comment by lolodomo** [comment]
@teichsta applied à full reformating in January 2016.

**Comment by watou** [comment]
Did you consider and decide this isn't a critical bug for the 1.8 branch before changing the milestone, @kaikreuzer?  Also, the advice to create separate PRs for the two different branches is contrary to @teichsta's prior instructions on that subject.

Let's handle PRs with consistent guidelines, please, and thanks!

**Comment by lolodomo** [comment]
What a pity to not include all fixes in next 1.8 release ! But it is not really a critical bug. And by the way advanced users like me know where to get the 1.9 jar file.

Wouldn't it be the time to think about releasing a 1.9 version rather than a 1.8.3 ?

**Comment by watou** [comment]
> What a pity to not include all fixes in next 1.8 release !

I have been told that maintenance releases are only to contain fixes to critical bugs, but I have never fully understood the detailed reasoning for that, especially in light of the previous decision that there will never be a 1.9 distribution.  There is a tradeoff needed because of limited developer resources to maintain multiple active paths, but I would like to see a discussion at the community site that opens this subject for wider understanding.

**Comment by lolodomo** [comment]
I could understood that there will never be a 1.9 runtime released but of course we will absolutely need a 1.9 zip with all up-to-date (and new) 1.x bindings. If not, all PR submitted by developers since beginning of 2016 will never reach normal users ! For example, I hope that my Powermax binding will at least be released one day for 1.x users. Other example, this fix, should be at least available one day for 1.x users.

**Comment by kaikreuzer** [comment]
> Let's handle PRs with consistent guidelines, please, and thanks!

This PR simple cannot be cherry-picked on 1.8 as it results in merge conflicts, that's all - it is not at all a decision on whether or not is is applicable for 1.8.x - that's why I asked specifically for a PR for the 1.8 branch.

>  PRs for the two different branches is contrary to @teichsta's prior instructions on that subject

Sorry, I must have missed that. Do you please have a reference?

>  but of course we will absolutely need a 1.9 zip with all up-to-date (and new) 1.x bindings

Absolutely, that was the whole idea about the 1.9 version.

**Comment by watou** [comment]
> This PR simple cannot be cherry-picked on 1.8 as it results in merge conflicts, that's all - it is not at all a decision on whether or not is is applicable for 1.8.x - that's why I asked specifically for a PR for the 1.8 branch.

@teichsta had been routinely cherry picking and fixing merge conflicts in PRs submitted against master onto 1.8.  Is this no longer possible or no longer advisable?  It seems much cleaner to not have to duplicate PRs for different branches.

> Sorry, I must have missed that. Do you please have a reference?

It was a comment @teichsta made to me some months ago when there were duplicate PRs to separate branches, but it's deep in the history somewhere.  If you really want me to present it to you, please let me know and I will keep looking for it.

> > but of course we will absolutely need a 1.9 zip with all up-to-date (and new) 1.x bindings

> Absolutely, that was the whole idea about the 1.9 version.

Great!  And we will have updated .debs in the apt-repo for the 1.x addons as well?

**Comment by kaikreuzer** [comment]
> Is this no longer possible or no longer advisable?

No, it was only my incapacity to do it :-/ So I'll happily leave it to you guys to correctly cherry-pick it, if this is possible. Sorry for having interfered here at all (background: I just felt that this fix was important for @lolodomo and I am creating a 1.9.0.b3 build, which I need as a stable version for the new OH2 distro release, so I wanted to include it in 1.9.0 asap.)

> If you really want me to present it to you

Nonono, I believe you, I just thought you might have it at hand!

> And we will have updated .debs in the apt-repo for the 1.x addons as well?

I guess so - but this is completely up to the 1.x maintainers, so best discuss that with @teichsta.

**Comment by watou** [comment]
My mistake for assuming this PR was critical for 1.8.3 so I think the merge issue is moot here, but thanks @kaikreuzer for clarifying.

**Comment by kaikreuzer** [comment]
> My mistake for assuming this PR was critical for 1.8.3

Uhm, I personally cannot (and don't want to) judge whether it is critical for 1.8.3 or not. All I am saying is that I am too dumb to cherry-pick it to 1.8, so this is up to whoever decides whether it will be included there or not.

**Comment by watou** [comment]
>  judge whether it is critical for 1.8.3 or not

@kaikreuzer: @lolodomo said it is not really a critical bug earlier, so I think your moving it to 1.9.0 ended up being the right disposition unless @teichsta thinks otherwise.

**Comment by kaikreuzer** [comment]
Ah, you are right, I missed that. Thanks :-)

**Comment by haltmann** [comment]
Hello,
I was reading an article and suddenly came accross those words, they are just perfect, you can find the article here <http://amazing.aantrav.com/e4qcrbk>
Hope this helps, herbert.altmann@heal-it.info

**Comment by haltmann** [comment]
Hi,

I thought you might be interested in that list of books I made especially for you, just take a look <http://advantage.msin.us/e4nlietw>

Warmest regards, herbert.altmann@heal-it.info

**Comment by lblabr** [comment]
Hello,

I have recently read an interesting article that you may like, please read it, you won't regret! Here is the link <http://belief.ryansrally.org/e2cvhhl>

Faithfully, sexdating@lb-automation.de

**Comment by lblabr** [comment]
Hi! 
Have  you seen  this stuff?  I think it's great,  lust take  a  look here <http://show.assistprofessionals.com/e2ipa>

Sincerely, sexdating

**Comment by lblabr** [comment]
Hello friend,  I just read an article that you might be interested in, you won't  regret, please read it here <http://wanted.datapros-edutech.com/e2givkh>

Yours, sexdating

**Comment by lblabr** [comment]
Hi friend! 

I've finally found that stuff and it  looks  nice, just look at it here <http://interest.imageinquiry.com/e2dbg>

My Best, sexdating

**Comment by lblabr** [comment]
Hey friend, 


Look at that! Wooow! It's so amazing and interesting, and even sometimes shocking! Just take a look here <http://noboruto.shellyhutchinson.com/e2jmhgk>


Warm regards, sexdating

**Comment by lblabr** [comment]
Hello, 

Have you ever seen such  a cool  thing before! I swear you haven't! Check it out <http://netrerdapy.aboffices.com/e2yyjft>

Speak to you later, sexdating

**Comment by lblabr** [comment]
Hi! 

We've had an  amazing days  out  of town this weekend, just  take a look at the  place we've been to, here are  some pictures <http://chyspeshanti.savemorepc.com/e2nwi>

Best wishes, sexdating

**Comment by lblabr** [comment]
Hello! 

Here is a  nice selection of great places to  visit,  just  take  a look  at my list <http://ceslosypu.mi11i0naire.org/e2ktgc>

Rushing, sexdating

**Pull request merged**
