### PR TITLE
New devices and xcore/emf Mars and newer compatibility

### PR DESCRIPTION
**Pull request by theoweiss**
Don't merge yet. This PR is not yet ready, some code is missing for Stepper and AnalogOut.
This PR adds new devices and xcore/emf Mars and newer compatibility.

### CODE REVIEW

**Comment by theoweiss** [comment]
I would like to merge this PR before the b5 release. Stepper is not yet integrated but lots of fixes and enhancements. There is a thread in the german tinkerforge forum with lots of tests and feedback: http://www.tinkerunity.org/forum/index.php/topic,1769.285.html

If no one objects I would merge this PR next week.

**Comment by 9037568** [comment]
I did a fast scan through, and I only have one comment for consideration.

Several of the newly added files are missing their copyright/license headers. I think those need to be added.

**Comment by theoweiss** [comment]
@9037568 thanks for checking this out. I'll update the files accordingly.

**Comment by theoweiss** [comment]
@sihui62 could you again contribute the docs like you did it the last time?  It would be great! You will find configuration examples here https://github.com/theoweiss/openhab-tinkerforge-configuration-examples and here https://github.com/theoweiss/openhab2-tinkerforge-configuration-examples. I'll checkout whats new at all.

**Comment by sihui62** [comment]
> could you again contribute the docs like you did it the last time?

Sure, will fork and submit a PR as soon as I have something available (could take some time ...)

**Comment by theoweiss** [comment]
@sihui62 thanks!

**Comment by theoweiss** [comment]
@9037568 I've added the licence headers - hopefully I've got them all.

**Comment by 9037568** [comment]
Thanks @theoweiss 

Eclipse still found 2 files in need of reformatting:
        modified:   src/main/java/org/openhab/binding/tinkerforge/internal/model/IndustrialDualAnalogInDevice.java
        modified:   src/main/java/org/openhab/binding/tinkerforge/internal/model/ModelPackage.java

**Comment by theoweiss** [comment]
Thanks @9037568 I'll fix it this evening.

**Comment by theoweiss** [comment]
@9037568 I've pushed the formatting changes.

**Comment by 9037568** [comment]
Thanks, @theoweiss ! LGTM.

**Comment by theoweiss** [comment]
As far as I understand I can merge this now?

**Pull request merged**
