### PR TITLE
Added support for Insteon FanLinc module, model 2475F.

### PR DESCRIPTION
**Pull request by BrianTillman**
@teichsta Replacement PR for #3139

### CODE REVIEW

**Comment by berndpfrommer** [comment]
Brian,

I just submitted PR #3205, which will conflict with yours.

@teichsta I suggest to proceed with this PR (#3180). Once merged I will resolve the conflicts with #3205.

Brian,
With my new pull request I added some flexible handlers that could have allowed you to write the FanLinc support (almost) entirely by modifying the xml files, without adding new java code.
Once your PR has gone through I will rewrite your handlers using the new code base. Would be nice if you could test again once that has happened!

**Comment by BrianTillman** [comment]
@berndpfrommer Awesome! -- Give me a shout when you're ready for me to test.

**Comment by berndpfrommer** [comment]
@teichsta Please merge this PR when you have time, thanks!

**Comment by teichsta** [comment]
Thanks @BrianTillman and @berndpfrommer you can now proceed with #3205

**Comment by berndpfrommer** [comment]
@BrianTillman I'm looking over the code right now as I'm migrating it, and think I found a bug:
In the command handler, you are sending the message twice, once before you even set the userdata1 = 0x02. Is that on purpose?


+				Msg m = null;
+
+				switch (dc) {
+				case 1:            //Turn fan off
+					m = dev.makeExtendedMessage((byte) 0x0f, (byte) 0x11, (byte) 0x00);
+					dev.enqueueMessage(m, m_feature);
+					logger.info("{}: sent msg to fan OFF", nm());
+					break;
+				case 2:            //Set fan speed to low
+					m = dev.makeExtendedMessage((byte) 0x0f, (byte) 0x11, (byte) 0x55);
+					
+					logger.info("{}: sent msg to set fan to low speed", nm());
+					break;
+				case 3:            //Set fan speed to medium
+					m = dev.makeExtendedMessage((byte) 0x0f, (byte) 0x11, (byte) 0xAA);
+					dev.enqueueMessage(m, m_feature);
+					logger.info("{}: sent msg to set fan to medium speed", nm());
+					break;
+				case 4:            //Set fan speed to high
+					m = dev.makeExtendedMessage((byte) 0x0f, (byte) 0x11, (byte) 0xFF);
+					dev.enqueueMessage(m, m_feature);
+					logger.info("{}: sent msg to set fan to high speed", nm());
+					break;
+				default:
+					break;
+				}
+				
+				if (m != null) {
+					m.setByte("userData1", (byte)0x02);
+					dev.enqueueMessage(m, m_feature);
+					m = null;
+				}
+

**Comment by BrianTillman** [comment]
Almost certainly an oversight. I don't believe the the messages sent without userdata1 set to 0x02 are doing anything of value (likely not causing any harm either, with the exception of overhead).

**Pull request merged**
