### PR TITLE
multiple recipients to sendMail is added

### PR DESCRIPTION
**Pull request by erdemlal**
https://github.com/openhab/openhab/issues/771#issuecomment-34875578

### CODE REVIEW

**Comment by teichsta** [comment]
Hi @erdemlal, thanks a lot for this contribution! Could you please also update the https://github.com/openhab/openhab/wiki/Actions Wiki page? Thanks, Thomas E.-E.

**Comment by devTechi** [comment]
Thank you! @erdemlal @teichsta

**Comment by erdemlal** [comment]
Your welcome, @teichsta i've updated wiki page, https://github.com/openhab/openhab/wiki/Actions/2621a5692aa2ab21c746a7cc7c09752690e11b6b

**Comment by teichsta** [comment]
great, thanks!

**Pull request merged**
