### PR TITLE
Issue#2362 Core-Rules: Rule threading/Context corruption issue (Thread Safety)

### PR DESCRIPTION
**Pull request by mrguessed**
See Issue #2362 for details.

I unravel any sharing of contexts, occurring within the file, so a unique `RuleEvaluationContext` is used in all cases.  Changes mostly relate to changing `executeRules(...)` calls, so they don't take a [shared] `RuleEvaluationContext`

The rest of the diffs are due to formatting changes (use of newer Eclipse openHAB profile)

After the change, the testcase from Issue #2362 is running correctly (tweaked TC to run every second instead of every 10)
```log
10:53:26.005 DEBUG o.o.m.r.i.e.ExecuteRuleJob[:53]- Executing scheduled rule 'context trigger'
10:53:26.005 INFO  o.o.m.script.context-trigger[:53]- Beforecontext trigger
10:53:26.006 INFO  o.o.m.script.context-trigger[:53]- Aftercontext trigger
10:53:26.006 DEBUG o.o.m.r.i.engine.RuleEngine[:305]- Executing rule 'context a'
10:53:26.007 DEBUG o.o.m.r.i.engine.RuleEngine[:305]- Executing rule 'context b'
10:53:26.007 INFO  o.o.model.script.context-a[:53]- context a
10:53:26.007 INFO  o.o.model.script.context-b[:53]- context b
10:53:27.005 DEBUG o.o.m.r.i.e.ExecuteRuleJob[:53]- Executing scheduled rule 'context trigger'
10:53:27.005 INFO  o.o.m.script.context-trigger[:53]- Beforecontext trigger
10:53:27.006 INFO  o.o.m.script.context-trigger[:53]- Aftercontext trigger
10:53:27.007 DEBUG o.o.m.r.i.engine.RuleEngine[:305]- Executing rule 'context a'
10:53:27.007 DEBUG o.o.m.r.i.engine.RuleEngine[:305]- Executing rule 'context b'
10:53:27.007 INFO  o.o.model.script.context-a[:53]- context a
10:53:27.008 INFO  o.o.model.script.context-b[:53]- context b
10:53:28.005 DEBUG o.o.m.r.i.e.ExecuteRuleJob[:53]- Executing scheduled rule 'context trigger'
10:53:28.006 INFO  o.o.m.script.context-trigger[:53]- Beforecontext trigger
10:53:28.007 INFO  o.o.m.script.context-trigger[:53]- Aftercontext trigger
10:53:28.007 DEBUG o.o.m.r.i.engine.RuleEngine[:305]- Executing rule 'context a'
10:53:28.007 DEBUG o.o.m.r.i.engine.RuleEngine[:305]- Executing rule 'context b'
10:53:28.008 INFO  o.o.model.script.context-a[:53]- context a
10:53:28.008 INFO  o.o.model.script.context-b[:53]- context b
10:53:29.005 DEBUG o.o.m.r.i.e.ExecuteRuleJob[:53]- Executing scheduled rule 'context trigger'
10:53:29.006 INFO  o.o.m.script.context-trigger[:53]- Beforecontext trigger
10:53:29.007 INFO  o.o.m.script.context-trigger[:53]- Aftercontext trigger
10:53:29.008 DEBUG o.o.m.r.i.engine.RuleEngine[:305]- Executing rule 'context a'
10:53:29.008 DEBUG o.o.m.r.i.engine.RuleEngine[:305]- Executing rule 'context b'
10:53:29.008 INFO  o.o.model.script.context-a[:53]- context a
10:53:29.009 INFO  o.o.model.script.context-b[:53]- context b
10:53:30.005 DEBUG o.o.m.r.i.e.ExecuteRuleJob[:53]- Executing scheduled rule 'context trigger'
10:53:30.005 INFO  o.o.m.script.context-trigger[:53]- Beforecontext trigger
10:53:30.006 INFO  o.o.m.script.context-trigger[:53]- Aftercontext trigger
10:53:30.006 DEBUG o.o.m.r.i.engine.RuleEngine[:305]- Executing rule 'context a'
10:53:30.007 DEBUG o.o.m.r.i.engine.RuleEngine[:305]- Executing rule 'context b'
10:53:30.007 INFO  o.o.model.script.context-a[:53]- context a
10:53:30.008 INFO  o.o.model.script.context-b[:53]- context b
10:53:31.005 DEBUG o.o.m.r.i.e.ExecuteRuleJob[:53]- Executing scheduled rule 'context trigger'
10:53:31.005 INFO  o.o.m.script.context-trigger[:53]- Beforecontext trigger
10:53:31.006 INFO  o.o.m.script.context-trigger[:53]- Aftercontext trigger
10:53:31.006 DEBUG o.o.m.r.i.engine.RuleEngine[:305]- Executing rule 'context a'
10:53:31.007 DEBUG o.o.m.r.i.engine.RuleEngine[:305]- Executing rule 'context b'
10:53:31.007 INFO  o.o.model.script.context-a[:53]- context a
10:53:31.008 INFO  o.o.model.script.context-b[:53]- context b
```

### CODE REVIEW

**Comment by teichsta** [comment]
Hi @mrguessed thanks for providing this fix. Since it touches the very core of the Rule-Engine i'll have to find some "quite" minutes in order to reproduce. Best, Thomas E.-E.

/cc @kaikreuzer

**Comment by mrguessed** [comment]
The test case is in the related issue #2362, and is very simple.  It won't take long for you to see the problem.

If you're planning a 1.6.x patchrelease patch then you may want it there also, as it's very easy to trigger when building real world HA rules.

**Comment by mrguessed** [comment]
@teichsta,
This bug should be listed in the 1.7.0 milestone, since it's very easy to hit in real-world Rule deployments.  I also think it should be labelled as a bug, not an enhancement.

**Comment by teichsta** [comment]
Thanks again @mrguessed if reproduced the issue and can confirm that it doesn't occur after applying your patch. Great work!!

**Comment by sumnerboy12** [comment]
Relates to this I believe; https://code.google.com/p/openhab/issues/detail?id=487

**Pull request merged**
