### PR TITLE
KNX1 some issues, improvements, updates

### PR DESCRIPTION
**Pull request by lewie**
changelog KNX1-issues-improvements-updates:
-  Issue: Updated calimero-core-2.3-beta.jar with improved KNX 'RequestedFlag' handling. See:  https://github.com/calimero-project/calimero-core/issues/32#issuecomment-208225076
-  Issue: Updated can not be called before the bundle is activated (down-to-earth solution)
-  Issue: Autorefresh, filled Requests, still were not deleted from the queue.
-  Improvement: ProcessListener replaced by ProcessListenerEx - for more granulated event event processing.
-  Improvement: For TUNNEL connections, sourceaddress ('busaddr' in config) is always set to '0.0.0'.
  Explaination: 
  If '0.0.0' is set as device/source address, means no/unset Address.
  Then the Tunnel addresses provided by the router can be used, 
  otherwise confirmation fails! 
-  Improvement: KNX Bundle now can respond  read requests.
  Explaination:
  An Item accepts read requests from OpenHAB EventBus as is OR it can respond read requests from the KNX bus. Both (< and >) makes no sense, because otherwise two devices could respond to the same requested address.
  
  examples: `(knx=">4/2/10), (knx=">4/2/10+0/2/10, 5.001:4/2/11+0/2/11")`
  
  `knx="`
  `[>]||[<[(<autoRefresh>)]][<dptId>:]<mainGA>[[+`
  `[>]||[<[(<autoRefresh>)]]<listeningGA>]+`
  `[>]||[<[(<autoRefresh>)]]<listeningGA>..],`
  `[>]||[<[(<autoRefresh>)]][<dptId>:]<mainGA>[[+`
  `[>]||[<[(<autoRefresh>)]]<listeningGA>]+`
  `[>]||[<[(<autoRefresh>)]]<listeningGA>..]`
  `"`
-  Update: calimero-core-2.3-beta.jar
-  Added: For better code investigation added to folder lib: calimero-core-2.3-beta-sources.jar and calimero-device-2.3-beta-sources.jar
-  Added: Using ProcessCommunicationResponder calimero-device-2.3-beta.jar is needed.

### CODE REVIEW

**Comment by kgoderis** [comment]
@lewie can you send me all the jars so that I can align in KNX 2.0?

**Comment by lewie** [comment]
@kgoderis, with pleasure: 

[calimero-core-2.3-beta-sources.jar](https://github.com/lewie/openhab/raw/KNX1-issues-improvements-updates/bundles/binding/org.openhab.binding.knx/lib/calimero-core-2.3-beta-sources.jar)

[calimero-core-2.3-beta.jar](https://github.com/lewie/openhab/raw/KNX1-issues-improvements-updates/bundles/binding/org.openhab.binding.knx/lib/calimero-core-2.3-beta.jar)

[calimero-device-2.3-beta-sources.jar](https://github.com/lewie/openhab/raw/KNX1-issues-improvements-updates/bundles/binding/org.openhab.binding.knx/lib/calimero-device-2.3-beta-sources.jar)

[calimero-device-2.3-beta.jar](https://github.com/lewie/openhab/raw/KNX1-issues-improvements-updates/bundles/binding/org.openhab.binding.knx/lib/calimero-device-2.3-beta.jar)

Testjar: [org.openhab.binding.knx-1.9.0-SNAPSHOT.jar](https://github.com/lewie/openhab/raw/TESTJAR-KNX1-issues-improvements-updates/org.openhab.binding.knx-1.9.0-SNAPSHOT.jar)

KNX1 works great now! :-)

**Comment by lewie** [comment]
I did not redesign KNX1 to a device for now, but it would be useful for KNX2 I think.

As you have already mentioned, we should think about to see the KNX2 binding as one 'BaseKnxDevice' or 'KnxDevice', see [PushButtonActuator.java](https://github.com/calimero-project/introduction/raw/master/examples/java8/PushButtonActuator.java)

It works great and it is a more comprehensible structure/design, suitable for KNX logic.

**Comment by lewie** [comment]
@teichsta, other maintainer,
this should definitely be used in 1.8.3 milestone, because the Issues are (a little) critical.

They cause no stop of the KNX Bus or the Binding, but they are the cause of many many indefinable problems.

**Comment by kgoderis** [comment]
> I did not redesign KNX1 to a device for now, but it would be useful for KNX2 I think.
> 
> As you have already mentioned, we should think about to see the KNX2 binding as one 'BaseKnxDevice' or 'KnxDevice', see PushButtonActuator.java
> 
> It works great and it is a more comprehensible structure/design, suitable for KNX logic.

I did study that part of Calimero, and it is not very well adapted to our needs either, e.g. concept of Things and Channels. But, we can reproduce some of the ideas of that repo in the binding (which I am currently doing).

**Comment by lewie** [comment]
Yes, I think so, Things and Channels to constrict into devices seams not to be a win.
Therefore I thought to see the OpenHAB Instance as ONE device. This device could manage multiple or a mass of  KNX addresses organized over abstraction in Things and Channels?!

**Comment by teichsta** [comment]
Thanks a lot @lewie for this contribution! However i'd like to discuss whether this PR should be merged into 1.8 completely. Could you please elaborate which of the changes are bugfixes and of them are enhancements. I'd love to update the lib and integrate fixes but we should move enhancements into another PR (for 1.9)

**Comment by lewie** [comment]
@teichsta, I did the enhancements first (which is not really an enhancement, in reality KNX binding was never complete), then I found all the other Problems.

The only "enhancement" for 1.9 I would detach, is: *KNX Bundle now can respond read requests.*

After I found out that 1.8.3 is around the corner, I have concentrated me on Issue and invested time to test and deliver clean work.




If you want to do a second PR for 1.9, it is really simple:
Comment out the Line 491 in  *KNXGenericBindingProvider.java*
```
--   isResponding = true;
++ //isResponding = true;
```
I do not think we need a new PR in Github, isn't it? ;-)

**Comment by teichsta** [comment]
hmm … since you've applied the ESH code formatter is quite hard to review your changes. Any chance to revert the formatting changes?

**Comment by lewie** [comment]
@teichsta, ahh ok sorry.

Have no eclipse here.

But formatting only in this 4 files changed too hard. The others are normal to review I hope.
https://github.com/openhab/openhab/pull/4282/commits/b987e6cd8e53bd750c721a13e27ba75536c905c9

MANIFEST.MF
```
 - lib/calimero-core-2.2.0-SNAPSHOT.jar,
 + lib/calimero-core-2.3-beta.jar,
 + lib/calimero-device-2.3-beta.jar,
```

knxbinding.xml
```
+   <reference bind="setItemRegistry" cardinality="0..1" interface="org.openhab.core.items.ItemRegistry" 
-      <provide interface="tuwien.auto.calimero.process.ProcessListener"/>
```

knxconnection.xml
```
-   <reference bind="setProcessListener" cardinality="1..1" interface="tuwien.auto.calimero.process.ProcessListener" name="ProcessListener" policy="dynamic" unbind="unsetProcessListener"/>
```

KNXBindingProvider.java
```
+    /**
+     * This method returns all datapoints, which allowed to respond (groupReadResponse) a request (groupReadRequest)
+     * from the KNX bus.
+     *
+     * @return all datapoints which allowed to respond on a request
+     */
+    public Iterable<Datapoint> getRespondingDatapoints();
```

If this is not enough, I have to have a look next weekend. :-(

Thanks in Advance...

**Comment by lewie** [comment]
@teichsta,
found the Time to do two PRs, this is for 1.9

The only difference to [1.8.3](https://github.com/openhab/openhab/pull/4285) is:
Line 491 in  *KNXGenericBindingProvider.java*:
```
-- //isResponding = true;
++ isResponding = true;
```

**Comment by lewie** [comment]
As discussed [here](https://github.com/openhab/openhab2-addons/pull/21#issuecomment-215410150), the enhancement to respond read requests, fits well from KNX perspective.

But from opemHAB perspective it is discouraged to respond through this binding.

From my perspective as an intensive daily user of knx binding, it is very important to use this feature finally. I do not want to miss, it works perfect! ;-)

We should decide in what way the "responding read requests" can be included in the main branch.

 1. Include in the main branch as is -> not perfect fitting from opemHAB perspective, but from KNX perspective.
 2. To program a second bundle -> done through a new "I/O" addon, [as proposed by Kai.](https://github.com/openhab/openhab2-addons/pull/21#issuecomment-215410150)

I would outsource the functionality into a new "knxio" addon. (It would be helpful, to see an another bundle as example of an "I/O" addon?!)

**Comment by lewie** [comment]
does not fit with OH architecture.

**Pull request closed without merging**
