### PR TITLE
Possible fix for HeatMiser Binding

### PR DESCRIPTION
**Pull request by SkynetHome**
An attempt at solving the problem mentioned in Issue #2177  and the
corresponding problem caused by my PR #2829

### CODE REVIEW

**Comment by cdjackson** [comment]
Thanks - I appreciate you taking a look at this, but I don't think this will work. It is however along the lines of what I was thinking but the issue is that there's a missing link with the items themselves, so there's no way to get the new variable out to the real world...

When I get some time I'll take a closer look...

**Comment by SkynetHome** [comment]
Thanks Chris, I know this is not a pressing issue now but I just thought I would take a stab at trying to solve it before it is. Let me know if there is anything else I can do!

**Comment by steve-bate** [comment]
@teichsta @cdjackson Should we close this pull request?

**Comment by teichsta** [comment]
to me it looks like the issue isn't really fixed by this PR. So could you @cdjackson and @SkynetHome please advise how to proceed with this PR? Thanks, Thomas E.-E.

**Pull request closed without merging**
