### PR TITLE
Weather: Removed org.openhab.ui dependency and added formatter

### PR DESCRIPTION
**Pull request by gerrieg**
see https://github.com/openhab/openhab/issues/2970

### CODE REVIEW

**Comment by teichsta** [comment]
Thanks @gerrieg for this update! This PR lgtm. Out of curiosity: the binding configuration won't be backwards compatible right?

**Comment by gerrieg** [comment]
Only the HTML layout files are not 100% backwards compatible, everything else is the same. I already updated the docs and put a new weather-data file with an updated html layout example on the wiki page.

**Comment by udo1toni** [comment]
I think I found a (very little) typo in example.html: At line 52 and 53 it has to be `forecast(1)` respectively `forecast(2)`

**Comment by teichsta** [comment]
> a (very little) typo in example.html

something to add to this PR?

**Comment by gerrieg** [comment]
@udo1toni 
Thank you for the hint, i fixed the new weather-data file

@teichsta 
No, nothing for this PR, just a example file on the wiki page.

**Comment by teichsta** [comment]
ok, thanks guys!

**Comment by staehler** [comment]
Hi, can I access openhab items within the html layout as before?
Till now I used to show values from my weatherstation as well, as here

                                        <tr>
                                                <td>Windstärke:</td>
                                                <td>${item:WeatherWind.value} km/h</td>
                                        </tr>

Regards, Michael

**Comment by gerrieg** [comment]
unfortunately no, i had to remove the item token :-(

**Pull request merged**
