### PR TITLE
Update Plex binding to support Plex Home

### LINKED ISSUE #3120: Can't get Plex Binding to work - 401 Error
Hi Folks,

Can't get the plex binding to work keep getting these errors:
 java.io.IOException: Server returned HTTP response code: 401 for URL: http://10.0.1.17:32400/clients

If I go to that url directly I get a 401.

My "List of networks that are allowed without auth" setting in plex is:
192.168.1.0/255.255.255.0,10.0.1.0/255.255.255.0

What am I doing wrong?

Thanks

### PR DESCRIPTION
**Pull request by idserda**
If you're using Plex Home the binding needs to know additional credentials to access the Plex server. This fixes #3120.

### CODE REVIEW

**Comment by teichsta** [comment]
Thanks for PR which LGTM already. I am wondering if you could change the configuration mechanism to follow the new mechanism (without using the ManagesService implementation). See the Binding archetype for more details …

**Comment by idserda** [comment]
Sure, I'll look into it.

**Comment by brettyj** [comment]
Any update? :)

**Comment by teichsta** [comment]
i'll merge this PR now without the changes of the configuration mechanismus. However It would be great if you could have a look into this @idserda. Thanks, Thomas E.-E.

**Comment by idserda** [comment]
Thanks! I'm working on some more updates for the binding, I'll incorporate the configuration change in that pull request.

**Comment by teichsta** [comment]
great, but please don't mix features in one PR. Each PR should represent a single Fix, Enhancement, etc …

**Pull request merged**
