### PR TITLE
2502 - fix for NumberFormatException

### PR DESCRIPTION
**Pull request by Chel**
Continued from https://github.com/openhab/openhab/pull/2519

Hopefully this time I've done it right.

### CODE REVIEW

**Comment by teichsta** [comment]
any chance to get this merged today, @theoweiss ?

**Comment by theoweiss** [comment]
I can do it this evening.

**Comment by theoweiss** [comment]
I just tested the influxdb persistence. So far it looks good. But I just realized that changing the handling for DateTimeType as I suggested would brake backward compatibility and is wrong in general. I will merge this PR and fix the DateType with a new PR.
@Chel thanks for your efforts.

**Comment by theoweiss** [comment]
new PR #2639

**Pull request merged**
