### PR TITLE
Chamberlain MyQ Binding

### PR DESCRIPTION
**Pull request by computergeek1507**
I created a binding for the Chamberlain MyQ API for openhab1. I cannot get it to work with openhab2 because it has some dependencies that are not included and I do not know how to add them.

need to add:
import com.sun.jersey.api.client.Client;
import com.sun.jersey.api.client.ClientHandlerException;
import com.sun.jersey.api.client.ClientResponse;
import com.sun.jersey.api.client.WebResource;

Thanks,

### CODE REVIEW

**Comment by teichsta** [comment]
ESH and hence OH2 uses a newer version of jersey where the package name changed meanwhile (see https://jersey.java.net/apidocs/2.7/jersey/javax/ws/rs/client/Client.html) since jersey got the JAX-RS reference implementation and is hence part of the JRE.

**Comment by computergeek1507** [comment]
Is there a way to make it work with both openhab versions?

**Comment by computergeek1507** [comment]
I updated the binding to support openhab2 as well now

**Comment by teichsta** [comment]
> I updated the binding to support openhab2 as well now

great, thanks!

**Comment by digitaldan** [comment]
Hi @computergeek1507 , My  myQ receiver came today, I just spent that last half hour sniffing packets from their IOS app in preparation for a binding, did not realize you beat me too it!  Nice job!  I'm going to give this a spin today.

**Comment by computergeek1507** [comment]
@digitaldan I had to re-write it for myq's newer api. The calls I was using stopped working. I committed my changes so it works again. https://drive.google.com/file/d/0Bx6EpCMtJQHVYjUwWXpPZVdGbTg/view?usp=sharing

**Comment by digitaldan** [comment]
@computergeek1507 we should definitely coordinate our efforts.  I had to change a few things to get it working, namely:
* Change to using /api/v4 for calls
* Use MyQDeviceID instead of DeviceID
* Added HTTP User-Agent Header to all calls

I also cleaned up a few things and plan to add some logic to speed up the polling when the door is in motion.  I was working off your latest revision in master in your repo, is this not the most recent version?  I was planning on committing my changes soon and send you a pull request.

**Comment by computergeek1507** [comment]
@digitaldan I changed it last night (13 hours ago) to use the /api/v4 stuff and committed it I think. I'm still new to git so I might have failed at something.

**Comment by digitaldan** [comment]
@computergeek1507,  my changes look very similar, i'll pull from your repo again and start from there.  Your commit looks fine, usually I like to keep master clean and work in branches ,  just an FYI if you continue to develop for openhab.  Is this your first binding?  You picked a good one, I think a lot of people can benefit from it.  If you don't mind I'll send you a couple of pull requests for functionality and some cleanup stuff if you are OK with that?

**Comment by computergeek1507** [comment]
@digitaldan This is my first binding and I never really used git before. If you have fixes or clean up I have no problem will you committing them. I am a "self taught" programmer so my coding is terrible at best. I live in the US and there seems to be less support for products from here so I'm trying to create bindings for products I have at home. I am working on another binding but I have no idea how to commit it because all my commits are being added to this pull request. Do you make a branch of the whole repository or of just the binding itself. Thanks

**Comment by digitaldan** [comment]
@computergeek1507, well first off welcome to the openHAB community.  Second, for being self taught your code is clear and manageable, so well done.  There are some minor syntax changes around class names, variable names and code reuse that I'll update, but those are things you will pick up quickly as you do more Java development.  I'll hopefully get something to you tonight or tomorrow to look at.  If you have any questions or need advice let me know!

As for being in the US, Europe does have a few more things then here, KNX, fritz boxes, etc...  My setup here in the US uses z-wave for power, lighting, locks and thermostats. Sonos for music. Logitech Harmony Hubs for physical remotes.  Yamaha and Denon bindings for receiver control.  And a few others bindings for various stuff.

**Comment by computergeek1507** [comment]
Opened PR #3539 with branch and single commit

**Pull request closed without merging**
