### PR TITLE
new persistence functions

### PR DESCRIPTION
**Pull request by querdenker2k**

### CODE REVIEW

**Comment by watou** [comment]
Just today I was looking for a changesSince persistence method, in order to determine how often an item's state had changed since some time. There are a few potential use cases and it's straightforward to implement. Thoughts?

**Comment by teichsta** [comment]
Thanks @querdenker2k, hope to find the time for reviewing soon … Best, Thomas E.-E.

**Comment by querdenker2k** [comment]
will this pull request merged to openhab 2 as well???

**Comment by teichsta** [comment]
@querdenker2k i am very sorry for not coming back to you earlier! As i remember some discussions about missing functions in PersistenceExtensions, is this related to that discussion? If not i'd suggest to first add these changes to ESH core and merge into OH1 once this is done. Move to 1.9 hence …

**Comment by querdenker2k** [comment]
Which discussion do you mean?

**Comment by kaikreuzer** [comment]
@teichsta What was the status here, could you clarify?

**Comment by 9037568** [comment]
@kaikreuzer should we merge or drop this PR?

**Comment by kaikreuzer** [comment]
Well, the PR made sense in 2015 when it was created, but I am afraid that by now, we have to close it here as there won't be any further OH1 runtime release.
I'd therefore like to suggest to @querdenker2k to open a PR at https://github.com/eclipse/smarthome/ instead - I'd guess most of the code can be kept and this should mainly require a namespace refactoring. Very sorry that this PR has never been process, I hope @querdenker2k isn't too frustrated and will give us a new chance at ESH :-)

**Pull request closed without merging**
