### PR TITLE
First commit of the mojio binding

### PR DESCRIPTION
**Pull request by sipvoip**
Mojio binding. http://www.moj.io

### CODE REVIEW

**Comment by watou** [comment]
Great contribution!  Also, please update `distribution/pom.xml` in this PR to include the new binding.

**Comment by watou** [comment]
You might also want to remove the file `bundles/binding/org.openhab.binding.mojio/src/main/java/Test.java`

**Comment by sipvoip** [comment]
Done, thanks!

**Comment by sipvoip** [comment]
Actually, can you hold on this, just talked to the guy who wrote this for me and he wants to clean up some things.

**Comment by watou** [comment]
I will close this one and look out for a new PR.  Thanks.

**Pull request closed without merging**
