### PR TITLE
mpd: fix artist and track not updated

### PR DESCRIPTION
**Pull request by stefanroellin**
It may happen that a song changes, but the id stays the same (e.g. for streams).
Therefore, test whether the title or the artist has changed instead of
the id (which is of no interest anyway).

### CODE REVIEW

**Comment by stefanroellin** [comment]
When I wrote the patch, I was not aware of issue #2847, which could be fixed with this pull request.

**Comment by teichsta** [comment]
Thanks @stefanroellin for this contribution! Does this address any other open issue regarding MPD?

**Comment by stefanroellin** [comment]
I am not aware of further issues that could be solved by this patch.

**Comment by teichsta** [comment]
ok, thanks @stefanroellin! @stefanroellin could you please also follow-up on #2847?

**Pull request merged**
