### PR TITLE
Update codes for FGS211

### PR DESCRIPTION
**Pull request by cdjackson**
closes https://github.com/openhab/openhab/issues/3400

Signed-off-by: Chris Jackson <chris@cd-jackson.com>

### CODE REVIEW

**Comment by lexkanev** [comment]
Unfortunately I have no experience to build .jar file with zwave bindings from src.
Where can I find instructions to do this?

Thnx.

**Comment by cdjackson** [comment]
You can download the latest snapshot from cloudbees tomorrow.

**Comment by lexkanev** [comment]
Can you post url to cloudbees  here?

Thnx.

**Comment by cdjackson** [comment]
https://openhab.ci.cloudbees.com/ <https://openhab.ci.cloudbees.com/>

**Pull request merged**
