### PR TITLE
Add linear garage door opener controller

### PR DESCRIPTION
**Pull request by jhuizingh**
Attempting to add a new zwave item for a Linear garage door opener controller.

Please verify that this looks ok as this is my first attempt at doing this.

Details here: http://www.pepper1.net/zwavedb/device/684
File eco/tiltzwave2.xml used as an example

### CODE REVIEW

**Comment by cdjackson** [comment]
Thanks - looks good.

**Comment by jhuizingh** [comment]
Is there a way to get a build with this change integrated? I thought it might show up in a snapshot on cloudbees, but it doesn't look like it got built since yesterday. Am I looking in the right place? This is where I'm checking: https://openhab.ci.cloudbees.com/job/openHAB/

**Comment by cdjackson** [comment]
It should have built, but it looks like it’s been nearly a week so maybe something is busted.   @teichsta any idea why cloudbees isn't building?

**Comment by jhuizingh** [comment]
No luck still? I looked at the cloudbees page again and I found this on the git log:

Git Polling Log

Started on Aug 21, 2015 3:01:00 AM
Using strategy: Default
[poll] Last Built Revision: Revision 1fb0c00f548e2581ff32e879d284eb349ad5b226 (refs/remotes/origin/master)
ERROR: Failed to record SCM polling for hudson.maven.MavenModuleSet@13413aa9[openHAB]
java.lang.NullPointerException
	at hudson.plugins.m2extrasteps.M2ExtraStepsAction.buildEnvVars(M2ExtraStepsAction.java:29)
	at hudson.model.AbstractBuild.getEnvironment(AbstractBuild.java:939)
	at hudson.maven.AbstractMavenBuild.getEnvironment(AbstractMavenBuild.java:56)
	at hudson.maven.MavenModuleSetBuild.getEnvironment(MavenModuleSetBuild.java:165)
	at hudson.plugins.git.GitSCM.compareRemoteRevisionWithImpl(GitSCM.java:564)
	at hudson.plugins.git.GitSCM.compareRemoteRevisionWith(GitSCM.java:526)
	at hudson.scm.SCM.compareRemoteRevisionWith(SCM.java:380)
	at hudson.scm.SCM.poll(SCM.java:397)
	at hudson.model.AbstractProject._poll(AbstractProject.java:1446)
	at hudson.model.AbstractProject.poll(AbstractProject.java:1349)
	at jenkins.triggers.SCMTriggerItem$SCMTriggerItems$Bridge.poll(SCMTriggerItem.java:119)
	at hudson.triggers.SCMTrigger$Runner.runPolling(SCMTrigger.java:510)
	at hudson.triggers.SCMTrigger$Runner.run(SCMTrigger.java:539)
	at hudson.util.SequentialExecutionQueue$QueueEntry.run(SequentialExecutionQueue.java:118)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by cdjackson** [comment]
Ok - I’ll build one and put it on the HABmin repo later tonight…

**Comment by jhuizingh** [comment]
Great. Thank you!

**Comment by cdjackson** [comment]
It’s on the HABmin repo now...

**Pull request merged**
