### PR TITLE
[enphaseenergy] add/removeBindingProvider

### PR DESCRIPTION
**Pull request by watou**
Forum discussion [here](https://community.openhab.org/t/planning-1-8-1-and-2-0-beta2-releases/6812/18?u=watou).

Test JAR [here](https://dl.dropboxusercontent.com/u/4286376/enphaseenergy-addBindingProvider/org.openhab.binding.enphaseenergy-1.9.0-SNAPSHOT.jar).

Signed-off-by: John Cocula <john@cocula.com>

### CODE REVIEW

**Comment by teichsta** [comment]
Thanks @watou!

**Comment by xsnrg** [comment]
I finally got some time to test this.  Unfortunately, it is not working yet.

``` 
13:21:35.480 [DEBUG] [ergy.internal.EnphaseenergyActivator] - Enphaseenergy binding has been started.
13:21:35.495 [DEBUG] [org.openhab.binding.enphaseenergy   ] - ServiceEvent REGISTERED - {org.openhab.model.item.binding.BindingConfigReader, org.openhab.binding.enphaseenergy.EnphaseenergyBindingProvider}={component.name=org.openhab.binding.enphaseenergy.genericbindingprovider, component.id=68, service.id=169, service.bundleid=107, service.scope=bundle} - org.openhab.binding.enphaseenergy
13:21:38.889 [INFO ] [b.core.service.AbstractActiveService] - Enphaseenergy Refresh Service has been started
13:21:38.891 [INFO ] [b.core.service.AbstractActiveService] - Enphaseenergy Refresh Service has been shut down
13:21:41.356 [DEBUG] [.EnphaseenergyGenericBindingProvider] - Processing binding configuration: '732830#last_report_at'
13:21:41.357 [DEBUG] [.EnphaseenergyGenericBindingProvider] - Adding binding: EnphaseenergyBindingConfig [systemId=732830, measure=last_report_at]
13:21:41.358 [DEBUG] [.EnphaseenergyGenericBindingProvider] - Processing binding configuration: '732830#current_power'
13:21:41.358 [DEBUG] [.EnphaseenergyGenericBindingProvider] - Adding binding: EnphaseenergyBindingConfig [systemId=732830, measure=current_power]
```

This is with debug enable, but I see no indication why it is shutting down right away.

**Comment by watou** [comment]
It's probably due to immediate="false".  I will set it to immediate="true" in the bulk PR I'm working on.

**Comment by xsnrg** [comment]
that sounds like a problem we have seen solved before with the immediate setting.  Thanks for working on this @watou

**Comment by watou** [comment]
```
13:21:38.889 [INFO ] [b.core.service.AbstractActiveService] - Enphaseenergy Refresh Service has been started
13:21:38.891 [INFO ] [b.core.service.AbstractActiveService] - Enphaseenergy Refresh Service has been shut down
```

This commit https://github.com/watou/openhab/commit/4d4b6bc94e9c3f38c612c27439d3ea6c386c7a78 should (hopefully) resolve that.

**Pull request merged**
