### PR TITLE
starting all components immediately after bundle start to prevent iss…

### PR DESCRIPTION
**Pull request by kaikreuzer**
…ues with Felix SCR

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
To be discussed whether this should be merged or not.
Does anybody know of a reason, why any existing component should NOT be started?

Would be good if some openHAB 1 users could test this first and see if it has any impact on the openHAB 1 runtime.

@maggu2810 Any comments from your side?

**Comment by watou** [comment]
Would this also apply to action service bundles?
If this is merged, OH1 testers could have a Cloudbees build to extract from more easily for testing on 1.8.0.  If it's a problem, the commit could be reverted.

**Comment by kaikreuzer** [comment]
> Would this also apply to action service bundles?

It seems as if this pattern is already applied on our actions.

**Comment by robnielsen** [comment]
Please also apply to the netatmo binding also

**Comment by kaikreuzer** [comment]
> Please also apply to the netatmo binding also

Did you test that it still works with that change?
In https://github.com/openhab/openhab/commit/4581431c3db83ffcd75cdf01d5110eb0b5d2189c @clinique set immediate specifically to false - I assume that had some specific reason?

**Comment by maggu2810** [comment]
I think it is ok, to set immediate for all bindings. The DS of the binding should be started after registration.
I assume the Eclipse IDE added the immediate="false", but let's wait for @clinique

**Comment by robnielsen** [comment]
I  changed immediate=true for Netatmo, and it now works with both 1.8 and the latest build of 2.0. I'll create a PR that includes the change, along with the changes to gets picked up by the distribution build

**Comment by kaikreuzer** [comment]
Cool! No need for a separate PR. As this one needs to be rebased anyhow, I will include Netatmo in it.

**Comment by kaikreuzer** [comment]
Done. As nobody vetoed against this PR, I'll merge it now.

**Pull request merged**
