### PR TITLE
[pioneeravr] Fix zone2 power query response not being picked up by openhab

### PR DESCRIPTION
**Pull request by jediperry**
Not sure why this works. I replicated the zone1 configuration, which seemed to do the trick.

### CODE REVIEW

**Comment by jediperry** [comment]
This change is probably appropriate for zone3 as well, but I haven't tested that.

**Comment by teichsta** [comment]
> Not sure why this works.

hmm … doesn't sound really deterministic. Could you please find other users (through https://community.openhab.org) confirming this PR as a fix? Thanks, Thomas E.-E.

**Comment by jediperry** [comment]
Yeah, I wish I'd not written that now! The fix is at least consistent with an equivalent function that does work.
Anyway, I posted the question [here](https://community.openhab.org/t/call-for-help-users-of-pioneer-avr-binding/3118). I did also post a question about this in the old forum, but didn't got a response.
Thanks,
Mike.

**Comment by teichsta** [comment]
> in the old forum, but didn't got a response.
you shouldn't be able to post to the old forum anymore. We just keep it running for reference (and as archive)

**Comment by jediperry** [comment]
It was 5 months ago when I first noticed [the problem](https://groups.google.com/forum/#!searchin/openhab/pioneer/openhab/x0negPrHces/S29F1lzWlSEJ).

**Comment by teichsta** [comment]
> This change is probably appropriate for zone3 as well, but I haven't tested that.

could you then please update this PR for zone3 as well? Will merge it then right away (assuming it is squashed again).

**Comment by jediperry** [comment]
Thanks @teichsta,
Sorry it took a while to get round to this. Equivalent zone3 fix is attached and confirmed working.

**Comment by teichsta** [comment]
great thanks, could you please finally squash your commits into one to get this PR merged soon?

**Comment by teichsta** [comment]
any chance to squash the commits until tonight?

**Comment by jediperry** [comment]
OK, I should be able to.

**Comment by teichsta** [comment]
great, thanks!

**Comment by jediperry** [comment]
First attempt at squashing. I think it looks OK.

**Comment by teichsta** [comment]
cool, thanks @jediperry!

**Pull request merged**
