### PR TITLE
Fix ClassicUI Sloder for no-value-labels

### PR DESCRIPTION
**Pull request by sja**
This is mentioned in issue #2900 and #3795

Signed-off-by: Sebastian Janzen <sebastian.janzen@innoq.com>

### CODE REVIEW

**Comment by sja** [comment]
Not my fault:

Failed to execute goal org.apache.karaf.tooling:karaf-maven-plugin:4.0.3:verify (verify) on project openhab-addons-verify: Unable to load features descriptors: Error -> [Help 1]

**Comment by kaikreuzer** [comment]
@sja No other exception lor log message there?

**Comment by sja** [comment]
@kaikreuzer I don't see any other errors. The summary table at the end marks every bundle as SUCCESS.

**Comment by kaikreuzer** [comment]
Ok, I didn't see the Jenkins PR build log at https://openhab.ci.cloudbees.com/job/PR-openHAB1-Addons/22/consoleFull

Looks as if the dependency 
```xml
<dependency>
<groupId>org.openhab.addons</groupId>
<artifactId>openhab-addons</artifactId>
<version>${project.version}</version>
<classifier>features</classifier>
<type>xml</type>
</dependency>
```
is not resolved from the local reactor and since no official 1.8.1-SNAPSHOT build has yet been executed, the artifact is also not available in the snapshot repo.
Does anybody know whether it is possible to make it resolve the artefact from the reactor?

**Comment by teichsta** [comment]
fix has been confirmed working … thanks @sja!

**Comment by kaikreuzer** [comment]
@sja, @teichsta What is the status about synchronizing these code changes with ESH?

**Pull request merged**
