### PR TITLE
Update Z-Wave database for 1.8.2 release

### PR DESCRIPTION
**Pull request by cdjackson**
Signed-off-by: Chris Jackson <chris@cd-jackson.com>

### CODE REVIEW

**Comment by cdjackson** [comment]
I don't think the failure here has anything to do with this PR. This PR only contains XML files, and the failure wasn't in the zwave binding...

**Comment by watou** [comment]
All PRs against the 1.8 branch fail the Jenkins check.

**Comment by cdjackson** [comment]
thanks…

**Comment by teichsta** [comment]
Many thanks @cdjackson!

**Comment by lumachan** [comment]
Hi Chris,

It seems there is an issue with the 1.8 branch database sync.

For example : 
- in master : greenwave/np210.xml, **greenwave/np310.xml**, greenwave/ns210.xml, greenwave/ns310.xml
- in 1.8 : greenwave/np210.xml, greenwave/ns210.xml, greenwave/ns310.xml

And the xml versions in 1.8 are outdated.

Maybe it lacks other xml, not sure !

Thanks Chris !

**Comment by cdjackson** [comment]
Ok - there’s nothing we can do about this though - sorry.

**Comment by cdjackson** [comment]
Actually, I take that back... I thought 1.8.2 was already released, but it seems not...  I'll update this - thanks.

**Comment by lumachan** [comment]
Thanks to you Chris !

**Pull request merged**
