### PR TITLE
Adding feature for Nikobus.

### PR DESCRIPTION
**Pull request by crnjan**
Have been using this binding in OH2 and seems to work fine.

### CODE REVIEW

**Comment by watou** [comment]
Thank you @crnjan!

**Comment by watou** [comment]
@kaikreuzer : what causes the documentation site to be rebuilt after a commit like this one?  Also, how can my local build take into account the new 1.x binding?

**Comment by kaikreuzer** [comment]
I am currently doing this manually, but I plan to setup a nightly Jenkins build to do so.
All you need to do locally is to call `update.sh` - this will pull the changes from the submodule repos and re-generate and copy all required files.

**Comment by kaikreuzer** [comment]
Just pushed an update, so that Nikobus now shows up as well.

**Comment by watou** [comment]
Thanks, Kai.

**Pull request merged**
