### PR TITLE
Fix scale for not defined.

### PR DESCRIPTION
**Pull request by benoit934**
No tested but this may work.

### CODE REVIEW

**Comment by teichsta** [comment]
I am lacking the context … could you please reference to a Bug or explain what this PR is about?

**Comment by benoit934** [comment]
It's when the value is not defined not a number but, "-" with the map it's working, not with scale.

**Comment by clinique** [comment]
as the scale transform currently falls down to map transform when the value is not a number, it would be better to use the same logic for Undef inseated of extending the current regular expression no ?

**Comment by benoit934** [comment]
I thinks it's a better error handling, maybe faster too, i don't know i'm not a pro of JAVA.

**Comment by teichsta** [comment]
Thanks @clinique and @benoit934 for this discussion. I tend to go with @clinique (use the same logic for Undef). Can you please adjust this PR accordingly?

**Comment by teichsta** [comment]
Any news?

**Comment by benoit934** [comment]
I'm sorry I don't really have the time, maybe the issue can just be closed.

But when I coding in others languages I try to handle everything faster by limiting any sub conditions.

**Comment by teichsta** [comment]
@clinique would you mind adding the proposed behaviour yourself? If no, please reference the new PR here. Thanks, Thomas E.-E.

**Pull request closed without merging**
