### PR TITLE
Introducing PointType and LocationItem - Round 2

### PR DESCRIPTION
**Pull request by clinique**
Converted PointType logic to BigDecimal as in smarthome instead of double.
Added a GUI introducing Mapview widget in sitemaps.
The mapview is currently based on OpenStreetMaps, could be changed by any javascript guru (that I'm not) to have something nicer

### CODE REVIEW

**Comment by teichsta** [comment]
Since there are some ongoing discussions at ESH i'd tend to wait with the merge? Agreed?

**Comment by clinique** [comment]
Sure

**Comment by teichsta** [comment]
Not sure what the current state of the ESH Location is? Could you link the appropriate Issue here? Thanks, Thomas E.-E.

**Comment by clinique** [comment]
It has been merged (https://github.com/eclipse/smarthome/pull/222)

**Comment by teichsta** [comment]
perfect. Before merging into master could you please squash your commits into one? Thanks, Thomas E.-E.

**Comment by clinique** [comment]
Done but it generates a merge conflict with the example I introduced in Netatmo Binding to get benefits of this PR - I'll remove this and introduce Netatmo evolutions in another PR

**Comment by clinique** [comment]
Removed but it appears that I still have a merge conflict with another project : "stdout: bundles/binding/org.openhab.binding.bticino/.project: needs merge". @teichsta can you indicate me how to solve this ?

**Comment by teichsta** [comment]
I've merged this PR manually. Could you please have a look if i resolved the conflicts correctly? Thanks, Thomas E.-E.

**Pull request merged**
