### PR TITLE
Add Log Info for GPIO binding

### PR DESCRIPTION
**Pull request by Speederc**
Add Log Info for GPIO send & receive commands

### CODE REVIEW

**Comment by Speederc** [comment]
The buildhive compilation failed at the end when it tries to send an email to teichsta@gmail.com
"com.sun.mail.smtp.SMTPAddressFailedException: 501 <null>: recipient address must contain a domain"

Is it normal ?

Regards,

Damien

**Comment by teichsta** [comment]
@Speederc thanks for this contribution!

Please reduce the log level to DEBUG and squash your commits into one finally.

Thanks, Thomas E.-E.

**Comment by teichsta** [comment]
great thanks, @Speederc!

If you finally could squash your commits into i would be fine to merge.

Thanks, Thomas E.-E.

**Comment by Speederc** [comment]
Hi Thomas,
I'm sorry but I don't find any way to squash the 2 commits. As there is only one impacted file can you only commit the last one ? Thanks

**Comment by teichsta** [comment]
> I'm sorry but I don't find any way to squash the 2 commits

That's simple :-)

(assuming no further changes happened on your branch!)
* Reset (soft) your branch to the first commit
* now there will be changed files again
* commit again with amend option
* force push

Next time, please create a new branch for your changes (Best practice). This makes things easier when working in a project with many commits (like this one).

**Comment by Speederc** [comment]
Sorry I didn't find how to reset the second commit, neither how to commit with amend option through the github website.

**Comment by teichsta** [comment]
which OS is your client? For Windows and OS X i can recommend Sourcetree as client … if you this doesn't help please create a new PR containing just one single commit. Thanks in advance, Thomas E.-E.

**Comment by Speederc** [comment]
With a lot of difficulties, I managed to create the commit be39f65 which should be a squash of the 2 others. Unfortunately few others strange commits still appear in this request. Are you anyway able to merge this PR ? Otherwise I will create anew PR.

**Comment by teichsta** [comment]
cherry picked https://github.com/Speederc/openhab/commit/be39f65acd4e9de2bfe1e3cb44b9190dfa30e31b into 1.7 and 1.8. Thanks @Speederc!

**Comment by teichsta** [comment]
i've reverted the commits since they led to compilation errors. Could you please resend a PR against the latest master? Thanks, Thomas E.-E.

**Pull request closed without merging**
