### PR TITLE
modbus binding bug fix - connections were left open on command execution

### PR DESCRIPTION
**Pull request by paolodenti**
substitues pull request #3211 / fix for #658

### CODE REVIEW

**Comment by teichsta** [comment]
Thanks for this fix. Since i am no modbus i have absolutely no clue about the insights of this binding. To me it doesn't look like the connection is being opened within execute() so it doesn't sound to me good to close something which is not opened before. Could you shed some light on this? Can other users confirm  this fix is working?

**Comment by wtrucci** [comment]
I confirm that this fix modbus connection.
This is a fix for the issue https://github.com/openhab/openhab/issues/658

**Comment by paolodenti** [comment]
@teichsta 
connection is opened at the beginning of method but it is just never closed. issue #658, pointed out by @wtrucci, gives failure after too many connections for the device are opened and not closed or "timeouted" because of that

```
      //3. open the connection if not connected
      if (!m_Connection.isConnected()) {
        try {
          m_Connection.connect();
          m_IO = m_Connection.getModbusTransport();
        } catch (Exception ex) {
          throw new ModbusIOException("Connecting failed.");
        }
      }
```

**Comment by teichsta** [comment]
Thanks @paolodenti!

**Pull request merged**
