### PR TITLE
Changed regex matcher to "Find" method to support more garage door openers

### PR DESCRIPTION
**Pull request by computergeek1507**

### CODE REVIEW

**Comment by watou** [comment]
Thanks for this, @computergeek1507.  Is it tested and ready for merge from your perspective?  Is it needed for a 1.8.2, or is 1.9.0 OK?  Is there a link to a forum discussion for context?

**Comment by computergeek1507** [comment]
@watou I would like it added o 1.8.2 too but I didn't know If I had to make two pull requests. I tested it on my 1.8.1 install and tested it with all the JSON other users provided in the forum while I was debugging. 
https://community.openhab.org/t/chamberlain-myq-binding/4192/59

**Comment by watou** [comment]
Thanks very much.  I marked it for 1.8.2 milestone.

**Comment by teichsta** [comment]
Thanks @computergeek1507! Also cherry-picked onto 1.8

**Pull request merged**
