### PR TITLE
1.8

### PR DESCRIPTION
**Pull request by SilverGhostBS**

### CODE REVIEW

**Comment by watou** [comment]
Is this an identical set of changes as in #4443, but meant for the 1.8 branch?  Would it be possible to close this PR, address comments in #4443, and then a maintainer could cherry-pick it onto the 1.8 branch after it's done with review and merge on master?  Or have the branches diverged too much for that to be practical?

**Comment by watou** [comment]
There is currently no 1.8.4 release planned (that I'm aware of), so perhaps this PR is a duplicate of #4443?  Please comment, @SilverGhostBS, and thanks!

**Comment by SilverGhostBS** [comment]
Ok, so 1.8.3 will probably be the last of the 1.8 branch, in this case I will close this PR as you mentionned, it is the same as #4443 but for 1.8.

Please note however that the code was tested on an 1.8 installation and confirmed as working. I didn't test the 1.9 version as my system is currently running 1.8.3.

I will upgrade everything to 1.9 after the summer holidays ;)

Thanks.

**Comment by watou** [comment]
Thanks @SilverGhostBS !

**Pull request closed without merging**
