### PR TITLE
[nest] October 2016 API Update

### PR DESCRIPTION
**Pull request by watou**
Updates to the Nest binding to match [the October 2016 API Update](https://developers.nest.com/documentation/cloud/release-notes).

Please test [this JAR](https://dl.dropboxusercontent.com/u/4286376/nest-oct-2016-api-update/org.openhab.binding.nest-1.9.0-SNAPSHOT.jar) to verify that the new features work.  You will have to update your Product at developer.nest.com to use the v6 permissions, and set up a new PIN for your account and update your nest.cfg or openhab.cfg file.  Also, the thermostat against which you are testing must be at the 5.6 or later firmware version.

Please report back here or [on the forum](https://community.openhab.org/) with your results, and thanks!

### CODE REVIEW

**Comment by mrguessed** [comment]
> Also, the thermostat against which you are testing must be at the 5.6 or later firmware version.

To validate the firmware version of the TStats, you can use the following menu on the device itself:

_Settings_ / _Technical Info_ / _Display_

You can see the same data from the Nest Application by:
* Selecting the TStat
* Selecting the Gear ⚙️  in the upper right hand corner
* Selecting _Technical Info_

If your TStats are not (yet) on the 5.6 version, the new binding _will_ crash.


@watou : You may want to add code that validates the `software_version` field of each TStat, and dump a warning.  

Currently you'll bang out with an parsing exception.
The code itself could be temporary, mostly to handle the Nest's cutover transition period - my app updated a few days back, but the TStats still haven't (and I'd assumed they had)

**Comment by watou** [comment]
Sorry; here's a new [test JAR](https://dl.dropboxusercontent.com/u/4286376/nest-oct-2016-api-update/org.openhab.binding.nest-1.9.0-SNAPSHOT.jar).

**Comment by mrguessed** [comment]
Looks better now, thanks for the quick turn-around!

**Comment by watou** [comment]
Thanks for testing again, Mark.

**Comment by watou** [comment]
A new [test JAR](https://dl.dropboxusercontent.com/u/4286376/nest-oct-2016-api-update/org.openhab.binding.nest-1.9.0-SNAPSHOT.jar), including new commit that accepts "" for `previous_hvac_mode`.

**Comment by watou** [comment]
Only based on a guess, but...

[511903214 278542 org.openhab.binding.nest-1.9.0-SNAPSHOT.jar](https://dl.dropboxusercontent.com/u/4286376/nest-oct-2016-api-update/org.openhab.binding.nest-1.9.0-SNAPSHOT.jar)

**Comment by watou** [comment]
I tested the most recent JAR (linked above) under a recent OH2 nightly and the v6 Nest Product permissions, and my JSON payload is parsing completely.  New item bindings from this PR were coming through as expected.  The thermostats in the payload are both still at v5.5 firmware.

_About testing under OH2: The configuration settings via Paper UI don't seem to have any effect on the running binding. I needed to enter them manually into nest.cfg before the binding would start doing work._

**Comment by vzorglub** [comment]
Hello,
I know you have commited the change of the binding but the version in the Openhab downloads is still 1.8.3.  Where can I download the 1.9.0. jar version. Thanks

**Comment by watou** [comment]
> Where can I download the 1.9.0. jar version.

@vzorglub: For openHAB 1.x users, you can get the new JAR file [here](https://openhab.ci.cloudbees.com/job/openHAB1-Addons/lastSuccessfulBuild/artifact/bundles/binding/org.openhab.binding.nest/target/org.openhab.binding.nest-1.9.0-SNAPSHOT.jar).  Just replace the JAR in your addons folder.

**Pull request merged**
