### PR TITLE
fix for #3244. New version of PostgreSQL (9.4) driver.

### PR DESCRIPTION
**Pull request by mdbergmann**
I've closed the old PR.
This one has only a bug fix and minor changes.

### CODE REVIEW

**Comment by teichsta** [comment]
@lewie could you please have a look at this one? Thanks, Thomas E.-E.

**Comment by lewie** [comment]
@teichsta,
JPA persistence works as expected with PostgreSQL 9.4.5.

The only but known Bug is the missing Implementation of Item types 'Call' and 'Location'.

Rgds
Helmut

**Comment by mdbergmann** [comment]
I'm unaware of those types.
But it should be a simple fix.
Can I update this PR?

**Comment by lewie** [comment]
@mdbergmann, 
'Call' and 'Location': https://github.com/openhab/openhab/wiki/Explanation-of-items#itemtype

**Comment by lewie** [comment]
See org.openhab.core.library.items.LocationItem and org.openhab.library.tel.items.CallItem.

**Comment by teichsta** [comment]
> Can I update this PR?
yes, you can … it's "just" a branch in your repository!

**Comment by mdbergmann** [comment]
Any idea why the import for CallItem and CallType fails?

```
[ERROR] /Users/mbergmann/Development/MySources/openhab/bundles/persistence/org.openhab.persistence.jpa/java/org/openhab/persistence/jpa/internal/JpaHistoricItem.java:[26]
[ERROR] import org.openhab.library.tel.items.CallItem;
```

**Comment by mdbergmann** [comment]
OK, sorry. Got it. An entry in manifest was missing.

**Comment by mdbergmann** [comment]
I have a weird thing here.
The PointType.toString() gives me an output like this:
PointType 3vals toString(): 1,20°N, 2,30°W, 3,40 m

Feeding this back to PointType.valueOf() doesn't work.
Looking at the source code of PointType I don't understand what's happening here.
The BigDecimal.toPlainString() shouldn't give such an output.

See the test code:
```
    @Test
    public void testPointTypeToStringAndBack2Vals() throws Exception {
        PointType type = new PointType(new DecimalType(1.2), new DecimalType(2.3));
        System.out.println("PointType 2vals toString(): " + type.toString());
        PointType type2 = new PointType(type.toString());
        
        assertTrue(type.getLatitude().doubleValue() == type2.getLatitude().doubleValue());
        assertTrue(type.getLongitude().doubleValue() == type2.getLongitude().doubleValue());
    }
```

**Comment by watou** [comment]
I fixed this and [merged the change](https://github.com/openhab/openhab/pull/3410) #3410 9 days ago for availability in 1.8.  Could you rebase your PR and try again?

**Comment by mdbergmann** [comment]
All right now.
I've added support for LocationItem and CallItem.
There are now some more enhancements, like the ability to override the syncmapping property, new version of openjpa and I've included the embedded derby driver.

**Comment by lewie** [comment]
@mdbergmann,
LocationItem and CallItem works well now.

Got Errors while restoring PercentType, so based on this [PR](https://github.com/openhab/openhab/pull/3438) I changed fromPersistedItem in JpaHistoricItem and it runs well now, if you want you can use my changes:
````
    public static HistoricItem fromPersistedItem(JpaPersistentItem pItem, Item item) {
        State state;
        if (item instanceof NumberItem) {
            state = DecimalType.valueOf(pItem.getValue());
        } else if (item instanceof DimmerItem) {
            state = PercentType.valueOf(pItem.getValue());
        } else if (item instanceof SwitchItem) {
            state = OnOffType.valueOf(pItem.getValue());
        } else if (item instanceof ContactItem) {
            state = OpenClosedType.valueOf(pItem.getValue());
        } else if (item instanceof RollershutterItem) {
            state = PercentType.valueOf(pItem.getValue());
        } else if (item instanceof ColorItem) {
            state = HSBType.valueOf(pItem.getValue());
        } else if (item instanceof DateTimeItem) {
            Calendar cal = Calendar.getInstance();
            cal.setTime(new Date(Long.valueOf(pItem.getValue())));
            state = new DateTimeType(cal);
        } else if (item instanceof LocationItem) {
            PointType pType = null;
            String[] comps = pItem.getValue().split(";");
            if (comps.length >= 2) {
                pType = new PointType(DecimalType.valueOf(comps[0]), DecimalType.valueOf(comps[1]));

                if (comps.length == 3) {
                    pType.setAltitude(DecimalType.valueOf(comps[2]));
                }
            }
            state = pType;

        } else if (item instanceof CallItem) {
            state = new CallType(pItem.getValue());
        } else {
            state = new StringType(pItem.getValue());
        }

        return new JpaHistoricItem(item.getName(), state, pItem.getTimestamp());
    }
````

**Comment by mdbergmann** [comment]
OK, done. Thanks.

**Comment by mdbergmann** [comment]
@lewie 
Alright, wait a sec.
I'd like to remove all but the embedded derby driver.
You hint is great that all drivers are OSGi bundles and can just be dropped in addons.

**Comment by mdbergmann** [comment]
Alright. This should now be it.

**Comment by teichsta** [comment]
Thanks guys! @mdbergmann could you please change the title of the PR finally. For the release notes the current title would be misleading since the update of the postgresql driver didn't actually happen :-)

**Pull request merged**
