### PR TITLE
Update zw100-a.xml

### PR DESCRIPTION
**Pull request by mstormi**
updated according to latest Aeon engineering spec as of 2015/08/11

### CODE REVIEW

**Comment by cdjackson** [comment]
Thanks.

Since you've done a great job of improving the help text, can I be a pain and ask if you'd mind supporting HTML in these descriptions? (see here -: https://github.com/cdjackson/HABmin2/wiki/ZWave-Product-Database---OH2#label-conventions).

If you don't want to, or don't have the time, then no problem - just let me know. But if you can, then it will be better in OH1, and much better when we convert the database to OH2.

Just let me know either way :)

Thanks
Chris

**Comment by mstormi** [comment]
Am 06.09.2015 um 12:20 schrieb Chris Jackson:
>
> Thanks.
>
> Since you've done a great job of improving the help text, can I be a 
> pain and ask if you'd mind supporting HTML in these descriptions? (see 
> here -: 
> https://github.com/cdjackson/HABmin2/wiki/ZWave-Product-Database---OH2#label-conventions).
>
> If you don't want to, or don't have the time, then no problem - just 
> let me know. But if you can, then it will be better in OH1, and much 
> better when we convert the database to OH2.
>
> Just let me know either way :)
>
> Thanks
> Chris
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/openhab/openhab/pull/3132#issuecomment-138062964>.
>
Hi.
Ihaven't seen any HTML description so far, but I agree it makes sense. 
Do you mean me to change the Aeon sensor description into HTML? Sure, 
will do, will create another PR when done.
Or are you asking for me to HTMLize all device descriptions? That's a 
no, then. A bit too much work for me.
regards, Markus

**Comment by cdjackson** [comment]
Yes - I was just asking if you could put some formatting into the descriptions so that we don’t just have a single very long line that will not format very well, but instead we add <BR> at the end of each line, as necessary, to correctly format it. It shouldn’t take very long - 10 or 20 minutes - but if you think it’s too much work then I’ll merge. Please let me know.

This WILL need to be done soon - it would be appreciated if you could do it, but if not I’ll do it when we convert to OH2 :(

Cheers
Chris

**Comment by mstormi** [comment]
Of course, here you are.

**Comment by SkynetHome** [comment]
I think CDATA tags are going to be needed as well.  I can edit after merge or copy edit and issue a separate PR if OP doesn't want to edit it again.

**Comment by mstormi** [comment]
CDATA is in, now.
Anything else?
Chris' habmin2 Wiki page shows a neat example to also include device images, but I didn't see described how to include that through .xml

Btw, is there a template or reference device .xml file to demostrate usage of a 'complete' set of HTML tags ?
It's probably aa good idea to provide such a template to anyone who is willing to implement a new device, so new device descriptions are as nicely-looking as possible right from the start, with no need to work over later on (which is what few people are willing to do once they got the device working).

**Pull request merged**
