### PR TITLE
InsteonPLM: attempted fix for incompatibility with Z-Wave binding

### PR DESCRIPTION
**Pull request by berndpfrommer**
Attempted fix for issue #2642

### CODE REVIEW

**Comment by teichsta** [comment]
Thanks for this fix, @berndpfrommer.

With regards to your comments about thread safety of setting the System property. Wouldn't it be better if we would implement something generally available (in io.transport.serial) that deals with this issue? Otherwise we would have check this again and again in all new Addons using serial.

Might also be interesting for OH2

**Comment by berndpfrommer** [comment]
I'm all for it.

Since I added the same setProperties() call to the URTSI binding, it also suffered from the same incompatibility issues: https://github.com/openhab/openhab/issues/1351

The updateSerialProperties() method I added for the fix purposefully does not reference any local variables, so it can be readily moved elsewhere. Adding a "synchronized" statement to it would also take care of the race condition mentioned in the comments.

I'm really clumsy with the build environment though. Would you mind adding a utils class to io.transport.serial?

**Comment by teichsta** [comment]
> I'm really clumsy with the build environment though. Would you mind adding a utils class to io.transport.serial?

i could try … please ping me if nothing happened in the next three weeks.

Thanks, Thomas E.-E.

**Comment by xsnrg** [comment]
As this was merged to master, should this ticket be closed and a new one opened for the broader issue?

It has been working for me since merged by the way, but I only have the two serial interfaces.

**Comment by wishmoooop** [comment]
While developing a binding between OH2 and MySensors, where I'm using the io.transport.serial library, I'm too getting in conflict with the zwave binding from 1.X. 
If I add the code for the fix from @berndpfrommer (updateSerialProperties()) in: https://github.com/cdjackson/openhab/blob/master/bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/ZWaveController.java

Both bindings work together. MySensors most of the time is initialized before zwave at startup. A general solution for all bindings that use io.transport.serial would be nice.

**Comment by plajjan** [comment]
I too am seeing conflicts but between benq serial and zwave. I'm having difficulty following all the issues used here to track various things. Do we have one to track the more generic problem? Given that I wrote the benq serial transport, am I expected to update that?

**Comment by aroop** [comment]
I am running into this issue with openhab 2.3.0. I only use two serial ports one for zwave and another for insteon. 

If I remove the insteon bindings zwave binding will be able to find its COM port or else zwave does not work

**Pull request merged**
