### PR TITLE
Updates to Mqttitude binding in preparation for new iOS/Android apps

### PR DESCRIPTION
**Pull request by sumnerboy12**
There are some new versions of the Owntracks app in the pipeline which use a slightly different topic for publishing. Along with sending lat/lons as floats (real types) rather than strings as they currently do.

This PR ensures the Mqttitude binding is backward compatible with the current versions of the app but will also work with the new version.

Only change required to binding configuration for the new versions of the Owntracks app, is to add `/event` to the binding topic.

### CODE REVIEW

**Comment by sumnerboy12** [comment]
I have also updated the Mqttitude WIKI page to reflect these changes.

**Comment by jpmens** [comment]
Thank you very much for doing this, Ben, and I hope it slips into the upcoming openHAB release!

**Comment by teichsta** [comment]
>  I hope it slips into the upcoming openHAB release!

it will :-)

**Comment by sumnerboy12** [comment]
Thanks Thomas!

**Comment by jpmens** [comment]
@teichsta much appreciated, Thomas. Danke! :-)

**Comment by sumnerboy12** [comment]
This will be announced by OwnTracks - I will post something in here when 
that happens tho. The new version should work as long as you are using 
region mode, just ensure your item binding topic is the base topic - 
i.e. no /event.

**Comment by sumnerboy12** [comment]
What is your configuration and OwnTracks version number?

In order to debug subscribe to exactly the same topic as you have 
configured in your Mqttitude openHAB item binding and check what you see 
when your phone moves in/out of that waypoint.

Remember the waypoint/region has to be `shared` in your Owntracks app 
otherwise the `name` is not sent with the event payloads.

**Comment by sumnerboy12** [comment]
Wondered why I couldn't see the question on Github! I have been having 
internet connection problems so apologies for the delay in responding.

Glad it is working for you now.

**Pull request merged**
