### PR TITLE
HeatMiserPRT edit for Issue #2177

### PR DESCRIPTION
**Pull request by SkynetHome**
Updated HeatMiserPRT.java per request on Issue #2177 for testing of accurate room temperature reading.

### CODE REVIEW

**Comment by cdjackson** [comment]
I haven’t looked at the PR, but it includes multiple issues that really should be separated out. It has some suff associated with the Heatmiser binding, and other stuff that includes zwave devices…

**Comment by SkynetHome** [comment]
I dont know why that zwave binding commit got pushed in, I created a separate branch just for the Heatmiser. Whats the easiest way to separate?

**Comment by cdjackson** [comment]
Depending on how you’ve branched this, you could reset the zwave files. Alternatively, you might need to create a separate branch. 

I think I mentioned before, but you should keep master branch un touched, and then always change to the master before creating a branch. Otherwise your new branch will contain all the PRs from the old branch. If this is what you’ve done, then you’ll need to start again I think since you’re effectively working on the same branch as the other ones with the same files in them.

**Comment by SkynetHome** [comment]
So I have master, then I need a sub branch  and then another branch under
that sub branch for each thing I work on?

**Comment by cdjackson** [comment]
> 
> So I have master, then I need a sub branch and then another branch under
> that sub branch for each thing I work on?
> On Jun 30, 2015 11:28 AM, "Chris Jackson" <notifications@github.com> wrote:

No. Just create a branch from master. This will be a fresh branch starting with the master. You then add your changes to it and commit them. If you make a new feature, change back to master and creat the new branch from there. This keeps all the features separate.

**Comment by SkynetHome** [comment]
OMG...I see what you are saying!!!!! So after I get through choking myself
out, do I need to just close my pulls and  then re edit the files into the
correct branch system and recommit?

**Comment by cdjackson** [comment]
I’ve not looked at how the branches are organised in your repo, but yes, I suspect the best thing to do is to start from a clean master branch, then create the new branch off that for each feature and put the appropriate file(s) for that feature into the repo and commit the changes.

**Comment by SkynetHome** [comment]
Omg...ok well...here we go again. Look for new pulls from me in about an
hour!

**Comment by SkynetHome** [comment]
Ok...please tell me I've got it right now!

**Comment by cdjackson** [comment]
Sorry - same problem.

This switch PR must be in your master branch or something, so when you create a new branch, it’s already there?

**Comment by cdjackson** [comment]
Ah - sorry - I looked at the old PR - the new one is OK :)

**Comment by SkynetHome** [comment]
I was about to have a melt down. So just for clarification one more time as
it takes a considerable amount of work to keep resetting all of this up. I
created a fork off openhab and cloned my repo. Then from my repo master I
added a branch Linear and comited file to that branch. Then I went back to
master and created new branch from master called GE. I am about add files
there and commit those. If i do that all will be well...right? I just need
to create a new branch from master before I commit new files or changes.

**Comment by cdjackson** [comment]
Yes - that's all good...

Just one comment. You should periodically pull the main OH master branch into your master, so that you're always starting your new branches with the latest code. Otherwise you'll slowly get out of sync...

It doesn't matter too much right now as you're doing the changes at basically the same time, but it's one for future. (I hope that makes sense - I don't want to complicate things more, but it is needed to avoid problems like merge conflicts).

**Comment by SkynetHome** [comment]
Thank you and yes I DESPERATELY  want to avoid merge conflicts. So just so
that I understand. When I clone openhab I have to go through this entire
build process in eclipse in order to remove errors and set target and all
that. Ok I've got that down because I have done it about 10 times now. I
understand how to create branches and update files, think I have that order
down pat now as well. But when I go to update openhab in my master. Do I
reclone and if so will I have to repeat the entire build process again in
eclipse every time?

**Comment by cdjackson** [comment]
> 
>  But when I go to update openhab in my master. Do I
> reclone and if so will I have to repeat the entire build process again in
> eclipse every time?

No - you don’t need to reclone. If you have SourceTree (which I think you are now using), then configure the main OH repo as a REMOTE. You need to click on ‘fetch from all remotes’ to get everything updated. Then, you should be able to change your local branch to master, then right click on the OH master branch in its remote, and select “pull openhab/master into your local branch”. This just keeps your local branch in synch with the OH master branch.

**Comment by SkynetHome** [comment]
Ok maybe one thing at a time. I downloaded source tree to try and fix the
merge nightmare I had the first go round several days ago but had no luck
went back to using github windows for managing repo and comitts. I seem to
have this down as the last two pulls are only showing the relevant files. I
am going to redo the edit for this Issue and commit and then see if I can't
setup source tree.

**Comment by SkynetHome** [comment]
Here's a weird problem. After I reinstalled and setup everything I can no
longer see src/main/java in the bindings folders in Eclipse. Nor do I see
src/main/resources or JRE system library tabs? Do you know what is causing
this?

**Comment by SkynetHome** [comment]
Ignore last I fixed it.

**Comment by SkynetHome** [comment]
Chris,

In source tree after pulling OH remote into local branch master I have 4
files to push. I assume these are the commits that as of yet have not been
merged. Do I push them?

**Comment by SkynetHome** [comment]
Chris

I wrote a db file for the remotec thermostat that was one of the issues on
your assigned list. It's ready to comit but I also need to edit the
products file and I am concerned that because I still have another pull
that has yet to be merged with a products file in it that if I commit
another products file for the remotec  the two will then be out of sync so
I think I am just going to leave this alone for now until I hear back from
you tomorrow if possible. I would hate to screw this up again and I have
been at this for 10 hours now today so I think a break is probably in order
:)

**Comment by cdjackson** [comment]
It should be fine - so long as you’re editing different parts of the products file. The system will sort this out - there should only be merge conflicts if there are two changes to the same line in the file. Also, not pushing it won’t actually make any difference since it’s not the merging that causes the conflict anyway.

**Comment by SkynetHome** [comment]
Awesome thanks for responding! Now I have a ton of more work to do as
several jobs were waiting on this answer. :) Back at it! I appreciate the
continued support!

**Comment by cdjackson** [comment]
No probs - I appreciate the help :)

**Pull request closed without merging**
