### PR TITLE
Atmosphere 2.2 update

### PR DESCRIPTION
**Pull request by sja**
Upgrade from Atmosphere 2.0.9 to 2.2.5. Due to API changes, openhab's packages .io.rest* and .io.cv had to be changed, too.

Other changes:
* Prevent logger to do heavy string operations on every request
* Give jvm optimizer a chance to remove logging code
* Remove unneccessary casts
* Remove nestes try/catch blocks
* Use eclipse formatter
* Add exceptions on error logging to get stack traces
* Use slf4j feature to log with varargs to not create and cast String[]

I think it's best to leave this branch un-squased for better reviewability.

### CODE REVIEW

**Comment by digitaldan** [comment]
hi @sja , thanks for doing this.  I was under the impression there was an issue with needing to upgrade jetty to go beyond the 2.0.x branches of atmosphere and that there was some problems with this, do you know of any issues?  I'm trying to test a fix right now in the rest code, your migration to the 2.2.x branch is really good timing.

**Comment by teichsta** [comment]
great, thanks @sja!

@digitaldan, @peuter, @jochenkluger, @oliver-M, @berndpfrommer it would be great if you could help testing this PR.

Thanks, Thomas E.-E.

**Comment by digitaldan** [comment]
Absolutely! I'll pull it down shortly.

**Comment by digitaldan** [comment]
So far so good. I did notice an exception thrown in Habmin, you might want to ping @cdjackson about it, but it did not seem to effect it adversely as I was still able to use its zwave functionality.  I'm going to run some load tests and confirm memory issues are low.   The exception is below:

```
4:02:30.757 WARN  o.a.cpr.AtmosphereFramework[:1097]- 
java.lang.ClassNotFoundException: org.atmosphere.interceptor.DefaultHeadersInterceptor
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:501)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412)
        at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
        at org.atmosphere.util.IOUtils.loadClass(IOUtils.java:309)
        at org.atmosphere.cpr.AtmosphereFramework.configureAtmosphereInterceptor(AtmosphereFramework.java:1094)
        at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:892)
        at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:780)
        at org.atmosphere.cpr.AtmosphereServlet.configureFramework(AtmosphereServlet.java:101)
        at org.atmosphere.cpr.AtmosphereServlet.init(AtmosphereServlet.java:80)
        at org.eclipse.equinox.http.servlet.internal.ServletRegistration.init(ServletRegistration.java:49)
        at org.eclipse.equinox.http.servlet.internal.ProxyServlet.registerServlet(ProxyServlet.java:179)
        at org.eclipse.equinox.http.servlet.internal.HttpServiceImpl.registerServlet(HttpServiceImpl.java:66)
        at org.openhab.io.habmin.HABminApplication.activate(HABminApplication.java:178)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:491)
        at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:235)
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
        at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
        at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
        at org.eclipse.equinox.internal.ds.Resolver.buildNewlySatisfied(Resolver.java:473)
        at org.eclipse.equinox.internal.ds.Resolver.enableComponents(Resolver.java:217)
        at org.eclipse.equinox.internal.ds.SCRManager.performWork(SCRManager.java:816)
        at org.eclipse.equinox.internal.ds.SCRManager$QueuedJob.dispatch(SCRManager.java:783)
        at org.eclipse.equinox.internal.ds.WorkThread.run(WorkThread.java:89)
        at org.eclipse.equinox.internal.util.impl.tpt.threadpool.Executor.run(Executor.java:70)
```

**Comment by teichsta** [comment]
great, thanks Dan!

- sent from a mobile device -

**Comment by sja** [comment]
Oh, that class was renamed by Atmosphere. I had to change that in the
jersey servlet parameters, too. Ill contact him tomorrow, Im on a mobile
right now.

Am Samstag, 21. Februar 2015 schrieb Thomas Eichstädt-Engelen :

**Comment by cdjackson** [comment]
Pinged :)

I’ll take a look...

**Comment by cdjackson** [comment]
The line that’s causing the error is -:

			httpService.registerServlet(HABMIN_SERVLET_ALIAS,
			new AtmosphereServlet(), getJerseyServletParams(), createHttpContext());

I’m guessing that the new version doesn’t support some options (since the exception is ‘class not found’). I’ve not followed closely the changes here - can someone enlighten me?
My guess is it probably doesn’t matter, but it would be nice to eliminate it if possible.

**Comment by sja** [comment]
@cdjackson Your error is in your [RESTApplication.java:198] (https://github.com/cdjackson/openhab/blob/HABmin/bundles/io/org.openhab.io.rest/src/main/java/org/openhab/io/rest/RESTApplication.java#L198). The `DefaultHeadersInterceptor` was renamed to `CacheHeadersInterceptor` in Atmosphere 2.2.

**Comment by cdjackson** [comment]
But isn’t that in a separate bundle? I don’t think this is statically linked into HABmin is it? It’s dynamically included through the org.open.io.rest bundle (isn’t it?)??

**Comment by sja** [comment]
Yes, it's dynamically included. But your HABminApplication seems to include that dynamically, too. Oh, I see that the HABmin-Bundle comes with it's own Atmosphere ... did you left that as is or have you upgraded that Atmosphere in you test, too?

**Comment by Testato** [comment]
On 1.7.1 + Habmin 0.1.3 is there the same exception.
It create problem ?
```
java.lang.ClassNotFoundException: org.atmosphere.interceptor.DefaultHeadersInterceptor

**Pull request merged**
