### PR TITLE
[Weather] remove caching

### PR DESCRIPTION
**Pull request by jowi24**
In reference to  #3092 this pull request removes the internal caching in the weather binding to avoid holding state in the binding.

### CODE REVIEW

**Comment by teichsta** [comment]
Thanks @jowi24 for this contribution. However as discussed in #3092 i'll close this issue since @gerrieg had good reasons to implement caching in the Weather binding.

**Comment by teichsta** [comment]
as further discussed in #3092 we agreed to remove the caching after all.

**Comment by teichsta** [comment]
the PR lgtm. @jowi24 could you please squash your commits into one? Thanks, Thomas E.-E.

**Comment by jowi24** [comment]
I squashed both commits into one now.

**Pull request merged**
