### PR TITLE
applied updated and neutral copyright header

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by teichsta** [comment]
Thanks Kai!

**Comment by watou** [comment]
Hi @teichsta @kaikreuzer , it looks like a number of files were added to master with this merge, including o.o.io.transport.cul.internal.CULSerialHandlerImpl.java that seems to have broken the build.  Did you mean to add a number of files to master with this PR?

**Comment by kaikreuzer** [comment]
It should have clearly been merged before https://github.com/openhab/openhab/pull/4330 was merged.
As this PR is anyhow more than a month old by now, I guess it makes sense to reapply the license header to the whole repo as there are probably some further changes meanwhile.

**Comment by watou** [comment]
Did this PR, cherry picked onto 1.8, change pom.xml files as described [here](https://community.openhab.org/t/is-there-any-github-project-related-to-openhab1-core-source-code/8539/18?u=watou)?  Sorry not enough time to investigate myself at the moment.

**Comment by 9037568** [comment]
I just ran a build of the 1.8 branch, and it appears to have been completely successful, with the distributable zips built and intact.

```
[INFO] openHAB Distribution ............................... SUCCESS [01:49 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 09:10 min
[INFO] Finished at: 2016-05-13T07:20:54-04:00
[INFO] Final Memory: 273M/1022M
[INFO] ------------------------------------------------------------------------

05/13/2016  07:19 AM        37,303,608 distribution-1.8.3-SNAPSHOT-runtime.zip
05/13/2016  07:20 AM        36,849,968 openhab-runtime-1.8.3-SNAPSHOT.deb
```

The multimedia package is included:
    server/plugins/org.openhab.io.multimedia_1.8.3.201605131112.jar

I uploaded [a full dump of the contents](https://drive.google.com/file/d/0B8vYheWfObP9UU1KR0c1a0dwVlU/view?usp=sharing) of the runtime zip.

**Comment by watou** [comment]
Thank you, Chris. I didn't have the chance to test the claim on the forum
myself; glad you did!  I vote to add you to the maintainers group!

**Comment by kaikreuzer** [comment]
> I vote to add you to the maintainers group!

With such a good reference: @9037568, you're added :-) (btw, Chris, what is your handle in the community.openhab.org, I would add you there as well)

**Comment by 9037568** [comment]
Thanks for the vote of confidence, John.

Kai, my handle in the community is [namraccr](https://community.openhab.org/users/namraccr)

**Comment by kaikreuzer** [comment]
Thanks, I've added you there as well!

**Comment by watou** [comment]
@9037568 Welcome aboard, Chris, and thank you @kaikreuzer !

**Comment by kaikreuzer** [comment]
> No, i'll have a look at it in about two hours ...

@teichsta Are there any problems with cleaning the messed up repo again? Do you need help?

**Comment by teichsta** [comment]
see https://github.com/openhab/openhab/pull/4381 which should address this … could you please verify?

**Pull request merged**
