### PR TITLE
Small fixes to TACmi binding

### PR DESCRIPTION
**Pull request by Wolfgang1966**
Fixed handling of negative temperature values
Improved BigDecimal Math
Improved error handling, logging and socket timeout in exec loop

### CODE REVIEW

**Comment by Wolfgang1966** [comment]
This is a recreated pull request of some fixes I made a few weeks ago. As I am new to git and GitHub, I messed up the commits, so I finally started from scratch. Changes were reviewed by Thomas Eichstädt Engelen last time. Sorry for the trouble I caused.

**Comment by watou** [comment]
Thanks for contributing this!  Ought this fix be present in openHAB 1.8.2?

**Comment by Wolfgang1966** [comment]
Yes, I recommend that. Especially the current implementation doesn't handle temperature values below zero degrees celsius correctly.

**Comment by teichsta** [comment]
Thanks @Wolfgang1966! Also cherry-picked onto 1.8 …

**Pull request merged**
