### PR TITLE
Better SsdpDiscovery and improved stability

### PR DESCRIPTION
**Pull request by steintore**
During my latest testing and discussions in the forums, there has been some issues with SsdpDiscovery.
I've handled the discovery better, and it has been tested by some other users as well.
Also the air conditioners sometimes disconnect from the WIFI, this caused the binding to drop the connection and not properly reconnect, this should, if not fix it entirely, better the problem...

### CODE REVIEW

**Comment by teichsta** [comment]
Thanks @steintore! It would be great if you could also check the compatibility against the OH2 core and note your results here https://github.com/openhab/openhab2/blob/master/docs/sources/addons.md#compatible-1x-add-ons. Thanks again, Thomas E.-E.

**Comment by watou** [comment]
A number of logger.debug calls are now logger.info calls.  Is this intentional?

**Comment by steintore** [comment]
@watou Yes, some logging has been changed to debug, some to warn and some to info. I think this is better than before, cause it gives the user more information about what is going on.
Please, let me know if you thing it logs too much or if it logs the "wrong" things...

**Comment by steintore** [comment]
@teichsta I've tested the binding today and it works fine with openhab 2 for my Air Conditioner.

**Comment by teichsta** [comment]
great, thanks a million!

**Comment by kaikreuzer** [comment]
Thanks @steintore. With all the Ssdp and discovery functionality, this binding actually looks like a pretty good candidate to be migrated to the new 2.0 APIs, which directly support upnp and device discovery out of the box.

**Comment by JuStAdsor** [comment]
Hi!
I can use the discovery to find the AC, however, I can not get the token:

00:13:47.341 [INFO ] [.s.communicator.AirConditioner:93   ] - Disconnected from AC: 192.168.1.177
00:13:47.341 [DEBUG] [.b.s.internal.SamsungAcBinding:285  ] - java.lang.Exception: Cannot connect to 192.168.1.177:2878 : javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
00:13:47.342 [INFO ] [.b.s.internal.SamsungAcBinding:286  ] - Reconnect failed for 'Livingroom', will retry in 60s
00:14:47.341 [INFO ] [.b.s.internal.SamsungAcBinding:275  ] - Broken connection found for 'Livingroom', attempting to reconnect...
00:14:47.342 [INFO ] [.s.communicator.AirConditioner:257  ] - Disconnected so we'll try again
00:14:47.343 [INFO ] [.s.communicator.AirConditioner:93   ] - Disconnected from AC: 192.168.1.177
00:14:47.401 [INFO ] [.s.communicator.AirConditioner:75   ] - Disconneting...
java.lang.Exception: Cannot connect to 192.168.1.177:2878
	at org.binding.openhab.samsungac.communicator.AirConditioner.connect(AirConditioner.java:283) ~[bundlefile:na]
	at org.binding.openhab.samsungac.communicator.AirConditioner.login(AirConditioner.java:71) ~[bundlefile:na]
	at org.openhab.binding.samsungac.internal.SamsungAcBinding.reconnectToAirConditioner(SamsungAcBinding.java:279) [bundlefile:na]
	at org.openhab.binding.samsungac.internal.SamsungAcBinding.execute(SamsungAcBinding.java:269) [bundlefile:na]
	at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:156) [org.openhab.core_1.8.0.201510121306.jar:na]
	at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:173) [org.openhab.core_1.8.0.201510121306.jar:na]
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at com.sun.net.ssl.internal.ssl.Alerts.getSSLException(Alerts.java:174) ~[na:1.6]
	at com.sun.net.ssl.internal.ssl.Alerts.getSSLException(Alerts.java:136) ~[na:1.6]
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:1822) ~[na:1.6]
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1004) ~[na:1.6]
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1188) ~[na:1.6]
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1215) ~[na:1.6]
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1199) ~[na:1.6]
	at org.binding.openhab.samsungac.communicator.AirConditioner.connect(AirConditioner.java:280) ~[bundlefile:na]
	... 5 common frames omitted
00:14:47.402 [INFO ] [.s.communicator.AirConditioner:93   ] - Disconnected from AC: 192.168.1.177
00:14:47.402 [DEBUG] [.b.s.internal.SamsungAcBinding:285  ] - java.lang.Exception: Cannot connect to 192.168.1.177:2878 : javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
00:14:47.402 [INFO ] [.b.s.internal.SamsungAcBinding:286  ] - Reconnect failed for 'Livingroom', will retry in 60s

**Comment by steintore** [comment]
Hi @JuStAdsor there is already an open bug on the issue you're describing, check it out here: https://github.com/openhab/openhab/issues/2863
Unfortunately there is currently no solution for the handshake failure

**Pull request merged**
