### PR TITLE
First Checkin of FritzBox TR064 Binding for 1.8.0

### PR DESCRIPTION
**Pull request by gitbock**
Hi,
After @teichsta 's Code Review I created this pull request. Reference [here] (https://github.com/openhab/openhab/pull/2494#issuecomment-145274238).

Regards
gitbock

### CODE REVIEW

**Comment by teichsta** [comment]
Hi @gitbock,

i've merged this PR. However it would be great if you could please address the following issues:

* try your binding in the OH2 runtime
* provide create the according wiki page
* remove dependencies to HTTPClient (remove jar, remove from build.properties, remove from MANIFEST.MF, add import-package statements to MANIFEST.MF)

Thanks again, Thomas E.-E.

**Comment by gitbock** [comment]
Hi @teichsta 
* I did a quick test using openHAB v2: The binding is working. It cann access the FritzBox using the SOAP requests. I extracted the openhab.cfg part into a new conf file ./conf/services/fritzboixtr064.conf for this.
* I created a [wiki page] (https://github.com/openhab/openhab/wiki/FritzBox-TR064-Binding).
* I will have a look reagarding the HTTPClient.

**Comment by mattnl** [comment]
Hi,
I just downloaded the latest addons-snapshot build from cloudbees - #1105 (Dec 28, 2015 3:31:24 AM) and noticed the the fritzbox064 binding is not included yet. Since it seems to be merged, can someone please check why it is not included in the latest build?

@gitbock, thank you very much for this binding! I am currently using the 0.7 release from your repository and it is working very good.

Thanks,
Matt

**Comment by watou** [comment]
It's not included in the build because it's not added to `bundles/binding/pom.xml` or `distribution/pom.xml`.  Just a note to @teichsta to be sure he will consider this.  Please let me know if you would like a JAR for it in the meantime.

**Comment by gitbock** [comment]
@mattnl 
Thanks for the nice feedback :)

Somebody already reported [this] (https://github.com/gitbock/fritzboxtr064/issues/6). I need to check if I can add the needed statements to pom.xml myself or if only Kai/Thomas can do that.

**Comment by watou** [comment]
@gitbock you can create a branch with those 2 file changes and submit a pull request.

**Pull request merged**
