### PR TITLE
Modify to persistence.cosm

### PR DESCRIPTION
**Pull request by fazioa**
In origin was Patchube,  then Cosm and now Xively.
I need to log my data on Xively, but actual org.openhab.persistence.cosm don't work.
I propose this modify.

### CODE REVIEW

**Comment by teichsta** [comment]
Hi @fazioa, for the sake of transparency please split this PR into several. Each PR should follow a single purpose. Thanks, Thomas E.-E.

**Comment by eekhoorn** [comment]
Hi @fazioa, I'm interested in this binding too. However I'm using Openhab 1.7. 
I tested your new binding, but it didn't work. Do you have also a 1.7 version?

Regards, E.

**Comment by fazioa** [comment]
Yes, I run OH 1.7
Il 28/lug/2015 12:47, "eekhoorn" <notifications@github.com> ha scritto:

**Comment by teichsta** [comment]
@fazioa please split this PR into different with one single feature/purpose each

**Comment by fazioa** [comment]
New PR #3233, only for Cosm Persistence

**Comment by teichsta** [comment]
PR is outdated and can be closed.

**Pull request closed without merging**
