### PR TITLE
Edited Aeon MSES

### PR DESCRIPTION
**Pull request by SkynetHome**
Edited Aeon MSES to more accurately reflect actual parameters for a
first generation smart switch from Aeon Labs pursuant to HABmin Issue #106 and in attempt to clean up the inconsistencies in Aeon Labs portion of the database!

### CODE REVIEW

**Comment by SkynetHome** [comment]
CHRIS JACKSON:

I wrote this to help clean up the Aeon Labs Database before I realized that there is an Issue #108 on your HABmin repository concerning this but I felt this was the best place to attempt at adding the changes and just mention your repository Issue. Let me know what you think and if further work on the database would be helpful. Thanks!

**Comment by cdjackson** [comment]
Do you really mean 108 or 106 or? (since you’re posting this in the OH repository, the links go to the wrong place - you need to paste full URL in for it to work and GH will work it out).

I’m happy if you want to knock off database questions on the HABmin or HABmin2 repo - feel free to reference them, but yes, the PR needs to come here, so all good…

Thanks (again :) )

**Comment by cdjackson** [comment]
How sure are you about these changes?

The reason that https://github.com/cdjackson/HABmin/issues/106 stalled is because it became unclear what the different versions were. I contacted Aeon, and they also couldn't tell me what the versions really were!

I'm just hesitant to change the database to fix a problem that one person reports when someone else originally added the entry to the database, and therefore it's likely to cause problems elsewhere (so ultimately we're not improving things).

What do you think?

**Comment by SkynetHome** [comment]
I actually came across this because as I have learned to properly write database entries from you I have noticed many entries that are not written "properly" if that is the term. So I was looking through the aeon database as I have several of their switches and noticed that the MSES was just wrong. Minor things like help lines that were clearly copy and pasted to the wrong parameter, english in the "de" help tags mostly minor stuff but one just incorrect parameter setting. So I started looking more closely at the pepper database and realized that the file being used for MSES was just a copy of the file for the second gen model and there is zero indication that MSES has the same parameters or associations. So rather than just make the minor changes I originally found I rewrote the file to match the actual parameters for the device. In so doing I came across https://github.com/cdjackson/HABmin/issues/106 and realized that the cause of the problems is likely that the database files were not properly written.  So I decided to write this in accordance with what the pepper database says and commit for your approval. I realize that Pepper is not the utmost authority on the matter as I have found numerous errors in their database as well and  what is even more troubling is that AEON doesnt seem to know their own product. Its likely that because they are apparently not producing anymore first gen models that they simply dont care. So all that to say that all we have to go on with some of these devices is pepper and logical deduction that there are going to be some differences between a 1st gen and 2nd gen model. I would have just ignored this but once I saw in the above issue from habmin that there were reported issues with AEON products I thought it might be worth it for me to go through and try to sort them out by at least matching the files with what we do know about the devices and testing from there.

**Comment by cdjackson** [comment]
Hi Mike,
I completely understand where you’re coming from, and it would be nice to sort the files out :)  I’m just as guilty for rushing some of this through as in the past I’ve done the lions share of these files (along with the binding itself) - again, I appreciate you picking this up :)

However, a few words of caution to avoid wasting your time… OH2 is coming and the database will be different. That’s not to say that if you fix things in OH1, it will be a total waste of time for OH2 - it won’t. I have a converter that will convert most of the data from the OH1 format to OH2, but there are changes… I’m currently working heavily on the OH2 binding and will try and get a document with the OH2 format out in the next few days (it’s in progress).

As a starter, things that will ‘get lost’ in the conversion are -:
- command classes - don’t spend time putting these in the top of the file
- translations - translation is done completely differently in OH2 and I’m not going to do the conversion as it really isn’t simple.

The parameters, help, labels, options etc will all be converted straight over, so anything you do there won’t be wasted.

If you’re tidying up the help text, I intend to put together some guidelines on this, but the following is what I’m thinking…
Use HTML if there’s a lot of text. Put them inside the CDATA tags in the XML (I think I’ve seen you’ve done this already). HABmin 1 also supports this, and it makes the help much more readable. In HABmin 2, I will display the first line under the parameter - if there’s a <BR>, then that terminates the line, otherwise it will just be displayed up to the length of available space. Clicking on the truncated text will pop up a dialog with the full help - again, a nice HTML page should look much better, especially when trying to format up descriptions of options etc…

I’ll let you know how this goes and also when I publish the format (maybe tomorrow if I get things vaguely working ok tonight :) ).

Cheers
Chris

**Comment by SkynetHome** [comment]
Thanks for taking the time to respond in such detail. It's likely that I am being a bit over zealous which is causing met to LOOK for things to work on rather than just work on what needs to be done. I am going to spend some time just learning more about Java as whole and handle what I am capable of handling with openhab as it comes up rather than, tearing through the database trying to find something to work on. I will be looking forward to your OH2 format so that I can make sure my efforts are directed in a manner that will pay off in the long run and as always I appreciate your continued support!

**Comment by cdjackson** [comment]
> On 12 Jul 2015, at 18:06, Mike Van Dusen <notifications@github.com> wrote:
> 
> I will be looking forward to your OH2 format so that I can make sure my efforts are directed in a manner that will pay off in the long run and as always I appreciate your continued support!

Hi Mike,
I finally got some time to put this together -:
https://github.com/cdjackson/HABmin2/wiki/ZWave-Product-Database---OH2 <https://github.com/cdjackson/HABmin2/wiki/ZWave-Product-Database---OH2>

Chris

**Comment by SkynetHome** [comment]
Okay so just for clarification. Should I add/edit devices to follow this format in the OH1 IDE and database or setup a new OH2 IDE and starting working in there?

**Comment by cdjackson** [comment]
> 
> Okay so just for clarification. Should I add/edit devices to follow this format in the OH1 IDE and database or setup a new OH2 IDE and starting working in there?
> 
> 

Just keep using the old format in the current repository for now until OH2 is ready. The formats aren’t compatible so we will need to support both for a while and I think that adding the devices to OH1 first, then converting them to OH2 and adding the extra information is best… I have a converter which converts most of the information to the new format, but there will still be information that needs to be added as the OH2 binding needs additional information.

**Pull request closed without merging**
