### PR TITLE
Added support for Energenie PWM-LAN Measurement Device

### PR DESCRIPTION
**Pull request by chris-kuhr**

### CODE REVIEW

**Comment by teichsta** [comment]
any update @chris-kuhr?

**Comment by chris-kuhr** [comment]
I have not found the time yet, sorry...

**Comment by teichsta** [comment]
> I have not found the time yet, sorry...
no worries … any idea when you'll find the time?

**Comment by hmerk** [comment]
@chris-kuhr, any news ?

**Comment by chris-kuhr** [comment]
not until now... it took me about a year to get started in the first place...  but I hope that I will find the time over christmas...

BR,
Christoph

Am 15. Dezember 2015 22:58:13 MEZ, schrieb "Hans-Jörg Merk" <notifications@github.com>:
>@chris-kuhr, any news ?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/openhab/openhab/pull/2908#issuecomment-164908517

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by chris-kuhr** [comment]
Hi,

I am sorry. I am no Java developer, and Yoxos reminded me why!
After hours of dealing with Yoxos and its permanent crashing, I have no
time and no nerves left to look any further into this...
This development environment is the worst I have ever seen and is the
reason, why my work on this has always been delayed.
If some makes the adjustments to the code, that you asked for, I am
happy to test it!
But I won't do any further development. Sorry...

BR,
Christoph Kuhr

**Comment by teichsta** [comment]
@chris-kuhr sorry to hear about your hurdles with yoxos. At first sight yoxos looked very great but meanwhile they moved to a premium version and stopped maintaining the profiles for projects like us. Hence we didn't recommend using yoxos anymore.

In OH2/ESH Kai spent a lot of time optimizing the setup using the new [Eclipse Oomph Installer which works pretty smoothly](https://www.youtube.com/watch?v=o2QjCGdZl7s). 

Best, Thomas E.-E.

**Comment by teichsta** [comment]
@hmerk would you probably able to send your suggestions as PR to this PR which @chris-kuhr can easily merge to make progress on this issue?

**Comment by hmerk** [comment]
@teichsta I will try to do so until Wednesday, as I have some days off.

**Comment by teichsta** [comment]
great, thanks!

**Comment by hmerk** [comment]
@chris-kuhr 
Chris, could you please try the attached approach, as I don't have a PWM-LAN.
For Item Config, please use the channel Numbers for Switching, for Measurement please use the Channel Names "VOLTAGE, CURRENT, POWER, ENERGY".
[org.openhab.binding.energenie-1.8.0-SNAPSHOT.jar.zip](https://github.com/openhab/openhab/files/73859/org.openhab.binding.energenie-1.8.0-SNAPSHOT.jar.zip)

**Comment by chris-kuhr** [comment]
Hi,

I will test... But I first have to update to 1.8.0 ... I will need a few
days and then report back...

BR,
Ck

**Comment by hmerk** [comment]
Hi Chris,
You don't have to update to 1.8, just put the jar into your running installation.
Best
Hans-Jörg

**Comment by chris-kuhr** [comment]
Ok...

Item Config:

Number B_Trockner_Voltage     "Trockner Spannung [%.1f]" <energy>   
(BasementMeasurement)            {energenie="pwm1;VOLTAGE"}
Number B_Trockner_Current     "Trockner Strom [%.1f]" <energy>   
(BasementMeasurement)            {energenie="pwm1;CURRENT"}
Number B_Trockner_Power     "Trockner Leistung [%.1f]" <energy>   
(BasementMeasurement,G_Basement)            {energenie="pwm1;POWER"}
Number B_Trockner_Energy     "Trockner Energie [%.1f]" <energy>   
(BasementMeasurement)            {energenie="pwm1;ENERGY"}

Number B_WaschMasch_Voltage     "Waschmaschiene Spannung [%.1f]"
<energy>    (BasementMeasurement)            {energenie="pwm2;VOLTAGE"}
Number B_WaschMasch_Current     "Waschmaschiene Strom [%.1f]"
<energy>    (BasementMeasurement)            {energenie="pwm2;CURRENT"}
Number B_WaschMasch_Power     "Waschmaschiene Leistung [%.1f]"
<energy>    (BasementMeasurement,G_Basement)           
{energenie="pwm2;POWER"}
Number B_WaschMasch_Energy     "Waschmaschiene Energie [%.1f]"
<energy>    (BasementMeasurement)            {energenie="pwm2;ENERGY"}


Following findings:
2015-12-30 10:07:23.058 [DEBUG] [.e.internal.EnergenieActivator] -
Energenie binding has been started.
2015-12-30 10:07:23.234 [ERROR] [i.internal.GenericItemProvider] -
Binding configuration of type 'energenie' of item ‘B_Trockner_Voltage‘
could not be parsed correctly.
org.openhab.model.item.binding.BindingConfigParseException: item
'B_Trockner_Voltage' is of type 'NumberItem', only SwitchItems are
allowed - please check your *.items configuration
    at
org.openhab.binding.energenie.internal.EnergenieGenericBindingProvider.validateItemType(EnergenieGenericBindingProvider.java:56)
~[na:na]
    at
org.openhab.model.item.internal.GenericItemProvider.internalDispatchBindings(GenericItemProvider.java:347)
[org.openhab.model.item_1.7.0.jar:na]
    at
org.openhab.model.item.internal.GenericItemProvider.dispatchBindingsPerType(GenericItemProvider.java:309)
[org.openhab.model.item_1.7.0.jar:na]
    at
org.openhab.model.item.internal.GenericItemProvider.addBindingConfigReader(GenericItemProvider.java:106)
[org.openhab.model.item_1.7.0.jar:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
~[na:1.8.0_33]
    at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
~[na:1.8.0_33]
    at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
~[na:1.8.0_33]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_33]
    at
org.eclipse.equinox.internal.ds.model.ComponentReference.bind(ComponentReference.java:376)
[org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
    at
org.eclipse.equinox.internal.ds.model.ServiceComponentProp.bindReference(ServiceComponentProp.java:444)
[org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
    at
org.eclipse.equinox.internal.ds.InstanceProcess.dynamicBind(InstanceProcess.java:416)
[org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
    at
org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:334)
[org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
    at
org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
[org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
    at
org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:107)
[org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
    at
org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:861)
[org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
    at
org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
[org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
    at
org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
[org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
    at
org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:819)
[org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
    at
org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:771)
[org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
    at
org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
[org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
    at
org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:214)
[org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
    at
org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:433)
[org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
    at
org.eclipse.equinox.internal.ds.InstanceProcess.registerService(InstanceProcess.java:536)
[org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
    at
org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:260)
[org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
    at
org.eclipse.equinox.internal.ds.Resolver.buildNewlySatisfied(Resolver.java:473)
[org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
    at
org.eclipse.equinox.internal.ds.Resolver.enableComponents(Resolver.java:217)
[org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
    at
org.eclipse.equinox.internal.ds.SCRManager.performWork(SCRManager.java:816)
[org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
    at
org.eclipse.equinox.internal.ds.SCRManager$QueuedJob.dispatch(SCRManager.java:783)
[org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
    at
org.eclipse.equinox.internal.ds.WorkThread.run(WorkThread.java:89)
[org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
    at
org.eclipse.equinox.internal.util.impl.tpt.threadpool.Executor.run(Executor.java:70)
[org.eclipse.equinox.util_1.0.400.v20120917-192807.jar:na]
2015-12-30 10:07:23.245 [ERROR] [i.internal.GenericItemProvider] -
Binding configuration of type 'energenie' of item ‘B_Trockner_Current‘
could not be parsed correctly.
org.openhab.model.item.binding.BindingConfigParseException: item
'B_Trockner_Current' is of type 'NumberItem', only SwitchItems are
allowed - please check your *.items configuration
... see above ...
2015-12-30 10:07:23.257 [ERROR] [i.internal.GenericItemProvider] -
Binding configuration of type 'energenie' of item ‘B_Trockner_Power‘
could not be parsed correctly.
org.openhab.model.item.binding.BindingConfigParseException: item
'B_Trockner_Power' is of type 'NumberItem', only SwitchItems are allowed
- please check your *.items configuration
... see above ...
2015-12-30 10:07:23.268 [ERROR] [i.internal.GenericItemProvider] -
Binding configuration of type 'energenie' of item ‘B_Trockner_Energy‘
could not be parsed correctly.
org.openhab.model.item.binding.BindingConfigParseException: item
'B_Trockner_Energy' is of type 'NumberItem', only SwitchItems are
allowed - please check your *.items configuration
... see above ...
2015-12-30 10:07:23.291 [ERROR] [i.internal.GenericItemProvider] -
Binding configuration of type 'energenie' of item ‘B_WaschMasch_Current‘
could not be parsed correctly.
org.openhab.model.item.binding.BindingConfigParseException: item
'B_WaschMasch_Current' is of type 'NumberItem', only SwitchItems are
allowed - please check your *.items configuration
... see above ...
2015-12-30 10:07:23.302 [ERROR] [i.internal.GenericItemProvider] -
Binding configuration of type 'energenie' of item ‘B_WaschMasch_Power‘
could not be parsed correctly.
org.openhab.model.item.binding.BindingConfigParseException: item
'B_WaschMasch_Power' is of type 'NumberItem', only SwitchItems are
allowed - please check your *.items configuration
... see above ...
2015-12-30 10:07:23.313 [ERROR] [i.internal.GenericItemProvider] -
Binding configuration of type 'energenie' of item ‘B_WaschMasch_Energy‘
could not be parsed correctly.
org.openhab.model.item.binding.BindingConfigParseException: item
'B_WaschMasch_Energy' is of type 'NumberItem', only SwitchItems are
allowed - please check your *.items configuration
... see above ...

**Comment by hmerk** [comment]
@chris-kuhr did you forget to remove the old .jar ?
Within the new Version, the Message is changed to "only SwitchItems and NumberItems are allowed - please check your *.items configuration", but that's not what your log states.

Best
Hans-Jörg

**Comment by chris-kuhr** [comment]
I renamed the old jar to jar.bak
openhab.log sais it shuts the binding down after I rename it...

Now I moved it one folder up and restarted openhab, but I got the same
error logs...

**Comment by hmerk** [comment]
Ups, my fault. I was in the wrong workspace and compiled old sources.
Please try this one.
[org.openhab.binding.energenie-1.8.0-SNAPSHOT.jar.zip](https://github.com/openhab/openhab/files/74829/org.openhab.binding.energenie-1.8.0-SNAPSHOT.jar.zip)

**Comment by chris-kuhr** [comment]
Hi,

the binding seems to parse correctly, but the refreshing service shuts down after some time. I see no values in the browser. The output is below. I also rebooted the devices, but no difference. 
oH is currently not running in debug mode, which I will try on friday.

BR



2015-12-30 13:45:13.204 [DEBUG] [.e.internal.EnergenieActivator] - Energenie binding has been stopped.
2015-12-30 13:45:13.362 [DEBUG] [.e.internal.EnergenieActivator] - Energenie binding has been started.
2015-12-30 13:45:13.567 [INFO ] [.service.AbstractActiveService] - Energenie Refresh Service has been started
2015-12-30 13:45:13.569 [DEBUG] [.b.e.internal.EnergenieBinding] - execute() method is called!
2015-12-30 13:45:42.893 [INFO ] [.service.AbstractActiveService] - Energenie Refresh Service has been shut down
2015-12-30 13:46:16.929 [TRACE] [.b.e.internal.EnergenieBinding] - logout from ip 192.168.178.4
2015-12-30 13:46:17.104 [TRACE] [.b.e.internal.EnergenieBinding] - logout from ip 192.168.178.4
2015-12-30 13:46:17.274 [TRACE] [.b.e.internal.EnergenieBinding] - logout from ip 192.168.178.4
2015-12-30 13:46:17.440 [TRACE] [.b.e.internal.EnergenieBinding] - logout from ip 192.168.178.6
2015-12-30 13:46:17.615 [TRACE] [.b.e.internal.EnergenieBinding] - logout from ip 192.168.178.6
2015-12-30 13:46:17.785 [TRACE] [.b.e.internal.EnergenieBinding] - logout from ip 192.168.178.6
2015-12-30 13:46:32.989 [TRACE] [.b.e.internal.EnergenieBinding] - logout from ip 192.168.178.4
2015-12-30 13:46:33.166 [TRACE] [.b.e.internal.EnergenieBinding] - logout from ip 192.168.178.6



On 30.12.2015 13:41, Hans-Jörg Merk wrote:

Ups, my fault. I was in the wrong workspace and compiled old sources.
Please try this one.
org.openhab.binding.energenie-1.8.0-SNAPSHOT.jar.zip

—
Reply to this email directly or view it on GitHub. 



-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by hmerk** [comment]
@chris-kuhr thanks for testing and your patience.
I found some transformation bugs which should be solved now.
During my tests, the refresh service was not terminated and socket values got updated fine.
Please try the attached version.
[org.openhab.binding.energenie-1.8.0-SNAPSHOT.jar.zip](https://github.com/openhab/openhab/files/74985/org.openhab.binding.energenie-1.8.0-SNAPSHOT.jar.zip)

**Comment by chris-kuhr** [comment]
Its working!

I have not confirmed all values, because the dryer and wasching machine
are  not in use right now, but openhab.log and the attached screenshot
indicate, it looks fine...
I report back as soon as I have veryfied the other measurements.

I am not without patients by default :-)
I just get mad if I struggle more with the environment, then with the
code...
So testing is very fine for me and I hope my additions were not too
cryptic...

BR



2015-12-30 22:09:17.754 [DEBUG] [.e.internal.EnergenieActivator] -
Energenie binding has been started.
2015-12-30 22:09:18.889 [INFO ] [.service.AbstractActiveService] -
Energenie Refresh Service has been started
2015-12-30 22:09:18.894 [DEBUG] [.b.e.internal.EnergenieBinding] -
execute() method is called!
2015-12-30 22:09:19.390 [TRACE] [.b.e.internal.EnergenieBinding] - item
is of Type B_Trockner_Current (Type=NumberItem, State=Uninitialized)
2015-12-30 22:09:19.392 [TRACE] [.b.e.internal.EnergenieBinding] - about
to process NumberItem
2015-12-30 22:09:19.394 [TRACE] [.b.e.internal.EnergenieBinding] -
searchstring var I  =  found at position 500
2015-12-30 22:09:19.396 [TRACE] [.b.e.internal.EnergenieBinding] -
transformed state response = 1;      var
2015-12-30 22:09:19.398 [TRACE] [.b.e.internal.EnergenieBinding] -
transformed state response = 1 -       var
2015-12-30 22:09:19.400 [TRACE] [.b.e.internal.EnergenieBinding] -
transformed state for item B_Trockner_Current = 0.01
2015-12-30 22:09:19.524 [TRACE] [.b.e.internal.EnergenieBinding] -
logout from ip 192.168.178.4
2015-12-30 22:09:19.602 [TRACE] [.b.e.internal.EnergenieBinding] - item
is of Type B_Trockner_Voltage (Type=NumberItem, State=Uninitialized)
2015-12-30 22:09:19.603 [TRACE] [.b.e.internal.EnergenieBinding] - about
to process NumberItem
2015-12-30 22:09:19.605 [TRACE] [.b.e.internal.EnergenieBinding] -
searchstring var V  =  found at position 483
2015-12-30 22:09:19.606 [TRACE] [.b.e.internal.EnergenieBinding] -
transformed state response = 2324;   var
2015-12-30 22:09:19.608 [TRACE] [.b.e.internal.EnergenieBinding] -
transformed state response = 2324 -    var
2015-12-30 22:09:19.609 [TRACE] [.b.e.internal.EnergenieBinding] -
transformed state for item B_Trockner_Voltage = 232.4
2015-12-30 22:09:19.710 [TRACE] [.b.e.internal.EnergenieBinding] -
logout from ip 192.168.178.4
2015-12-30 22:09:19.871 [TRACE] [.b.e.internal.EnergenieBinding] - item
is of Type B_Trockner_Energy (Type=NumberItem, State=Uninitialized)
2015-12-30 22:09:19.872 [TRACE] [.b.e.internal.EnergenieBinding] - about
to process NumberItem
2015-12-30 22:09:19.873 [TRACE] [.b.e.internal.EnergenieBinding] -
searchstring var E= found at position 534
2015-12-30 22:09:19.874 [TRACE] [.b.e.internal.EnergenieBinding] -
transformed state response = 4747382;   var
2015-12-30 22:09:19.876 [TRACE] [.b.e.internal.EnergenieBinding] -
transformed state response = 4747382 -    var
2015-12-30 22:09:19.877 [TRACE] [.b.e.internal.EnergenieBinding] -
transformed state for item B_Trockner_Energy = 185.444609375
2015-12-30 22:09:19.979 [TRACE] [.b.e.internal.EnergenieBinding] -
logout from ip 192.168.178.4
2015-12-30 22:09:20.080 [TRACE] [.b.e.internal.EnergenieBinding] - item
is of Type B_WaschMasch_Voltage (Type=NumberItem, State=Uninitialized)
2015-12-30 22:09:20.082 [TRACE] [.b.e.internal.EnergenieBinding] - about
to process NumberItem
2015-12-30 22:09:20.084 [TRACE] [.b.e.internal.EnergenieBinding] -
searchstring var V  =  found at position 483
2015-12-30 22:09:20.085 [TRACE] [.b.e.internal.EnergenieBinding] -
transformed state response = 2379;   var
2015-12-30 22:09:20.086 [TRACE] [.b.e.internal.EnergenieBinding] -
transformed state response = 2379 -    var
2015-12-30 22:09:20.088 [TRACE] [.b.e.internal.EnergenieBinding] -
transformed state for item B_WaschMasch_Voltage = 237.9
2015-12-30 22:09:20.183 [TRACE] [.b.e.internal.EnergenieBinding] -
logout from ip 192.168.178.6
2015-12-30 22:09:20.263 [TRACE] [.b.e.internal.EnergenieBinding] - item
is of Type B_WaschMasch_Energy (Type=NumberItem, State=Uninitialized)
2015-12-30 22:09:20.266 [TRACE] [.b.e.internal.EnergenieBinding] - about
to process NumberItem
2015-12-30 22:09:20.268 [TRACE] [.b.e.internal.EnergenieBinding] -
searchstring var E= found at position 534
2015-12-30 22:09:20.270 [TRACE] [.b.e.internal.EnergenieBinding] -
transformed state response = 1768263;   var
2015-12-30 22:09:20.272 [TRACE] [.b.e.internal.EnergenieBinding] -
transformed state response = 1768263 -    var
2015-12-30 22:09:20.274 [TRACE] [.b.e.internal.EnergenieBinding] -
transformed state for item B_WaschMasch_Energy = 69.0727734375
2015-12-30 22:09:20.366 [TRACE] [.b.e.internal.EnergenieBinding] -
logout from ip 192.168.178.6
2015-12-30 22:09:20.441 [TRACE] [.b.e.internal.EnergenieBinding] - item
is of Type B_WaschMasch_Current (Type=NumberItem, State=Uninitialized)
2015-12-30 22:09:20.443 [TRACE] [.b.e.internal.EnergenieBinding] - about
to process NumberItem
2015-12-30 22:09:20.445 [TRACE] [.b.e.internal.EnergenieBinding] -
searchstring var I  =  found at position 500
2015-12-30 22:09:20.447 [TRACE] [.b.e.internal.EnergenieBinding] -
transformed state response = 9;      var
2015-12-30 22:09:20.450 [TRACE] [.b.e.internal.EnergenieBinding] -
transformed state response = 9 -       var
2015-12-30 22:09:20.452 [TRACE] [.b.e.internal.EnergenieBinding] -
transformed state for item B_WaschMasch_Current = 0.09
2015-12-30 22:09:20.655 [TRACE] [.b.e.internal.EnergenieBinding] -
logout from ip 192.168.178.6
2015-12-30 22:09:20.753 [TRACE] [.b.e.internal.EnergenieBinding] - item
is of Type B_Trockner_Power (Type=NumberItem, State=Uninitialized)
2015-12-30 22:09:20.755 [TRACE] [.b.e.internal.EnergenieBinding] - about
to process NumberItem
2015-12-30 22:09:20.757 [TRACE] [.b.e.internal.EnergenieBinding] -
searchstring var P= found at position 517
2015-12-30 22:09:20.759 [TRACE] [.b.e.internal.EnergenieBinding] -
transformed state response = 0;         var
2015-12-30 22:09:20.761 [TRACE] [.b.e.internal.EnergenieBinding] -
transformed state response = 0 -          var
2015-12-30 22:09:20.763 [TRACE] [.b.e.internal.EnergenieBinding] -
transformed state for item B_Trockner_Power = 0.0
2015-12-30 22:09:20.866 [TRACE] [.b.e.internal.EnergenieBinding] -
logout from ip 192.168.178.4
2015-12-30 22:09:20.943 [TRACE] [.b.e.internal.EnergenieBinding] - item
is of Type B_WaschMasch_Power (Type=NumberItem, State=Uninitialized)
2015-12-30 22:09:20.945 [TRACE] [.b.e.internal.EnergenieBinding] - about
to process NumberItem
2015-12-30 22:09:20.947 [TRACE] [.b.e.internal.EnergenieBinding] -
searchstring var P= found at position 517
2015-12-30 22:09:20.948 [TRACE] [.b.e.internal.EnergenieBinding] -
transformed state response = 0;         var
2015-12-30 22:09:20.949 [TRACE] [.b.e.internal.EnergenieBinding] -
transformed state response = 0 -          var
2015-12-30 22:09:20.950 [TRACE] [.b.e.internal.EnergenieBinding] -
transformed state for item B_WaschMasch_Power = 0.0
2015-12-30 22:09:21.056 [TRACE] [.b.e.internal.EnergenieBinding] -
logout from ip 192.168.178.6

**Comment by teichsta** [comment]
Thanks, guys!

**Comment by hmerk** [comment]
@teichsta 
No Thomas, I have not commted my refactoring yet. please revert this.
I would suggest to close this PR after reverting and I will create a new one with the tested changes tomorrow.
Best
Hans-Jörg

**Comment by teichsta** [comment]
done, see https://github.com/openhab/openhab/commit/49ab601ea57472ffb219fe65cbc67aaa37c89f66 … sorry for messing this up!

**Comment by hmerk** [comment]
No Problem ;-)

**Pull request merged**
