### PR TITLE
[ecobee] Remove leading spaces to avoid confusion

### PR DESCRIPTION
**Pull request by watou**
See https://community.openhab.org/t/ecobee-3-setup/10413

### CODE REVIEW

**Comment by watou** [comment]
OK to cherry pick onto 1.8?

**Comment by teichsta** [comment]
also cherry-picked onto 1.8!

@mrguessed please see https://community.openhab.org/t/merging-prs/10008 for more details on how to merge PRs now. Please always use "squash and merge" now.

**Comment by mrguessed** [comment]
@teichsta, no problems.  See my comments on that thread...

I did one of each type so I could see the _practical_ gain/value of the different models.

**Comment by watou** [comment]
@mrguessed @teichsta Thank you!

**Pull request merged**
