### PR TITLE
Use smarthome.userdata for persisting MAX! pairing information

### PR DESCRIPTION
**Pull request by johgoe**
With this fix, it's possible to save the pairing information in a writeable folder for the server. The start up folder had not work in a Linux (apt-get install) configuration.
With this fix it's working because it's saving in the /var/lib/openhab folder.

I also added support for PushButton (switch and battery).
ShutterContact is now a ContactItem.
The SetDisplayActualTemp message is implemented now

### CODE REVIEW

**Comment by teichsta** [comment]
@cyclingengineer @habnefrage @dominicdesu could you please have a look at this change?

**Comment by dominicdesu** [comment]
@teichsta @johgoe I have added some inline comments of what I think could be rechecked. However, I cannot comment on the specific CUL logic as I don't own a MAX CUL but a MAX Cube.

**Comment by johgoe** [comment]
@dominicdesu thx for the review.
@teichsta Should I rebase (squash) my commits?

**Comment by teichsta** [comment]
@johgoe yes, please! Would be great if you could do this soon, would that be possible?

**Comment by teichsta** [comment]
any chance to rebase until tonight? Otherwise we would have to move to 1.9

**Comment by johgoe** [comment]
@teichsta I squashed the commits and rebased the branch to the current master.

**Comment by johgoe** [comment]
something went wrong. I will check it.

**Comment by hakan42** [comment]
The pr shows multiple thousand changed files, please recheck

**Comment by johgoe** [comment]
I see the problem. It's the wrong target branch. I will close it and repopen another one.

**Comment by johgoe** [comment]
continue in #3669 (target branch is master)

**Pull request closed without merging**
