### PR TITLE
Add new fibaro smoke detector FGSD-002

### PR DESCRIPTION
**Pull request by pierok13**
the new version of the FGSS-001, available in france from now.

### CODE REVIEW

**Comment by cdjackson** [comment]
Have you tested that this works? In the 001 version, the device doesn't support get requests in the multi level command class (31 I think). This can cause errors and retries and the database needs to reflect this.
Maybe you can confirm if this is fixed in this version?

**Comment by pierok13** [comment]
not yet. I will try as soon as I can.

**Comment by cdjackson** [comment]
Ok, please let me know when it’s tested, but please check the debug log for timeouts during the DYNAMIC phase of the initialisation. I doubt this will have changed from the other version as it’s common on most Fibaro devices, and we’ll probably have to update the file to stop the timeouts…

**Comment by filhome** [comment]
Hi, how can I retrieve a jar file with this update. I have 2 new smoke detectors, I would like to test.

**Comment by cdjackson** [comment]
It's not yet included in the code, so you can't currently get a version with this. @pierok13 I was wondering if you'd had a chance to test - if not, I can merge the code so that @filhome  can test?

**Comment by pierok13** [comment]
Yes you can. I still didn't receive mine... So I can't test it.

**Comment by cdjackson** [comment]
Ah- ok. My mistake - I'd thought you had it...

Ok - I'll merge, then it should be available tomorrow in the cloudbees snapshot. If there's any updates needed please let me know (I have a suspicion that there may be some timeouts during initialisation).

**Comment by filhome** [comment]
ok good i will keep you informed

**Comment by faurel** [comment]
I just received mine today. Here are the logs (sorry, I forgot to set DEBUG level).
We can see timeout logs right after inclusion. I don't know if these are the lines you are looking for:

2015-03-19 20:51:42.569 ERROR o.o.b.z.i.c.ZWaveConfiguration[:1318]- Neither inclusion nor exclusion was active!
2015-03-19 20:53:02.099 WARN  o.o.b.z.i.p.c.ZWaveCommandClass[:221]- NODE 6: Unsupported command class ZWAVE_PLUS_INFO
2015-03-19 20:53:02.102 WARN  o.o.b.z.i.p.c.ZWaveCommandClass[:221]- NODE 6: Unsupported command class DEVICE_RESET_LOCALLY
2015-03-19 20:53:02.103 WARN  o.o.b.z.i.p.c.ZWaveCommandClass[:221]- NODE 6: Unsupported command class ASSOCIATION_GROUP_INFO
2015-03-19 20:53:02.106 WARN  o.o.b.z.i.p.c.ZWaveCommandClass[:221]- NODE 6: Unsupported command class POWERLEVEL
2015-03-19 20:53:02.111 WARN  o.o.b.z.i.p.c.ZWaveCommandClass[:221]- NODE 6: Unsupported command class MULTI_INSTANCE_ASSOCIATION
2015-03-19 20:53:02.115 WARN  o.o.b.z.i.p.c.ZWaveCommandClass[:221]- NODE 6: Unsupported command class FIRMWARE_UPDATE_MD
2015-03-19 20:53:07.782 WARN  o.o.b.z.i.ZWaveActiveBinding[:467]- NODE 6: No item bound for event, endpoint = 0, command class = CONFIGURATION, value = org.openhab.binding.zwave.in
2015-03-19 20:53:07.941 WARN  o.o.b.z.i.ZWaveActiveBinding[:467]- NODE 6: No item bound for event, endpoint = 0, command class = CONFIGURATION, value = org.openhab.binding.zwave.in
2015-03-19 20:53:13.024 ERROR o.o.b.z.i.p.ZWaveController$ZWaveSendThread[:1327]- NODE 6: Timeout while sending message. Requeueing - 2 attempts left!
2015-03-19 20:53:13.138 WARN  o.o.b.z.i.p.c.ZWaveCommandClass[:221]- NODE 6: Unsupported command class ZWAVE_PLUS_INFO
2015-03-19 20:53:13.140 WARN  o.o.b.z.i.p.c.ZWaveCommandClass[:221]- NODE 6: Unsupported command class DEVICE_RESET_LOCALLY
2015-03-19 20:53:13.142 WARN  o.o.b.z.i.p.c.ZWaveCommandClass[:221]- NODE 6: Unsupported command class ASSOCIATION_GROUP_INFO
2015-03-19 20:53:13.144 WARN  o.o.b.z.i.p.c.ZWaveCommandClass[:221]- NODE 6: Unsupported command class POWERLEVEL
2015-03-19 20:53:13.148 WARN  o.o.b.z.i.p.c.ZWaveCommandClass[:221]- NODE 6: Unsupported command class MULTI_INSTANCE_ASSOCIATION
2015-03-19 20:53:13.150 WARN  o.o.b.z.i.p.c.ZWaveCommandClass[:221]- NODE 6: Unsupported command class FIRMWARE_UPDATE_MD
2015-03-19 20:53:18.654 ERROR o.o.b.z.i.p.ZWaveController$ZWaveSendThread[:1327]- NODE 6: Timeout while sending message. Requeueing - 1 attempts left!
2015-03-19 20:54:24.484 ERROR o.o.b.z.i.p.ZWaveController$ZWaveSendThread[:1327]- NODE 6: Timeout while sending message. Requeueing - 2 attempts left!

**Comment by filhome** [comment]
@cdjackson the specification of this module is not the same as fgss001 ...
You can find the specification here ...
http://gurau-audibert.hd.free.fr/josdblog/wp-content/uploads/2015/02/FGSD-002-EN-A-v1.00.pdf

**Comment by filhome** [comment]
I made some changes on the configuration part ... for the others, I don't find what changed. I am looking for ...
https://github.com/filhome/openhab/pull/1

**Comment by cdjackson** [comment]
As this PR was merged and is closed, can we start another discussion on this? Alternatively, if you want to create a PR for your changes, we can then discuss there?

**Comment by filhome** [comment]
Hi, I create https://github.com/filhome/openhab/pull/1. Can it be used as new PR ? If not, I am newbie and I don't know how to do ...
Can you check, if my modifications are ok ...

**Comment by cdjackson** [comment]
Hi,
Yes - you can use this as a PR. 

You need to go to you OH repository in github, at the top there’s a button that says [branch: master] - change this to the branch with your changes (filhome-patch-1), then click on the green button to the left of the [branch] button. This should open a page that allows you to create a PR and it’s easiest if you can do this first for me to review.

Let me know if you have any problems...

Chris

**Comment by filhome** [comment]
I hope I have done this well :) https://github.com/openhab/openhab/pull/2341

**Comment by cdjackson** [comment]
Yep- it looks fine - thanks.

**Pull request merged**
