### PR TITLE
Support for changing operation mode of novelanheatpump

### PR DESCRIPTION
**Pull request by frami**
I added for the binding 'org.openhab.binding.novelanheatpump' the feature for changing the operation mode for heating and warmwater. The items are:
    
    Number heatpump_heating_operation_mode   "Heizung Betriebsart [%.0f]"  (gHeatpump) { novelanheatpump="heating_operation_mode" }
    Number heatpump_heating_temperatur   "Heizung Temperatur [%.1f]"  (gHeatpump) { novelanheatpump="heating_temperatur" }
    Number heatpump_warmwater_operation_mode   "Warmwasser Betriebsart [%.0f]"  (gHeatpump) { novelanheatpump="warmwater_operation_mode" }
    Number heatpump_warmwater_temperatur   "Warmwasser Temperatur [%.1f]"  (gHeatpump) { novelanheatpump="warmwater_temperatur" }

I'm new heare. Where can I update the documentation?

Best regards
Michael

### CODE REVIEW

**Comment by nickma82** [comment]
@frami concerning documentation: 
I'm also new but I think that should sit in the appropriate github-wiki page (e.g. https://github.com/openhab/openhab/wiki/Novelan-Heat-Pump-Binding). If you are logged in, there's an "edit" button at the upper right corner.

**Comment by frami** [comment]
@nickma82 
I see it now. Thank you for the hint.

**Comment by boxerfahrer** [comment]
@frami concerning cooling operation mode and target temperature
Hello Michael, I have been using the novelan plugin since it came out. Great work!

I have just added the new 1.7 operation modes. 

Since I am using the heatpump also for cooling, is there a chance you would also include two or three more items concerning cooling?

Operation_Mode_Mode would help me to switch on and off (it only has value "auto" and "off)
Temperature_Cooling (Mixer circuit 1 target temperature, with values between 18..25 °C) would help me to keep Temperature above dew point.
Temperature_Release_Cooling would define the outside temperature when cooling starts

These three items would really help a lot. If I can support you somehow, just let me know.

**Comment by frami** [comment]
@boxerfahrer 
Hello
Your proposals are good. The only problem is, I don't have the necessary information to implement this. Until now, I implemented the functions with reverse engineering on my owne heat pump.
But if you agree, I can write a program to readout all parameters from your heat pump. So we can find out, which parameters are corresponds to your wish.

**Comment by boxerfahrer** [comment]
@frami 
no problem we can do that. I can offer ubuntu 14.04 on ARM (odroid) or windows as a platform.  But I already might have such a program in place. I have taken the description from

http://knx-user-forum.de/forum/supportforen/smarthome-py/27461-neues-plugin-luxtronic2-w%C3%A4rmepumpen-von-alphainnotec-siemens-etc

and created a small perl script that reads all parameters from the heatpump.
I can confirm that 
index 22 - Sollwert_TVL_MK1 - is the target temperature for cooling
index 66 - Zaehler_BetrZeitKue - is the total operating time for cooling
index 126 - SH_MK1 - is unknown to me, returns "0" right now (a hint might be that index 125 - SH_HZ - returns "1" right and my heatpump is currently heating
index 146 - FreigabKuehl - reutrns "0" right now

I did not find values for Operation_Mode_Cooling or Temperature_Release_Cooling, but then again I also did not find a value for Temperature_Release_Heating (Heizgrenze).

I looked up the BACNet documentation of Alpha Innotec

**Comment by frami** [comment]
@boxerfahrer

This are the calculate values(type 3004). There are other parameters(type
3002). I have written a small client to read/write the parameters(type
3002). You can get it from this link:

https://drive.google.com/file/d/0B23HtUQaxrDjTGFMRE1KS3BRVzA/view?usp=sharing

You need Java 6 or higher.
Execute to read all parameters: java -jar heatpump-client.jar ip
192.168.1.1 read
Execute to write the value 510 to parameter 2: java -jar
heatpump-client.jar ip 192.168.1.1 write 2=510

I hope you can so find out, which parameter have which function. After that
you can provide me with this information and I will implement it to the
plugin.

2015-03-24 9:59 GMT+01:00 boxerfahrer <notifications@github.com>:

**Comment by boxerfahrer** [comment]
@frami 

That really helped a lot :-)
Here are the values - I made suggestions for the new keywors, but just change them as appropriate

Index 108 - COOLING_MODE (0=OFF, 1=AUTO)
Index 110 - TEMP_RELEASE (AT-Freigabe) (220 = 22,0 °C), steps every 0.5°C  
Index 132 - COOLING_INLET_TEMP (Solltemp MK1) (190 = 19.0 °C), steps every 0.5°C
Index 850 - COOLING_START (AT Überschreitung) (50 = 5,0 hr), steps every 0.5 hr
Index 851 - COOLING_STOP (AT-Unterschreitung) (120 = 12.0 hr), steps every 0.5 hr

If you implement this I will be happy to test it.
Thanks a lot for your support!

**Comment by frami** [comment]
@boxerfahrer 
Thank you for the test results. I implemented it. Pull request: https://github.com/openhab/openhab/pull/2375

The items are:
* cooling_operation_mode
* cooling_release_temperature
* cooling_inlet_temperature
* cooling_start_hours
* cooling_stop_hours

For the documentation. Can you explain me, for what this parameter "cooling_inlet_temperature"  is?

Let me know, if everything works. ;-)

**Comment by boxerfahrer** [comment]
@frami 

"cooling_inlet_temperature" is "Soll-Vorlauftemperatur", so it is the target temperature that goes into the heating circuit (Heizkreis, meist Fussbodenheizung)

I am an amateur with git - can you please tell me how to get the binding jar file noe? I have clicked the pull request link but got lost...

**Comment by frami** [comment]
I have compiled it and you can get it from here: https://drive.google.com/file/d/0B23HtUQaxrDjdnZrcmZQUWtCOHc/view?usp=sharing

**Comment by boxerfahrer** [comment]
@frami 

everything works just fine except for the operation mode. It doesnt read or write any value.
I checked the test again. It should be index 108, 0=AUS, 1=AUTO

**Comment by frami** [comment]
@boxerfahrer 
The implementation looks right. Can you provide me the log files? There should be some messages like "Heatpump cooling operation mode set to ..."

**Comment by boxerfahrer** [comment]
@frami 
My error. They entry in the items file was type "Switch" instead of "Number". Everythink works fine now :-)
I am really delighted. I will couple the Cooling_Inlet Temperature with a dew point calculation so that I avoid wet floors. Plus I will start cooling early depending on weather forecast.

Thank you so much for your help. Great Job!

**Pull request merged**
