### PR TITLE
eBUS Major Update 1

### PR DESCRIPTION
**Pull request by csowada**
Major Update, add send support and rewritten item syntax

* New parameter `set` allows to set a value
* New syntax for property `id`, `command` and `set`
* Improved sender timings
* Improved cpu load for serial connections
* Restructured configurations
* Add new configurations for Vaillant VRC430,470,BAI00
* All offical configurations in english language
* Add CSV support to record raw telegrams
* Fix for openHAB 2.0 compatiblity
* Adjust some warning messages
* Workaround for serial close issue
* Smaller bugfixes and optimizations

### CODE REVIEW

**Comment by csowada** [comment]
Im working on an adittional update that changes the item configuration to a more logical syntax. I hope I can pull the update tomorrow.

**Comment by teichsta** [comment]
thanks for letting us know @csowada!

**Comment by csowada** [comment]
So, update done.
Please read updated readme file.md https://github.com/csowada/openhab/tree/ebus-update-pr1/bundles/binding/org.openhab.binding.ebus for more information

**Comment by teichsta** [comment]
@csowada do you know of anybody could help testing this huge change?

**Comment by csowada** [comment]
@teichsta I would ask the guys from the community thread https://community.openhab.org/t/ebus-binding/3399 . Specially the user nikores helped me with the vaillant commands and I think he uses the binding.

Btw: I use this binding 24/7 for a wolf heating system and it runs well.

But I will also add the changes from https://github.com/openhab/openhab/pull/3463 in this binding. So only the binding should change items to a new valid state not the AutoUpdater.

**Comment by csowada** [comment]
I got feedback from the [community topic](https://community.openhab.org/t/ebus-pre-release-for-1-8-0/3497/6) from nikoraes that it works with this updates since a longer time.
I will reduce the log level for some errors that are normal on a shared bus.

I currently try to reduce the latency for ethernet connections. But this is only fine tuning.

**Comment by csowada** [comment]
Hello @teichsta ,

I got feedback and it running well. I also update the docs and now the binding is compatible with openhab 2.0. For me this PR is finish and I only will add additional configurations in the future.

**Comment by teichsta** [comment]
Thanks a lot for this great work @csowada!

**Comment by kaikreuzer** [comment]
@teichsta How did you actually review this PR? It seems that there are no diffs in the PR, but mainly completely replaced files due to changed line ending characters. That makes it hard to see what has been actually changed...

**Comment by teichsta** [comment]
> How did you actually review this PR?

i used an external tool ignoring the different line endings

**Comment by csowada** [comment]
Oh no, what has happend there? Should I fix this this and we revert the merge? In that case I could directly merge the PR from @kaikreuzer

**Comment by hakan42** [comment]
Honestly, with that much line ending changes, I would love if we could revert and merge a fresh PR.

Otherwise, the next one working on this code and using the "official" editor settings would again create huge PRs (which in turn are not easily readable / reviewable).

**Comment by hakan42** [comment]
@teichsta , I assume you used your github app on your mobile, the comment came from "openhab-bot" :smile: 

Anyway, I'll work with @csowada to have the new PR merged.

**Comment by csowada** [comment]
So added two new PRs: https://github.com/openhab/openhab/pull/3636, https://github.com/openhab/openhab/pull/3639

**Comment by hakan42** [comment]
@csowada , Thank you for your patience and efforts on this. Both PRs are merged now and should be available in tonights Jenkins build.

**Pull request merged**
