### PR TITLE
Redesigned version of onewire binding

### PR DESCRIPTION
**Pull request by Dennis650**

### CODE REVIEW

**Comment by teichsta** [comment]
@Dennis650 there are ongoing discussion about the new configuration – would be great if you could take over /cc @druciak and also please update the Wiki accordingly. Thanks, Thomas E.-E.

**Comment by teichsta** [comment]
thanks @Dennis650 :-)

**Comment by Dennis650** [comment]
@teichsta i have to thank you for your great work on this great project openhab! It works perfectly!

**Comment by AcidReptile** [comment]
@Dennis650 Hello! Thanks for your beautiful work! :)
What version OWFS do you use?
I'm trying to use LCD but nothing happens on 2.9p8.

**Comment by Dennis650** [comment]
Hi,

i use 3.0p0. 

Greetings
Dennis

**Comment by AcidReptile** [comment]
Linux or Windows?

**Comment by Dennis650** [comment]
What is windows?? :-) I use Linux. Is there a owfs version for windows?

Please use the google group for discussion and support.

Greetings Dennis

**Pull request merged**
