### PR TITLE
support for dS-iSens200

### PR DESCRIPTION
**Pull request by georgwiltschek**
added item parameter "sensor" for humidity and temperature on digitalstrom climate sensors like the dS-iSens200

Usage:
Number LR_Temp "Temp [%.1f °C]" <icon> (LivingRoom) { digitalstrom="dsid:123456#sensor:TEMPERATURE_INDOORS#timeinterval:1000" }
Number LR_Humidity "Humidity [%.1f]" <icon> (LivingRoom) { digitalstrom="dsid:123456#sensor:RELATIVE_HUMIDITY_INDOORS#timeinterval:1000" }

timeinterval is optional, per digitalstrom device, not item, so both will update at the same time

### CODE REVIEW

**Comment by teichsta** [comment]
@hmerk could you please help reviewing this? Thanks, Thomas E.-E.

**Comment by hmerk** [comment]
@teichsta 
I will do the review over the weekend.
Best
Hans-Jörg

**Comment by teichsta** [comment]
great, thanks!

**Comment by hmerk** [comment]
@georgwiltschek, i guess your changes are based on the OH2 binding development, right?
Cause I do not have any sensor devices, can you confirm your changes are running without any problem?
@teichsta, the PR looks good to me, feel free to merge.

Best
Hans-Jörg

**Comment by teichsta** [comment]
thanks @hmerk for the review. @georgwiltschek could you finally please squash your commits into one?

Thanks, Thomas E.-E.

**Comment by georgwiltschek** [comment]
@hmerk: no, the changes are based on the current binding from the 1.x master tree, I was going through the code and found that there were bits and pieces for temp/humidity sensors but no implementation, so I tried to implement them according to the rest of the binding, but I can confirm that its been running for a few days now without any problems although as far as those sensors go I only have the dS-iSens200 for testing.

@teichsta done at commit https://github.com/georgwiltschek/openhab/commit/114dfd0b5f0732938fe50b5c08b9f1f375929deb

Regards,
Georg

**Comment by georgwiltschek** [comment]
@teichsta: The commit https://github.com/georgwiltschek/openhab/commit/2a0b5dda9d24b9f9f94de95c7ff31770f762f4e7 shouldn't be part of this pull request (although I'm most likely going to open another one for it in the future), shall I rebase the whole thing to get rid of it or do you cherry pick anyway?

Kind regards,
Georg

**Comment by teichsta** [comment]
no, please rebase … it's much easier for me to merge the whole PR rather than cherry-picking.

Thanks in advance, Thomas E.-E.

**Comment by georgwiltschek** [comment]
done, will do some branching next time :)

**Comment by teichsta** [comment]
great, thanks!

May i ask you (as well as @hmerk)  to also test the digitalSTROM Binding against openHAB2? It would be great to fill up the https://github.com/openhab/openhab2/blob/master/docs/sources/addons.md#compatible-1x-add-ons list (see also https://groups.google.com/forum/#!category-topic/openhab/announcements/1RnkDGaWTiM)

**Comment by hmerk** [comment]
@teichsta, this is definitely on my todo list for the next weeks.
Best
Hans-Jörg

**Pull request merged**
