### PR TITLE
SONOS Favorite support.

### PR DESCRIPTION
**Pull request by digitaldan**
Signed-off-by: Dan Cunningham dan@digitaldan.com

### CODE REVIEW

**Comment by digitaldan** [comment]
@kgoderis  Can you take a look for me?  This is the first time I have hacked on sonos and ended up doing a bunch of wireshark dumps to figure favorites out.  Couple interesting points, I added a new search for favorites (FV:2), I also need to parse a html encoded xml document within a resMD tag in the entries response, kinda odd but its needed to grab the user identifier for services like pandora. The result is that any thing you save (radio station, pandora, google music, ect..) as a favorite can be played.

**Comment by digitaldan** [comment]
oh, and I'll look at adding this to the OH2 port today.

**Comment by teichsta** [comment]
thanks @digitaldan please refer to the OH2, too …

**Comment by digitaldan** [comment]
Way ahead of you @teichsta  ;-)

**Comment by kgoderis** [comment]
Looks good to me. Welcome to the world of Sonos reverse-engineering ;-)

When you have it for OH2, then I will give a try with Spotify. Should be very similar in code as I have kept much of the helper classes for the parsing and alike.

**Comment by teichsta** [comment]
@digitaldan just give me a sign when this PR is ready to merge. Thanks, Thomas E.-E.

**Comment by digitaldan** [comment]
Thanks all, I'm going to spend a little more time to make sure i really understand the code and the SONOS xml better.  I kinda rushed through this in my excitement to get it working ; -)

**Comment by digitaldan** [comment]
So this is a little better, I'll update the oh2 binding as well

**Comment by digitaldan** [comment]
@teichsta I'm going to let this run for the week, if all looks good I'll give you the green light to merge.  Thanks.

**Comment by teichsta** [comment]
ok thanks!

**Comment by digitaldan** [comment]
@teichsta lets go ahead and merge, I'll update the wiki, thanks!

**Comment by teichsta** [comment]
ok, thanks @digitaldan!

**Pull request merged**
