### PR TITLE
Implemented RWE Smarthome binding

### PR DESCRIPTION
**Pull request by ollie-dev**
This is the RWE Smarthome binding with all changes as discussed in #3143. Sorry for the double PRs due to my git inability...

Best regards
Ollie

### CODE REVIEW

**Comment by teichsta** [comment]
thanks :-)

May i finally ask you to check the compatibility against OH2? So simply use the OH2 runtime and deploy your binding there (throw it into /addons dir) and see if it works.

Thanks, Thomas E.-E.

**Comment by ollie-dev** [comment]
Hi Thomas,
I just tried it and it works! Never tried it before - but great! :)

Regards
Ollie

**Comment by teichsta** [comment]
welcome to the future of openHAB … would be great btw if you could go ahead with the implementation and enhance your binding to be OH2 compatible (e.g. implementation of discovery). Will you?

**Comment by ollie-dev** [comment]
Yes, definitely. I think I'll first implement one or two missing devices and will then take a look at OH2.

**Comment by teichsta** [comment]
> Yes, definitely. I think I'll first implement one or two missing devices and will then take a look at OH2.

great! 

Could you finally please resolve the conflicts that currently occur (keep in mind to squash commits again afterwards).

Thanks, Thomas E.-E.

**Comment by ollie-dev** [comment]
I fear I have to create another PR again. I still don't know how to do it. I read the attlassian git tutorial, googled for hours, followed these steps (https://www.youtube.com/watch?v=b1K_oZX02KU) to resolve the conflicts and now have a branch mixed up with some master commits from other bindings and still have conflicts remaining. Why must this be so complicated? Is there a good tutorial out there about how to do it step by step?

**Comment by teichsta** [comment]
> Why must this be so complicated?

well, i would call it "complicated" but probably "not so obvious" ;-)

Let's go through some steps:

* keep your local master free from any changes
* pull  all changes from remote/openhab/master into your local master
* push the changes to your master
* merge your local master into your branch
* resolve conflicts
* commit --amend the changes to your latest commit (which is the only one in your branch)
* (force) push to your remote/branch

Hope this helps, Thomas E.-E.

**Comment by teichsta** [comment]
@ollie-dev i tried out your binding but didn't manage to logon successfully. sResponse in logon() always returns an empty String. Any idea what that might be about?

**Comment by teichsta** [comment]
ah this might be a consecutive fault of

```
2015-11-18 21:05:46 [INFO ] [r.i.c.RWESmarthomeCommunicator:84   ] - Starting RWE Smarthome communicator
2015-11-18 21:05:46 [ERROR] [.o.b.r.i.c.RWESmarthomeSession:252  ] - SSLHandshakeExceptionjavax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1343)
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:728)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
	at org.apache.http.impl.io.AbstractSessionOutputBuffer.flushBuffer(AbstractSessionOutputBuffer.java:159)
	at org.apache.http.impl.io.AbstractSessionOutputBuffer.flush(AbstractSessionOutputBuffer.java:166)
	at org.apache.http.impl.io.ContentLengthOutputStream.flush(ContentLengthOutputStream.java:101)
	at org.apache.http.entity.StringEntity.writeTo(StringEntity.java:171)
	at org.apache.http.entity.HttpEntityWrapper.writeTo(HttpEntityWrapper.java:89)
	at org.apache.http.impl.client.EntityEnclosingRequestWrapper$EntityWrapper.writeTo(EntityEnclosingRequestWrapper.java:108)
	at org.apache.http.impl.entity.EntitySerializer.serialize(EntitySerializer.java:117)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at sun.security.ssl.InputRecord.read(InputRecord.java:505)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:954)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1343)
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:728)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
	at org.apache.http.impl.io.AbstractSessionOutputBuffer.flushBuffer(AbstractSessionOutputBuffer.java:159)
	at org.apache.http.impl.io.AbstractSessionOutputBuffer.flush(AbstractSessionOutputBuffer.java:166)
	at org.apache.http.impl.io.ContentLengthOutputStream.flush(ContentLengthOutputStream.java:101)
	at org.apache.http.entity.StringEntity.writeTo(StringEntity.java:171)
	at org.apache.http.entity.HttpEntityWrapper.writeTo(HttpEntityWrapper.java:89)
	at org.apache.http.impl.client.EntityEnclosingRequestWrapper$EntityWrapper.writeTo(EntityEnclosingRequestWrapper.java:108)
```

**Comment by ollie-dev** [comment]
Yeah, you have to use java 1.7 or force 1.8 to use TLSv1 by adding `-Djdk.tls.client.protocols=TLSv1` to start.sh.
I am trying to fix my repo right now. There is some progress and maybe I can finally send you a conflict-free, one-commit PR. Fingers crossed... ;)

**Comment by teichsta** [comment]
> Yeah, you have to use java 1.7 or force 1.8 to use TLSv1 by adding -Djdk.tls.client.protocols=TLSv1 to start.sh.

ok, that's it, thanks! The should definitely be part of the wiki page ;-)

**Comment by ollie-dev** [comment]
All right, @teichsta - I think I finally made it. Puh! :bowtie:

I already prepared a Wiki page: https://github.com/openhab/openhab/wiki/RWE-Smarthome-binding :)

**Comment by ollie-dev** [comment]
@teichsta, is everything fine now for you to accept the PR or is still something missing in your opinion?

**Comment by teichsta** [comment]
no, nothing missing … just lack of time again.

Again, many thanks for this contribution! Hope to see many more from you :-)

**Comment by hakan42** [comment]
Nice. @ollie-dev  :smile: 

could I ask you to write a short announcement on https://community.openhab.org/c/add-ons/bindings when your new binding is in tonights nightly build?

**Comment by ollie-dev** [comment]
@hakan42 - yes! :D

I am only a bit confused because the binding is available here... https://openhab.ci.cloudbees.com/job/openHAB/lastSuccessfulBuild/org.openhab.binding$org.openhab.binding.rwesmarthome/
...but not included in the addon.zip-File here...
https://openhab.ci.cloudbees.com/job/openHAB/lastSuccessfulBuild/artifact/distribution/target/distribution-1.8.0-SNAPSHOT-addons.zip

?!?

**Comment by teichsta** [comment]
overlooked that in the Review. Please add your binding to:

* bundles/binding/pom.xml (as module)
* distribution/pom.xml (as dependency)

and send a PR for that. Would you?

Thanks, Thomas E.-E.

**Comment by ollie-dev** [comment]
Hi,
bundles was already done. I now fixed distribution/pom.xml in #3467. Go for it! :)

**Pull request merged**
