### PR TITLE
[mail action] Supply attachment name; allow multiple attachments.

### PR DESCRIPTION
**Pull request by watou**
Also see #3348 as an alternative pull request (didn't realize this existed; please consider the more appropriate one).  This pull request tries to use the file name or falls back to "Attachment", and also has a new action method signature that takes a list of strings with are URLs to attachments.

### CODE REVIEW

**Comment by watou** [comment]
Made the code more concise and more flexible in naming the attachment.  Please try the JAR [here](https://dl.dropboxusercontent.com/u/4286376/mail-action-attachments/org.openhab.action.mail-1.8.0-SNAPSHOT.jar) and report if it's good.

**Comment by watou** [comment]
Intended to correct part of #3338.

**Comment by watou** [comment]
Reported working correctly by @Dan1001 [here](https://github.com/openhab/openhab/issues/3338#issuecomment-151799741) (and I've tested the attachment name and sending multiple attachments as well).  Thanks, Dan!

**Comment by Dan1001** [comment]
not at all - thank you!

**Comment by teichsta** [comment]
Thanks @watou - could you please also update https://github.com/openhab/openhab/wiki/Actions#mail-actions accordingly?

**Comment by watou** [comment]
Thanks @teichsta; wiki page updated.

**Pull request merged**
