### PR TITLE
Aeon DSB45-ZWUS

### PR DESCRIPTION
**Pull request by SkynetHome**
Added product to database per Issue #3001

### CODE REVIEW

**Comment by cdjackson** [comment]
Just a small comment on your descriptions... You don't need to put the CDATA stuff in every description - only when you have embedded HTML, which you don't have here...

So...
- for the first few helps, you could remove the CDATA (it doesn't hurt if it's there, but it's not needed).
- for 121, it would be good to format the description with some HTML tags - either using UL/LI tags, or just using BR tags to split the lines...

**Comment by SkynetHome** [comment]
Got it, will change and squash!

**Comment by SkynetHome** [comment]
Trying to squash but for some  reason git rebase -i origin/master is showing tons of commits that are not in this branch.  Will get it sorted out.

**Comment by SkynetHome** [comment]
got it sorted out let me know if those <br> tags are used properly.

**Comment by cdjackson** [comment]
Sorry - the ```</BR>``` tags need to be removed - either just use ```<br>``` or ```<br />```...  If you want to test, you could take a look at this -: http://rendera.herokuapp.com/

Thanks :)

**Comment by SkynetHome** [comment]
LOL...I was pretty sure you were going to say that. It became apparent when I typed the br tag into my above comment and it inserted line break so I had to edit the comment. Figured it would work that way in the help dialog but wasnt sure. Will fix and squash!

**Comment by SkynetHome** [comment]
That should get it. I need to get a refresher on HTML. I am currently 3/4 of the way through a Java Development course. Was planning on moving on to the Android development track after that and then Java Script. Thanks for the link above, that should help me sort out any HTML issues in the time being.

**Comment by cdjackson** [comment]
Thanks :)

**Comment by cdjackson** [comment]
One last, possibly stupid, question... Is the filename for the XML file correct. It looks like in github there's a space at the beginning of the name - it might just be how it looks in GH, but thought I'd check...

**Comment by SkynetHome** [comment]
OMG...you are right there is a space in the file namepath in eclipse as well. Ughh, sorry for the headache with this one. Will correct now!

**Comment by SkynetHome** [comment]
Done...3rd times a charm?

**Comment by cdjackson** [comment]
Sure is - thanks :)

**Pull request merged**
