### PR TITLE
Zwave Database Cleanup Aeon SES3

### PR DESCRIPTION
**Pull request by SkynetHome**
Edited SES3 adding missing configuration parameters, correcting values,
editing help and formatting for portability into OH2

### CODE REVIEW

**Comment by cdjackson** [comment]
As this is a large change I missed the fact that you've removed the commandClasses list. This will stop this device working properly - can you add it back in please.

I'm not sure that changing files in OH1 is the right move - I don't want to break OH1, and I think we'd probably be better off doing these changes when we convert to OH2 rather than risk breaking devices in OH1...  IF you want to fix the formatting for devices you own, and can therefore test, then fine, but otherwise I think it's best to leave the changes to when we do the conversions...

**Comment by SkynetHome** [comment]
Np will put the commandClasses back in. I thought I understood from the wiki that they had no effect. put them all in or none in and that only certain classes with values such as readonly or writeonly were necessary but. No worries I will replace the commandClasses!

**Comment by cdjackson** [comment]
It's used in a couple of places - I forget exactly what, but I think if the command class list doesn't include certain values (eg associations) that it won't set the associations on startup... It isn't used for much, but it is used...

**Comment by SkynetHome** [comment]
Np I am on it. While you are here did you write the binding for the Aeon Multi Sensor 6. There is an issue regarding it that I was working on. One parameter is in fact missing and I have added. It the parameters referring to disabling 101-103 show no values in the documentation and seem better left alone unless you know of standard values to put in there. The issue is #3005

**Comment by SkynetHome** [comment]
recommitted changes but they are not showing up here from what I can see and I have no option to issue a new PR

**Comment by SkynetHome** [comment]
@cdjackson It finally came around. New PR to set this straight is now open! Thanks for your patience! I'll try desperately to make sure that my love of working on this project does not become a thorn in your ass! :)

**Comment by cdjackson** [comment]
No worries - I'm happy to help - you're helping me a lot, so I'm happy to help :)

**Comment by SkynetHome** [comment]
LOL...well it makes me happy, that you are happy, to help me, help you, which in turn helps me. :) ......and I think that is my cue that I have stayed up to late again and need to get some sleep. I'll see if I cant manage to send more help your way tomorrow!

**Pull request merged**
