### PR TITLE
Fix caldav-personal hashCode usage.

### PR DESCRIPTION
**Pull request by watou**
Correct build error introduced by https://github.com/openhab/openhab/pull/4766.

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Thanks!

**Comment by watou** [comment]
FYI, build # 1355 (that you started) failed due to an unrelated HTTP 401.

**Comment by kaikreuzer** [comment]
I know, Jenkins fails to upload stuff to Artifactory, I am trying to get that working again since a while now...

**Comment by aschor** [comment]
thanks ; any hint to why int java.lang.Boolean.hashCode(boolean value) does not work, as it is suggested by eclipse ?

**Pull request merged**
