### PR TITLE
fgfs101_new_parameters

### PR DESCRIPTION
**Pull request by nesys**
Fibaro Flood Sensor:
- Adding new parameters
- Little rewording

### CODE REVIEW

**Comment by cdjackson** [comment]
There is unfortunately something strange about this PR. It seems to have a load of other stuff mixed into it - if you look in the commits tab above, you'll see a load of stuff from last year, and mentions of version 1.5. Likewise, the files have all sorts of changes not related to the zwave binding.

I'd suggest closing this PR and copying your changes to a clean version of a clone of the openhab master branch so that there's no other changes incorporated other than the ones you've made.

**Comment by nesys** [comment]
ack

2015-02-14 11:19 GMT+01:00 Chris Jackson <notifications@github.com>:

**Comment by nesys** [comment]
PR 2132 created. Maybe this is better :-)

Andrea

2015-02-14 11:21 GMT+01:00 Andrea Riela <ariela@nesys.it>:

**Comment by cdjackson** [comment]
Looks better - at least there’s no other commits this time :)

**Comment by nesys** [comment]
Sorry, probably I did something wrongly :-) but now I understood the
procedure. Thanks

Andrea

2015-02-14 11:41 GMT+01:00 Chris Jackson <notifications@github.com>:

**Pull request closed without merging**
