### PR TITLE
Remove httpclient lib and use import in Daikin binding

### PR DESCRIPTION
**Pull request by sumnerboy12**

### CODE REVIEW

**Comment by teichsta** [comment]
Thanks @sumnerboy12!

**Comment by sumnerboy12** [comment]
@teichsta apologies but I just realised I forgot to commit a change to one file in my PR - `build.properties` still has references to the old httpclient libraries. Is it easy enough for you to manually edit that file and reference this PR? Or do I need to do a new PR for this change?

**Comment by sumnerboy12** [comment]
Actually - I see that you fixed it up already - once again, very sorry I missed that!

**Comment by teichsta** [comment]
It's fixed already. Thanks, Tom

- sent from a mobile device -

**Comment by teichsta** [comment]
No worries, that's why we are doing Coke reviews.

- sent from a mobile device -

**Comment by udo1toni** [comment]
Coke reviews? ;) SCNR

**Comment by teichsta** [comment]
well … that's what's happening when using the Text Recognition system :-)

**Pull request merged**
