### PR TITLE
Added Ecobee action bundle.

### PR DESCRIPTION
**Pull request by watou**
The new bundle adds ten new actions for use with the Ecobee binding.

Parameters in _italics_ are optional, in which case each unused parameter must be replaced with `null`.  Read the [API documentation](https://www.ecobee.com/home/developer/api/documentation/v1/functions/using-functions.shtml) to be sure you know the rules for calling these functions.

* ecobeeAcknowledge(Item item, String thermostatIdentifier, String ackRef, String ackType, _Boolean remindMeLater_) - Acknowledge an alert.
* ecobeeControlPlug(Item item, String plugName, String plugState, _Date startDateTime_, _Date endDateTime_, _String holdType_, _Integer holdHours_) - Control the on/off state of a plug by setting a hold on the plug.
* ecobeeCreateVacation(Item item, String name, DecimalType coolHoldTemp, DecimalType heatHoldTemp, _Date startDateTime_, _Date endDateTime_, _String fan_, _Integer fanMinOnTime_) - Create a vacation event on the thermostat.
* ecobeeDeleteVacation(Item item, String name) - Delete a vacation event from a thermostat.
* ecobeeResetPreferences(Item item) - Set all user configurable settings back to the factory default values.
* ecobeeResumeProgram(Item item, _Boolean resumeAll_) - Remove the currently running event providing the event is not a mandatory demand response event.
* ecobeeSendMessage(Item item, String text) - Send an alert message to the thermostat.
* ecobeeSetHold(Item item, _DecimalType coolHoldTemp_, _DecimalType heatHoldTemp_, _String holdClimateRef_, _Date startDateTime_, _Date endDateTime_, _String holdType_, _Integer holdHours_) - Set the thermostat into a hold with the specified temperature.
* ecobeeSetOccupied(Item item, Boolean occupied, _Date startDateTime_, _Date endDateTime_, _String holdType_, _Integer holdHours_) - Switches a (EMS model only) thermostat from occupied mode to unoccupied, or vice versa.
* ecobeeUpdateSensor(Item item, String name, String deviceId, String sensorId) - Update the name of an ecobee3 remote sensor.

### CODE REVIEW

**Comment by teichsta** [comment]
Thanks @watou for this contribution! Hope to find the time for a review soon.

Can you confirm this Action is being shown in the Designer properly?

Best, Thomas E.-E.

**Comment by watou** [comment]
Hi Thomas, even though your comment prompted me to add the missing entry to feature.xml, I still cannot see the new actions in the Designer (on macosx).  There must still be something missing or incorrect in my PR.  Can you offer any suggestions?

**Comment by watou** [comment]
Added a note to issue #1403, which seems to be related to why the actions do not appear in the Designer.

**Comment by teichsta** [comment]
> Hi Thomas, even though your comment prompted me to add the missing entry to feature.xml

that was my intention ;-)

Also saw your comment on #1403 … i've also investigated some time already but didn't find an explanation. @kaikreuzer any additional ideas?

**Comment by watou** [comment]
@teichsta, I'm thinking that I need to change the Integer parameter types in some of the actions to DecimalType before I test more, you review, etc. So I will comment here when I think this PR is suitable for your time.  Thanks!

**Comment by teichsta** [comment]
ok, than give me a sign, when you think this PR is ready for review. Thanks, Thomas E.-E.

**Comment by watou** [comment]
@teichsta, this PR is ready for your review.  Thank you!

**Comment by teichsta** [comment]
ok, great, thanks!

**Comment by watou** [comment]
Added [testing discussion](https://groups.google.com/forum/#!category-topic/openhab/rules/ecobee/2VK_hFpJZ10) to the Google Group.

**Comment by watou** [comment]
squashed and rebased off master

**Comment by watou** [comment]
I will make changes that mirror those made in #2967 once it's merged, as well as rename the Java package `org.openhab.binding.ecobee.internal.messages` to `org.openhab.binding.ecobee.messages`.  IMHO it would make the action bundle harder to use to require the user to specify the instance name and set of thermostats to target in the action call, since the user must already have a matching item binding, and all connection state is already maintained in the binding and is therefore dependent.   Please let me know if this sounds acceptable in concept.

**Comment by tbschmitz8611** [comment]
Hey I'm new to adding in my own apps that aren't already configured.  I tracked down someone on here that had some instructions for adding an ecobee3 thermostat as a smartapp.  Im sure I missed a step somewhere in my setup.  I can see the ecobee as an app to add but when I step thru the process to do so on my phone at the final page I hit done....and get error "Error- bad state. Unable to complete page configuration.  Any guidance for adding the ecobee3 into Smarthings/Smarthub?

**Pull request merged**
