### PR TITLE
Modify daikin binding to work with JDaikin library (Fixes #2723)

### LINKED ISSUE #2723: Modify daikin binding to work with JDaikin library
JDaikin (https://bitbucket.org/JonathanGiles/jdaikin) is a library which supports wired and wireless connections to Daikin heatpump and Airconditioner. This request is to modify daikin binding to use this library

### PR DESCRIPTION
**Pull request by JosSchering1**
The JDaikin library allows to connect to Daikin split system air conditioner with a BRP072A42 Wireless Lan controller.

### CODE REVIEW

**Comment by JosSchering1** [comment]
Hmm, I just realize that the diakin binding documentation needs to be updated. 
The openhap.cfg for daikin has changed. 

To enable a wireless connection, the configuration item looks like:
daikin:lounge.host=wireless@http://DaikinDeviceIP

**Comment by teichsta** [comment]
see #2723 - would be great if you could give us a short update once you've finalised your tests @sumnerboy12.

Thanks, Thomas E.-E.

**Comment by sumnerboy12** [comment]
Sorry this has taken so long! @JosSchering1 can you send me a compiled version of the new binding so I can test? I am having all sorts of trouble building openHAB on my new laptop at the moment!

**Comment by sumnerboy12** [comment]
@JosSchering1 - thanks for the binding jar - I can confirm the indoor/outdoor temp sensor values are being reported, and the on/off and temp setpoint commands are working. However the mode command isn't working. If I change from HEAT to AUTO nothing is sent to my wired Daikin. I tested with the original binding and this works fine there.

**Comment by sumnerboy12** [comment]
I can confirm that testing the jdaikin library on its own is working - I can set the mode using that directly.

**Comment by sumnerboy12** [comment]
Ok - so now it is working - the item binding has changed from String to Number for the enum commands - i.e. Mode and Fan. Not sure how I missed the config exception! After changing to Number it started working correctly. This will need some good documentation so users know what numbers to use for each enum value. Other than that - looking good with my WIRED Daikin unit! Great job.

**Comment by JonathanGiles** [comment]
I haven't tested the openhab binding, but I am using the JDaikin library directly and that works for my wireless Daikin unit, and I know Jos has the same unit as I do. Therefore, if Jos has this working and Ben has this working, it seems good to go (with the exception of needing updated documentation).

**Comment by teichsta** [comment]
great, thanks for the update guys!

**Comment by guitarglen** [comment]
Hi there - if its any use, I have given the binding (1.8.0 snapshot) a quick test tonight, against the BRP072A42 wireless units. 

Have just tested basic functions, including power on/off & retrieving values. Looks good, and is very responsive. 
I have tested using multiple BRP072A42 units (4 in total) - One on a older standalone split system, and 3 on a multi-split system (none of which is officially supported by the BRP wireless unit)   Will have more of a play with the binding over the next week (including setting up groupings for the modes on the multi-split, and testing more set functions). 

Thanks for all your great work on the binding guys....

**Comment by teichsta** [comment]
great, thanks for this update, Glen!

**Comment by JosSchering1** [comment]
Thanks Glen for the update, feedback is useful. 
The binding has not been tested using multiple units as far as I know.

**Comment by guitarglen** [comment]
Hi there - have had a bit of a further play with the 1.8.0 snapshot binding (with the BRP072A42) have found one minor issue, but it doesn't stop the binding from working... (But we do get an entry in openhab.log every minute when it refreshes the status). The error is at the bottom of this post.

I didn't notice the error last night (as it was not happening at the time), and I've tried to do a bit of correlation on what is causing the error.... Short version is that this error occurs when the heatpump is turned off (any of the heatpumps, be it the multi, or standalone systems).

So hopefully the following information will help find a solution:

Firstly if I browse to the BRP072A42 module from my browser, the following are the returns we see: 

STATE:  Heatpump Off
URL: /aircon/get_sensor_info
RETURN: ret=OK,htemp=21.0,hhum=-,otemp=-,err=0,cmpfreq=0

URL: /aircon/get_control_info
RETURN: ret=OK,pow=0,mode=4,adv=,stemp=18.0,shum=0,dt1=25.0,dt2=M,dt3=25.0,dt4=18.0,dt5=18.0,dt7=25.0,dh1=AUTO,dh2=50,dh3=0,dh4=0,dh5=0,dh7=AUTO,dhh=50,b_mode=4,b_stemp=18.0,b_shum=0,alert=255

STATE:  Heatpump On
URL: /aircon/get_sensor_info
RETURN: ret=OK,htemp=20.0,hhum=-,otemp=11.0,err=0,cmpfreq=34

URL: /aircon/get_control_info
RETURN: ret=OK,pow=1,mode=4,adv=,stemp=18.0,shum=0,dt1=25.0,dt2=M,dt3=25.0,dt4=18.0,dt5=18.0,dt7=25.0,dh1=AUTO,dh2=50,dh3=0,dh4=0,dh5=0,dh7=AUTO,dhh=50,b_mode=4,b_stemp=18.0,b_shum=0,alert=255

So I am perhaps guessing that the "otemp=-" may be the culprit for the error, and it is trying to parse it as a numeric value? I assume "hhum" may be similar, but I don't have any items for that, and I note that this does not cause errors when the heatpump is on, even though the value remains at "-"  (But could be worth having a similar 'catch' for this value too, to prevent errors).

Let me know if I can provide any further information/assistance.... 
Cheers,

Glen
-------------------------------------------------------------------
Error from openhab.log:


2015-08-06 18:26:01.000 [ERROR] [.service.AbstractActiveService] - Error while executing background thread Daikin Refresh Service
java.lang.NumberFormatException: For input string: "-"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1250) ~[na:1.7.0_60]
        at java.lang.Float.parseFloat(Float.java:452) ~[na:1.7.0_60]
        at net.jonathangiles.daikin.wireless.WirelessDaikin.parseFloat(WirelessDaikin.java:235) ~[na:na]
        at net.jonathangiles.daikin.wireless.WirelessDaikin.readDaikinState(WirelessDaikin.java:139) ~[na:na]
        at org.openhab.binding.daikin.internal.DaikinBinding.execute(DaikinBinding.java:111) ~[na:na]
        at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:156) ~[na:na]
        at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:173) ~[na:na]

**Comment by JosSchering1** [comment]
Hi Glenn,
Following function is failing Float.parseFloat(value) in JDaikin library if input value is "-".
I'm a bit surprised this error does not effect the devices that are running. There is a bit of work involved to handle null values.
Please raise a ticket and assign to me. I'm familiar processing bugs, but not with OpenHAB project, so it is a good learning curve for me.

**Comment by guitarglen** [comment]
Hi Jos - Thanks for this - I have raised #3032 in relation to this issue.
Hopefully I have done this correctly, as I have only just signed-up to, and started using GitHub.....

Hopefully I will be in a position to help start fixing some bugs soon.... (I have only played around in programming languages whose name is one letter long.... So just learning to spell Java, let alone get my head around the OH project too!!....)
 Let me know if there is anything I can do to retest/provide further information.

Cheers - Glen

**Comment by welbymcroberts** [comment]
@guitarglen / @JosSchering1 : I've also got some of the wireless modules (BRP069A42 is the wireless modules part number but the units are in a single package as the BRP069A43 as this contains the '42 and a board for the AC unit) on a multi-split.

I've got a similar situation where I'm able to set values, but not read them from the unit. I'll update issue #3032 with more info

**Pull request merged**
