### PR TITLE
Initial commit of alarm binding and respective core modifications.

### PR DESCRIPTION
**Pull request by Snickermicker**
Initial commit of alarm binding and respective core modifications.
Summary:
This is a modification of the core and a new binding to generate alarms and distribute them over the openHAB bus and show them on UIs and mobile devices.

Detailed description: [link](https://github.com/Snickermicker/openhab/wiki/Alarm-Binding)
Discussion group: [link](https://groups.google.com/forum/#!category-topic/openhab/features/AoJW4b7uiqY)

### CODE REVIEW

**Comment by staehler** [comment]
@Snickermicker: Is your binding already ready to use? I'm quite keen on it, as it could reduce a huge amount of my alarm rules.
Thanks for your great work!

**Comment by Snickermicker** [comment]
Yes, it is ready to be used.
But it requires also the proposed core modifications to work.

**Comment by Snickermicker** [comment]
Binding and core  modifications are ready to be reviewed.

**Comment by staehler** [comment]
What does on-hold mean? Il'd appreciate a fast merge as I'm really interested in this binding.
Is this project going on?

**Comment by watou** [comment]
[This](https://groups.google.com/d/msg/openhab/AoJW4b7uiqY/EpUF9RWKr5gJ) may be related to your question (not certain).

**Comment by staehler** [comment]
@watou This answers my question, unfortunately. But thanks for the hint.

**Pull request closed without merging**
