### PR TITLE
Weather: Added Wunderground total precipitation

### PR DESCRIPTION
**Pull request by gerrieg**
see [discussion](https://community.openhab.org/t/wunderground-forecast-rain-total/5343/11) and https://github.com/openhab/openhab/issues/3596

### CODE REVIEW

**Comment by teichsta** [comment]
Thanks @gerrieg!

**Comment by watou** [comment]
@gerrieg , could you update the [wiki](https://github.com/openhab/openhab/wiki/Weather-Binding#available-bindings) so users know of this new value in 1.8?  Also, the wiki lists `rain` and `snow` twice under `precipitation`. (And `visibility` and `pressure` twice under `atmosphere`.)

**Comment by gerrieg** [comment]
I've updated the wiki with this new property. Some properties are twice to show the different unit conversions, thats OK.

**Comment by watou** [comment]
Thank you, @gerrieg.  I notice in the [Available Bindings section](https://github.com/openhab/openhab/wiki/Weather-Binding#available-bindings) that the new `total` property isn't listed (but is present in the example [items section](https://github.com/openhab/openhab/wiki/Weather-Binding#items)).  Perhaps you intend to add that later?

**Pull request merged**
