### PR TITLE
Heatmiser update per Issue #2177

### PR DESCRIPTION
**Pull request by SkynetHome**
Added suggested code referenced in Issue #2177  to handle remote sensor air temp.

### CODE REVIEW

**Comment by cdjackson** [comment]
I'm interested in why this change was made like this? This is labeled as a bug, but it wasn't really a bug, but it's a change in 'concept' on how the binding works...

With this change the binding now selects different temperature sensors - why not just make both available - it doesn't have to select different sensors like this?

**Comment by SkynetHome** [comment]
Just  trying to help out. A user indicated that they couldn't get a proper sensor reading because there was no code to handle the PRTE sensor and suggested a code update. I took the suggested update and wrote it into the binding in a manner that I thought would achieve the desired result without comprising the rest of the binding and uploaded for approval and testing. It was merged so I assumed that my additions were reviewed and deemed useful. I have requested a report back from the OP in his issue to find out if the code addition is working properly. As of yet, no response!

**Comment by cdjackson** [comment]
I just don’t think it’s the best way forward as it means that it’s no longer possible to read the internal sensor if you have the external sensor as well. Both sensors should be separately readable, and we’ve now solved one ‘bug’ with another…

ie - someone couldn’t read the external sensor as only the internal was available, but now you can’t read the internal sensor if you also have the external, as now only the external is available...

**Comment by SkynetHome** [comment]
Could the problem be solved by simply adding the internal sensor inside the if statement before the else? So if you have external sensor read both internal and external sensor else read on without setting external sensor?

**Comment by cdjackson** [comment]
I don’t think so - or at least I don’t understand how? If I understand what you’re suggesting, then this would effectively reverse your change anyway as only the second = statement will do anything?

The only way I think this can be solved is to handle the sensors separately so they can be assigned to separate items. At the end of the day, there’s only a single value being read - it can only be the internal OR the external sensor that resides in the dcbRoomTemperature variable - never both. Before it was the internal, and now it’s the external...

For sensors that only support one or the other, it doesn’t matter, but I have both connected...

**Comment by SkynetHome** [comment]
Chris, 

Was this issue ever addressed? Did you revert the changes or is it working as I submitted? I was wondering if it would be possible to add another variable for the remote sensor or if the variables that are included in the binding are all that are supported. ie. add dcbRemoteRoomTemperature so that both sensors could be read and rectify the problem.

**Comment by cdjackson** [comment]
I’ve not had the chance to do anything yet, and as my heating is off, it’s not killing me right now :)

> I was wondering if it would be possible to add another variable for the remote sensor or if the variables that are included in the binding are all that are supported. ie. add dcbRemoteRoomTemperature so that both sensors could be read and rectify the problem.

Yes, this is exactly what I meant previously - this is how I think it should have been handled so that the user can display any or both sensors...

**Pull request merged**
