### PR TITLE
Specify pid file when checking process status

### LINKED ISSUE #3540: Init.d reports incorrect openHAB status in Ubuntu 14.04
Working on Ubuntu 14.04.3 LTS (GNU/Linux 3.13.0-68-generic x86_64), /etc/init.d/openhab reports that openhab is running when it is not.

```shell
$ sudo /etc/init.d/openhab status
 * openhab is running
```
The shell echo flag reveals that the openhab script checks the wrong pid file. Although the openhab script sets a `PIDFILE` variable to `/var/run/openhab.pid`, that value is not passed to the `status_of_proc` function. The system functions `status_of_proc` and `pidofproc` instead derive the value `pidfile=/var/run/java.pid` from the program path `/usr/bin/java`.

```shell
$ sudo /bin/sh -x openhab status
+ PATH=/sbin:/usr/sbin:/bin:/usr/bin
+ OPENHAB_INST_DIR=/usr/share/openhab
+ DESC=openHAB server
+ NAME=openhab
+ JAVA=/usr/bin/java
+ PIDFILE=/var/run/openhab.pid
+ SCRIPTNAME=/etc/init.d/openhab
...
+ status_of_proc /usr/bin/java openhab
+ local pidfile daemon name status OPTIND
+ pidfile=
+ OPTIND=1
+ getopts p: opt
+ shift 0
+ [ -n  ]
+ daemon=/usr/bin/java
+ name=openhab
+ status=0
+ pidofproc /usr/bin/java
+ local pidfile base status specified pid OPTIND
+ pidfile=
+ specified=
+ OPTIND=1
+ getopts p: opt
+ shift 0
+ [ 1 -ne 1 ]
+ base=java
+ [ !  ]
+ pidfile=/var/run/java.pid
+ [ -n /var/run/java.pid -a -r /var/run/java.pid ]
+ [ -n  ]
+ [ -x /bin/pidof ]
+ status=0
+ /bin/pidof -o %PPID -x /usr/bin/java
+ [ 0 = 1 ]
+ return 0
+ [ 0 = 0 ]
+ log_success_msg openhab is running
+ echo  * openhab is running
 * openhab is running
+ return 0
+ exit 0
```
I recommend (and will try) adding an explicit `-p` option to the `status_of_proc` call on line 154 of `openhab/distribution/src/deb/etc/init.d/openhab`, as described at https://wiki.debian.org/LSBInitScripts/StatusSupport.

This would change
```shell
        status_of_proc "$JAVA" "$NAME" && exit 0 || exit $?
```
to
```shell
        status_of_proc -p "$PIDFILE" "$JAVA" "$NAME" && exit 0 || exit $?
```

### PR DESCRIPTION
**Pull request by jshprentz**
This fixes #3540.

### CODE REVIEW

**Comment by teichsta** [comment]
@theoweiss  could you please have a look into this PR (since you've self-assigned the according issue :-))

**Comment by theoweiss** [comment]
@teichsta OK

**Comment by theoweiss** [comment]
Thanks @jshprentz I've commented on https://github.com/openhab/openhab/issues/3540

**Comment by teichsta** [comment]
Thanks guys!!

**Pull request merged**
