### PR TITLE
Revert "eBUS Major Update 1"

### PR DESCRIPTION
**Pull request by csowada**
Many files uses different line end characters, makes it hard to see the real changes.
Reverts openhab/openhab#2981

### CODE REVIEW

**Comment by hakan42** [comment]
Reversal PR looks good and contains only files in the directory bundles/binding/org.openhab.binding.ebus

Merging.

@csowada , could you please rename readme.md to README.md in your next PR?

**Comment by hakan42** [comment]
@csowada , by the way, could I ask you to commit the files in .../docs (all those small markup files) in a seperate PR if possible?

github gets hickups on huge diffs on PRs, and some of us use the web interface to review PRs :smile:

**Comment by csowada** [comment]
Ok, I will do that

**Comment by dvanherbergen** [comment]
This merge seems to break the build:
```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:41 min
[INFO] Finished at: 2015-12-30T12:42:48+01:00
[INFO] Final Memory: 410M/889M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:0.22.0:compile (default-compile) on project org.openhab.binding.ebus: Compilation failure: Compilation failure:
[ERROR] /Users/davy/git/openhab/bundles/binding/org.openhab.binding.ebus/src/main/java/org/openhab/binding/ebus/internal/EBusBinding.java:[205]
[ERROR] public void addBindingProvider(EBusBindingProvider provider) {
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The method addBindingProvider(EBusBindingProvider) of type EBusBinding must override or implement a supertype method
[ERROR] /Users/davy/git/openhab/bundles/binding/org.openhab.binding.ebus/src/main/java/org/openhab/binding/ebus/internal/EBusBinding.java:[225]
[ERROR] public void removeBindingProvider(EBusBindingProvider provider) {
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The method removeBindingProvider(EBusBindingProvider) of type EBusBinding must override or implement a supertype method
[ERROR] 2 problems (2 errors)
```

**Comment by csowada** [comment]
Yes, this was the change from https://github.com/openhab/openhab/issues/3612, will be fixed in approx an hour

**Comment by csowada** [comment]
So added two new PRs: https://github.com/openhab/openhab/pull/3636, https://github.com/openhab/openhab/pull/3639

**Pull request merged**
