### PR TITLE
 One KNX command causes two busevents

### PR DESCRIPTION
**Pull request by lewie**
https://github.com/openhab/openhab/issues/2508

### CODE REVIEW

**Comment by lewie** [comment]
Done.

**Comment by lewie** [comment]
Now a Pull Request for openhab/openhab?! I'm confused...

**Comment by lewie** [comment]
Hmm, 
jenkins found a problem.
In console output https://buildhive.cloudbees.com/job/openhab/job/openhab/2988/org.openhab.binding$org.openhab.binding.knx/consoleText"  there found this Warning: 
```
[WARNING] The effective compiler target level 1.6 is incompatible with the following OSGi execution 
environments: [J2SE-1.5 (assumes 1.5)] @ MavenProject: 
org.openhab.binding:org.openhab.binding.knx:1.7.0-SNAPSHOT @ /scratch/jenkins/workspace
/openhab/openhab/bundles/binding/org.openhab.binding.knx/pom.xml
```
The pom.xml I did not change, its original from openhab/master.
Jar and deb where compiled.
What is missing, please help.

**Comment by teichsta** [comment]
Hi @lewie, thanks for this contribution. Unfortunately reviewing the code is quite since you've changed the formatting which makes it near to impossible to compare the code you've changed at the end of the day. Could you please give me some pointers where to find changed code? Thanks, Thomas E.-E.

**Comment by lewie** [comment]
Hi @teichsta, I see the same Formatting as before in eclipse, did not reformat it, consciously!

You'll get Pointers in new Version: 
KNXBinding.java: 
line 168: groupWrite

KNXConnection.java: 
line 32
line 67 - 72
line 263
line 299 - 308
line 428 - 436

KNXBindingDatapointReaderTask.java:
line 14, 15
line 39
line 92
line 103, 104
line 115 -132

Sorry again, I promise improvement.. ;-)
Thanks Helmut

**Comment by lewie** [comment]
The diff issues is caused by space changes:
space changes.

gitk Diffs:

org.openhab.binding.knx.internal.bus.KNXBinding.java: 
```
Eltern: 77149372b4451fcf80e6639ff7965b8eb9abe9f3 (Fixed error in logging statements (used for autoRefresh).)
Kind:  0000000000000000000000000000000000000000 (Lokale Änderungen, nicht bereitgestellt)
Zweig: fix-knx-issue, remotes/origin/fix-knx-issue
Folgt auf: v1.6.0
Vorgänger von: 

    Issue: One KNX command causes two busevents
    https://github.com/openhab/openhab/issues/2508

 bundles/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/bus/KNXBinding.java 
index 3bd5009..3a2f6cc 100644
@@ -158,10 +158,18 @@ public class KNXBinding extends AbstractBinding<KNXBindingProvider> implements
 	/* (non-Javadoc)
 	 * @see tuwien.auto.calimero.process.ProcessListener#groupWrite(tuwien.auto.calimero.process.ProcessEvent)
 	 */
+	/**
+	 * If <code>knx:ignorelocalevents=true</code> is set in configuration, it prevents internal events 
+	 * coming from 'openHAB event bus' a second time to be sent back to the 'openHAB event bus'.
+	 *  
+	 * @param e the {@link ProcessEvent} to handle.
+	 */
 	@Override
 	public void groupWrite(ProcessEvent e) {
 		logger.debug("Received groupWrite Event.");
+		if (!(KNXConnection.getIgnoreLocalSourceEvents() && e.getSourceAddr().toString().equalsIgnoreCase(KNXConnection.getLocalSourceAddr()))) {
 			readFromKNX(e);
+		}else logger.warn("Ignoring local Event, received from my local Source address {} for Group address {}.", e.getSourceAddr().toString(), e.getDestination().toString());
 	}
 
 	/* (non-Javadoc)
```

org.openhab.binding.knx.internal.bus.KNXBindingDatapointReaderTask.java:
```
Eltern: 86148260e88142113f6463ec899f3102f470df8c (updated license header to 2015)
Zweig: fix-knx-issue, remotes/origin/fix-knx-issue
Folgt auf: v1.6.0
Vorgänger von: 

    Issue: One KNX command causes two busevents
    https://github.com/openhab/openhab/issues/2508

 bundles/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/bus/KNXBindingDatapointReaderTask.java 
index 415a837..2819a8d 100644
@@ -11,6 +11,8 @@
  */
 package org.openhab.binding.knx.internal.bus;
 
+import java.util.HashMap;
+import java.util.Map;
 import java.util.concurrent.BlockingQueue;
 
 import org.openhab.binding.knx.internal.connection.KNXConnection;
@@ -34,6 +36,7 @@ import tuwien.auto.calimero.process.ProcessCommunicator;
 public class KNXBindingDatapointReaderTask extends Thread implements KNXConnectionListener {
 
 	private final BlockingQueue<Datapoint> readQueue;
+	private final Map<Datapoint, Integer> dpReadRetries = new HashMap<Datapoint, Integer>();
 	private final static Logger sLogger = LoggerFactory.getLogger(KNXBindingDatapointReaderTask.class);
 	private boolean mKNXConnected=true;
 
@@ -86,7 +89,7 @@ public class KNXBindingDatapointReaderTask extends Thread implements KNXConnecti
 		try {
 			ProcessCommunicator pc = KNXConnection.getCommunicator();
 			if (pc != null) {
-				sLogger.debug("Autorefresh: Sending read request to KNX for item '{}'", datapoint.getName());
+				sLogger.debug("Autorefresh: Sending read request to KNX for item '{}' DPT '{}'", datapoint.getName(), datapoint.getDPT());
 				pc.read(datapoint);
 			}
 			else {
@@ -97,7 +100,8 @@ public class KNXBindingDatapointReaderTask extends Thread implements KNXConnecti
 		} catch (KNXInvalidResponseException e) {
 			sLogger.warn("Autorefresh: Cannot read value for item '{}' from KNX bus: {}: invalid response", datapoint.getName(), e.getMessage() );
 		} catch (KNXTimeoutException e) {
-			sLogger.warn("Autorefresh: Cannot read value for item '{}' from KNX bus: {}: timeout", datapoint.getName(), e.getMessage() );
+			sLogger.warn("Autorefresh: Cannot read value for item '{}' from KNX bus: {}: timeout", datapoint.getName(), e.getMessage());
+			addToReadQueue(datapoint);
 		} catch (KNXLinkClosedException e) {
 			sLogger.warn("Autorefresh: Cannot read value for item '{}' from KNX bus: {}: link closed", datapoint.getName(), e.getMessage() );
 		} catch (KNXException e) {
@@ -108,6 +112,24 @@ public class KNXBindingDatapointReaderTask extends Thread implements KNXConnecti
 
 	}
 
+
+	/**
+	 * Adds or re-adds a datapoint to readQueue, 
+	 * if datapoint is known in dpReadRetries, retries will be reduced.
+	 * Otherwise it will be registered in dpReadRetries with retriesLimit.
+	 *  
+	 * @param datapoint
+	 */
+	private void addToReadQueue(Datapoint datapoint) throws InterruptedException {
+		Integer r = dpReadRetries.remove(datapoint);
+		int retries = ( r != null ? r : KNXConnection.getReadRetriesLimit() ) - 1;
+		if(retries >= 0 ){
+			sLogger.warn("Autorefresh: Remaining retries for address '{}' = '{}'", datapoint.getMainAddress().toString(), retries );
+			readQueue.put(datapoint);
+			dpReadRetries.put(datapoint, retries);
+		}else if(retries == -1)sLogger.warn("Autorefresh: Give up, could not read address '{}' after '{}' retries.", datapoint.getMainAddress().toString(), KNXConnection.getReadRetriesLimit() );
+	}
+	
 	/* (non-Javadoc)
 	 * @see org.openhab.binding.knx.internal.connection.KNXConnectionListener#connectionEstablished()
 	 */
```


org.openhab.binding.knx.internal.connection.KNXConnection.java: 
```
Eltern: 86148260e88142113f6463ec899f3102f470df8c (updated license header to 2015)
Zweig: fix-knx-issue, remotes/origin/fix-knx-issue
Folgt auf: v1.6.0
Vorgänger von: 

    Issue: One KNX command causes two busevents
    https://github.com/openhab/openhab/issues/2508

 bundles/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/connection/KNXConnection.java 
index 22b55f5..316452d 100644
@@ -29,6 +29,7 @@ import org.slf4j.LoggerFactory;
 
 import tuwien.auto.calimero.CloseEvent;
 import tuwien.auto.calimero.FrameEvent;
+import tuwien.auto.calimero.IndividualAddress;
 import tuwien.auto.calimero.exception.KNXException;
 import tuwien.auto.calimero.knxnetip.KNXnetIPConnection;
 import tuwien.auto.calimero.link.KNXNetworkLink;
@@ -63,6 +64,12 @@ public class KNXConnection implements ManagedService {
 	/** the ip address to use for connecting to the KNX bus */
 	private static String sIp;
 
+	/** the KNX bus address to use as local sourceaddress in KNX bus */
+	private static String sLocalSourceAddr = "0.0.0";
+
+	/** the KNX bus address to use as local sourceaddress in KNX bus */
+	private static boolean sIgnoreLocalSourceEvents = false;
+
 	/** the ip connection type for connecting to the KNX bus. Could be either TUNNEL or ROUTING */
 	private static int sIpConnectionType;
 
@@ -253,7 +260,7 @@ public class KNXConnection implements ManagedService {
 			}
 		}
 		
-		return new KNXNetworkLinkIP(ipConnectionType, localEndPoint, new InetSocketAddress(ip, port), false, TPSettings.TP1);
+		return new KNXNetworkLinkIP(ipConnectionType, localEndPoint, new InetSocketAddress(ip, port), false, new TPSettings(new IndividualAddress(sLocalSourceAddr), true));
 	}
 
 	private static KNXNetworkLink connectBySerial(String serialPort) throws KNXException {
@@ -289,6 +296,16 @@ public class KNXConnection implements ManagedService {
 			sLogger.debug("KNXBinding configuration present. Setting up KNX bus connection.");
 			sIp = (String) config.get("ip");
 
+			String readingBusAddrString = (String) config.get("busaddr");
+			if (StringUtils.isNotBlank(readingBusAddrString)) {
+				sLocalSourceAddr = readingBusAddrString;
+			}
+
+			String readingIgnLocEv = (String) config.get("ignorelocalevents");
+			if (StringUtils.isNotBlank(readingIgnLocEv)) {
+				sIgnoreLocalSourceEvents = readingIgnLocEv.equalsIgnoreCase("true");
+			}
+
 			String connectionTypeString = (String) config.get("type");
 			if (StringUtils.isNotBlank(connectionTypeString)) {
 				if ("TUNNEL".equals(connectionTypeString)) {
@@ -408,6 +425,15 @@ public class KNXConnection implements ManagedService {
 		}
 	}
 
+	
+	public static String getLocalSourceAddr() {
+		return sLocalSourceAddr;
+	}
+
+	public static boolean getIgnoreLocalSourceEvents() {
+		return sIgnoreLocalSourceEvents;
+	}
+	
 	public static long getReadingPause() {
 		return sReadingPause;
 	}
```

**Comment by teichsta** [comment]
Thanks @lewie!

**Comment by lewie** [comment]
@teichsta: 

The parameters are optional, but to do it right, the new cfg Parameters in KNXConnection.java "knx:busaddr" and "knx:ignorelocalevents" should be present in openhab_default.cfg.

openhab_default.cfg:
```
Eltern: 54ecbddbacbf3f5567b6bec3251d0d38de58ae39 (Merge pull request #2590 from berndpfrommer/insteonplm)
Zweig: fix-knx-issue, remotes/origin/fix-knx-issue
Folgt auf: v1.6.0
Vorgänger von: 

    Issue: One KNX command causes two busevents
    https://github.com/openhab/openhab/issues/2508

--------- distribution/openhabhome/configurations/openhab_default.cfg ---------
index 09b46e3..4d80f61 100644
@@ -505,6 +505,18 @@ logging:pattern=%date{ISO8601} - %-25logger: %msg%n
 # (optional, if serialPort or connection type 'ROUTER' is specified)
 #knx:ip=
 
+# Local KNX Binding bus address.
+# Use it, when two or more openHAB Instances are connected to the same KNX bus.
+# (optional, defaults to 0.0.0)
+#knx:busaddr=
+
+# Ignore local KNX Events, prevents internal events coming from
+# 'openHAB event bus' a second time to be sent back to the 'openHAB event bus'.
+# Note: To send back events second time is a Bug, but for backward compatibility, the behavior is not changed.
+# For new installations, its recommend to set "knx:ignorelocalevents=true"
+# (optional, defaults to false)
+#knx:ignorelocalevents=
+
 # KNX IP connection type. Could be either TUNNEL or ROUTER (optional, defaults to TUNNEL)
 # Note: If you cannot get the ROUTER mode working (even if it claims it is connected), 
 # use TUNNEL mode instead with setting both the ip of the KNX gateway and the localIp.
```

Later when the changes are in openhab/master I'll complete wiki with the new knx parameters: https://github.com/openhab/openhab/wiki/KNX-Binding

That took some doing, I hope that was all.

Thank You
Helmut

**Comment by lewie** [comment]
@teichsta: Can it be merged now?!

**Pull request merged**
