### PR TITLE
Jdbc add to distribution

### PR DESCRIPTION
**Pull request by hakan42**

### CODE REVIEW

**Comment by hakan42** [comment]
This is in addition to #3248

**Comment by watou** [comment]
Thank you!

**Comment by watou** [comment]
Might have broken the build though?

**Comment by watou** [comment]
```
[INFO] Resolving dependencies of MavenProject: org.openhab.persistence:org.openhab.persistence.jdbc:1.8.0-SNAPSHOT @ /Users/jcocula/src/openhab/bundles/persistence/org.openhab.persistence.jdbc/pom.xml
[INFO] {osgi.ws=gtk, osgi.os=linux, osgi.arch=x86, org.eclipse.update.install.features=true}
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.openhab.persistence.jdbc 1.8.0.qualifier
[ERROR]   Missing requirement: org.openhab.persistence.jdbc 1.8.0.qualifier requires 'package org.sqlite 0.0.0' but it could not be found
[ERROR] 
[ERROR] See http://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
[ERROR] Cannot resolve dependencies of MavenProject: org.openhab.persistence:org.openhab.persistence.jdbc:1.8.0-SNAPSHOT @ /Users/jcocula/src/openhab/bundles/persistence/org.openhab.persistence.jdbc/pom.xml: See log for details -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException
```

**Comment by hakan42** [comment]
I will check why the binding needs sqlite at compile time.

**Comment by teichsta** [comment]
@hakan42 please don't forget to squash your commits ;-)

**Comment by hakan42** [comment]
:smiling_imp:

**Comment by lewie** [comment]
OK, found the reason, but searching to solve it yet.

In my Environment Maven found the database drivers in a compiled test jar which is in openHAB Name space.  There are three ways to solve this:
 1. Includes all drivers needed optionally into JDBC-Bundle. -> bäh :-(
 2. Add a dummy-project which includes all drivers needed optionally. So they are in openHAB Namespace and Maven keeps cool -> this only would be a solution if maven drives me insane :-(
 3. A Maven/OSGI crack here or I find a Maven Magic, to exclude drivers whithout an error. -> best solution :-)

I stay tuned!

**Comment by lewie** [comment]
Updated sqlite, and now it works:
[PR](https://github.com/openhab/openhab/pull/3493)

**Pull request merged**
