### PR TITLE
[urtsi] Fixes #3756; code cleanup; 2.0 compatible

### LINKED ISSUE #3756: Xtend classes should be removed from URTSI binding
The urtsi binding contains three small classes that are written in Xtend. Since the new openHAB IDE does not have Xtend plugins installed by default anymore, I would suggest to replace these classes by a Java version.

### PR DESCRIPTION
**Pull request by watou**
Lurching this binding into the present.

After review and user(s) can test on 1.8 and recent 2.0 build, please consider merging for 1.9.  I am unable to test the binding here, so testers with actual hardware are needed.

I don't know how to add it to default IDE setup, though, now that it's Xtend-free.

Signed-off-by: John Cocula <john@cocula.com>

### CODE REVIEW

**Comment by watou** [comment]
Reported working [here](https://community.openhab.org/t/any-somfy-urtsi-ii-binding-users-tester-needed/6582/4?u=watou).

**Comment by kaikreuzer** [comment]
Great work, @watou, thanks!

**Comment by kaikreuzer** [comment]
> I don't know how to add it to default IDE setup

This way: https://github.com/openhab/openhab2-addons/pull/641

**Comment by watou** [comment]
Thank you!

**Pull request merged**
