### PR TITLE
add new feature sumSince to persistence extensions

### PR DESCRIPTION
**Pull request by J-N-K**
adds solution for second part of #2599 (deltaSince with rrd4j counter db)

### CODE REVIEW

**Comment by teichsta** [comment]
Thanks @J-N-K! Would you mind adding this to ESH as well?

**Comment by J-N-K** [comment]
@teichsta: I probaly would, but couldn't find the right place in the openhab2 repo.

**Comment by kaikreuzer** [comment]
@J-N-K The code has moved here: https://github.com/eclipse/smarthome/blob/master/bundles/model/org.eclipse.smarthome.model.persistence/src/org/eclipse/smarthome/model/persistence/extensions/PersistenceExtensions.java

**Comment by J-N-K** [comment]
done.

**Pull request merged**
