### PR TITLE
Neohub Binding OH2

### PR DESCRIPTION
**Pull request by sprehn**
Neohub Binding tested in OH2

### CODE REVIEW

**Comment by watou** [comment]
Thanks @sprehn!  Could you squash the 2 commits, and then it will lgtm.

**Comment by sprehn** [comment]
first time I use the squash feature, hope I did it correctly. now the build failes on a enocaen test... don't think this is related to my changes....

**Comment by watou** [comment]
Thanks.  There are now 5 commits (see near top of this page).  Here is one way I've used to squash commits:
```bash
$ git checkout neohubbinding
$ git merge-base neohubbinding master
<commit_id>
$ git rebase -i <commit_id>
change second and subsequent pick to squash, save file
$ git push -f origin neohubbinding
```

**Comment by sprehn** [comment]
not good, now everything that I was working on in my local fork has been added - which is not ready to commit

**Comment by sprehn** [comment]
New PR created: #4086

**Pull request closed without merging**
