### PR TITLE
Lgtv Minor fix for issue #1943 

### PR DESCRIPTION
**Pull request by martinfluchgmxnet**
Lgtv Minor 2015 fix for issue #1943

### CODE REVIEW

**Comment by teichsta** [comment]
Hi @martinfluchgmxnet thanks for this Fix. Could you point me to the Commit's with the fix? Since all classes changes it looks like a complete new checkin to me. For 1.6.2 i would only like to cherry-pick real Bugfixes and let the rest go into 1.7.0. Best, Thomas E.-E.

**Comment by martinfluchgmxnet** [comment]
Hi, don't know why all the file changes of the past are in there / the only Important Change for bugfix is the one in  ...les/binding/org.openhab.binding.lgtv/src/main/java/org/openhab/binding/lgtv/internal/LgtvConnection.java as the binding hangs in the keepalive Check without this Change

Martin

**Comment by teichsta** [comment]
would you mind fixing this? It's probably a good idea to create a new PR from a fresh new Branch?

**Comment by teichsta** [comment]
Hi @martinfluchgmxnet, any chance to get this PR cleaned up? Best, Thomas E.-E.

**Comment by teichsta** [comment]
Any news?

**Comment by teichsta** [comment]
I would propose to create a new (clean) PR containing only the LgConnection class. Best, Thomas E.-E.

**Pull request closed without merging**
