### PR TITLE
Tinkerforge binding and action: new devices, enhancements and fixes

### PR DESCRIPTION
**Pull request by theoweiss**
This PR should replace PR https://github.com/openhab/openhab/pull/3552 .
This branch hopefully  holds all changes from my branch TF-2015-10-new-devices as single commit. I think squashing the original PR would not work because I merged upstream/master into the TF-2015-10-new-devices (commit b1af2b1).

Fixes also #2968

### CODE REVIEW

**Comment by hannibal85** [comment]
Hi,
I'm using your Thinkerforge 1.8.0-SNAPSHOT to use bricklet_ambient_lightv2. It works well without an entry in the openhab.cfg for this bricklet. 
But when adding one of these 3 parameters to the openhab.cfg
- tinkerforge:luminance_wz.illuminanceRange=3
- tinkerforge:luminance_wz.integrationTime=5
- tinkerforge:luminance_wz.callbackPeriod=10
the whole Tinkerforge-Binding stops working. 
Other parameters (treshold) work without any problems.

Greetings
Hannibal

**Comment by teichsta** [comment]
PR lgtm … please go ahead an merge!

**Comment by theoweiss** [comment]
Yes Sir!

**Comment by teichsta** [comment]
Sir, thanks, Sir :D !!

**Comment by theoweiss** [comment]
@hannibal85 use the values as described in the TF API, the config examples are faulty and will be fixed soon.

**Pull request merged**
