### PR TITLE
Qubino zmnhla binding in process.

### PR DESCRIPTION
**Pull request by SkynetHome**
Chris, I am committing my work so far for your perusal. Its about 1/3rd
the way done but I thought I would commit in case you want to review the
progress thus far. This is in reference to Issue #2553

### CODE REVIEW

**Comment by cdjackson** [comment]
It looks fine from a quick look, however for parameters that are numeric (ie have a range such as 11, 12, 13, 14) please add the minimum and maximum value elements.

Also, please can you merge the future changes on this PR together so that we don't have lots of commits for a single PR? If you're still using SourceTree, there's an option to do this in the "Commit Options" box when you go to commit changes.

**Comment by SkynetHome** [comment]
Got it, will make corrections, finish this and try and merge it.

**Comment by SkynetHome** [comment]
Made the corrections and then completed the file and added updated products xml. If edits are required I will figure out how to merge that commit or commits with source tree.

**Comment by cdjackson** [comment]
Thanks - looks good. I've one comment. For the associations, the labels are quite long and I don' think will work well in the GUI. Maybe it would be good to changethese to ```<Help>``` and use a short version for the label?

eg for ```basic on/off (triggered by Too low temperature limit, it sends FF )``` maybe just make it ```Low Temperature```?

**Comment by cdjackson** [comment]
Oh - and thanks for doing these - I really do appreciate it. It gives me a bit more time to work on other things (most notably the OH2 zwave binding at the moment)...

**Comment by SkynetHome** [comment]
Np and I see your point. Will make change. Any hints for merging with Source Tree? I have not been using it for anything other than pulling openhab master into local branch. That I have got down thanks to your explanation, if you have any tips for merging the commits they would be welcome. I will play around with it in the meantime!

**Comment by SkynetHome** [comment]
Chris, I cannot rebase children in Source Tree because I cannot set these files to ignore. Untracking them only makes them turn red. These files have been hanging around since I first setup the Eclipse IDE should they have been committed?
problems

**Comment by cdjackson** [comment]
These are auto generated files I think (other than gitignore) - although I’m not 100% sure. It’s probably easiest to stash the changes, or to simply reset them. gitignore probably changes each time you ignore a file.  I wouldn’t commit them though…

**Comment by SkynetHome** [comment]
rebase children allowed me to combined the last two commits in one, which left me with a file to push. When I tried to rebase the new combined commit with the parent commit nothing happens. So I pushed the change and that just set everything back to where I started with three individual commits. I guess I should have been doing this as I committed each file and not after the fact.

**Comment by cdjackson** [comment]
If using SourceTree, you need to click on the one before the one you want to combine (if that makes sense!) and then click on the “interactive rebase” option. To me this seems a little strange - I’d before to click on the one I want to combine - not it’s parent, but that’s the way ST works…

It is however easier to do this as you go and just combine with the previous commit, but you ca’t go back and do this now… There are also other tricks that I’m not that familiar with (I’m far from a Git expert unfortunately!).

If you can’t merge them, then let’s not bother too much now and keep it in mind for future commits...

**Comment by SkynetHome** [comment]
I figured out the ST process with the parent child relationship being sort of inverse to what you would expect and was able to rebase 3 into 2 but not the new 3-2 combination into 1 for some reason. As you said I would much prefer to leave this one as is and get it merged.  I will make sure and proceed with future commits through Source Tree merging each with the next.

**Comment by SkynetHome** [comment]
So is this good to go or do I need to make additional changes?

**Comment by cdjackson** [comment]
Sorry - I missed this one... I'll take a look tomorrow - gotta think about some sleep (it's 1:30)

**Comment by SkynetHome** [comment]
No problem, and I appreciate the continued support. Goodnight.

**Comment by SkynetHome** [comment]
OMG...I think I finally got it. I dont have a clue how to make this work with Source Tree but git terminal appears to have done the trick. Please let me know if this has panned out but it certainly seems to have from my end!!

**Comment by cdjackson** [comment]
Looks good - thanks.

**Pull request merged**
