### PR TITLE
add maven-bundle-plugin configuration

### PR DESCRIPTION
**Pull request by maggu2810**
The configuration has been added, so we could a manual manifest
generation. The generated manifest could be used by developers to
identify missing imports.
The manifest generation could be triggered by:
mvn bundle:manifest -DniceManifest=true
The "nice manifest" option will e.g. add line breaks after every
imported package.
Now you can have a look at the manifest that would be generated by the
bndtool using:
cat target/classes/META-INF/MANIFEST.MF

### CODE REVIEW

**Comment by watou** [comment]
This tool helped me identify some unneeded imports in the Nest binding:
```diff
Import-Package:
- com.google.common.base,
- com.google.common.io,
- org.apache.commons.httpclient,
  org.apache.commons.httpclient.methods,
  org.apache.commons.httpclient.params,
  org.apache.commons.httpclient.util,
  org.apache.commons.io,
  org.apache.commons.lang,
  org.apache.commons.lang.builder,
- org.apache.commons.logging,
  org.codehaus.jackson,
  org.codehaus.jackson.annotate,
  org.codehaus.jackson.map,
  org.openhab.core.binding,
  org.openhab.core.events,
  org.openhab.core.items,
- org.openhab.core.library.items,
  org.openhab.core.library.types,
  org.openhab.core.types,
  org.openhab.io.net.http,
  org.openhab.model.item.binding,
  org.osgi.framework,
  org.osgi.service.cm,
- org.osgi.service.component,
- org.osgi.service.event,
  org.slf4j
```

**Comment by maggu2810** [comment]
@watou It needs to be said, that the created manifest should be used as a indication what is needed. It is not always correct, that missing packages are not needed (e.g. if the code is using "get class for name" etc.).

**Comment by hakan42** [comment]
Looks extremely nice to me, could be a part of the review process

**Comment by teichsta** [comment]
> if the code is using "get class for name" etc.

which shouldn't be the case … but +1 for @maggu2810 i've often observed wrong results of this import-calculation tool.

**Comment by teichsta** [comment]
Thanks @maggu2810!

**Pull request merged**
