### PR TITLE
Edit Popp Z - Weather

### PR DESCRIPTION
**Pull request by SkynetHome**
Added missing configuration parameters not mentioned in Pepper Database. Ref PR #2855

### CODE REVIEW

**Comment by ZeroNine00** [comment]
Hi Sorry but the update of product.xml is missing. As I wrote in issue for z-weather device popp have a manufactor id !

**Comment by SkynetHome** [comment]
@cdjackson What do you think about this? I cannot find a reference to a new Mfg ID in any of the literature. Pepper has ID for this device as 0154 as well. Although as I have seen Pepper is far from perfect. Should I make changes based on what habmin is showing this users device to be or based on the literature?

**Comment by cdjackson** [comment]
Update it with the value that HABmin is showing. I’ve seen multiple manufacturer IDs pop up in the past - we just need to be mindful that it might be wrong and we might need to change the name later. For example, sometimes a manufacturer gets another company to develop a unit, and we might fond other random devices use the same ID, but supposedly come from different suppliers…

Anyway, for now, use the value HABmin provides - it’s gotta be right and we’ll worry about the name if something conflicts later…

**Comment by SkynetHome** [comment]
Thanks will update now!

**Comment by cdjackson** [comment]
Thanks - hopefully this will sort it :)

**Comment by SkynetHome** [comment]
Agreed. I just downloaded and am running openhab2. I saw your latest post on the openhab2 format but havent had a chance to look at it as ive run into some problems with OH2 I'm trying to sort out. Will take a look in a bit and start making any changes to database in accordance with your new format!

**Comment by cdjackson** [comment]
Don’t get too far ahead with the OH2 files yet - things may still change around for a day or three. I’ve currently got my dimmer running under the new OH2 binding, but as I start to incorporate a few more devices it might change a little. I’ve also got to sort out some of the configuration issues yet, so there might be some changes…

I have put a converted version of the database into my repo though - it’s linked near the top of the wiki page so it’s a good starter :)

**Comment by SkynetHome** [comment]
So far when I run OH2 the only binding that is recognized is Astro binding.
Should I be breaking down my openhab.cfg file that I copied over into
individual cfg files or do I just need to edit out the name spaces in the
openhab.cfg

**Comment by cdjackson** [comment]
You need to move (for example) the zwave:port= config from the openhab.cfg file into a zwave.cfg file, and remove the zwave part (so just leaving port=… in the zwave.cfg file).

**Comment by SkynetHome** [comment]
Thanks will try that tommorrow it's 3am I've got to get to bed.

**Pull request merged**
