### PR TITLE
JSR223: Support for UpdatedEventTrigger

### PR DESCRIPTION
**Pull request by steve-bate**
This pull request adds an UpdatedEventTrigger to the JSR223 bundle. Most of the code to support it was already in place, but it was never completed. Previously, the ChangedEventTrigger was coded to respond to updated events but the trigger was not registered to respond to update events so it did not work as expected. I've added an UpdatedEventTrigger and am registering it to be evaluated on update events. I've also added the class to the predefined globals defined during script invocation.

Related discussion: https://community.openhab.org/t/jsr223-updatedeventtrigger/2908/2

### CODE REVIEW

**Comment by teichsta** [comment]
@smerschjohann @lewie @mdbergmann could one of you please have a look into this PR?

**Comment by smerschjohann** [comment]
Thank you for the PR. Looks good to me - matches exactly what I had in mind,
I will test it tomorrow on my local setup.

**Comment by teichsta** [comment]
@steve-bate please finally squash your commits into one, once @smerschjohann confirmed the functionality. Thanks, Thomas E.-E.

**Comment by smerschjohann** [comment]
I just checked the PR and everything is working as expected :+1:

**Comment by steve-bate** [comment]
This is my first PR and I'm not a experienced git user. I've researched various techniques for squashing commits but the examples I've seen seem to primarily apply to situations where the commits to squash are sequential. Unfortunately, I merged from master into my branch during the commit sequence. I've tried rebase -i but the warnings about lost commits concerns me. Would it be easier for me to start with a completely new branch and PR? Suggestions are welcome.

**Comment by teichsta** [comment]
> Would it be easier for me to start with a completely new branch and PR? Suggestions are welcome.

yes, could be easier :-)

Before that you can try to reset your branch (in mixed mode) to the first commit. After that you should see all changed files as uncommitted changes, commit and force push.

**Comment by steve-bate** [comment]
Thanks Thomas. I've resubmitted the PR with the squashed commits (#3263). And thanks to Simon for the testing.

**Pull request closed without merging**
