### PR TITLE
RFXCOM Add lighting4 fix and new commands

### PR DESCRIPTION
**Pull request by Speederc**
Modification of lighting4 code :
- Fix the ID and command field mappings : S1-S24 field is divided into S1-S20 for ID and S21-S24 for command
- Add new command IDs : 
    OFF : 0,2,4
    ON : 1,3,5,7,12

Validated in #3858

### CODE REVIEW

**Comment by teichsta** [comment]
Thanks @Speederc for this PR series for RFXCom! Any idea who could help verifying your changes against a real system? Did you announce your changes at community.openhab.org in order to find Beta-Testers for the changes?

**Comment by Speederc** [comment]
As indicated in this PR, it was validated in #3858 with a real system.
For others PR, I indicated if it was validated with a real sensor. All modifications of the existing code were validated with real system. Only new message types were sometimes not validated, but as it is a new code, it has no impact on the existing configuration. 
It could be difficult to find a beta tester for each new sensor type.

**Comment by Speederc** [comment]
OK the battery field can be removed as it will be always 0. I will update the PR. Thanks !

**Comment by Speederc** [comment]
Done ! Can be merged.

**Comment by teichsta** [comment]
great, thanks @Speederc!

**Comment by julesbike** [comment]
Hi I've found a cheap door/window contact sensor which has 4 codes and works with lighting4, 
7 is On (closed)
14 is Off (open)
11 is Tamper 
The 4th code is low battery but I have not been able to capture that yet!

Is there a chance you could add 14 to the Off code?  Tamper is less important.   ~Thanks

**Pull request merged**
