### PR TITLE
MegaDevice binding

### PR DESCRIPTION
**Pull request by Pshatsillo**
This binding is for device called MegaDevice.
http://ab-log.ru/forum/viewtopic.php?f=1&t=632

### CODE REVIEW

**Comment by resetnow** [comment]
<a href="http://ab-log.ru/smart-house/ethernet/megad-328">This</a> might be a better link

**Comment by Pshatsillo** [comment]
Thank You! Should i commited new link?

**Comment by resetnow** [comment]
It's up to maintainers :) I just posted it to give some more context (that it's a real device and it is actually being sold)

**Comment by Pshatsillo** [comment]
Put external configuration for binding

**Comment by Pshatsillo** [comment]
Sorry... can't undo...

**Pull request closed without merging**
