### PR TITLE
reverted: Implement slider widget for WebUI #2792

### PR DESCRIPTION
**Pull request by teichsta**
This PR reverts #2792 which originally added a slider to Class-UI.

I reverted the change for several reasons:
* there was a serious issue with the slider which renders the Classic-UI under certain conditions (see #3985)
* for the sake of consistency the slider would have to be ported to ESH Classic-UI which hadn't been done yet
* OH2 comes with the Basic-UI which provides a nice slider implementation

An ongoing discussion can be [found here](https://community.openhab.org/t/solved-more-then-one-slider-item-breaks-1-8-0-classic-ui/6091/9).

Signed-off-by: Thomas Eichstädt-Engelen <thomas@openhab.org>

### CODE REVIEW

**Comment by teichsta** [comment]
@hakan42 @steve-bate @watou would be great if any of you could have a quick look at this one, please. Thanks, Thomas E.-E.

**Comment by resetnow** [comment]
Would it be okay if I try to fix it after it gets merged? Or does ClassicUI need slider at all?

**Comment by teichsta** [comment]
> Would it be okay if I try to fix it after it gets merged?

what are you going to fix? This PR is about reverting the given changes. The Classic-UI "slider" worked before afairc?

> And does ClassicUI need slider at all?

i would say the given support (Up/Down arrow) is ok for the time being. Basic-UI and other new generation UIs will do and will surely provide a "real" slider.

**Comment by udo1toni** [comment]
Unfortunately this revert breaks dimming functionality with knx dimmers from Classic UI at all, if the dimmers make use of start/stop-dimming. :(

**Comment by watou** [comment]
> Unfortunately this revert breaks dimming functionality with knx dimmers from Classic UI at all

Is this also true of the Classic UI in openHAB 2?  Is there a closed issue to reopen, or a new issue to open, that describes the issue in detail?

**Pull request merged**
