### PR TITLE
Update to allow launch from Eclipse IDE

### PR DESCRIPTION
**Pull request by marcelrv**
Signed-off-by: Marcel Verpaalen <marcel@verpaalen.com>

### CODE REVIEW

**Comment by teichsta** [comment]
Wouldn't that fix fit into the 1.6.2 Release?

**Comment by kaikreuzer** [comment]
That is just a launch config for tests, so not relevant for a release, is it?
Btw, I merged it by accident because I thought it is openHAB 2 ;-)

**Comment by teichsta** [comment]
> That is just a launch config for tests, so not relevant for a release, is it?

joa … but it's fix and it should be consistent on the 1.6 branch as well … will cherry-pick it.

> Btw, I merged it by accident because I thought it is openHAB 2 ;-)

no worries … feel free to merge as much PRs as you want ;-)

**Comment by marcelrv** [comment]
lol, that's why you were so fast:)
test suite for OH2 is in progress...

2015-01-15 14:40 GMT+01:00 Thomas Eichstädt-Engelen <
notifications@github.com>:

**Pull request merged**
