### PR TITLE
This fixes #2747 - decreases severity of lib version logging and decr…

### LINKED ISSUE #2747: KNX binding floods log
With the 1.7.0 version of the KNX binding, I have my log full of entries like 
```
2015-06-16 19:42:30 [INFO ] [tuwien.auto.calimero          :51   ] - [KNXnet/IP receiver] link 127.0.0.1:3671: indication from 1.1.7
```
when starting in debug mode. I would expect that those are suppressed as it was in the past and to only have the openhab KNX log messages instead.

Furthermore, when starting in normal mode, I have a log entry 
```
2015-06-16 19:45:17.259 [INFO ] [.b.knx.internal.bus.KNXBinding] - Calimero library version 2.2.0-alpha
```
which imho also should not be there as it is irrelevant for a normal user.

### PR DESCRIPTION
**Pull request by teichsta**
…eased calimero logger to ERROR

### CODE REVIEW

**Comment by teichsta** [comment]
please review @kaikreuzer

**Comment by kaikreuzer** [comment]
Thanks! But shouldn't logback_debug.xml be changed instead of logback.xml?
I will have to add the same to openHAB 2 then (which is a bit nasty having to add binding specific logger settings in the global logback configuration, but what to do...)

**Comment by teichsta** [comment]
> But shouldn't logback_debug.xml be changed instead of logback.xml?

true i would rather suggest to change both …

**Comment by kaikreuzer** [comment]
> true i would rather suggest to change both …
Why? The root level is already WARN, so there should not be any logging visible from calimero.

**Comment by teichsta** [comment]
> but what to do...

we could also change LogAdapter and map calimeros INFO log level onto openHAB DEBUG?

**Comment by kaikreuzer** [comment]
> we could also change LogAdapter and map calimeros INFO log level onto openHAB DEBUG?

Sounds rather complex to do within a certain binding, so I'd suggest to leave it as it is, thanks!

**Pull request merged**
