### PR TITLE
Added Zwave Device TKB T78

### PR DESCRIPTION
**Pull request by SkynetHome**
Added per request reference Issue #2745 
There is little to no information available on this device. This is a
best guess configuration based on what is available. Please test and
report back!

### CODE REVIEW

**Comment by cdjackson** [comment]
Looking at the original request, we can't solve this like this. If the device is already recognised by the binding, then we can't just add another device with the same IDs. We would need to understand why it is wrong rather than change it, otherwise the next request will be from the people who were using the original definition asking for it to be changed back.

**Comment by SkynetHome** [comment]
If i understand this situation correctly it is as the op says a totally different device than what it is being recognized as. The documentation he provided showed that he has an in wall microswitch that is being recognized as a receptacle. He compared it to another in wall micro switch in his OP but that was a dual relay not single so I tried to match his device as closely as I could based on limited documentation.  It looks like a knock off of an aeotec or other similar micro switch.

**Comment by cdjackson** [comment]
I'm slightly concerned that this is being added without any information, so we need to be careful. If there are parameters added that don't exist, it could cause the initialisation to slow down or stall, so please keep an eye out for any timeouts during the initialisation procedure.

Ideally, I would have preferred this to be tested before merging, but since the auto build is down and @solucionesmipc is ready to test(and there are only 2 parameters anyway!), I'll merge now. Please report any findings as soon as possible.

**Comment by solucionesmipc** [comment]
hi:
i am trying to test it, but openhab still recognizes the device as tz68 (tz68 and tz 78 xml are included in database)

do you how to force it?

diego

**Comment by cdjackson** [comment]
You can't force it - it is detected from the device, so either you have a device that has been badged incorrectly (this does happen), or the database is wrong.

**Pull request merged**
