### PR TITLE
Update for Plex binding

### PR DESCRIPTION
**Pull request by idserda**
This fixes two issues in the current Plex binding:

- Latest Plex Media Server (>= 1.3.2.3112) sends a different message format over the websocket connection. The binding now supports both this and the earlier format.
- No websocket connections were possible when authentication was enabled in PMS. The token used for other http calls is now also sent as a query parameter when connecting to the websocket.

### CODE REVIEW

**Comment by watou** [comment]
Thanks @idserda, please report here when the PR passes the testing cycle you started [here](https://community.openhab.org/t/openhab2-plex/14036/42?u=watou).  Code change looks good (but I haven't tested it myself).

**Comment by watou** [comment]
Give the go-ahead when you think this change has gotten sufficient field testing, and thanks for your PR!

**Comment by idserda** [comment]
All testing was successful, this PR can be merged.

**Comment by watou** [comment]
Thank you very much, @idserda!

**Pull request merged**
