### PR TITLE
openhab - Bticino / legrand openweb binding

### PR DESCRIPTION
**Pull request by TomDeVlaminck**
Dear Thomas,
I have created a new pull request for the bticino / legrand openweb binding.
This PR only contains the essential files and is based on the latest pull.
Friendly greetings
Tom

### CODE REVIEW

**Comment by teichsta** [comment]
Thanks @TomDeVlaminck. I've merged your Binding and changed some of my comments myself (Formatting, @since, license header). Best, Thomas E.-E.

**Comment by xmor** [comment]
Hello @TomDeVlaminck i'm trying bticino binding.
You can handle the part related to thermoregulation (central zone 99 + probes) ?

**Comment by TomDeVlaminck** [comment]
For the moment no. I have the central zone 99 and the probes but they are not installed yet.
I have a mh200 but have to check if that support thermoregulation controlling. I think i need to buy a mh200n for that.
Controlling is necessary to send the command to the probes to read the temperature or to control the f430 actuators.
It is on my list for this year...
Greetings
Tom

--- Original Message ---

**Comment by teichsta** [comment]
@TomDeVlaminck please keep in mind to create the according Wiki page? For now it will be quite for the people to use your Binding without any documentation.

**Comment by teichsta** [comment]
@xmor reate a Wiki page (see https://github.com/openhab/openhab/wiki/Bticino-Binding)

**Comment by 1achy** [comment]
Hi all i want to collabore for expand the binding. @TomDeVlaminck Tom can you give me some rules ...... can i implementetion 25 dirty contact and alarm. Some therregulation.


11achy@gmail.com

**Pull request merged**
