### PR TITLE
MochadX10 fix hanging on OH2 shutdown - Issue #4136

### PR DESCRIPTION
**Pull request by smar000**
https://github.com/openhab/openhab/issues/4136

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Thanks, could you please squash your commits?

**Comment by smar000** [comment]
Done.

**Comment by kaikreuzer** [comment]
Nope, it still shows three: https://github.com/openhab/openhab/pull/4137/commits

**Comment by smar000** [comment]
Sorry, forgot to push it. Should be done now.

**Comment by kaikreuzer** [comment]
Thanks!

**Pull request merged**
