### PR TITLE
RRD4J : Remove dependency on TimerThreads, and replace it with Schedu…

### PR DESCRIPTION
**Pull request by kgoderis**
…ledExecu…torService

Fixes openhab/openhab2#358

Sorry, reformatting due to ESH auto-formatting in the Oomph provided IDE.

Signed-off-by: Karel Goderis <karel.goderis@me.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
> Sorry, reformatting due to ESH auto-formatting in the Oomph provided IDE.

For openHAB 1 contributions, you should disable the auto-formatter in the "Save Options" preferences - it is otherwise too difficult to understand what you have changed.

**Comment by teichsta** [comment]
@kgoderis would you mind reverting the code formatting?

**Comment by teichsta** [comment]
@kgoderis any chance to help with the code formatting? Reviewing the code is near to impossible now. Thanks (and happy new year), Thomas E.-E.

**Comment by teichsta** [comment]
moved to 1.9

**Comment by kgoderis** [comment]
@teichsta Thomas, I just noticed that this one is still lingering. Since I saved the file in the wrong formatting, I have no clue how to revert that. Selecting the built-in java formatting does change only little, e.g. the file is still incomparable. How to push this forward because this bundle is killing the OH2/ESH runtime big time?

**Comment by kgoderis** [comment]
Replaced by #4516

**Pull request closed without merging**
