### PR TITLE
Use name of sitemap file when creating sitemap page bean, as it may be d...

### PR DESCRIPTION
**Pull request by llamahunter**
...ifferent than the sitemap name itself.

### CODE REVIEW

**Comment by llamahunter** [comment]
Note that this is a fix for issue https://github.com/openhab/openhab/issues/2510

**Comment by teichsta** [comment]
well spotted, thanks @llamahunter

**Comment by teichsta** [comment]
seems this has been fixed in ESH already (see https://github.com/eclipse/smarthome/blob/master/bundles/io/org.eclipse.smarthome.io.rest.sitemap/src/main/java/org/eclipse/smarthome/io/rest/sitemap/internal/SitemapResource.java)

**Comment by llamahunter** [comment]
All hail OpenHAB 2.0.

**Comment by llamahunter** [comment]
Uh, no.  still looks broken. there. Line 250.

**Comment by kaikreuzer** [comment]
So, would anyone want to create a PR for ESH in order to make sure that there is no regression in openHAB 2?

**Comment by kaikreuzer** [comment]
No one?

**Comment by llamahunter** [comment]
I have not had a chance to set up an openhab 2 branch for development.  At some point soon, I'm going to move to OH2, and if no one has beaten me to it, I'll do it.  I've been busy lately and have had to suspend my openhab tinkering for a bit.

**Comment by d2inco** [comment]
This looks like it is still a problem in OH2.  Its apparent when I use the Android app, and fails for diving down into any of the 2nd level groups.   
With my sitemap file starting out as:
`sitemap main label="David's House (Main)"`

the response to http://hahub:8080/rest/sitemaps
shows wrong url:
```
[
  {
    "name": "main",
    "label": "David's House (Main)",
    "link": "http://hahub:8080/rest/sitemaps/main",
    "homepage": {
      "link": "http://hahub:8080/rest/sitemaps/main/main",
      "leaf": false,
      "widgets": []
    }
  },
  {
    "name": "_default",
    "label": "Home",
    "link": "http://hahub:8080/rest/sitemaps/_default",
    "homepage": {
      "link": "http://hahub:8080/rest/sitemaps/_default/_default",
      "leaf": false,
      "widgets": []
    }
  }
]
```

and, in fact, errs out when you try to reference the single "sitemaps/main" (or _default), and requires the sitemaps/main/main in order to traverse the sitemaps tree.  I don't think this is right...

**Pull request merged**
