### PR TITLE
deb packaging: docker support

### PR DESCRIPTION
**Pull request by theoweiss**
Related to issue #4246
Set `ENV OH_DOCKER_INSTALLATION true` for docker installations.
For example:
```
COPY files/openhab-runtime-1.8.2.deb /
ENV OH_DOCKER_INSTALLATION true
RUN dpkg -i /openhab-runtime-1.8.2.deb
```

### CODE REVIEW

**Comment by teichsta** [comment]
thanks @theoweiss! is this PR also meant to be cherry-picked onto 1.8?

**Comment by theoweiss** [comment]
Oops, I made this PR against 1.8, wrong?

**Comment by kaikreuzer** [comment]
I would say it is fully correct, the PR does not make any sense against master.

**Comment by roblad** [comment]
[image: Obraz w treści 1]

2016-05-02 19:00 GMT+02:00 Thomas Eichstädt-Engelen <
notifications@github.com>:

**Pull request merged**
