### PR TITLE
Serial action

### PR DESCRIPTION
**Pull request by joek**
Hi,
I created a serial Action, to push commands to applications which are stateless. Especial for arduino devices it is possible to configure a device in openhab.cfg. This device will be opened once only closed at shutdow. Otherwise arduino devices on linux boxes will be reset at close.

### CODE REVIEW

**Comment by jernejz5** [comment]
Hello, since I would really love to have this feature I am wondering if there is anything I can do to help implement this Serial Action or just get it working for the next release? 

Is @joek still actively participating in this issue?

**Comment by joek** [comment]
@teichsta sorry I was on vacation. Yes I implemented a startup rule to check if the feature is working. I will double check the rule.

**Comment by teichsta** [comment]
any news?

**Comment by joek** [comment]
I will not make it within the next year. Maybe somebody like to take it over.

**Pull request closed without merging**
