### PR TITLE
Update debug logging for configuration converter

### PR DESCRIPTION
**Pull request by cdjackson**
#2082

### CODE REVIEW

**Comment by cdjackson** [comment]
Try this latest version to see if it works - also, hopefully this might fix the issue with config parameter 10.

**Comment by rezethon** [comment]
Parameter change through HABmin works fine now but that error in the logs is still there (see below). By the way have you seen my last comment in my HABmin issue?
Thanks for your help so far. Much appreciated.

```
2015-04-23 22:45:25.187 [DEBUG] [.z.i.config.ZWaveConfiguration:1071]- doSet domain 'nodes/node4/parameters/configuration10' to '1'
2015-04-23 22:45:25.317 [DEBUG] [.z.i.config.ZWaveConfiguration:1136]- Set parameter index '10' to '1'
2015-04-23 22:45:25.317 [DEBUG] [ZWaveConfigurationCommandClass:182 ]- NODE 4: Creating new message for application command CONFIGURATIONCMD_SET
2015-04-23 22:45:25.317 [DEBUG] [o.b.z.i.protocol.SerialMessage:109 ]- NODE 4: Creating empty message of class = SendData (0x13), type = Request (0x00)
2015-04-23 22:45:25.317 [DEBUG] [b.z.i.protocol.ZWaveController:976 ]- Callback ID = 65
2015-04-23 22:45:25.322 [DEBUG] [WaveController$ZWaveSendThread:1249]- Took message from queue for sending. Queue length = 0
2015-04-23 22:45:25.322 [DEBUG] [b.z.i.protocol.ZWaveController:658 ]- Enqueueing message. Queue length = 1
2015-04-23 22:45:25.322 [TRACE] [o.b.z.i.protocol.SerialMessage:179 ]- Calculated checksum = 0xFB
2015-04-23 22:45:25.322 [DEBUG] [ZWaveConfigurationCommandClass:154 ]- NODE 4: Creating new message for application command CONFIGURATIONCMD_GET
2015-04-23 22:45:25.322 [DEBUG] [o.b.z.i.protocol.SerialMessage:233 ]- Assembled message buffer = 01 0C 00 13 04 05 70 04 0A 01 01 25 41 FB 
2015-04-23 22:45:25.322 [DEBUG] [o.b.z.i.protocol.SerialMessage:109 ]- NODE 4: Creating empty message of class = SendData (0x13), type = Request (0x00)
2015-04-23 22:45:25.322 [DEBUG] [WaveController$ZWaveSendThread:1306]- NODE 4: Sending REQUEST Message = 01 0C 00 13 04 05 70 04 0A 01 01 25 41 FB 
2015-04-23 22:45:25.322 [DEBUG] [b.z.i.protocol.ZWaveController:976 ]- Callback ID = 66
2015-04-23 22:45:25.327 [TRACE] [WaveController$ZWaveSendThread:1312]- Message SENT
2015-04-23 22:45:25.327 [TRACE] [eController$ZWaveReceiveThread:1524]- Received ACK
2015-04-23 22:45:25.327 [DEBUG] [b.z.i.protocol.ZWaveController:658 ]- Enqueueing message. Queue length = 1
2015-04-23 22:45:25.332 [DEBUG] [eController$ZWaveReceiveThread:1519]- Receive Message = 01 04 01 13 01 E8 
2015-04-23 22:45:25.332 [TRACE] [o.b.z.i.protocol.SerialMessage:136 ]- NODE 255: Creating new SerialMessage from buffer = 01 04 01 13 01 E8 
2015-04-23 22:45:25.332 [TRACE] [o.b.z.i.protocol.SerialMessage:179 ]- Calculated checksum = 0xE8
2015-04-23 22:45:25.332 [TRACE] [o.b.z.i.protocol.SerialMessage:141 ]- NODE 255: Checksum matched
2015-04-23 22:45:25.332 [TRACE] [o.b.z.i.protocol.SerialMessage:153 ]- NODE 255: Message payload = 01 
2015-04-23 22:45:25.337 [TRACE] [eController$ZWaveReceiveThread:1428]- Message is valid, sending ACK
2015-04-23 22:45:25.337 [TRACE] [eController$ZWaveReceiveThread:1413]- Response SENT
2015-04-23 22:45:25.337 [DEBUG] [eController$ZWaveReceiveThread:1443]- Receive queue ADD: Length=1
2015-04-23 22:45:25.337 [DEBUG] [b.z.i.protocol.ZWaveController:1201]- Receive queue TAKE: Length=0
2015-04-23 22:45:25.337 [TRACE] [o.b.z.i.protocol.SerialMessage:179 ]- Calculated checksum = 0xE8
2015-04-23 22:45:25.337 [DEBUG] [o.b.z.i.protocol.SerialMessage:233 ]- Assembled message buffer = 01 04 01 13 01 E8 
2015-04-23 22:45:25.337 [DEBUG] [b.z.i.protocol.ZWaveController:1202]- Process Message = 01 04 01 13 01 E8 
2015-04-23 22:45:25.337 [DEBUG] [b.z.i.protocol.ZWaveController:190 ]- Message: class = SendData (0x13), type = Response (0x01), payload = 01 
2015-04-23 22:45:25.337 [TRACE] [b.z.i.protocol.ZWaveController:244 ]- Incoming Message type = RESPONSE
2015-04-23 22:45:25.337 [TRACE] [b.z.i.p.s.SendDataMessageClass:36  ]- Handle Message Send Data Response
2015-04-23 22:45:25.337 [DEBUG] [b.z.i.p.s.SendDataMessageClass:38  ]- NODE 4: Sent Data successfully placed on stack.
2015-04-23 22:45:25.352 [DEBUG] [eController$ZWaveReceiveThread:1519]- Receive Message = 01 07 00 13 41 00 00 02 A8 
2015-04-23 22:45:25.352 [TRACE] [o.b.z.i.protocol.SerialMessage:136 ]- NODE 255: Creating new SerialMessage from buffer = 01 07 00 13 41 00 00 02 A8 
2015-04-23 22:45:25.352 [TRACE] [o.b.z.i.protocol.SerialMessage:179 ]- Calculated checksum = 0xA8
2015-04-23 22:45:25.352 [TRACE] [o.b.z.i.protocol.SerialMessage:141 ]- NODE 255: Checksum matched
2015-04-23 22:45:25.352 [TRACE] [o.b.z.i.protocol.SerialMessage:153 ]- NODE 255: Message payload = 41 00 00 02 
2015-04-23 22:45:25.352 [TRACE] [eController$ZWaveReceiveThread:1428]- Message is valid, sending ACK
2015-04-23 22:45:25.352 [TRACE] [eController$ZWaveReceiveThread:1413]- Response SENT
2015-04-23 22:45:25.352 [DEBUG] [eController$ZWaveReceiveThread:1443]- Receive queue ADD: Length=1
2015-04-23 22:45:25.352 [DEBUG] [b.z.i.protocol.ZWaveController:1201]- Receive queue TAKE: Length=0
2015-04-23 22:45:25.352 [TRACE] [o.b.z.i.protocol.SerialMessage:179 ]- Calculated checksum = 0xA6
2015-04-23 22:45:25.357 [DEBUG] [o.b.z.i.protocol.SerialMessage:233 ]- Assembled message buffer = 01 09 00 13 41 00 00 02 00 00 A6 
2015-04-23 22:45:25.357 [DEBUG] [b.z.i.protocol.ZWaveController:1202]- Process Message = 01 09 00 13 41 00 00 02 00 00 A6 
2015-04-23 22:45:25.357 [DEBUG] [b.z.i.protocol.ZWaveController:190 ]- Message: class = SendData (0x13), type = Request (0x00), payload = 41 00 00 02 
2015-04-23 22:45:25.357 [TRACE] [b.z.i.protocol.ZWaveController:210 ]- Incoming Message type = REQUEST
2015-04-23 22:45:25.357 [TRACE] [b.z.i.p.s.SendDataMessageClass:58  ]- Handle Message Send Data Request
2015-04-23 22:45:25.357 [DEBUG] [b.z.i.p.s.SendDataMessageClass:74  ]- NODE 4: SendData Request. CallBack ID = 65, Status = Transmission complete and ACK received(0)
2015-04-23 22:45:25.357 [TRACE] [o.b.z.i.protocol.SerialMessage:399 ]- Ack Pending cleared
2015-04-23 22:45:25.357 [DEBUG] [.z.i.p.s.ZWaveCommandProcessor:63  ]- Sent message Message: class = SendData (0x13), type = Request (0x00), payload = 04 05 70 04 0A 01 01 
2015-04-23 22:45:25.357 [DEBUG] [.z.i.p.s.ZWaveCommandProcessor:64  ]- Recv message Message: class = SendData (0x13), type = Request (0x00), payload = 41 00 00 02 
2015-04-23 22:45:25.357 [DEBUG] [.z.i.p.s.ZWaveCommandProcessor:65  ]- Checking transaction complete: class=SendData, expected=SendData, cancelled=false
2015-04-23 22:45:25.357 [DEBUG] [.z.i.p.s.ZWaveCommandProcessor:68  ]-          transaction complete!
2015-04-23 22:45:25.362 [DEBUG] [b.z.i.protocol.ZWaveController:673 ]- Notifying event listeners: ZWaveTransactionCompletedEvent
2015-04-23 22:45:25.362 [DEBUG] [.z.internal.ZWaveActiveBinding:433 ]- ZwaveIncomingEvent
2015-04-23 22:45:25.362 [TRACE] [b.z.i.protocol.ZWaveController:225 ]- Released. Transaction completed permit count -> 1
2015-04-23 22:45:25.362 [DEBUG] [WaveController$ZWaveSendThread:1365]- NODE 4: Response processed after 35ms/170ms.
2015-04-23 22:45:25.362 [TRACE] [WaveController$ZWaveSendThread:1366]- Acquired. Transaction completed permit count -> 0
2015-04-23 22:45:25.362 [DEBUG] [WaveController$ZWaveSendThread:1249]- Took message from queue for sending. Queue length = 0
2015-04-23 22:45:25.362 [TRACE] [o.b.z.i.protocol.SerialMessage:179 ]- Calculated checksum = 0xF9
2015-04-23 22:45:25.362 [DEBUG] [o.b.z.i.protocol.SerialMessage:233 ]- Assembled message buffer = 01 0A 00 13 04 03 70 05 0A 25 42 F9 
2015-04-23 22:45:25.362 [DEBUG] [WaveController$ZWaveSendThread:1306]- NODE 4: Sending REQUEST Message = 01 0A 00 13 04 03 70 05 0A 25 42 F9 
2015-04-23 22:45:25.362 [TRACE] [WaveController$ZWaveSendThread:1312]- Message SENT
2015-04-23 22:45:25.367 [TRACE] [eController$ZWaveReceiveThread:1524]- Received ACK
2015-04-23 22:45:25.372 [DEBUG] [eController$ZWaveReceiveThread:1519]- Receive Message = 01 04 01 13 01 E8 
2015-04-23 22:45:25.372 [TRACE] [o.b.z.i.protocol.SerialMessage:136 ]- NODE 255: Creating new SerialMessage from buffer = 01 04 01 13 01 E8 
2015-04-23 22:45:25.372 [TRACE] [o.b.z.i.protocol.SerialMessage:179 ]- Calculated checksum = 0xE8
2015-04-23 22:45:25.372 [TRACE] [o.b.z.i.protocol.SerialMessage:141 ]- NODE 255: Checksum matched
2015-04-23 22:45:25.377 [TRACE] [o.b.z.i.protocol.SerialMessage:153 ]- NODE 255: Message payload = 01 
2015-04-23 22:45:25.377 [TRACE] [eController$ZWaveReceiveThread:1428]- Message is valid, sending ACK
2015-04-23 22:45:25.377 [TRACE] [eController$ZWaveReceiveThread:1413]- Response SENT
2015-04-23 22:45:25.377 [DEBUG] [eController$ZWaveReceiveThread:1443]- Receive queue ADD: Length=1
2015-04-23 22:45:25.377 [DEBUG] [b.z.i.protocol.ZWaveController:1201]- Receive queue TAKE: Length=0
2015-04-23 22:45:25.377 [TRACE] [o.b.z.i.protocol.SerialMessage:179 ]- Calculated checksum = 0xE8
2015-04-23 22:45:25.377 [DEBUG] [o.b.z.i.protocol.SerialMessage:233 ]- Assembled message buffer = 01 04 01 13 01 E8 
2015-04-23 22:45:25.377 [DEBUG] [b.z.i.protocol.ZWaveController:1202]- Process Message = 01 04 01 13 01 E8 
2015-04-23 22:45:25.377 [DEBUG] [b.z.i.protocol.ZWaveController:190 ]- Message: class = SendData (0x13), type = Response (0x01), payload = 01 
2015-04-23 22:45:25.377 [TRACE] [b.z.i.protocol.ZWaveController:244 ]- Incoming Message type = RESPONSE
2015-04-23 22:45:25.382 [TRACE] [b.z.i.p.s.SendDataMessageClass:36  ]- Handle Message Send Data Response
2015-04-23 22:45:25.382 [DEBUG] [b.z.i.p.s.SendDataMessageClass:38  ]- NODE 4: Sent Data successfully placed on stack.
2015-04-23 22:45:25.387 [DEBUG] [eController$ZWaveReceiveThread:1519]- Receive Message = 01 07 00 13 42 00 00 02 AB 
2015-04-23 22:45:25.392 [TRACE] [o.b.z.i.protocol.SerialMessage:136 ]- NODE 255: Creating new SerialMessage from buffer = 01 07 00 13 42 00 00 02 AB 
2015-04-23 22:45:25.392 [TRACE] [o.b.z.i.protocol.SerialMessage:179 ]- Calculated checksum = 0xAB
2015-04-23 22:45:25.392 [TRACE] [o.b.z.i.protocol.SerialMessage:141 ]- NODE 255: Checksum matched
2015-04-23 22:45:25.392 [TRACE] [o.b.z.i.protocol.SerialMessage:153 ]- NODE 255: Message payload = 42 00 00 02 
2015-04-23 22:45:25.392 [TRACE] [eController$ZWaveReceiveThread:1428]- Message is valid, sending ACK
2015-04-23 22:45:25.392 [TRACE] [eController$ZWaveReceiveThread:1413]- Response SENT
2015-04-23 22:45:25.392 [DEBUG] [eController$ZWaveReceiveThread:1443]- Receive queue ADD: Length=1
2015-04-23 22:45:25.392 [DEBUG] [b.z.i.protocol.ZWaveController:1201]- Receive queue TAKE: Length=0
2015-04-23 22:45:25.397 [TRACE] [o.b.z.i.protocol.SerialMessage:179 ]- Calculated checksum = 0xA5
2015-04-23 22:45:25.397 [DEBUG] [o.b.z.i.protocol.SerialMessage:233 ]- Assembled message buffer = 01 09 00 13 42 00 00 02 00 00 A5 
2015-04-23 22:45:25.397 [DEBUG] [b.z.i.protocol.ZWaveController:1202]- Process Message = 01 09 00 13 42 00 00 02 00 00 A5 
2015-04-23 22:45:25.397 [DEBUG] [b.z.i.protocol.ZWaveController:190 ]- Message: class = SendData (0x13), type = Request (0x00), payload = 42 00 00 02 
2015-04-23 22:45:25.397 [TRACE] [b.z.i.protocol.ZWaveController:210 ]- Incoming Message type = REQUEST
2015-04-23 22:45:25.397 [TRACE] [b.z.i.p.s.SendDataMessageClass:58  ]- Handle Message Send Data Request
2015-04-23 22:45:25.397 [DEBUG] [b.z.i.p.s.SendDataMessageClass:74  ]- NODE 4: SendData Request. CallBack ID = 66, Status = Transmission complete and ACK received(0)
2015-04-23 22:45:25.397 [TRACE] [o.b.z.i.protocol.SerialMessage:399 ]- Ack Pending cleared
2015-04-23 22:45:25.402 [DEBUG] [.z.i.p.s.ZWaveCommandProcessor:63  ]- Sent message Message: class = SendData (0x13), type = Request (0x00), payload = 04 03 70 05 0A 
2015-04-23 22:45:25.402 [DEBUG] [.z.i.p.s.ZWaveCommandProcessor:64  ]- Recv message Message: class = SendData (0x13), type = Request (0x00), payload = 42 00 00 02 
2015-04-23 22:45:25.402 [DEBUG] [.z.i.p.s.ZWaveCommandProcessor:65  ]- Checking transaction complete: class=SendData, expected=ApplicationCommandHandler, cancelled=false
2015-04-23 22:45:25.407 [DEBUG] [eController$ZWaveReceiveThread:1519]- Receive Message = 01 0B 00 04 00 04 05 70 06 0A 01 01 8D 
2015-04-23 22:45:25.407 [TRACE] [o.b.z.i.protocol.SerialMessage:136 ]- NODE 255: Creating new SerialMessage from buffer = 01 0B 00 04 00 04 05 70 06 0A 01 01 8D 
2015-04-23 22:45:25.407 [TRACE] [o.b.z.i.protocol.SerialMessage:179 ]- Calculated checksum = 0x8D
2015-04-23 22:45:25.407 [TRACE] [o.b.z.i.protocol.SerialMessage:141 ]- NODE 255: Checksum matched
2015-04-23 22:45:25.407 [TRACE] [o.b.z.i.protocol.SerialMessage:153 ]- NODE 255: Message payload = 00 04 05 70 06 0A 01 01 
2015-04-23 22:45:25.412 [TRACE] [eController$ZWaveReceiveThread:1428]- Message is valid, sending ACK
2015-04-23 22:45:25.412 [TRACE] [eController$ZWaveReceiveThread:1413]- Response SENT
2015-04-23 22:45:25.412 [DEBUG] [eController$ZWaveReceiveThread:1443]- Receive queue ADD: Length=1
2015-04-23 22:45:25.412 [DEBUG] [b.z.i.protocol.ZWaveController:1201]- Receive queue TAKE: Length=0
2015-04-23 22:45:25.412 [TRACE] [o.b.z.i.protocol.SerialMessage:179 ]- Calculated checksum = 0x8D
2015-04-23 22:45:25.412 [DEBUG] [o.b.z.i.protocol.SerialMessage:233 ]- Assembled message buffer = 01 0B 00 04 00 04 05 70 06 0A 01 01 8D 
2015-04-23 22:45:25.417 [DEBUG] [b.z.i.protocol.ZWaveController:1202]- Process Message = 01 0B 00 04 00 04 05 70 06 0A 01 01 8D 
2015-04-23 22:45:25.417 [DEBUG] [b.z.i.protocol.ZWaveController:190 ]- Message: class = ApplicationCommandHandler (0x04), type = Request (0x00), payload = 00 04 05 70 06 0A 01 01 
2015-04-23 22:45:25.417 [TRACE] [b.z.i.protocol.ZWaveController:210 ]- Incoming Message type = REQUEST
2015-04-23 22:45:25.417 [TRACE] [ApplicationCommandMessageClass:30  ]- Handle Message Application Command Request
2015-04-23 22:45:25.417 [DEBUG] [ApplicationCommandMessageClass:38  ]- NODE 4: Application Command Request (ALIVE:DONE)
2015-04-23 22:45:25.417 [DEBUG] [ApplicationCommandMessageClass:56  ]- NODE 4: Incoming command class CONFIGURATION
2015-04-23 22:45:25.422 [TRACE] [ApplicationCommandMessageClass:79  ]- NODE 4: Found Command Class CONFIGURATION, passing to handleApplicationCommandRequest
2015-04-23 22:45:25.422 [DEBUG] [ZWaveConfigurationCommandClass:76  ]- NODE 4: Received Configuration Request
2015-04-23 22:45:25.422 [TRACE] [ZWaveConfigurationCommandClass:87  ]- NODE 4: Process Configuration Report
2015-04-23 22:45:25.422 [DEBUG] [ZWaveConfigurationCommandClass:115 ]- NODE 4: Node configuration report, parameter = 10, value = 1
2015-04-23 22:45:25.422 [DEBUG] [b.z.i.protocol.ZWaveController:673 ]- Notifying event listeners: ZWaveConfigurationParameterEvent
2015-04-23 22:45:25.422 [DEBUG] [.z.internal.ZWaveActiveBinding:433 ]- ZwaveIncomingEvent
2015-04-23 22:45:25.422 [DEBUG] [.z.internal.ZWaveActiveBinding:450 ]- NODE 4: Got a value event from Z-Wave network, endpoint = 0, command class = CONFIGURATION, value = org.openhab.binding.zwave.internal.protocol.ConfigurationParameter@e8e48a
2015-04-23 22:45:25.422 [TRACE] [.b.z.i.c.ZWaveConverterHandler:340 ]- Getting converter for item = PhilioMeterConfig, command class = CONFIGURATION, item command class = configuration
2015-04-23 22:45:25.427 [WARN ] [.c.ZWaveConfigurationConverter:99  ]- NODE 4: No converter found for item = PhilioMeterConfig(NumberItem), endpoint = 0, ignoring event.
2015-04-23 22:45:25.432 [TRACE] [.b.z.i.p.i.ZWaveNodeSerializer:50  ]- Initializing ZWaveNodeSerializer.
2015-04-23 22:45:25.452 [TRACE] [.b.z.i.p.i.ZWaveNodeSerializer:85  ]- Initialized ZWaveNodeSerializer.
2015-04-23 22:45:25.452 [DEBUG] [.b.z.i.p.i.ZWaveNodeSerializer:107 ]- NODE 4: Serializing to file etc\zwave\node4.xml
2015-04-23 22:45:25.482 [DEBUG] [.z.i.p.s.ZWaveCommandProcessor:63  ]- Sent message Message: class = SendData (0x13), type = Request (0x00), payload = 04 03 70 05 0A 
2015-04-23 22:45:25.482 [DEBUG] [.z.i.p.s.ZWaveCommandProcessor:64  ]- Recv message Message: class = ApplicationCommandHandler (0x04), type = Request (0x00), payload = 00 04 05 70 06 0A 01 01 
2015-04-23 22:45:25.482 [DEBUG] [.z.i.p.s.ZWaveCommandProcessor:65  ]- Checking transaction complete: class=ApplicationCommandHandler, expected=ApplicationCommandHandler, cancelled=false
2015-04-23 22:45:25.482 [DEBUG] [.z.i.p.s.ZWaveCommandProcessor:68  ]-          transaction complete!
2015-04-23 22:45:25.482 [DEBUG] [b.z.i.protocol.ZWaveController:673 ]- Notifying event listeners: ZWaveTransactionCompletedEvent

```

**Comment by teichsta** [comment]
@cdjackson any chance to get this done for 1.7.0?

**Comment by teichsta** [comment]
thanks @cdjackson … i've updated the milestone accordingly

**Pull request merged**
