### PR TITLE
[new binding] Initial version of Satel Integra security system binding

### PR DESCRIPTION
**Pull request by druciak**
This PR replaces #1750.

### CODE REVIEW

**Comment by druciak** [comment]
Hey @teichsta,
I hope you are aware this is *not* a new binding, but the one you have already reviewed. There are few additional changes, but in general it should be ready to merge. I expected you merge it in few days after creation, but 2 weeks passed and nothing. :(
I feel like it has landed at the end of the queue again...

**Comment by teichsta** [comment]
Hi @druciak, i've merged your Binding into master. Thanks again, Thomas E.-E.

**Comment by teichsta** [comment]
@druciak would you be able to create some short video, screencast, photo … anything that will help @kaikreuzer to pimp the press release for the upcoming release on Monday? That would be REALLY great :-) Thanks, Thomas E.-E.

**Comment by druciak** [comment]
I will try, but I need some guidance. Do you have any sample of such media? I have no idea what should be there. Also I don't have experience with creating videos/screencast neither I know tools for that. Any help appreciated.

**Comment by druciak** [comment]
So I prepared a short video with some basic features presented. Here is the link: https://www.youtube.com/watch?v=ogdgn0Dk1G8
Let me know if this is what you need. Unfortunately all texts are in polish, but everything is explained in the description.

**Comment by kaikreuzer** [comment]
Very nice, thanks a lot!

**Comment by teichsta** [comment]
thanks a lot! This is great ...

- sent from a mobile device -

**Pull request merged**
