### PR TITLE
Add CalDAV Bindings

### PR DESCRIPTION
**Pull request by querdenker2k**
CalDAV IO Binding, CalDAV Binding, CalDAV Presence Binding.
Used to connect to a caldav Server (e. g. owncloud) and detect presence or send commands from Events Begins and/or ends

### CODE REVIEW

**Comment by querdenker2k** [comment]
fix @since and parent pom versions

**Comment by querdenker2k** [comment]
This is a New binding for cal dav. With this you can detect presence and send commands throught events

**Comment by teichsta** [comment]
Hi @querdenker2k thanks a lot for this contribution! I'll let you know once i've finished the review. Thanks, Thomas E.-E.

**Comment by heaterC** [comment]
Thanks a lot @querdenker2k , I've been waiting for this for quite a while, a scheduler is really missing in OpenHAB so far!

**Comment by SpawnY0815** [comment]
I also wait a long time for this. So happy to see this! Thanks @querdenker2k !!

**Comment by querdenker2k** [comment]
I give it up, have i now pushed the onewire binding into the caldav pull request???
I made an extra branch for this and want a new pull request. how can i undo this?

**Comment by fmaack** [comment]
Maybe create a new branch based on your last commit before the onewire-mistake, cherry-pick the missing config-commit (or add the change manuelly) and create a new pullrequest?

I am looking foreward to replace some cron-rules by caldav-items! :)

**Comment by staehler** [comment]
Hi querdenker,
is it possible to get a pre-release of your caldav binding? I'm quite keen on it, as I have a running owncloud installation and would like to see, what your binding is able to do :-)
Is there already a wiki entry available?
Thanks a lot for your contribution!

**Comment by querdenker2k** [comment]
hi staehler,
yes you can download it from the buildhive build.
i created a wiki right now see here: https://github.com/openhab/openhab/wiki/CalDAV

**Comment by querdenker2k** [comment]
i cleaned the commit, the new pull request is now here: https://github.com/openhab/openhab/pull/2197

**Comment by kstaniek** [comment]
I can't make it working with iCloud CalDAV public calendar.
My config is as follows:
caldavio:command:url=https://p05-calendars.icloud.com/published/2/UqYy1tlZ_3JdKFNrukrqMNuTVIkQM8oVQ-aMGtMAT6eA6iO-377sD1K9E_gHQp9TSnsDPFWnCL7nx9NcPpBmDuBNIqv1wJJk3A8GAnaqrDU
caldavio:command:username=
caldavio:command:password=
caldavio:command:reloadInterval=1
caldavio:command:preloadTime=2880
caldavio:command:disableCertificateVerification=true
caldavio:timeZone=Europe/Warsaw

caldavCommand:readCalendars=command

getting exception:
11:18:51.996 [ERROR] [.i.c.internal.CalDavLoaderImpl:662  ] - error while loading calendar entries: Unexpected response
com.github.sardine.impl.SardineException: Unexpected response
	at com.github.sardine.impl.handler.ValidatingResponseHandler.validateResponse(ValidatingResponseHandler.java:48) ~[na:na]
	at com.github.sardine.impl.handler.MultiStatusResponseHandler.handleResponse(MultiStatusResponseHandler.java:40) ~[na:na]
	at com.github.sardine.impl.handler.MultiStatusResponseHandler.handleResponse(MultiStatusResponseHandler.java:35) ~[na:na]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:218) ~[na:na]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:160) ~[na:na]
	at com.github.sardine.impl.SardineImpl.execute(SardineImpl.java:828) ~[na:na]
	at com.github.sardine.impl.SardineImpl.list(SardineImpl.java:355) ~[na:na]
	at com.github.sardine.impl.SardineImpl.list(SardineImpl.java:347) ~[na:na]
	at com.github.sardine.impl.SardineImpl.list(SardineImpl.java:324) ~[na:na]
	at org.openhab.io.caldav.internal.CalDavLoaderImpl.loadEvents(CalDavLoaderImpl.java:437) ~[na:na]
	at org.openhab.io.caldav.internal.CalDavLoaderImpl.access$3(CalDavLoaderImpl.java:431) ~[na:na]
	at org.openhab.io.caldav.internal.CalDavLoaderImpl$4.run(CalDavLoaderImpl.java:648) ~[na:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_79]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]

**Comment by querdenker2k** [comment]
You don't have to use credentials?

**Comment by kstaniek** [comment]
No, this is public calendar.

**Comment by querdenker2k** [comment]
This seems not to be a valid calDAV URL. It looks like that iCloud does not provide calDAV URLs.

**Pull request closed without merging**
