### PR TITLE
Z-Wave: Added support for CENTRAL_SCENE

### PR DESCRIPTION
**Pull request by savageautomate**
@cdjackson ,

To support the double tap, triple tap, hold and release notifications from the Homeseer HS-(WS|WD)-100+ dimmers and switches, central scene support is required.  Both a **`scene`** number and **`key`** attribute are provided in the central scene data and these are used to determine which button and action were taken.

There may be a better/more appropriate name for the **`key`** argument.  I don't have access to the Z-Wave documentation to determine the best name for this data value.  I'll be happy to change the naming prior to merge if you can provide a more appropriate name for this field.

This implementation of central scene supports the following item configuration for the HomeSeer switches: 

```

Switch  HS_WS100_SWITCH         "HS_WS100 Switch"  {zwave="2:command=switch_binary,refresh_interval=500"}

//-------------------------------------------------------------------
// SCENE 1 = TOP (UP) BUTTON
//-------------------------------------------------------------------
Switch  HS_WS100_ANY_TAP_UP      "HS_WS100 <UP> Any Tap"      { zwave="2:command=CENTRAL_SCENE,scene=1" }
Switch  HS_WS100_SINGLE_TAP_UP   "HS_WS100 <UP> Single Tap"   { zwave="2:command=CENTRAL_SCENE,scene=1,key=0" }
Switch  HS_WS100_RELEASE_UP      "HS_WS100 <UP> Release"      { zwave="2:command=CENTRAL_SCENE,scene=1,key=1" }
Switch  HS_WS100_HOLD_UP         "HS_WS100 <UP> Hold"         { zwave="2:command=CENTRAL_SCENE,scene=1,key=2" }
Switch  HS_WS100_DOUBLE_TAP_UP   "HS_WS100 <UP> Double Tap"   { zwave="2:command=CENTRAL_SCENE,scene=1,key=3" }
Switch  HS_WS100_TRIPLE_TAP_UP   "HS_WS100 <UP> Triple Tap"   { zwave="2:command=CENTRAL_SCENE,scene=1,key=4" }

//-------------------------------------------------------------------
// SCENE 2 = BOTTOM (DOWN) BUTTON
//-------------------------------------------------------------------
Switch  HS_WS100_ANY_TAP_DOWN    "HS_WS100 <DOWN> Any Tap"    { zwave="2:command=CENTRAL_SCENE,scene=2" }
Switch  HS_WS100_SINGLE_TAP_DOWN "HS_WS100 <DOWN> Single Tap" { zwave="2:command=CENTRAL_SCENE,scene=2,key=0" }
Switch  HS_WS100_RELEASE_DOWN    "HS_WS100 <DOWN> Release"    { zwave="2:command=CENTRAL_SCENE,scene=2,key=1" }
Switch  HS_WS100_HOLD_DOWN       "HS_WS100 <DOWN> Hold"       { zwave="2:command=CENTRAL_SCENE,scene=2,key=2" }
Switch  HS_WS100_DOUBLE_TAP_DOWN "HS_WS100 <DOWN> Double Tap" { zwave="2:command=CENTRAL_SCENE,scene=2,key=3" }
Switch  HS_WS100_TRIPLE_TAP_DOWN "HS_WS100 <DOWN> Triple Tap" { zwave="2:command=CENTRAL_SCENE,scene=2,key=4" }
```

### CODE REVIEW

**Comment by cdjackson** [comment]
Are you using the Eclipse IDE? If so (or even if not) please can you ensure the formatter is applied.

**Comment by savageautomate** [comment]
No I am using IntelliJ.  Is there a specific formatter config/template for OpenHAB or you just want me to use the default built-in formatter settings?   

Thanks!

**Comment by cdjackson** [comment]
Yes - there is a formatter included in the IDE specific for ESH/OH2. I just note that a few things don’t look right - I’m not sure if InteliJ can import the Eclipse definitions?

**Comment by savageautomate** [comment]
OK, I followed the install directions here: http://www.eclipse.org/smarthome/documentation/community/contributing.html 

and loaded the ESH distribution of Eclipse and used it's formatter on the two primary files in this change set.  Let me know if this is correct or if you are expecting something different.  Thanks, Robert

**Pull request merged**
