### PR TITLE
updated greenT to new version + several fixes for browser compabillity

### PR DESCRIPTION
**Pull request by gunthor**
- changed sencha touch to version 2.4.2
- reformatted and fixed app.js
- recompiled css files

### CODE REVIEW

**Comment by gunthor** [comment]
https://groups.google.com/forum/#!topic/openhab/fjtwBlL3vps

**Comment by teichsta** [comment]
Thanks @gunthor! I won't be able to test earlier than end of the month. Would you mind announcing this fix at https://community.openhab.org and try to find other users/tester meanwhile?

**Comment by paulianttila** [comment]
@gunthor: At least app.js and app.min.js on your PR seems to be based on older version than current version on the openhab repository. So app.js seems to miss many improvements which have been implemented since 2014.

**Comment by teichsta** [comment]
any feedback @gunthor?

**Comment by teichsta** [comment]
@gunthor could you please follow-up on @paulianttila comment?

Thanks, Thomas E.-E.

**Comment by teichsta** [comment]
i'd tend to close this PR due to inactivity. Any chance to follow up on this @gunthor?

**Comment by teichsta** [comment]
Closed due to inactivity for now. Please feel free to reopen @gunthor.

**Pull request closed without merging**
