### PR TITLE
Update pairing mechanism of hue binding to be compatible with new firmware

### LINKED ISSUE #3258: Adjust hue binding for hue API whitelist changes
The API of the username whitelist for the hue bridge will change in the coming months: http://www.developers.meethue.com/documentation/important-whitelist-changes

Starting in February 2016, it will probably not be possible anymore to whitelist custom users on the hue bridge. As the current binding implementation uses this functionality, it will be necessary to update the binding before the bridge update is rolled out.

### PR DESCRIPTION
**Pull request by dominicdesu**
Fixes #3258.

Signed-off-by: Dominic Lerbs <dominicdesu@hallojapan.de>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
@teichsta Did you read https://community.openhab.org/t/merging-prs/10008?

**Comment by BradyRosino** [comment]
Was this actually included in 1.8.3? If downloading a fresh copy of the runtime from the website it does not have the new verbiage in the openhab_default.cfg file.

I ask because I am unable to successfully pair a new v1 hue hub with the latest firmware. OpenHAB sees the bridge and does the count down, but does not respond to pressing the connect button on the bridge.

**Comment by 9037568** [comment]
The [Release Notes](https://github.com/openhab/openhab/wiki/Release-Notes-1.8) for 1.8.3 don't appear to include any reference to this.

**Comment by BradyRosino** [comment]
The release notes list this under enhancements, not bug fixes. I missed it my first glance as well 😀

While it is listed in the release notes, I still don't see it in the actual release.

**Comment by 9037568** [comment]
Do you see any of these new log messages in the openhab.log?

````
No secret configured or secret rejected by bridge. Starting pairing with bridge.

########################################
# Hue bridge successfully paired!
# Please set the following secret in your openhab.cfg (and restart openHAB):
# [username]
########################################

Could not read Settings-Json from Hue Bridge.
````

**Comment by watou** [comment]
It looks like be5a04e69c4c6d640ef21dff5114210f120bb102 was not cherry picked onto the 1.8 branch, and so this PR was only applied to the master branch.  Unless I'm wrong, the milestone should be changed to either 1.8.4 or 1.9, and the 1.8.3 release notes should remove the reference to this PR.  Let's wait for @teichsta before making those changes.  In the meantime, could you try the 1.9.0-SNAPSHOT binding [here](https://openhab.ci.cloudbees.com/job/openHAB1-Addons/lastSuccessfulBuild/artifact/bundles/binding/org.openhab.binding.hue/target/org.openhab.binding.hue-1.9.0-SNAPSHOT.jar)?

**Comment by BradyRosino** [comment]
The 1.9.0 snapshot worked perfect.

**Comment by knockreff** [comment]
The 1.90 snapshot gets me closer as i'm now coming up with the successfully paired message and a a request to update the secret.  However after typing this mess in and restarting, openhab requests that a new secret be typed in again.

**Comment by dasmaeh** [comment]
The 1.9.0 snapshot is giving me an error on an up to date raspbian:
```
Jun 18 12:56:27 ha openhab.sh[23615]: 2016-06-18 12:56:27.595 [WARN ] [.h.internal.hardware.HueBridge] - Failed to connect to Hue bridge: HTTP request timed out.
Jun 18 12:56:27 ha openhab.sh[23615]: 2016-06-18 12:56:27.601 [INFO ] [inding.hue.internal.HueBinding] - No secret configured or secret rejected by bridge. Starting pairing with bridge.
Jun 18 12:56:27 ha openhab.sh[23615]: 2016-06-18 12:56:27.610 [INFO ] [.h.internal.hardware.HueBridge] - Please press the connect button on the Hue bridge. Waiting for pairing for 100 seconds...
Jun 18 12:56:27 ha openhab.sh[23615]: 2016-06-18 12:56:27.617 [INFO ] [.service.AbstractActiveService] - Hue Refresh Service has been started
Jun 18 12:56:32 ha openhab.sh[23615]: Exception in thread "Thread-27" com.sun.jersey.api.client.ClientHandlerException: java.net.SocketTimeoutException: connect timed out
Jun 18 12:56:32 ha openhab.sh[23615]: at com.sun.jersey.client.urlconnection.URLConnectionClientHandler.handle(URLConnectionClientHandler.java:155)
Jun 18 12:56:32 ha openhab.sh[23615]: at com.sun.jersey.api.client.Client.handle(Client.java:652)
Jun 18 12:56:32 ha openhab.sh[23615]: at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682)
Jun 18 12:56:32 ha openhab.sh[23615]: at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
Jun 18 12:56:32 ha openhab.sh[23615]: at com.sun.jersey.api.client.WebResource$Builder.post(WebResource.java:570)
Jun 18 12:56:32 ha openhab.sh[23615]: at org.openhab.binding.hue.internal.hardware.HueBridge.pingForPairing(HueBridge.java:113)
Jun 18 12:56:32 ha openhab.sh[23615]: at org.openhab.binding.hue.internal.hardware.HueBridge.access$0(HueBridge.java:102)
Jun 18 12:56:32 ha openhab.sh[23615]: at org.openhab.binding.hue.internal.hardware.HueBridge$BridgePairingProcessor.run(HueBridge.java:209)
Jun 18 12:56:32 ha openhab.sh[23615]: at java.lang.Thread.run(Thread.java:745)
Jun 18 12:56:32 ha openhab.sh[23615]: Caused by: java.net.SocketTimeoutException: connect timed out
Jun 18 12:56:32 ha openhab.sh[23615]: at java.net.PlainSocketImpl.socketConnect(Native Method)
Jun 18 12:56:32 ha openhab.sh[23615]: at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
Jun 18 12:56:32 ha openhab.sh[23615]: at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
Jun 18 12:56:32 ha openhab.sh[23615]: at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
Jun 18 12:56:32 ha openhab.sh[23615]: at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
Jun 18 12:56:32 ha openhab.sh[23615]: at java.net.Socket.connect(Socket.java:579)
Jun 18 12:56:32 ha openhab.sh[23615]: at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
Jun 18 12:56:32 ha openhab.sh[23615]: at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
Jun 18 12:56:32 ha openhab.sh[23615]: at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
Jun 18 12:56:32 ha openhab.sh[23615]: at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
Jun 18 12:56:32 ha openhab.sh[23615]: at sun.net.www.http.HttpClient.New(HttpClient.java:308)
Jun 18 12:56:32 ha openhab.sh[23615]: at sun.net.www.http.HttpClient.New(HttpClient.java:326)
Jun 18 12:56:32 ha openhab.sh[23615]: at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:998)
Jun 18 12:56:32 ha openhab.sh[23615]: at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:934)
Jun 18 12:56:32 ha openhab.sh[23615]: at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:852)
Jun 18 12:56:32 ha openhab.sh[23615]: at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1093)
Jun 18 12:56:32 ha openhab.sh[23615]: at com.sun.jersey.client.urlconnection.URLConnectionClientHandler$1$1.getOutputStream(URLConnectionClientHandler.java:238)
Jun 18 12:56:32 ha openhab.sh[23615]: at com.sun.jersey.api.client.CommittingOutputStream.commitStream(CommittingOutputStream.java:117)
Jun 18 12:56:32 ha openhab.sh[23615]: at com.sun.jersey.api.client.CommittingOutputStream.write(CommittingOutputStream.java:89)
Jun 18 12:56:32 ha openhab.sh[23615]: at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
Jun 18 12:56:32 ha openhab.sh[23615]: at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
Jun 18 12:56:32 ha openhab.sh[23615]: at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
Jun 18 12:56:32 ha openhab.sh[23615]: at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
Jun 18 12:56:32 ha openhab.sh[23615]: at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
Jun 18 12:56:32 ha openhab.sh[23615]: at java.io.BufferedWriter.flush(BufferedWriter.java:254)
Jun 18 12:56:32 ha openhab.sh[23615]: at com.sun.jersey.core.util.ReaderWriter.writeToAsString(ReaderWriter.java:191)
Jun 18 12:56:32 ha openhab.sh[23615]: at com.sun.jersey.core.provider.AbstractMessageReaderWriterProvider.writeToAsString(AbstractMessageReaderWriterProvider.java:128)
Jun 18 12:56:32 ha openhab.sh[23615]: at com.sun.jersey.core.impl.provider.entity.StringProvider.writeTo(StringProvider.java:88)
Jun 18 12:56:32 ha openhab.sh[23615]: at com.sun.jersey.core.impl.provider.entity.StringProvider.writeTo(StringProvider.java:58)
Jun 18 12:56:32 ha openhab.sh[23615]: at com.sun.jersey.api.client.RequestWriter.writeRequestEntity(RequestWriter.java:300)
Jun 18 12:56:32 ha openhab.sh[23615]: at com.sun.jersey.client.urlconnection.URLConnectionClientHandler._invoke(URLConnectionClientHandler.java:217)
Jun 18 12:56:32 ha openhab.sh[23615]: at com.sun.jersey.client.urlconnection.URLConnectionClientHandler.handle(URLConnectionClientHandler.java:153)
Jun 18 12:56:32 ha openhab.sh[23615]: ... 8 more
```

**Comment by dominicdesu** [comment]
@dasmaeh the binding currently does not handle the ClientHandlerException when the connection attempt to the bridge times out, therefore the pairing thread terminates. This should be fixed in the binding.
However, you still have the problem that the bridge cannot be reached. Can you check that you can ping the bridge from the device where openHAB is running?

**Comment by dasmaeh** [comment]
Thanks for the hint. There indeed was a networking problem.
Works like a charm now.

**Comment by peacepenguin** [comment]
For anyone running STABLE version 1.8.3 and having this problem, here is a quick workaround to get things paired up with a Gen1 Hue with latest firmware (Dec. 10, 2016) 

https://github.com/openhab/openhab/wiki/Hue-Binding#pairing-the-philips-hue-bridge

**Pull request merged**
