### PR TITLE
Comfoair: EWT bugfixes / enhancements

### PR DESCRIPTION
**Pull request by joltcoke**
- Fix EWT low/high temperature values
- Add EWT active state
- Minor typos fixed

### CODE REVIEW

**Comment by teichsta** [comment]
@HolgerHees could you please have a look at this fix? Can you confirm this as a Bug/Fix? Thanks, Thomas E.-E.

**Comment by HolgerHees** [comment]
I can't really test it because I does not own a EWT device.

But it is confusing me that the EWT_TEMPERATUR is interpreted as a temperature value and the EWT_TEMPERATUR_LOW and EWT_TEMPERATUR_HIGH as a number value.

based on the protocol description (not a official one)

http://www.see-solutions.de/sonstiges/Protokollbeschreibung_ComfoAir.pdf

all 3 values should be a temperature value.

@joltcoke which zehnder device are you using?

**Comment by joltcoke** [comment]
@teichsta If you're looking at a strictly bug fix only release, then feel free to cherry pick just changeset 37995fe.

@HolgerHees I'm having a CA350 Luxe + Comfofond-L Eco + Ease CC (disconnected). The change fixes two problems, index Low / High swapped and no (temp + 20) * 2 magic applied. For the latter please refer to the spec you've linked. None of the temperatures in reply 0xEC have an asterisk attached - no conversion necessary. The range for low temp is 0 - 15 with +1/-1 increments, thats why they send raw values.

**Comment by HolgerHees** [comment]
@joltcoke you are right :-) thanks for fixing!

@teichsta the other changeset a8ab09c is not a bugfix, but it does not affect any other areas.

i'm fine with the whole commit.

**Pull request merged**
