### PR TITLE
Siemens HVAC binding

### PR DESCRIPTION
**Pull request by lo92fr**
This pullrequest add a new binding for siemens OZW672 web gateway.
This gateway enable to connect openhab to a siemens RVS41.813/327 controler that is used by many Heat pump or boiler system.

https://community.openhab.org/t/new-biding-addon-for-siemens-hvac-controller-ozw672-01/6359

### CODE REVIEW

**Comment by engycz** [comment]
Hello. Why is this pull request deleted? Is there any other binding in openhab for siemens HVAC?

**Comment by lo92fr** [comment]
Hello Everybody,


Sorry for my delayed response.
The pull request was deleted by me because I was not very happy with 
first version of the binding.
I'm working on a new version that will be able to autodiscover 
parameters for the OZW672.
This version would also be easier to config as you won't have to 
indicate datapoint type, and that you can refer to datapoint using the 
datapoint index as in the first version, but also using the menu index, 
or the symbolic datapoint name.

I also work on a full openhab 2.0 compliant version, but this one is not 
ready for no.

Attach you will find the jar for this new version. It was compiled on 
openhab-2.0, but I test it with openhab 1.8.3 and it works as well.
Fill free to test it if you want, and to give your feedback.

I hope I will be able to create another pull request in a few days for this.

Regards,

     Laurent.


================================================================================================================================================================

*Technical background*


*1. Put the jar file inside your addons directory.*

*2. As in first version, you will need to give global configuration 
directives in your openhab.cfg *

siemenshvac:baseUrl=http://192.168.254.53/
siemenshvac:userName=Administrator
siemenshvac:userPassword=MyPassword
siemenshvac:refresh=10000

refresh is how often binding will pool the Ozw672 to refresh datapoint 
value (given in ms). In this exemple, it will be every 10s.


*3. Items can be defind using one of the three syntax below.*

dptMenuId is the Id you will find in Web Interface at the start of the line.

dptName is the name of the entry.

dptId is the index of the entry use internally by Ozw672. I wouldn't 
recommands using it as dptId is changing each time you update the 
firmware of the Ozw672.

4. *Write your sitemap as usual*

For multiple selection items, you will need to give a mappings value.
You can look into cache file below to know good value.

                 Setpoint item=Temperature_Consigne_C label="Consigne 
confort [%.1f °C]" step=0.5 minValue=0 maxValue=30

                 Selection item=Chauffage_Mode 
mappings=["1:Automatique"="Automatique", "3:Confort"="Confort", 
"2:Réduit"="Réduit", "0:Mode Protection"="Mode Protection"]*
*

*5. First Start and Cache File*

On first start, binding will scan all datapoint of Ozw672 to construct a 
cache file of datapoint meta data.
So first start will be a litlle slower, and it could take more then one 
minutes to have first data.

The cache file will be write under your configurations directory in the 
file configurations/siemens.json.
This file will be update on regular basics as openhab is running.
You can delete this file if something goes wrong, and it will be rewrite 
at the next start of openhab

*6. Full sample configs *

*_Default.items_**_
_*

String                  Chauffage_Mode                "Mode [%s]"     
                         <temperature> (gChauffage, Temperature)     { 
siemenshvac = "dptMenuId:700;"    }
Number                             Temperature_Consigne_C      "Consigne 
confort [%.1f °C]" <temperature>        (gChauffage, Temperature)     { 
siemenshvac = "dptMenuId:710;"    }
Number                             Temperature_Consigne_R      "Consigne 
réduit [%.1f °C]" <temperature>        (gChauffage, Temperature)     { 
siemenshvac = "dptMenuId:712;"    }
Number                             Temperature_Consigne_H      "Consigne 
hg [%.1f °C]" <temperature>        (gChauffage, Temperature)     { 
siemenshvac = "dptMenuId:714;"    }
Number                             Temperature_Confort_Max      "Confort 
maximum [%.1f °C]" <temperature>        (gChauffage, Temperature)     { 
siemenshvac = "dptMenuId:716;"    }
Number                             Chaudiere_Pente      "Pente de la 
courbe [%.1f °C]" <temperature>        (gChauffage, Temperature)     { 
siemenshvac = "dptMenuId:720;"    }

Number                             Temperature_ECS_Confort     "Consigne 
ECS Confort [%.1f °C]" <temperature>        (gChauffage, Temperature) 
     { siemenshvac = "dptMenuId:1610;"            }
Number                             Temperature_ECS_Reduit "Consigne ECS 
Réduit [%.1f °C]" <temperature>        (gChauffage, Temperature)     { 
siemenshvac = "dptMenuId:1612;"            }



Number                             Temperature_Consigne_Pompe     
"Consigne Pompe [%.1f °C]" <temperature>        (gChauffage, 
Temperature)     { siemenshvac = "dptMenuId:8411;"            }
Number                             Temperature_Depart_Pompe "Départ 
Pompe [%.1f °C]"                <temperature>     (gChauffage, 
Temperature)     { siemenshvac = "dptMenuId:8412;"            }
Number                             Modulation_Pompe "Modulation Pompe 
[%d %]"                <temperature>     (gChauffage, Temperature)     { 
siemenshvac = "dptMenuId:8413;"            }
Number                             Duree_blocage_Pompe     "Durrée de 
blocage pompe [%.1f heures]" <temperature>        (gChauffage, 
Temperature)     { siemenshvac = "dptMenuId:8454;"            }



Number                             Temperature_Exterieure_Ch "Exterieure 
(Ch) [%.1f °C]" <temperature>        (gChauffage, Temperature)     { 
siemenshvac = "dptMenuId:8700;"            }
Number                             Temperature_Exterieure_Min 
"Exterieure (Min) [%.1f °C]"            <temperature>     (gChauffage, 
Temperature)     { siemenshvac = "dptMenuId:8701;"               }
Number                             Temperature_Exterieure_Max 
"Exterieure (Max) [%.1f °C]"            <temperature>     (gChauffage, 
Temperature)     { siemenshvac = "dptMenuId:8702;"               }
Number                             Temperature_Thermostat "Température 
termostat [%.1f °C]"        <temperature>     (gChauffage, Temperature) 
     { siemenshvac = "dptMenuId:8740;"            }
String                             Chaudiere_Etat_Pompe_ECS "Etat Pompe 
ECS [%s]"                    <temperature>     (gChauffage, Temperature) 
     { siemenshvac = "dptMenuId:8820;"             }
String                             Chaudiere_Etat_ECS "Etat ECS [%s]" 
<temperature>        (gChauffage, Temperature)     { siemenshvac = 
"dptMenuId:1600;"             }


Number                             Temperature_Depart_Reel "Départ réel 
[%.1f °C]" <temperature>        (gChauffage, Temperature)     { 
siemenshvac = "dptMenuId:8743;"            }
Number Temperature_Depart_Consigne    "Départ consigne [%.1f °C]"     
         <temperature>        (gChauffage, Temperature)     { 
siemenshvac = "dptMenuId:8744;"            }

Number                             Heure_fct_ECS "Heure Fonctionnement 
ECS [%.1f heures]" <temperature>     (gChauffage, Temperature)     { 
siemenshvac = "dptMenuId:8840;"            }
Number                             Nb_Demarrage_ECS "Nbr démarrage ECS 
[%.1f]"                <temperature>     (gChauffage, Temperature)     { 
siemenshvac = "dptMenuId:8841;"            }

String                             Chaudiere_Etat_Pompe "Etat Pompe 
[%s]"                        <temperature>     (gChauffage, Temperature) 
     { siemenshvac = "dptMenuId:8730;"             }

String                             Chaudiere_Etat_Circuit_Ch "Etat 
Circuit Chauffe [%s]" <temperature>        (gChauffage, Temperature)     
{ siemenshvac = "dptMenuId:8000;"             }
String                             Chaudiere_Etat_Chaudiere "Etat 
Chaudiere [%s]"                    <temperature>     (gChauffage, 
Temperature)     { siemenshvac = "dptMenuId:8022;"             }
String                             Chaudiere_Etat_Pompe_Ch     "Etat 
Pompe à chaleur [%s]" <temperature>        (gChauffage, Temperature)     
{ siemenshvac = "dptMenuId:8006;"             }
String Chaudiere_Etat_Pompe_Chauff    "Etat Pompe circuit chauffage 
[%s]"        <temperature>        (gChauffage, Temperature)     { 
siemenshvac = "dptMenuId:8730;"             }
String                             Chaudiere_Etat_Dem_Chaleur "Etat 
demande chaleur [%s]" <temperature>        (gChauffage, Temperature)     
{ siemenshvac = "dptId:2192;"             }

_*Default.sitemaps*_

sitemap default label="Main Menu"    {



     Frame label="Test" {

                 Setpoint item=Temperature_Consigne_C label="Consigne 
confort [%.1f °C]" step=0.5 minValue=0 maxValue=30
                 Setpoint item=Temperature_Consigne_R label="Consigne 
réduit [%.1f °C]" step=0.5 minValue=0 maxValue=30
                 Setpoint item=Temperature_Consigne_H label="Consigne HG 
[%.1f °C]" step=0.5 minValue=0 maxValue=30

                 Selection item=Chauffage_Mode 
mappings=["1:Automatique"="Automatique", "3:Confort"="Confort", 
"2:Réduit"="Réduit", "0:Mode Protection"="Mode Protection"]

             }

     Frame label="ECS" {
         Text item=Chaudiere_Etat_Pompe_ECS label="Etat Pompe ECS [%s]"
         Text item=Heure_fct_ECS label="Heure Fonctionnement ECS [%.1f 
heures]"
         Text item=Nb_Demarrage_ECS label="Nbr démarrage ECS [%.1f]"
         Text item=Temperature_ECS_Confort label="Consigne ECS Confort 
[%.1f °C]"
         Text item=Temperature_ECS_Reduit label="Consigne ECS Réduit 
[%.1f °C]"
         Text item=Chaudiere_Etat_ECS label="Etat ECS [%s]"
     }


     Frame label="Pompe" {
         Text item=Chaudiere_Etat_Pompe label="Etat Pompe [%s]"
         Text item=Temperature_Consigne_Pompe label="Consigne pompe 
[%.1f °C]"
         Text item=Temperature_Depart_Pompe label="Départ pompe [%.1f °C]"
         Text item=Modulation_Pompe label="Modulation pompe [%d]"

         Text item=Chaudiere_Etat_Pompe_Ch label="Etat Pompe à chaleur [%s]"
         Text item=Duree_blocage_Pompe label="Durrée de blocage pompe 
[%.1f heures]"

         Text item=Chaudiere_Pente label="Pente de la courbe [%.1f]"
     }

     Frame label="Circuit" {
         Text item=Temperature_Depart_Consigne label="Départ consigne 
[%.1f °C]"
         Text item=Temperature_Depart_Reel label="Départ réel [%.1f °C]"
         Text item=Chaudiere_Etat_Pompe_Chauff label="Etat Pompe circuit 
chauffage [%s]"
         Text item=Chaudiere_Etat_Circuit_Ch label="Etat circuit 
chauffage [%s]"
         Text item=Chaudiere_Etat_Dem_Chaleur label="Etat demande 
chaleur [%s]"
     }

     Frame label="Chaudiere" {
         Text item=Chaudiere_Etat_Chaudiere label="Etat Chaudiere [%s]"
     }

}

**Comment by lo92fr** [comment]
Hello Everybody,


Sorry for my delayed response.
The pull request was deleted by me because I was not very happy with 
first version of the binding.
I'm working on a new version that will be able to autodiscover 
parameters for the OZW672.
This version would also be easier to config as you won't have to 
indicate datapoint type, and that you can refer to datapoint using the 
datapoint index as in the first version, but also using the menu index, 
or the symbolic datapoint name.

I also work on a full openhab 2.0 compliant version, but this one is not 
ready for no.

Attach you will find the jar for this new version. It was compiled on 
openhab-2.0, but I test it with openhab 1.8.3 and it works as well.
Fill free to test it if you want, and to give your feedback.

I hope I will be able to create another pull request in a few days for this.

Regards,

     Laurent.


================================================================================================================================================================

*Technical background*


*1. Put the jar file inside your addons directory.*

*2. As in first version, you will need to give global configuration 
directives in your openhab.cfg *

siemenshvac:baseUrl=http://192.168.254.53/
siemenshvac:userName=Administrator
siemenshvac:userPassword=MyPassword
siemenshvac:refresh=10000

refresh is how often binding will pool the Ozw672 to refresh datapoint 
value (given in ms). In this exemple, it will be every 10s.


*3. Items can be defind using one of the three syntax below.*

dptMenuId is the Id you will find in Web Interface at the start of the line.

dptName is the name of the entry.

dptId is the index of the entry use internally by Ozw672. I wouldn't 
recommands using it as dptId is changing each time you update the 
firmware of the Ozw672.

4. *Write your sitemap as usual*

For multiple selection items, you will need to give a mappings value.
You can look into cache file below to know good value.

                 Setpoint item=Temperature_Consigne_C label="Consigne 
confort [%.1f °C]" step=0.5 minValue=0 maxValue=30

                 Selection item=Chauffage_Mode 
mappings=["1:Automatique"="Automatique", "3:Confort"="Confort", 
"2:Réduit"="Réduit", "0:Mode Protection"="Mode Protection"]*
*

*5. First Start and Cache File*

On first start, binding will scan all datapoint of Ozw672 to construct a 
cache file of datapoint meta data.
So first start will be a litlle slower, and it could take more then one 
minutes to have first data.

The cache file will be write under your configurations directory in the 
file configurations/siemens.json.
This file will be update on regular basics as openhab is running.
You can delete this file if something goes wrong, and it will be rewrite 
at the next start of openhab

*6. Full sample configs *

*_Default.items_**_
_*

String                  Chauffage_Mode                "Mode [%s]"     
                         <temperature> (gChauffage, Temperature)     { 
siemenshvac = "dptMenuId:700;"    }
Number                             Temperature_Consigne_C      "Consigne 
confort [%.1f °C]" <temperature>        (gChauffage, Temperature)     { 
siemenshvac = "dptMenuId:710;"    }
Number                             Temperature_Consigne_R      "Consigne 
réduit [%.1f °C]" <temperature>        (gChauffage, Temperature)     { 
siemenshvac = "dptMenuId:712;"    }
Number                             Temperature_Consigne_H      "Consigne 
hg [%.1f °C]" <temperature>        (gChauffage, Temperature)     { 
siemenshvac = "dptMenuId:714;"    }
Number                             Temperature_Confort_Max      "Confort 
maximum [%.1f °C]" <temperature>        (gChauffage, Temperature)     { 
siemenshvac = "dptMenuId:716;"    }
Number                             Chaudiere_Pente      "Pente de la 
courbe [%.1f °C]" <temperature>        (gChauffage, Temperature)     { 
siemenshvac = "dptMenuId:720;"    }

Number                             Temperature_ECS_Confort     "Consigne 
ECS Confort [%.1f °C]" <temperature>        (gChauffage, Temperature) 
     { siemenshvac = "dptMenuId:1610;"            }
Number                             Temperature_ECS_Reduit     "Consigne 
ECS Réduit [%.1f °C]" <temperature>        (gChauffage, Temperature)     
{ siemenshvac = "dptMenuId:1612;"            }



Number                             Temperature_Consigne_Pompe     
"Consigne Pompe [%.1f °C]" <temperature>        (gChauffage, 
Temperature)     { siemenshvac = "dptMenuId:8411;"            }
Number                             Temperature_Depart_Pompe     "Départ 
Pompe [%.1f °C]" <temperature>        (gChauffage, Temperature)     { 
siemenshvac = "dptMenuId:8412;"            }
Number                             Modulation_Pompe     "Modulation 
Pompe [%d %]" <temperature>        (gChauffage, Temperature)     { 
siemenshvac = "dptMenuId:8413;"            }
Number                             Duree_blocage_Pompe     "Durrée de 
blocage pompe [%.1f heures]" <temperature>        (gChauffage, 
Temperature)     { siemenshvac = "dptMenuId:8454;"            }



Number Temperature_Exterieure_Ch    "Exterieure (Ch) [%.1f °C]"         
     <temperature>        (gChauffage, Temperature)     { siemenshvac = 
"dptMenuId:8700;" }
Number Temperature_Exterieure_Min    "Exterieure (Min) [%.1f °C]"     
     <temperature>        (gChauffage, Temperature)     { siemenshvac = 
"dptMenuId:8701;"               }
Number Temperature_Exterieure_Max    "Exterieure (Max) [%.1f °C]"     
     <temperature>        (gChauffage, Temperature)     { siemenshvac = 
"dptMenuId:8702;"               }
Number                             Temperature_Thermostat     
"Température termostat [%.1f °C]" <temperature>        (gChauffage, 
Temperature)     { siemenshvac = "dptMenuId:8740;"            }
String                             Chaudiere_Etat_Pompe_ECS "Etat Pompe 
ECS [%s]" <temperature>        (gChauffage, Temperature)     { 
siemenshvac = "dptMenuId:8820;"             }
String                             Chaudiere_Etat_ECS     "Etat ECS 
[%s]" <temperature>        (gChauffage, Temperature)     { siemenshvac = 
"dptMenuId:1600;"             }


Number                             Temperature_Depart_Reel "Départ réel 
[%.1f °C]" <temperature>        (gChauffage, Temperature)     { 
siemenshvac = "dptMenuId:8743;"            }
Number Temperature_Depart_Consigne    "Départ consigne [%.1f °C]"     
         <temperature>        (gChauffage, Temperature)     { 
siemenshvac = "dptMenuId:8744;" }

Number                             Heure_fct_ECS     "Heure 
Fonctionnement ECS [%.1f heures]" <temperature>        (gChauffage, 
Temperature)     { siemenshvac = "dptMenuId:8840;"            }
Number                             Nb_Demarrage_ECS "Nbr démarrage ECS 
[%.1f]" <temperature>        (gChauffage, Temperature)     { siemenshvac 
= "dptMenuId:8841;"            }

String                             Chaudiere_Etat_Pompe      "Etat Pompe 
[%s]" <temperature>        (gChauffage, Temperature)     { siemenshvac = 
"dptMenuId:8730;"             }

String Chaudiere_Etat_Circuit_Ch    "Etat Circuit Chauffe [%s]"         
     <temperature>        (gChauffage, Temperature)     { siemenshvac = 
"dptMenuId:8000;" }
String                             Chaudiere_Etat_Chaudiere "Etat 
Chaudiere [%s]" <temperature>        (gChauffage, Temperature)     { 
siemenshvac = "dptMenuId:8022;"             }
String                             Chaudiere_Etat_Pompe_Ch     "Etat 
Pompe à chaleur [%s]" <temperature>        (gChauffage, Temperature)     
{ siemenshvac = "dptMenuId:8006;"             }
String Chaudiere_Etat_Pompe_Chauff    "Etat Pompe circuit chauffage 
[%s]"        <temperature>        (gChauffage, Temperature)     { 
siemenshvac = "dptMenuId:8730;" }
String Chaudiere_Etat_Dem_Chaleur    "Etat demande chaleur [%s]"         
     <temperature>        (gChauffage, Temperature)     { siemenshvac = 
"dptId:2192;"             }

_*Default.sitemaps*_

sitemap default label="Main Menu"    {



     Frame label="Test" {

                 Setpoint item=Temperature_Consigne_C label="Consigne 
confort [%.1f °C]" step=0.5 minValue=0 maxValue=30
                 Setpoint item=Temperature_Consigne_R label="Consigne 
réduit [%.1f °C]" step=0.5 minValue=0 maxValue=30
                 Setpoint item=Temperature_Consigne_H label="Consigne HG 
[%.1f °C]" step=0.5 minValue=0 maxValue=30

                 Selection item=Chauffage_Mode 
mappings=["1:Automatique"="Automatique", "3:Confort"="Confort", 
"2:Réduit"="Réduit", "0:Mode Protection"="Mode Protection"]

             }

     Frame label="ECS" {
         Text item=Chaudiere_Etat_Pompe_ECS label="Etat Pompe ECS [%s]"
         Text item=Heure_fct_ECS label="Heure Fonctionnement ECS [%.1f 
heures]"
         Text item=Nb_Demarrage_ECS label="Nbr démarrage ECS [%.1f]"
         Text item=Temperature_ECS_Confort label="Consigne ECS Confort 
[%.1f °C]"
         Text item=Temperature_ECS_Reduit label="Consigne ECS Réduit 
[%.1f °C]"
         Text item=Chaudiere_Etat_ECS label="Etat ECS [%s]"
     }


     Frame label="Pompe" {
         Text item=Chaudiere_Etat_Pompe label="Etat Pompe [%s]"
         Text item=Temperature_Consigne_Pompe label="Consigne pompe 
[%.1f °C]"
         Text item=Temperature_Depart_Pompe label="Départ pompe [%.1f °C]"
         Text item=Modulation_Pompe label="Modulation pompe [%d]"

         Text item=Chaudiere_Etat_Pompe_Ch label="Etat Pompe à chaleur [%s]"
         Text item=Duree_blocage_Pompe label="Durrée de blocage pompe 
[%.1f heures]"

         Text item=Chaudiere_Pente label="Pente de la courbe [%.1f]"
     }

     Frame label="Circuit" {
         Text item=Temperature_Depart_Consigne label="Départ consigne 
[%.1f °C]"
         Text item=Temperature_Depart_Reel label="Départ réel [%.1f °C]"
         Text item=Chaudiere_Etat_Pompe_Chauff label="Etat Pompe circuit 
chauffage [%s]"
         Text item=Chaudiere_Etat_Circuit_Ch label="Etat circuit 
chauffage [%s]"
         Text item=Chaudiere_Etat_Dem_Chaleur label="Etat demande 
chaleur [%s]"
     }

     Frame label="Chaudiere" {
         Text item=Chaudiere_Etat_Chaudiere label="Etat Chaudiere [%s]"
     }

}

**Comment by engycz** [comment]
For everyone who is interested in OZW672 internals, I have connected a serial terminal and found some interesting things.
WebApi test page http://<ipaddr>/main.app?section=webapi
Diagnostics page http://<ipaddr>/main.app?section=diagnostics
but this needs a special password (I know how to construct it) [https://snag.gy/gtBau8.jpg](url)

Now I have also a ssh connection to my OZW672.

**Comment by lo92fr** [comment]
Hello,


Very interesting, never find this pages before.
I'm already manage to enable SSH server on OZW, but never success to 
login because don't find the correct SSH key.

Can you explain how you manager to find the password for diagnostics pages ?


Regards,

       Laurent.

**Comment by engycz** [comment]
You must add your own public key to /home/root/.ssh/authorized_keys

https://snag.gy/e6BFZk.jpg

**Comment by lo92fr** [comment]
Hello Jiri,


Thks for the last screenshoot. I give it a try, and it's work ok.
For ssh, already think to update the authorized_keys, but I would need 
to create a new firmware for this ?

Or did you find another way to upload the file to the server.


Laurent.

**Comment by engycz** [comment]
I connected TTL 3.3V <--> RS232 USB converter to pins in the bottom of PCB. Then I change temporary init cmd of linux to /bin/sh in uBoot (BootLoader). Mounted /proc, remounted / as rw and changed authorized_keys.

**Pull request closed without merging**
