### PR TITLE
Update nrjavaserial version to 3.9.3

### PR DESCRIPTION
**Pull request by faurel**
nrjavaserial has been updated to latest version to support ARM platforms.
This update fixes crash of OH on synology DS212j for instance.

### CODE REVIEW

**Comment by teichsta** [comment]
Fixes #2271

**Comment by cdjackson** [comment]
Has anyone checked if this actually works? The zwave binding no long compiles as the exports are no longer available apparently. I've not looked at this at all - just found a load of errors!

**Comment by cdjackson** [comment]
I suspect that the classpath for all bundles using the serial driver might need updating...

**Comment by faurel** [comment]
Hi Chris,
You're right. All components using this lib need to update their classpath. My mistake, I haven't rebuild all the project. I'll update all dependencies and send a new PR.

**Comment by paulianttila** [comment]
Hi,

I'm not sure if classpath is the problem. Official nrjavaserial is build
via ant and it not seems to be a valid OSGi bundle. I have had serial port
stability issues a while in os x and week a go I recognized that
nrjavaserial 3.9.3 have rebuilded os x native libraries. I wasn't able to
get official 3.9.3 version to work. I rebuild nrjavaserial via maven and it
started to work. I rebuild org.openhab.io.transport.serial and replaced
official one without modified any bindings and all binding which need
nrjavaserial works fine (rfxcom and epson projector bindings on my case). I
don't know yet does 3.9.3 solve my stability problem but binding are worked
few days fine now. 3.8.8 worked several days fine as well, but then
suddenly jammed in nativeDrain C function call.

-Pali


2015-03-18 0:11 GMT+02:00 faurel <notifications@github.com>:

**Comment by kgoderis** [comment]
Does it solve by any chance the lock file issue on Mac OS X ? 

Karel

**Comment by faurel** [comment]
I have rebuild once again my project after syncing with master branch and I successfully compiled all modules. I also reviewed the nightly build and the update of nrjavaserial didn't break  it.

**Comment by watou** [comment]
I can do an `mvn clean install` from the command line successfully, but I can't get Eclipse to recognize the presence of the 3.9.3 jar file, so all dependent projects fail to build in Eclipse.  No amount of cleaning and refreshing in Eclipse seems to clear up the problem.

**Comment by faurel** [comment]
You're right, I've just figured this out. Building with maven works but fails with eclipse. The .classpath files need to be updated to reflect the change of lib version.

**Comment by cdjackson** [comment]
In eclipse, you can right click on the project, then select something like 'library path' or something - it's about half way down. Then update the library in the dialog box. I'm not sure if there's a more systematic way of doing it, but I did get this working last night...

**Comment by teichsta** [comment]
will fix that soon … sorry for the inconvenience!

**Comment by paulianttila** [comment]
Damn, 3.9.3 doesn't solve OS X stability problem :( Epson projector binding is jammed last night to nrjavaserial native call.

gnu.io.RXTXPort.nativeDrain(Native Method)
gnu.io.RXTXPort$SerialOutputStream.flush(RXTXPort.java:1240)
org.openhab.binding.epsonprojector.connector.EpsonProjectorSerialConnector.sendMessage(EpsonProjectorSerialConnector.java:131)
org.openhab.binding.epsonprojector.internal.EpsonProjectorDevice.sendQuery(EpsonProjectorDevice.java:341)
org.openhab.binding.epsonprojector.internal.EpsonProjectorDevice.queryInt(EpsonProjectorDevice.java:370)
org.openhab.binding.epsonprojector.internal.EpsonProjectorDevice.queryInt(EpsonProjectorDevice.java:394)
org.openhab.binding.epsonprojector.internal.EpsonProjectorDevice.getPowerStatus(EpsonProjectorDevice.java:423)
org.openhab.binding.epsonprojector.internal.EpsonProjectorBinding.queryDataFromDevice(EpsonProjectorBinding.java:286)
org.openhab.binding.epsonprojector.internal.EpsonProjectorBinding.execute(EpsonProjectorBinding.java:150)
org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:156)
org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:173)

**Comment by teichsta** [comment]
see https://github.com/openhab/openhab/pull/2321 …

Thanks for your patience!

Thomas E.-E.

**Comment by paulianttila** [comment]
@teichsta: classpath fix does not make sense. Bindings should not have nrjavaserial directly on the class path. That's why we have separated bundle org.openhab.io.serial.transport which export gnu.io and we can change nrjavaserial without modifying any other bindings.

**Comment by teichsta** [comment]
Hi @paulianttila, the change in the .classpath file is necessary to satisfy the Eclipse IDE which seems to be buggy here. You are absolutely right the IDE should resolve the dependency in accordance to the MANIFEST but it simply doesn't. Best, Thomas E.-E.

**Comment by kaikreuzer** [comment]
This is not right - if the library is exported in the .classpath of the bundle that contains the lib, then dependent projects do not need a .classpath fix. See e.g. https://github.com/eclipse/smarthome/blob/master/bundles/io/org.eclipse.smarthome.io.transport.mdns/.classpath#L6

**Comment by teichsta** [comment]
even better! Didn't know that this has been fixed meanwhile. Then I'll refix as soon time permits or we'll find other volunteers :-)

- sent from a mobile device -

**Comment by teichsta** [comment]
exported the lib and removed the references from .classpath files.

Best, Thomas E.-E.

**Pull request merged**
