### PR TITLE
updated assembly (and as dependency) the jdeb maven plugins to reliably ...

### PR DESCRIPTION
**Pull request by teichsta**
...assemble shell scripts with execute rights.

Problem was raised with #1917.

### CODE REVIEW

**Comment by teichsta** [comment]
@kaikreuzer could you please confirm that it works on your machine as well (to have at least a second proof). Thanks, Thomas E.-E.

**Comment by kaikreuzer** [comment]
The build currently fails with 
```
Failed to resolve dependencies for: runtime: Missing:
[ERROR] ----------
[ERROR] 1) org.openhab.binding:org.openhab.binding.wago:jar:1.7.0-SNAPSHOT
```
so I cannot retest now...

**Comment by teichsta** [comment]
ok, Buildhive was successful … could you please try again?

**Comment by kaikreuzer** [comment]
I did a local build of the latest master and when unzipping the runtime I have:
```
-rw-r--r--   1 kai  staff    1043 Sep 14 21:39 start_debug.sh
-rw-r--r--   1 kai  staff    1110 Sep 14 21:39 start_debug.bat
-rw-r--r--   1 kai  staff     880 Sep 14 21:39 start.sh
-rw-r--r--   1 kai  staff     958 Sep 14 21:39 start.bat
```
Is it any better when you do it?

**Comment by teichsta** [comment]
yep

```
-rw-r--r--   1 thomasee  staff    958 Sep 12 13:38 start.bat
-rwxr-xr-x   1 thomasee  staff    880 Sep 12 13:38 start.sh
-rw-r--r--   1 thomasee  staff   1110 Sep 12 13:38 start_debug.bat
-rwxr-xr-x   1 thomasee  staff   1043 Sep 12 13:38 start_debug.sh
```

very strange! My config is:

```
Thomass-MacBook-Pro:openhab thomasee$ mvn -version
Apache Maven 3.2.1 (ea8b2b07643dbb1b84b6d16e1f08391b666bc1e9; 2014-02-14T18:37:52+01:00)
Maven home: /Users/thomasee/Dev/Tools/apache-maven-3.2.1
Java version: 1.7.0_71, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.1", arch: "x86_64", family: "mac"
```

**Comment by kaikreuzer** [comment]
Mine looks pretty similar:
```
Apache Maven 3.2.1 (ea8b2b07643dbb1b84b6d16e1f08391b666bc1e9; 2014-02-14T18:37:52+01:00)
Maven home: /usr/local/Cellar/maven/3.2.1/libexec
Java version: 1.7.0_21, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_21.jdk/Contents/Home/jre
Default locale: de_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.1", arch: "x86_64", family: "mac"
```

**Comment by teichsta** [comment]
weird :-(

**Comment by kaikreuzer** [comment]
I've just executed it a second time and it worked. So I would say it is as unreliable and shaky as before :-)

**Comment by teichsta** [comment]
so i would tend to close this issue and add an additional instruction to the "Release How-To" …

**Comment by kaikreuzer** [comment]
ok for me - just make sure that the release versions are from builds that are correct!

**Comment by teichsta** [comment]
i've updated the Release How-To (see https://github.com/openhab/openhab/wiki/How-to-release-openHAB)

**Pull request closed without merging**
