### PR TITLE
netatmo: fix for issue #3937

### PR DESCRIPTION
**Pull request by robnielsen**
This fixes https://github.com/openhab/openhab/issues/3937

### CODE REVIEW

**Comment by robnielsen** [comment]
fixed broken test

**Comment by lolodomo** [comment]
Please include this PR in version 1.8.1 as the binding is fully broken without it.

**Comment by watou** [comment]
@lolodomo, I don't think the OH2 1.8 branch was effected by the change that broke OH2 build 111.

**Comment by teichsta** [comment]
refused from cherry-picking onto 1.8 since the versions seem to diverge quite a lot already. Picking brought a lot of merge conflicts.

**Comment by robnielsen** [comment]
@lolodomo, The 1.8 branch doesn't have the changes to support camera (Welcome) and I agree with @teichsta, it shouldn't go into 1.8.1. See: https://github.com/openhab/openhab/commits/1.8/bundles/binding/org.openhab.binding.netatmo

**Pull request merged**
