### PR TITLE
changed the archetype default binding project according to #2720

### PR DESCRIPTION
**Pull request by tdiekmann**
updated the copyright header with the year 2015
added immediate="true" flag to binding.xml, otherwise the binding does
 not get started automatically
removed unnecessary imports
removed the Activator. The bundleContext is available from the call to
 the activate method. The static Activator access is discouraged, since
 it is only valid when the bundle is ACTIVE, however, any code could
 access the static variable at any point in time

### CODE REVIEW

**Comment by tdiekmann** [comment]
Thomas, this is the proposed change to the default binding project layout. I hope I followed the process correctly.

**Comment by kaikreuzer** [comment]
Hi Tim,

Thanks, looks very good to me! Just one question: Would it make sense to also add the modified method? Otherwise, if the configuration at startup is invalid, the setProperlyConfigured will never be set to true, even if the configuration is changed. What do you think?

**Comment by tdiekmann** [comment]
Yes, that sounds like a good option. Since you support dynamic updates of
the configuration, it will be worth adding that. I'll update the branch for
#2027. Does that mean I need to send a new pull request?

On Fri, Jan 23, 2015 at 3:05 AM, Kai Kreuzer <notifications@github.com>
wrote:

> Hi Tim,
>
> Thanks, looks very good to me! Just one question: Would it make sense to
> also add the modified method? Otherwise, if the configuration at startup is
> invalid, the setProperlyConfigured will never be set to true, even if the
> configuration is changed. What do you think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openhab/openhab/pull/2028#issuecomment-71178627>.
>



-- 


     Tim.

**Comment by teichsta** [comment]
No, if you update the branch the PR will be updated as well.

- sent from a mobile device -

**Comment by tdiekmann** [comment]
I'll make the change, but I noticed that the openhab.cfg file is not
monitored and, therefore, dynamic configuration changes are not detected
and propagated. This is not a problem, but could be enhanced in the future.

  Tim.

On Fri, Jan 23, 2015 at 8:25 AM, Thomas Eichstädt-Engelen <
notifications@github.com> wrote:

>
> No, if you update the branch the PR will be updated as well.
>
> - sent from a mobile device -
>
>
> > Am 23.01.2015 um 17:17 schrieb Tim Diekmann <notifications@github.com>:
> >
> > Yes, that sounds like a good option. Since you support dynamic updates
> of
> > the configuration, it will be worth adding that. I'll update the branch
> for
> > #2027. Does that mean I need to send a new pull request?
> >
> > On Fri, Jan 23, 2015 at 3:05 AM, Kai Kreuzer <notifications@github.com>
> > wrote:
> >
> > > Hi Tim,
> > >
> > > Thanks, looks very good to me! Just one question: Would it make sense
> to
> > > also add the modified method? Otherwise, if the configuration at
> startup is
> > > invalid, the setProperlyConfigured will never be set to true, even if
> the
> > > configuration is changed. What do you think?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/openhab/openhab/pull/2028#issuecomment-71178627>.
> > >
> >
> >
> >
> > --
> >
> >
> > Tim.
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openhab/openhab/pull/2028#issuecomment-71219311>.
>



-- 


     Tim.

**Comment by kaikreuzer** [comment]
> This is not a problem, but could be enhanced in the future. 

It actually is already enhanced in future - when you use openHAB 1 bindings on the openHAB 2 runtime, configuration changes are tracked and reloaded :-)

Cheers,
Kai

> Am 23 Jan 2015 um 19:28 schrieb Tim Diekmann <notifications@github.com>:
> 
> I'll make the change, but I noticed that the openhab.cfg file is not 
> monitored and, therefore, dynamic configuration changes are not detected 
> and propagated. This is not a problem, but could be enhanced in the future. 
> 
> Tim. 
> 
> On Fri, Jan 23, 2015 at 8:25 AM, Thomas Eichstädt-Engelen <

**Comment by kaikreuzer** [comment]
@teichsta : Any specific reason why you have put esh and openHAB2 tags on here?
@tdiekmann : Just noticed that we missed to update the wiki accordingly. Would you be able to do that? See https://github.com/openhab/openhab/wiki/How-To-Implement-A-Binding#global-binding-configuration

**Comment by tdiekmann** [comment]
Sure, I’ll take a look at it.


    Tim.

**Comment by teichsta** [comment]
> @teichsta : Any specific reason why you have put esh and openHAB2 tags on here?

as a reminder. Although the Archetypes itself will look differently the changes should be reflected there as well, shouldn't they?

**Comment by teichsta** [comment]
> Sure, I’ll take a look at it.

Thanks!

**Comment by kaikreuzer** [comment]
> Although the Archetypes itself will look differently the changes should be reflected there as well, shouldn't they?

Well, there are no ManagedServices in the ESH archetype, so need for such a refactoring.

**Comment by teichsta** [comment]
> there are no ManagedServices in the ESH archetype

a good argument :-)

**Comment by watou** [comment]
Regarding the recent wiki change (copied from my comment in Google Groups):

The wiki page for How to Implement a Binding instructs binding developers to include `configuration-policy="require"` in their `binding.xml` file if their binding requires configuration properties in `openhab.cfg`.  Mine does, so I added this to my binding, but when I copied the new JAR into a running 1.6.2 system, the binding shutdown but failed to restart.  I backed out `configuration-policy="require"`, rebuilt, and the new JAR is now working properly.

Do the recent edits to the wiki page only refer to some future openHAB release, where following the instructions in the current wiki page will produce bindings that don't work on openHAB 1.6?

Developers are used to being able to have their binding JAR work in different openHAB releases.  What release(s) of openHAB will work with the instructions that are currently in the wiki?

**Comment by teichsta** [comment]
any idea @tdiekmann ?

**Comment by tdiekmann** [comment]
That’s a fair question.

The changes apply to 1.7 onward. I guess I could take the previous version of the documentation and make it available through a link to a different wiki page. Would that work for you?

    Tim.

**Comment by teichsta** [comment]
> The changes apply to 1.7 onward

That is true for the created Bindings … but even the new Bindings should still be (backwards) compatible to a 1.6.2 Runtime since this PR didn't change anything in the Core/Runtime self, shouldn't they?

**Comment by tdiekmann** [comment]
Sure, they are. The archetype is a template for new bindings only. I did not change any of the existing bindings. Their functionality is still valid and supported, nothing has changed for them.


    Tim.

**Comment by watou** [comment]
While old bindings should be forward compatible as you say, the question is more about new bindings being backward compatible with openHAB 1.6.2.  I think we want to prevent a situation where someone follows the new wiki instructions, but produces a binding that will not work on 1.6.2 (or perhaps 1.5.*, 1.4.*, etc.).  As much as I want a nice clean new archetype for bindings, I don't think we want to see chaos with binding compatibility!

**Comment by tdiekmann** [comment]
They are binary compatible. At least, the openhab 1.6.2 version of Equinox DS already supports the 1.2 schema and, therefore, it is fully backward compatible.


    Tim.

**Comment by watou** [comment]
Perhaps my test was flawed in some way, but I think this should be thoroughly tested empirically.

**Pull request merged**
