### PR TITLE
Waterkotte Ecotouch heatpump binding for OH2

### PR DESCRIPTION
**Pull request by sibbi77**
This pull request adds some more recognized tags to the binding and provides the metadata for OH2.
I can squash the commits into one, if requested.

Open problems:
OH2 shows the binding under PaperUI/Configuration/Bindings, but changes to the configuration are ignored (AbstractActiveBinding<>.updated(Dictionary<String, ?> config) is called with config == null, if no ecotouch.cfg file is in place).
Only configuration via the provided ecotouch.cfg file works.

### CODE REVIEW

**Comment by watou** [comment]
It is common for `updated()` to be called with `config` being `null`.  But are you saying that attempts to use the Paper UI to configure the binding never take at all?

**Comment by watou** [comment]
Thanks very much!  Aside from comments, lgtm.

**Comment by sibbi77** [comment]
any attempt to configure the binding in the PaperUI only stores the configuration values at userdata/cache/org.eclipse.osgi/7/data/config/binding/ecotouch.config.
But this does not result in a valid config argument in the call to updated().
If I modify the conf/services/ecotouch.cfg and uncomment ip, username and password, the binding's refresh service starts.
Either ecotouch.cfg takes precedence over ecotouch.config, some ids inside binding.xml(?) not match or the framework does not propagate the UI config changes correctly (problem in compat layer?)

**Comment by watou** [comment]
@kaikreuzer any thoughts on the above?

**Comment by kaikreuzer** [comment]
I have a suspicion: I guess it simply ends up as a configuration for a different service pid.

I recently noticed that Paper UI sends binding configurations to a service pid `binding.<id>`, while openHAB 1 bindings expect their configuration as `org.openhab.<id>`. This would explain what you see.
I am nonetheless a bit puzzled, because I thought to remember seeing it once working. @watou When you did stuff like https://github.com/openhab/openhab/pull/4271/files, did you test it or did you blindly trust me?

**Comment by watou** [comment]
@kaikreuzer: I thought I had tested it but at this point I can't vouch for my own testing.  

I would like to add a few more binding.xml files to bindings.  Can you see a way to support dynamic config keys like`home.port=443`, `office.ip=192.168.0.10`, etc. in the schema and UI?

**Comment by kaikreuzer** [comment]
> I thought I had tested it but at this point I can't vouch for my own testing.

Ok, will have to find a solution for this then.

> Can you see a way to support dynamic config keys likehome.port=443, office.ip=192.168.0.10, etc. in the schema and UI?

No, we decided against this, because it is not really the way configurations are expected to be done in OSGi. To support such settings, we added the "expert mode" button in the Paper UI for configurations, so the user can still add it.

This mechanism was mainly used in OH1 for providing multiple instances of the same binding - in ESH, this is addressed by having Bridges/Things, so such configurations are not found not on the binding itself, but on the Bridges/Things that represent your instances ("home", "office", etc.).

**Comment by watou** [comment]
Makes perfect sense.

**Comment by watou** [comment]
> Ok, will have to find a solution for this then.

Could we add an optional service.pid setting to binding.xml, so that when it's present, the config is written to the given service PID instead of following the convention?  So all OH1 bindings would provide theirs.  I know it's duplication, but it seems like a fairly direct solution.

**Comment by kaikreuzer** [comment]
@watou Good news, exactly such a mechanism is already in place! I successfully tested it with the Nest binding, see https://github.com/openhab/openhab/pull/4804/files. Could you update the OH1 bindings accordingly? I'll make sure to update the documentation to cover this.

**Comment by watou** [comment]
> Could you update the OH1 bindings accordingly?

Great news.  I will update the other 1.x bindings.

**Comment by watou** [comment]
@sibbi77: Could you add `<service-id>org.openhab.ecotouch</service-id>` to `ESH-INF/binding/binding.xml` and see if it resolves the issue you identified in https://github.com/openhab/openhab/pull/4786#issuecomment-261566477 ?

**Comment by sibbi77** [comment]
Now it works as expected. Thanks!

**Pull request merged**
