### PR TITLE
Dragon tech zwave config files

### PR DESCRIPTION
**Pull request by llamahunter**

### CODE REVIEW

**Comment by cdjackson** [comment]
Sorry - I can't merge this now - I suspect it's due to the previous PR of yours I just merged - they probably overlap slightly in the products file.
Can you just pull the master into this branch to clear any conflicts - no need to do another PR or anything -just clear the conflict and push the updates.

**Comment by llamahunter** [comment]
Ok... hmm.. not sure that this fixed the problem.  Git is weird. It seems difficult to just bring things up to date without carrying along a lot of other garbage.

**Comment by cdjackson** [comment]
This is normal... It happens if two people change the same bit of code and then try and merge (in this case the two people were both you :) ). The first merge is ok, but the second one then gives a conflict that needs to be resolved by merging master back into the branch to be merged (if that all makes sense!).

One other problem (sorry) - the gitignore file has been changed - can you restore that back to the original?

**Comment by llamahunter** [comment]
Somehow that got picked up again.  sorry.  Since I use intellij, I really want those files in the .gitignore so that they don't show up in 'git status'.  How do I check that in to my tree, but prevent it from percolating up with every pull request to the openhab master?

**Comment by llamahunter** [comment]
I think I'm going to try again with a new branch and create a new pull request.  Still, an answer to above .gitignore (or other similarly locally changed file) question would be desirable.

**Comment by cdjackson** [comment]
I’m not sure about local changes to gitignore - I think you can probably configure git to do this, but I’ve not done it myself. I do agree with you though - it’s something that I also should do, but haven’t due to the hassle factor...

**Comment by llamahunter** [comment]
I resubmitted this pull request in 'clean' form using llamahunter:dragon-tech-configs-3, as I messed up the git merge trying to pull this one up to the master's HEAD.

**Pull request closed without merging**
