### PR TITLE
Added on/off module 2635-222

### PR DESCRIPTION
**Pull request by jhuizingh**
Added new device.

### CODE REVIEW

**Comment by robnielsen** [comment]
@berndpfrommer this is a new Insteon device.

**Comment by teichsta** [comment]
if you'd agree i am happy to merge …

**Comment by berndpfrommer** [comment]
Looks good, please merge.
Thanks Thomas!

**Comment by teichsta** [comment]
Thanks guys!

**Comment by jhuizingh** [comment]
Thank you!

**Pull request merged**
