### PR TITLE
Add suppport for Security2/Keeloq protocol on rfxcom binding - updated

### PR DESCRIPTION
**Pull request by ivanfmartinez**
This PR is a single commit to replace #4012 .
It solves the merge conflict appeared after @Speederc  PRs merged.

@Speederc  please check my current solution for the protocol change. Currently only if firmware is >= 251 the new format will be used.

### CODE REVIEW

**Comment by Speederc** [comment]
Hi @ivanfmartinez ,
It is not always firmware >= 251 as the firmware number is linked to the hardware version with something like : 
- RFXtrx433 version 1 (HW version=1.0 ou 1.1 ?) : 95
- RFXtrx433 version 2 (HW version 1.2??) : 195
- RFXtrx433E (HW version 1.3??) : 251

**Comment by ivanfmartinez** [comment]
@Speederc  I know, but hardware version is in the part of message that have changed. What is your suggestion to make this work ? I cannot be sure of hardware version because it have changed position. The only version I can be sure is the 251 because is the largest value.

**Comment by paulianttila** [comment]
You have both @ivanfmartinez and @Speederc done great job to extend the rfxcom binding. I'm not sure, if you are aware that I have already ported rfxcom binding to OH2. As v2 binding is merged to OH2 distribution, OH1 binding is not any more part of the OH2 release. Because version 1.8 was the last release for OH1, this OH1 binding is not automatically included to any new release (well, of course changes are included to 1.8 maintenance releases when/if that is done). 

Now there are big gaps between v1 and v2 bindings, so I encourage you to do those extensions to OH2 rfxcom binding as well. Currently I don't have much time to spend with OH2 development and all my  spare time I use to port other bindings from OH1 to OH2.

**Comment by ivanfmartinez** [comment]
@Speederc what you think about this new version check ? I think this will work for sometime. At least until we get better option from Bert. The 251 version will overflow in some time and he will have to change again the message format to support big version numbers also.

**Comment by ivanfmartinez** [comment]
@paulianttila I did not have an OH2 environment for testing and did not have time currently to migrate, I still spending time building my rules to make my things work fine.

We have changed only the internal parts of binding, I think these internal parts can be directly moved to oh2 binding.

Do you known someone else with OH2 environment who can do the tests ?

**Comment by teichsta** [comment]
Thanks guys!

> Now there are big gaps between v1 and v2 bindings, so I encourage you to do those extensions to OH2 rfxcom binding as well.

+1

Setting up an IDE for the 1.9 SNAPSHOT should be breeze. Please checkout https://github.com/openhab/openhab-distro/blob/master/docs/sources/development/ide.md for information.

**Pull request merged**
