### PR TITLE
DSCAlarm Binding: OpenHAB2 Compatibility Issue and Partition Arm Mode Message Change

### PR DESCRIPTION
**Pull request by RSStephens**
**Removed Dependency in MANIFEST.MF**

The DSCAlarm binding had a dependency on a module (org.openhab.model.core) that was not included
in the openHAB2 compatibility layer.  The entry was removed from the MANIFEST.MF file.  Once this dependency was removed the binding started working in openHAB2.  Evidently this dependency was not necessary.  This may have been the issue expressed in this Google group topic: https://groups.google.com/forum/#!topic/openhab/Qi7FV92HM5A.  I did some basic testing in the openHAB2 IDE and on a simulation setup (no DSC Alarm system), but the binding has not been tested against a real DSC Alarm system.  Not sure when I will be able to get to that.

**Partition Arm Mode Message Change**

In addition a commit was made to change the received message description for a partition in the armed state.  The message now reflects which arm mode (i.e. "Away", "Stay", "Away w/zero delay (ZEA)", or "Stay w/zero delay (ZES)") the alarm system is in.

### CODE REVIEW

**Comment by teichsta** [comment]
description and code does not seem to match … can you please adjust the documentation or commit the relevant code to this PR? Also please don't forget to squash your commits into one. Thanks, Thomas E.-E.

**Comment by RSStephens** [comment]
Hello Thomas,

Sorry about that.  I committed another change after this PR and forgot to update the documentation.  I will update it shortly.  Thank you.

**Comment by RSStephens** [comment]
Hello Thomas,

I have updated the documentation to reflect the additional change made in
the binding.  Thank you.

On Tue, Apr 14, 2015 at 6:32 AM, rsstephens@gmail.com <rsstephens@gmail.com>
wrote:

> Hello Thomas,
>
> Sorry about that.  I committed another change after this PR and forgot to
> update the documentation.  I will update it shortly.  Thank you.
>
> Sent from my iPad
>
> On Apr 13, 2015, at 4:53 PM, Thomas Eichstädt-Engelen <
> notifications@github.com> wrote:
>
> description and code does not seem to match … can you please adjust the
> documentation or commit the relevant code to this PR? Also please don't
> forget to squash your commits into one. Thanks, Thomas E.-E.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openhab/openhab/pull/2450#issuecomment-92494867>.
>
>


-- 
Russell Stephens
RSStephens@gmail.com

**Comment by teichsta** [comment]
Thanks, if you could now squash your commits into one i will merge this PR right away. Best, Thomas E.-E.

**Comment by RSStephens** [comment]
Hello Thomas,

I have squashed my commits.  Thank you.

Russell

**Pull request merged**
