### PR TITLE
MiOS Item Generator: Add support for MultiSwitch

### PR DESCRIPTION
**Pull request by mrguessed**
Add an alias for MultiSwitch devices, as `MSwitch1`, for their UPnP ServiceId:

```
   urn:dcineco-com:serviceId:MSwitch1
```

Add template/conversion code to make these devices work out of the box with reasonable defaults, for users migrating over from MiOS/Vera

Ref: http://forum.micasaverde.com/index.php/topic,31214.msg256830.html#msg256830

Signed-off-by: Mark Clark <mr.guessed@gmail.com>

### CODE REVIEW

**Comment by torpex77** [comment]
I think the settings for Status2 - Status8 might be in error.

```
bundles/binding/org.openhab.binding.mios/examples/transform/miosMSwitch4.map

+ON=urn:dcineco-com:serviceId:MSwitch1/SetStatus4(newStatus1=1)
+OFF=urn:dcineco-com:serviceId:MSwitch1/SetStatus4(newStatus1=0)
```
The newStatus variable name changes for each switch.  So that

```
bundles/binding/org.openhab.binding.mios/examples/transform/miosMSwitch4.map

+ON=urn:dcineco-com:serviceId:MSwitch1/SetStatus4(newStatus4=1)
+OFF=urn:dcineco-com:serviceId:MSwitch1/SetStatus4(newStatus4=0)[/code]
```
would be correct.

Thanks,

Doug

**Comment by mrguessed** [comment]
Thanks @torpex77, those changes have now been applied.  Can you run it against your `user_data.xml` to see that it's working correctly?

The resulting Items file itself won't work unless you have the alias fixes in the MiOS jar, but you can verify the correct form.

**Comment by torpex77** [comment]
Sure.  I'll give it a try tonight.

Doug

**Comment by torpex77** [comment]
Looks good, I think.  Here's the output:

```
/* Device - MultiSwitch */
Number   MultiSwitchId "ID [%d]" (GDevices) {mios="unit:house,device:134/id"}
String   MultiSwitchDeviceStatus "MultiSwitch Device Status [MAP(miosDeviceStatusUI.map):%s]" (GDevices) {mios="unit:house,device:134/status"}
Switch   MultiSwitchStatus1 "MultiSwitch Status 1" (GDevices) {mios="unit:house,device:134/service/MSwitch1/Status1"}
Switch   MultiSwitchStatus2 "MultiSwitch Status 2" (GDevices) {mios="unit:house,device:134/service/MSwitch1/Status2"}
Switch   MultiSwitchStatus3 "MultiSwitch Status 3" (GDevices) {mios="unit:house,device:134/service/MSwitch1/Status3"}
Switch   MultiSwitchStatus4 "MultiSwitch Status 4" (GDevices) {mios="unit:house,device:134/service/MSwitch1/Status4"}
Switch   MultiSwitchStatus5 "MultiSwitch Status 5" (GDevices) {mios="unit:house,device:134/service/MSwitch1/Status5"}
Switch   MultiSwitchStatus6 "MultiSwitch Status 6" (GDevices) {mios="unit:house,device:134/service/MSwitch1/Status6"}
Switch   MultiSwitchStatus7 "MultiSwitch Status 7" (GDevices) {mios="unit:house,device:134/service/MSwitch1/Status7"}
Switch   MultiSwitchStatus8 "MultiSwitch Status 8" (GDevices) {mios="unit:house,device:134/service/MSwitch1/Status8"}
String   MultiSwitchRadioBtns "MultiSwitch FIXME RadioBtns [%s]" (GDevices) {mios="unit:house,device:134/service/MSwitch1/RadioBtns"}
String   MultiSwitchPulseBtns "MultiSwitch FIXME PulseBtns [%s]" (GDevices) {mios="unit:house,device:134/service/MSwitch1/PulseBtns"}
String   MultiSwitchBtnNames "MultiSwitch FIXME BtnNames [%s]" (GDevices) {mios="unit:house,device:134/service/MSwitch1/BtnNames"}
String   MultiSwitchText1 "MultiSwitch Text 1 [%s]" (GDevices) {mios="unit:house,device:134/service/MSwitch1/Text1"}
String   MultiSwitchText2 "MultiSwitch Text 2 [%s]" (GDevices) {mios="unit:house,device:134/service/MSwitch1/Text2"}
String   MultiSwitchOptions "MultiSwitch Options [%s]" (GDevices) {mios="unit:house,device:134/service/MSwitch1/Options"}
String   MultiSwitchMsg "MultiSwitch Message [%s]" (GDevices) {mios="unit:house,device:134/service/MSwitch1/Msg"}
```

**Comment by mrguessed** [comment]
@torpex77, thanks for validating the output on your system, much appreciated!  The MultiSwitch is a bit of a swiss-army knife™, so it's likely they'll want to tweak it some but this is a reasonable starting point.

**Comment by teichsta** [comment]
Thanks @mrguessed!

**Pull request merged**
