### PR TITLE
Doc Update

### PR DESCRIPTION
**Pull request by dvanherbergen**
This is a recovered version of https://github.com/openhab/openhab/pull/3820

### CODE REVIEW

**Comment by dvanherbergen** [comment]
@kaikreuzer , if OK for you,  can you merge? :wink:

**Comment by kaikreuzer** [comment]
This repo is normally managed by @teichsta, so I am not tracking it actively.
But when pinged, I am happy to merge - but only if you squash your commits beforehand!

**Comment by dvanherbergen** [comment]
I tried squashing, but didn't succeed in this case. I accidentally overwrote the original commit some time ago using a push -f. So I had to merge the commit back into the branch to recover it. The original commit and the merged commit however, are now separated in the timeline by a number of other commits, so I can't squash them together anymore :cry:

**Comment by kaikreuzer** [comment]
Well, let's leave it like this then and put some shame on you :-P
What I usually do in such cases is to create a new branch from master, commit the changes, delete the old branch, rename the new branch to have the name of the old and force push.

**Comment by dvanherbergen** [comment]
> Well, let's leave it like this then and put some shame on you :-P

Oh no, this will live on the internets forever :fearful: 
I will try your approach next time :wink:

**Pull request merged**
