### PR TITLE
add support for the Aeon MultiSensor 6

### PR DESCRIPTION
**Pull request by paixaop**
Add support for the Aeon MultiSensor 6 ZW100-A

### CODE REVIEW

**Comment by cdjackson** [comment]
Thanks - this all looks good, but I have 2 requests....
1) Can you please check that there aren't 3 association groups for this device? There are config parameters associated with groups 2 and 3, but these association groups are included.
2) Can you please use the formatter in Eclipse to reformat the XML just to make it easier to read (ie in the source menu).

Thanks
Chris

**Comment by paixaop** [comment]
Chris 

I think it is fixed now.

**Comment by cdjackson** [comment]
Unfortunately you've made a number of other changes to the repository that need to be reverted - we just need the zwave files only...

**Comment by paixaop** [comment]
Chris rolled back the repo and re-added the XML files.

**Pull request closed without merging**
