### PR TITLE
rfxcom correct some message length errors detected by the rfxcom test binding

### PR DESCRIPTION
**Pull request by ivanfmartinez**

### CODE REVIEW

**Comment by teichsta** [comment]
any comments @Speederc?

**Comment by Speederc** [comment]
This PR complements #3957. It can be merged.

**Comment by teichsta** [comment]
great, thanks for this update @Speederc and for the contribution @ivanfmartinez!

**Comment by 9037568** [comment]
Thanks, @ivanfmartinez !

**Pull request merged**
