### PR TITLE
Support for Contact items in pilight binding

### PR DESCRIPTION
**Pull request by idserda**
This pull request adds support for Contact items to the pilight v6 binding. Please merge #2446 first.

[Updated wiki](https://github.com/idserda/openhab/wiki/pilight-Binding)

@SJoWie80 Could you also test this new functionality? Thanks!

### CODE REVIEW

**Comment by SJoWie80** [comment]
Thanks for adding support.

I will test this Monday/Tuesday (don`t have time sooner)

I will let you know if it works.

 

Thanks again!

**Comment by SJoWie80** [comment]
@idserda Found some time to test the Contact sensors en they are working perfect! 
Thanks!

**Comment by teichsta** [comment]
Hi @idserda it seems this PR also contains #2446 rather than being an addon to it. Could you please fix this and also squash the commits into one? Thanks, Thomas E.-E.

**Comment by idserda** [comment]
@teichsta Fixed

**Comment by teichsta** [comment]
Thanks @idserda

**Pull request merged**
