### PR TITLE
initial checkin of the AKM868 on behalf of @MitchSUEW

### PR DESCRIPTION
**Pull request by teichsta**
supersedes #3622

### CODE REVIEW

**Comment by teichsta** [comment]
@MitchSUEW could you please have a look if everything is fine with your contribution. Will merge after your explicit ok.

**Comment by MitchSUEW** [comment]
Looks very good. Thanks a lot @teichsta for your support. KUDOS!!

**Comment by teichsta** [comment]
ok, thanks, merged …

**Comment by teichsta** [comment]
@MitchSUEW after all could you please provide the according Wiki page until the weekend? Thanks, Thomas E.-E.

**Comment by MitchSUEW** [comment]
Sure, done.@teichsta

**Comment by teichsta** [comment]
great, thanks (ftr: https://github.com/openhab/openhab/wiki/AKM868-Binding)

**Pull request merged**
