### PR TITLE
Add hue and more icons

### PR DESCRIPTION
**Pull request by cniweb**
This PR add:
- More advanced icons
- HUE icons

### CODE REVIEW

**Comment by cniweb** [comment]
Now hopefully the PR will fit!

**Comment by teichsta** [comment]
unfortunately not :-) As described before:

* the holiday script, rules, items are better suited as an example since they only apply to Germany. Please add them to the Samples-Section of the Wiki
* please revert the change to the .gitignore since it add changes only suitable for Windows Installations
* please add your Icons to the License.txt file (also available in the ```./webapps/images``` directory)

**Comment by cniweb** [comment]
OK, better?

**Comment by teichsta** [comment]
> OK, better?

**Pull request merged**
