### PR TITLE
Adjust log level for DefaultAnnotationProcessor

### PR DESCRIPTION
**Pull request by J-N-K**
Fixes logging issue from #2555

### CODE REVIEW

**Comment by nesys** [comment]
Hi,

the login issue at #2555 seems still present on version 1.7.1

**Comment by omegacore** [comment]
Can confirm this line still shows up in 1.7.1

**Comment by krzychb** [comment]
Apparently I have the same warning on version1.7.1:

16:19:10.338 [WARN ] [cpr.DefaultAnnotationProcessor] - Unable to detect annotations. Application may fail to deploy.

**Comment by watou** [comment]
If you upgraded but left your old logback.xml in place, you would continue to see these WARN messages in the log.  If you make a manual change as described on the "Files changed" tab above, that ought to silence the messages.

**Comment by krzychb** [comment]
@watou - this was exactly the case. Thank you!

**Pull request merged**
