### PR TITLE
adding discovery to the harmony hub binding. 

### PR DESCRIPTION
**Pull request by digitaldan**
This is necessary as logitech has changed their auth api rendering the 1.x version of this binding unusable, see https://community.openhab.org/t/harmony-binding-stopped-working-in-oh1/16900/22 
Signed-off-by: Dan Cunningham <dan@digitaldan.com>

### CODE REVIEW

**Comment by staehler** [comment]
Hi Dan,
I downloaded the new harmony binding files few minutes ago, as I assumed your changes have already beenn applied. If not, then ignore my posting. 
My harmony still complains the logitech auth service:
`2016-11-24 20:37:17.457 [ERROR] [o.harmonyhub.HarmonyHubGateway] - Failed creating harmony hub connection to 192.168.2.129
java.lang.RuntimeException: Failed to parse response from Logitech auth service
        at net.whistlingfish.harmony.protocol.AuthService.getLoginToken(AuthService.java:45) ~[harmony-java-client-1.0.4.jar:1.0.4]
        at net.whistlingfish.harmony.HarmonyClient.connect(HarmonyClient.java:111) ~[harmony-java-client-1.0.4.jar:1.0.4]
        at org.openhab.io.harmonyhub.HarmonyHubGateway.connectClient(HarmonyHubGateway.java:264) [bundlefile:na]
        at org.openhab.io.harmonyhub.HarmonyHubGateway.connect(HarmonyHubGateway.java:228) [bundlefile:na]
        at org.openhab.io.harmonyhub.HarmonyHubGateway.access$0(HarmonyHubGateway.java:201) [bundlefile:na]
        at org.openhab.io.harmonyhub.HarmonyHubGateway$1.run(HarmonyHubGateway.java:194) [bundlefile:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
Caused by: us.monoid.json.JSONException: JSONObject["GetUserAuthTokenResult"] is not a JSONObject.
        at us.monoid.json.JSONObject.getJSONObject(JSONObject.java:579) ~[resty-0.3.2.jar:na]
        at net.whistlingfish.harmony.protocol.AuthService.getLoginToken(AuthService.java:41) ~[harmony-java-client-1.0.4.jar:1.0.4]
        ... 6 common frames omitted
`
Maybe I'm to impatient?

**Comment by digitaldan** [comment]
maybe, but the configuration changed and I need to update the docs , read the end of https://community.openhab.org/t/harmony-binding-stopped-working-in-oh1/16900/22 , if you are still getting an auth error after using the 'discoveryName' config option , then it's an old version

**Comment by staehler** [comment]
Great, it works!!! You're an code artist :-) Thanks, so much for your excellent work.
Have a nice weekend.

**Comment by thib5** [comment]
di i need to delete all other harmony binding ? witch fill do i need ? the 1.9 one ? 

Thanks

**Pull request merged**
