### PR TITLE
Orvibo S20 & allone ir blaster - start for new binding

### PR DESCRIPTION
**Pull request by 1achy**
There is low price ir blaster. ORVIBO WIWO IR .

I want implementation in openhab.

Is it possibile?

review of product:
https://shkspr.mobi/blog/2015/04/review-gearbest-orvibo-smart-remote/﻿

Revere enginnering on ORVIBO:
https://stikonas.eu/wordpress/2015/02/24/reverse-engineering-orvibo-s20-socket/

I found open source driver in js.
https://github.com/Grayda/ninja-allone

I found other  this code  :
https://github.com/Grayda/go-orvibo

### CODE REVIEW

**Comment by 1achy** [comment]
That socket looks very similar to one Aldi Australia are selling (under the brand name Bauhn, but it's actually an Orvibo socket, just rebranded). If it is the same, then check out the sample node.js code I've posted over on GitHub (This code actually controls an Orvibo AllOne, but also controls Orvibo S10 / S20 sockets too)

The short of it is:

The socket communicates via UDP on port 10000
You need to know the MAC address of your socket
You send a discovery packet to which the socket replies
You then 'subscribe' to the socket in order to control it
When you send on / off packets to the socket, it replies in turn with it's current state

**Comment by 1achy** [comment]
Is it possible use trasformation ( https://github.com/openhab/openhab/wiki/Transformations) for allone.js ?

**Comment by teichsta** [comment]
@1achy is the binding code already available in this PR. I didn't notice sind the PR seem to be screwed up. When developing a binding please create a new feature branch from the current master branch and develop your changes on top of this branch.

**Comment by richbeales** [comment]
Hi @1achy has any development been done on this? I can't see anything in the Pull request.  I've just purchased a S20 switch and don't want to start development if you've already got something started. Thanks

**Comment by 1achy** [comment]
Now i am sniffing data and study system i am dont good with pull github..... dp we want start togheter?

**Comment by richbeales** [comment]
Yes I'm happy to work together.  I've currently got it working using an
exec action to call out to python via the python-orvibo project on github,
but a native openHAB binding would be better.  Let me know what you've
found.  My primary interest is in the S20 socket as i don't have the IR
blaster

**Comment by cherezov** [comment]
You might be interesting in my [orvibo python lib](https://github.com/cherezov/orvibo) 
@richbeales

**Pull request closed without merging**
