### PR TITLE
Update of Featured Persistence Services

### PR DESCRIPTION
**Pull request by msfunty**
Added:
- InfluxDB (v. 1.0)
- MapDB

Deleted:
- Logging

### CODE REVIEW

**Comment by watou** [comment]
The new .cfg files would also have to be provided (identical to same sections of openhab_default.cfg except for mapdb: and influxdb: components).  Also, why remove logging persistence?

**Comment by kaikreuzer** [comment]
> Also, why remove logging persistence?

Good, question - I would actually assume that the documentation is wrong and it should work.

**Comment by teichsta** [comment]
@msfunty any updates on this? I guess the open question is why you removed the logging service …

**Comment by kaikreuzer** [comment]
Well, testing the logging persistence it shows that it does not work. But the reason is not that logback is missing, since this is included in the feature definition. In order to not lose this information, I would suggest to only put it in comments instead of deleting it.
@teichsta Any chance you could analyze what adaptions the logging persistence service might need to make it work as expected?

**Comment by teichsta** [comment]
> @teichsta Any chance you could analyze what adaptions the logging persistence service might need to make it work as expected?

yes, but i won't be able to work on this before end of next week

**Comment by kaikreuzer** [comment]
This is superseded by https://github.com/openhab/openhab/pull/4144

**Pull request closed without merging**
