### PR TITLE
Add new Hue images

### PR DESCRIPTION
**Pull request by cniweb**

### CODE REVIEW

**Comment by teichsta** [comment]
Hi @cniweb, thanks for this contribution. Please structure you PRs that they contain just Feature/Bugfix/Enhancement in order to handle and revert them easily. This PR contains at least two different change sets (Ferienkalender and Hue Pics). From my point of view the Holidaycalendar is a perfect example and should be published in the Wiki Samples section.

**Comment by teichsta** [comment]
see also #2192

**Comment by cniweb** [comment]
How can i do this?

**Comment by teichsta** [comment]
easiest would be to close this PR and open another from a clean branch (see also https://help.github.com/articles/creating-a-pull-request/). Best, Thomas E.-E.

**Comment by teichsta** [comment]
seems to be superseded by #2324

**Pull request closed without merging**
