### PR TITLE
N: octoller binding V1.0.0

### PR DESCRIPTION
**Pull request by JPlenert**
New binding for octoller. octoller is an open source, smart home and programmable logic controller(www.octoller.com). Right now the binding needs an .Net gateway (octoller.gateway). In a future version it may communicate directly to the octoller.

### CODE REVIEW

**Comment by teichsta** [comment]
Hi @JPlenert,

thanks for this contribution!

Before going into a detailed review please:

* add the unchanged license header to each of your files (using ```mvn -Dyear=2015 license:format```)
* add javadoc to each class on class level. Add @author and @since tags
* add javadoc at least to all public methods
* add newlines to all of your classes
* add your binding to bundles/binding/pom.xml
* add your binding to distribution/pom.xml

Hope to find time for a detailed review soon.

Best, Thomas E.-E.

**Comment by JPlenert** [comment]
Hi @teichsta,

I have updated the source code. Please do review.
Coming from the C/C++/C# world I did not understand the "newline" comment. Hope the code is well formed for you java guys ;-) 

Regards

Joerg P

**Comment by JPlenert** [comment]
I have added the binding to my octoller-pss repository (https://bitbucket.org/JPlenert/octoller-pss).
Feel free to use it!!

**Comment by teichsta** [comment]
and you are not going to contribute it to openHAB anymore?

Best, Thomas E.-E.

**Comment by JPlenert** [comment]
After recreating the whole fork and workspace I was able to compile again. So I started a new pull request. I don't think java and I will ever get friends ...

**Pull request closed without merging**
