### PR TITLE
Add mios rollershutter

### PR DESCRIPTION
**Pull request by Jakey69**
Added Rollershutter functionality to the MIOS binding

### CODE REVIEW

**Comment by Jakey69** [comment]
Hi Mark, sorry for the inconvenience, I'm still having troubles understanding git. I hope I did it right this time.

**Comment by mrguessed** [comment]
The MiOS bits look perfect, thanks!

What I'm not sure of is your commit list includes the MochadX10 Binding commit, which is a yet to be approved (and presumably in another Branch of your Master).  Not sure how they're becoming inter-twined, since your Master should be a clean-slate without either the MiOS mods or the new MochadX10 stuff in it (yet)

Side-bar, unrelated to MiOS, but you appear to have a 2014 Copyright on the new Mochad code, both here, and via PR# 2046

**Comment by Jakey69** [comment]
That indeed is strange... I'll look into it...

**Comment by teichsta** [comment]
Thanks @mrguessed  for taking care of this! @Jakey69 would be great if you could clean-up this PR. Please also try to squash your commits into one. Best, Thomas E.-E.

**Comment by Jakey69** [comment]
Created a new pull request #2309. This should be one commit starting from a fresh base without any Mochadx10 commits...

**Pull request closed without merging**
