### PR TITLE
Update products.xml - Fibaro Roller Shutter 2 v2.5

### PR DESCRIPTION
**Pull request by ghostreader86**
Fibaro Roller Shutter 2 with label V2.5 is reported as Type 302 and ID 1000.  Config remains the same.

### CODE REVIEW

**Comment by ghostreader86** [comment]
Thanks! Can i delete my branch?

**Comment by cdjackson** [comment]
Yes - you can delete the branch :)  Thanks.

**Comment by ghostreader86** [comment]
Sorry, this is my first contribution ;) Perfect, the little branch is deleted. Thanks again for quick merging

**Comment by ghostreader86** [comment]
Forgot to post, tested with nightlies 1.8.0.201601020237. Works ;)

**Pull request merged**
