### PR TITLE
RFXCOM Fix message data lengths

### PR DESCRIPTION
**Pull request by Speederc**
Fix message data lengths for the following sensor types : Current, Energy, Rain, UV, Wind.
Not really serious as it is mainly used as info for this kind of sensor, but it will be clearer.

### CODE REVIEW

**Comment by ivanfmartinez** [comment]
The new data lengths are correct.

But I found in the RFXComEnergyMessage the enum is wrong, it should have only ELEC2(1) and ELEC3(2), this message does not have ELEC1 according to RFXTRX documentation.

I think this should be commited, because the data lengths are wrong and then the enum can be corrected after.

**Comment by ivanfmartinez** [comment]
Now I have llooked at other PR. This can only be commited after #3956

**Comment by ivanfmartinez** [comment]
I have tried to make a test binding for rfxcom based on the mqtt.test
Can you take a look to see if is correct ?
[https://github.com/ivanfmartinez/openhab/pull/2/files]

Executing here it found many problems in the rfxcom binding, some of them will be solved by @Speederc PRs.

Now after this basic tests we can also create per message specific tests.

**Comment by Speederc** [comment]
Hi @ivanfmartinez 
I agree with you for ELEC2(1) and ELEC3(2) types for RFXComEnergyMessage and not ELEC1(0). I don't know why it was included at the beginning. Can you create a PR to fix this ?

**Comment by ivanfmartinez** [comment]
I have created the PR #4022 for the RFXComEnergyMessage update

**Comment by ivanfmartinez** [comment]
I have created the PR #4034  with a test binding for rfxcom. the test binding already can detect the problem that are being corrected by this PR.

**Comment by teichsta** [comment]
Thanks guys!

**Pull request merged**
