### PR TITLE
InfluxDB persistence for influxdb versions >= 0.9

### PR DESCRIPTION
**Pull request by theoweiss**
Influxdb database versions 0.9 and newer have a completely changed api and are not backward compatible.
This is a new influxdb persistence service plug-in which supports influxdb databases >=0.9. It is based on the existing influxdb persistence service that only supports version <0.9, but has some fundamental changes.
I decided to put this functionality in it's own plug-in in order to not force our users to upgrade their influxdb databases when upgrading to openHAB 1.8. Even more because influxdb until now has no upgrade path from influxdb 0.8 to 0.9, which means people would have to drop their databases.

Regards,
Theo

### CODE REVIEW

**Comment by teichsta** [comment]
@theoweiss can you please announce this major change (referring to this PR) at https://community.openhab.org and try to get some testers on board? Thanks, Thomas E.-E.

**Comment by theoweiss** [comment]
@teichsta  this PR is related to issue #2748 . I hope to get some feedback of @m4ci3k2 @couchounou or @itheiss. As you can see I've announced the availability of the influxdb >=0.9 support in this issue and provided a jar file on bintray.

If I can't get any feedback in the next days I will ask the community.

Furthermore we discussed the approach of having two influxdb services (0.9 and prior 0.9) vs. one 0.9-and-newer service when we met at the JavaForum. With this PR I've chosen to have two plugins. What do you think about this today? May be @kaikreuzer has an opinion whats the best way to go.

**Comment by couchounou** [comment]
Hello, i will try asap tonight and let you know.

Date: Tue, 20 Oct 2015 13:26:25 -0700

**Comment by theoweiss** [comment]
I've tested this service on openHAB2 and it's running well! I will create an according PR for openHAB2.

**Comment by bodiroga** [comment]
Hi theo!

Many thanks for uploading the binding to InfluxDB 0.9, great work!

One question, is storing Color and Dimmer items working correctly? I'm storing my Hue's color and brightness items in the database but they are stored as 0's. This are my items definitions:

Color   hue_color_1     "Hue Color 1"   (gr_hue,gr_hue_colores)         { hue="1" }
Color   hue_color_2     "Hue Color 2"   (gr_hue,gr_hue_colores)         { hue="2" }
...
Color   hue_color_6     "Hue Color 6"   (gr_hue,gr_hue_colores)         { hue="6" }

Dimmer  hue_dimmer_1    "Hue Dimmer 1"  (gr_hue,gr_hue_dimmers)         { hue="1;brightness;30" }
Dimmer  hue_dimmer_2    "Hue Dimmer 2"  (gr_hue,gr_hue_dimmers)         { hue="2;brightness;30" }
...
Dimmer  hue_dimmer_6    "Hue Dimmer 6"  (gr_hue,gr_hue_dimmers)         { hue="6;brightness;30" }

I have made a manual influxdb query to see what's being stored and I can confirm that openhab is writing 0s to the database:

> select * from hue_color_1
name: hue_color_1
-----------------
time				value
2015-10-21T08:50:25.087Z	0
2015-10-21T09:20:11.251Z	0
2015-10-21T09:20:12.955Z	0
2015-10-21T09:20:13.544Z	0
2015-10-21T09:20:13.853Z	0
2015-10-21T09:26:11.248Z	0
2015-10-21T09:26:11.271Z	0
2015-10-21T09:32:56.981Z	0
2015-10-21T09:32:58.333Z	0
2015-10-21T09:32:59.054Z	0
2015-10-21T09:32:59.883Z	0
2015-10-21T09:33:00.738Z	0
2015-10-21T09:33:01.608Z	0
2015-10-21T09:33:01.616Z	0
2015-10-21T09:33:03.669Z	0
2015-10-21T09:33:04.365Z	0
2015-10-21T09:33:04.682Z	0
2015-10-21T09:33:05.063Z	0
2015-10-21T09:33:07.047Z	0
2015-10-21T09:33:07.138Z	0
2015-10-21T09:33:07.278Z	0
2015-10-21T09:33:07.596Z	0
2015-10-21T09:33:07.915Z	0
2015-10-21T09:33:12.547Z	0
2015-10-21T09:33:17.092Z	0
2015-10-21T09:33:17.998Z	0
2015-10-21T09:33:18.007Z	0
2015-10-21T09:33:18.498Z	0
2015-10-21T09:33:19.062Z	0
2015-10-21T09:33:19.452Z	0
2015-10-21T09:33:19.98Z	0
2015-10-21T09:33:20.607Z	0

The same is happening with my dimmer items.

Have you seen any of this problems? Do you know where the error could be? The restoreOnStartup function seems to be working fine until one of this type of items needs to be restored. In that moment the process ends.

Many thanks again for your work and looking forward to seeing this merged!

Best regards,

Aitor

**Comment by theoweiss** [comment]
Hi Aitor,

thanks for your testing and feedback. I will check the dimmer and HSB stuff.

Regards,
Theo

**Comment by abrenk** [comment]
@theoweiss, thanks for your work!

I can also confirm that the persistence service for InfluxDB 0.9.x is working as well as the one for 0.8.x.

The following two problems remain:
Dimmer items are always stored as 0, as @bodiroga already mentioned.
Cron based strategies like 'everyHour   : "0 0 * * * ?"' don't seem to work, no values get written.

**Comment by abrenk** [comment]
Both problems I've mentioned have nothing to do with the InfluxDB Persistence.

DimmerItem extends SwitchItem so that `getStateAs` for  the requested PercentType leads to this:
`return state==OnOffType.ON ? PercentType.HUNDRED : PercentType.ZERO;`

I'll prepare a pull request for the fix.

(I haven't looked a the cron strategy, yet. Should be handled by `org.openhab.core.persistence.internal.PersistItemsJob`, not by the individual persistence services.)

**Comment by theoweiss** [comment]
I've fixed the HSB stuff. I will do some testing and then update the PR.

**Comment by theoweiss** [comment]
HSBType should work now.
DimmerItem will be fixes as soon as the PR of @abrenk  #3362 is merged.
I also added PointType support.

I would appreciate your feedback.

**Comment by teichsta** [comment]
#3362 has been merged!

**Comment by bodiroga** [comment]
Hi theo!

Great news, you and abrenk are really fast, wow!

Is there any place where I can download the new version of the binding in order to see if things are also fixed in my installation? ;)

Many thanks for your work and looking forward to give you some feedback.

**Comment by abrenk** [comment]
@bodiroga The fix for the dimmer item problem was in one of the core libraries. You can find a patched JAR at the following locations:

[v1.7.0] (https://www.dropbox.com/s/uk5zj6b6jwvypk8/org.openhab.core.library_1.7.0.jar?dl=0)
[v1.7.1] (https://www.dropbox.com/s/cl9hidgbwrk6ppi/org.openhab.core.library-1.7.1.jar?dl=0)

Just replace the corresponding JAR in the server/plugins directory.

**Comment by theoweiss** [comment]
@bodiroga a Snapshot of the influxdb1 jar is available from here: https://bintray.com/artifact/download/theoweiss/generic/3/org.openhab.persistence.influxdb1-1.8.0-SNAPSHOT.jar

**Comment by nmesstorff** [comment]
@theoweiss thank you for your work and the snapshot!
It's working like a charm for my needs (have only 6 datapoints). Tested with InfluxDB 0.9.3.

**Comment by theoweiss** [comment]
@nmesstorff Thanks for the feedback. Which version of influxdb have you used, 0.9.5RCx? There is an outstanding bug https://github.com/openhab/openhab/issues/2748#issuecomment-153857034 concerning the influxdb server.

**Comment by nmesstorff** [comment]
@theoweiss I'm using InfluxDB 0.9.3. But if I understand #2748 correctly the bug hits only on old 0.8 databases. I've created a new database for my openhab datapoints... all fine so far.

**Comment by theoweiss** [comment]
I've updated the influxdb-java library to 2.1. A snapshot binary download is available here:
https://bintray.com/artifact/download/theoweiss/generic/4/org.openhab.persistence.influxdb1-1.8.0-SNAPSHOT.jar
I appreciate any feedback!

Next step will be to rename the current influxdb bundle to influxdb08 and this bundle from influxdb1 to influxdb.

**Comment by theoweiss** [comment]
I've renamed the influxdb bundle to influxdb08 and influxdb1 to influxdb.
If you want to stay with influxdb 0.8 or older you'll have to use the influxdb08 bundle and change your openhab.cfg accordingly: influxdb: now is influxdb08: https://github.com/theoweiss/openhab/blob/influxdb-09/distribution/openhabhome/configurations/openhab_default.cfg

**Comment by theoweiss** [comment]
I've opened PR #3610 as replacement of this PR.

**Pull request closed without merging**
