### PR TITLE
[neohub] Set heating to on when preheat is on

### PR DESCRIPTION
**Pull request by carlossg**

### CODE REVIEW

**Comment by teichsta** [comment]
Thanks @carlossg for this contribution. Could you please resolve the current merge conflicts and squash your commits into one afterwards?

**Comment by carlossg** [comment]
rebased

WDYM about 1.8? a PR against 1.8 branch?
I'm using this binding with a 1.8 openhab with no problem

**Comment by watou** [comment]
Hi @carlossg, I think @teichsta was asking if this enhancement ought to appear in the 1.8.2 release (in which case, he would just cherry-pick this PR's commit onto 1.8 branch, not that you would have to make a new PR).

**Comment by teichsta** [comment]
thanks for clarifying @watou!

**Comment by teichsta** [comment]
also cherry-picked onto 1.8

**Pull request merged**
